In [171]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error
sns.set_theme(style="darkgrid")

# Teams

In [172]:
home= "Como"
away= "Napoli"

In [173]:
df_home= pd.read_csv(f"../Data/{home}.csv")
df_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Como,Juventus,2024-08-19,L,A,0,3,-3,0,0,...,0.2,0.3,-0.2,-0.2,-0.2,0.06,0,2.3,0.38,-0.7
1,Como,Cagliari,2024-08-26,D,A,1,1,0,1,0,...,1.2,0.7,-0.5,-0.5,-0.2,0.11,0,1.4,0.28,0.4
2,Como,Udinese,2024-09-01,L,A,0,1,-1,0,0,...,0.7,0.8,-1.6,-0.9,-0.7,0.04,0,0.6,0.31,-0.4
3,Como,Bologna,2024-09-14,D,H,2,2,0,1,0,...,1.1,0.5,-0.2,-0.2,-0.1,0.08,0,1.3,0.33,-0.7
4,Como,Atalanta,2024-09-24,W,A,3,2,1,2,0,...,1.0,0.4,0.9,0.9,1.0,0.08,0,1.5,0.17,-0.5
5,Como,Hellas Verona,2024-09-29,W,H,3,2,1,3,0,...,2.2,2.1,0.8,0.8,0.8,0.09,0,1.3,0.19,-0.7
6,Como,Napoli,2024-10-04,L,A,1,3,-2,1,0,...,0.3,0.5,0.6,0.6,0.7,0.03,0,2.6,0.28,-0.4
7,Como,Parma,2024-10-19,D,H,1,1,0,1,0,...,1.1,0.9,-0.3,-0.3,-0.1,0.11,0,1.0,0.34,0.0
8,Como,Torino,2024-10-25,L,A,0,1,-1,0,0,...,1.1,0.6,-1.4,-1.4,-1.1,0.07,0,1.1,0.53,0.1
9,Como,Lazio,2024-10-31,L,H,1,5,-4,1,0,...,0.9,0.6,-0.1,-0.1,-0.9,0.08,1,2.7,0.28,-2.3
10,Como,Empoli,2024-11-04,L,A,0,1,-1,0,0,...,0.3,0.4,-0.4,-0.4,-0.3,0.03,0,0.5,0.13,-0.5
11,Como,Genoa,2024-11-07,D,A,1,1,0,1,0,...,0.9,0.6,-0.4,-0.4,0.1,0.08,2,1.3,0.31,0.3
12,Como,Fiorentina,2024-11-24,L,H,0,2,-2,0,0,...,0.9,0.9,-1.1,-1.1,-0.9,0.12,0,0.9,0.21,-1.1
13,Como,Monza,2024-11-30,D,H,1,1,0,1,0,...,1.0,1.4,-0.3,-0.3,-1.0,0.08,0,0.7,0.02,-0.3
14,Como,Venezia,2024-12-08,D,A,2,2,0,1,0,...,1.0,0.4,0.0,0.0,0.0,0.10,0,1.0,0.25,-1.0
15,Como,Roma,2024-12-15,W,H,2,0,2,2,0,...,1.0,0.7,0.8,0.8,1.0,0.07,2,0.1,0.09,0.1
16,Como,Inter,2024-12-23,L,A,0,2,-2,0,0,...,0.3,0.6,-0.3,-0.3,-0.3,0.04,1,1.7,0.35,-0.3
17,Como,Lecce,2024-12-30,W,H,2,0,2,2,0,...,0.9,0.4,0.0,0.8,0.1,0.09,1,0.1,0.07,0.1
18,Como,Lazio,2025-01-10,D,A,1,1,0,1,0,...,1.9,2.0,-1.0,-1.0,-0.9,0.12,1,0.9,0.23,-0.1
19,Como,Milan,2025-01-14,L,H,1,2,-1,1,0,...,1.4,1.3,-0.4,-0.4,-0.4,0.12,1,1.6,0.29,-0.4
20,Como,Udinese,2025-01-20,W,H,4,1,3,3,0,...,1.4,1.3,1.6,1.6,1.6,0.13,0,0.4,0.22,-0.6
21,Como,Atalanta,2025-01-25,L,H,1,2,-1,1,0,...,0.5,0.5,0.2,0.2,0.5,0.05,1,1.6,0.54,-0.4
22,Como,Bologna,2025-02-01,L,A,0,2,-2,0,0,...,0.3,0.4,-0.5,-0.5,-0.3,0.07,1,1.8,0.45,-0.2
23,Como,Juventus,2025-02-07,L,H,1,2,-1,1,0,...,0.9,1.0,0.1,0.1,0.1,0.06,0,1.4,0.21,-0.6
24,Como,Fiorentina,2025-02-16,W,A,2,0,2,2,0,...,0.8,0.3,1.2,1.2,1.2,0.10,0,0.3,0.10,0.3

In [174]:
df_vs_home= pd.read_csv(f"../Data/vs {home}.csv")
df_vs_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Juventus,Como,2024-08-19,W,H,3,0,3,3,0,...,0.9,0.5,1.8,1.8,1.1,0.09,1,0.0,NaN,0.0
1,Cagliari,Como,2024-08-26,D,H,1,1,0,1,0,...,0.7,1.1,0.2,0.2,0.3,0.07,0,1.1,0.27,0.1
2,Udinese,Como,2024-09-01,W,H,1,0,1,1,0,...,0.8,1.4,0.0,0.0,0.2,0.10,0,0.3,0.08,0.3
3,Bologna,Como,2024-09-14,D,A,2,2,0,2,0,...,0.6,0.6,0.8,0.8,0.4,0.09,2,1.0,0.24,0.0
4,Atalanta,Como,2024-09-24,L,H,2,3,-1,1,1,...,0.6,0.7,0.4,0.2,-0.6,0.11,0,2.2,0.33,0.2
5,Hellas Verona,Como,2024-09-29,L,A,2,3,-1,1,1,...,0.2,0.2,0.9,0.6,0.8,0.07,1,1.7,0.16,-1.3
6,Napoli,Como,2024-10-04,W,H,3,1,2,2,1,...,1.1,0.4,1.1,0.9,0.9,0.14,0,0.4,0.21,-0.6
7,Parma,Como,2024-10-19,D,A,1,1,0,1,0,...,0.4,0.5,0.5,0.5,0.6,0.05,2,1.0,0.34,0.0
8,Torino,Como,2024-10-25,W,H,1,0,1,1,0,...,0.4,0.3,-0.3,-0.3,-0.4,0.16,0,0.6,0.10,0.6
9,Lazio,Como,2024-10-31,W,A,5,1,4,4,1,...,2.1,1.0,2.1,1.8,1.9,0.19,2,1.2,0.59,0.2
10,Empoli,Como,2024-11-04,W,H,1,0,1,1,0,...,0.5,0.2,0.4,0.4,-0.5,0.07,0,0.6,0.32,0.6
11,Genoa,Como,2024-11-07,D,H,1,1,0,1,0,...,0.9,0.7,0.1,0.1,0.1,0.11,0,1.7,0.22,0.7
12,Fiorentina,Como,2024-11-24,W,A,2,0,2,2,0,...,0.7,0.5,1.2,1.2,1.3,0.10,0,0.8,0.25,0.8
13,Monza,Como,2024-11-30,D,A,1,1,0,0,1,...,0.4,0.6,-0.3,-0.5,-0.4,0.07,0,1.4,0.45,0.4
14,Venezia,Como,2024-12-08,D,H,2,2,0,2,0,...,0.1,0.3,1.7,1.7,0.9,0.04,3,1.1,0.27,0.1
15,Roma,Como,2024-12-15,L,A,0,2,-2,0,0,...,0.2,0.2,-0.3,-0.3,-0.2,0.06,1,1.9,0.27,-0.1
16,Inter,Como,2024-12-23,W,H,2,0,2,2,0,...,1.3,1.0,0.4,0.4,0.7,0.10,0,0.4,0.10,0.4
17,Lecce,Como,2024-12-30,L,A,0,2,-2,0,0,...,0.4,0.4,-0.4,-0.4,-0.4,0.04,0,2.9,0.33,0.9
18,Lazio,Como,2025-01-10,D,H,1,1,0,1,0,...,0.4,0.3,0.5,0.5,0.6,0.04,1,1.6,0.52,0.6
19,Milan,Como,2025-01-14,W,A,2,1,1,2,0,...,0.9,0.6,0.7,0.7,0.1,0.11,0,0.5,0.12,-0.5
20,Udinese,Como,2025-01-20,L,A,1,4,-3,1,0,...,0.3,0.7,0.4,0.4,-0.3,0.10,0,2.1,0.27,-0.9
21,Atalanta,Como,2025-01-25,W,A,2,1,1,2,0,...,1.0,0.8,1.0,1.0,1.0,0.19,0,0.9,0.19,-0.1
22,Bologna,Como,2025-02-01,W,H,2,0,2,2,0,...,1.3,0.9,0.5,0.5,0.7,0.10,2,0.4,0.38,0.4
23,Juventus,Como,2025-02-07,W,A,2,1,1,1,1,...,0.3,0.7,0.9,0.6,0.7,0.05,0,1.8,0.30,0.8
24,Fiorentina,Como,2025-02-16,L,H,0,2,-2,0,0,...,0.3,0.4,-0.3,-0.3,-0.3,0.05,0,1.1,0.28,-0.9

In [175]:
df_away= pd.read_csv(f"../Data/{away}.csv")
df_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Napoli,Hellas Verona,2024-08-18,L,A,0,3,-3,0,0,...,0.6,0.6,-1.0,-1.0,-0.6,0.07,0,3.0,0.75,0.0
1,Napoli,Bologna,2024-08-25,W,H,3,0,3,3,0,...,2.5,1.4,0.5,0.5,0.5,0.15,0,0.4,0.20,0.4
2,Napoli,Parma,2024-08-31,W,H,2,1,1,2,0,...,1.8,2.0,-0.2,-0.2,0.2,0.08,1,1.1,0.25,0.1
3,Napoli,Cagliari,2024-09-15,W,A,4,0,4,4,0,...,1.9,1.9,2.1,2.1,2.1,0.15,0,1.1,0.22,1.1
4,Napoli,Juventus,2024-09-21,D,A,0,0,0,0,0,...,0.3,0.4,-0.3,-0.3,-0.3,0.04,0,0.0,0.01,0.0
5,Napoli,Monza,2024-09-29,W,H,2,0,2,2,0,...,1.0,0.9,0.9,0.9,0.0,0.11,0,0.8,0.81,0.8
6,Napoli,Como,2024-10-04,W,H,3,1,2,2,1,...,1.1,0.4,1.1,0.9,0.9,0.14,0,0.4,0.21,-0.6
7,Napoli,Empoli,2024-10-20,W,A,1,0,1,0,1,...,0.6,0.5,-0.3,-0.6,-0.6,0.08,0,0.9,0.23,0.9
8,Napoli,Lecce,2024-10-26,W,H,1,0,1,1,0,...,1.5,1.6,-1.7,-1.7,-1.5,0.13,0,0.0,0.04,0.0
9,Napoli,Milan,2024-10-29,W,A,2,0,2,2,0,...,1.1,0.4,0.9,0.9,0.9,0.13,0,0.8,0.17,0.8
10,Napoli,Atalanta,2024-11-03,L,H,0,3,-3,0,0,...,0.7,0.8,-0.8,-0.8,-0.7,0.06,0,1.0,0.32,-2.0
11,Napoli,Inter,2024-11-10,D,A,1,1,0,1,0,...,0.7,0.3,0.3,0.3,0.3,0.14,0,0.3,0.08,-0.7
12,Napoli,Roma,2024-11-24,W,H,1,0,1,1,0,...,1.3,1.3,-0.4,-0.4,-0.3,0.10,1,0.0,0.02,0.0
13,Napoli,Torino,2024-12-01,W,A,1,0,1,1,0,...,1.3,1.1,-0.4,-0.4,-0.3,0.09,0,0.4,0.37,0.4
14,Napoli,Lazio,2024-12-08,L,H,0,1,-1,0,0,...,0.4,1.2,-0.5,-0.5,-0.4,0.05,1,0.8,0.28,-0.2
15,Napoli,Udinese,2024-12-14,W,A,3,1,2,2,0,...,1.8,0.9,-0.2,-0.2,0.2,0.13,0,1.0,0.01,0.0
16,Napoli,Genoa,2024-12-21,W,A,2,1,1,2,0,...,1.1,0.8,0.8,0.8,0.9,0.11,0,1.0,0.34,0.0
17,Napoli,Venezia,2024-12-29,W,H,1,0,1,1,0,...,0.7,0.8,-0.9,-0.2,-0.7,0.05,0,0.4,0.22,0.4
18,Napoli,Fiorentina,2025-01-04,W,A,3,0,3,2,1,...,0.7,0.5,1.4,1.2,0.3,0.09,0,0.5,0.24,0.5
19,Napoli,Hellas Verona,2025-01-12,W,H,2,0,2,1,0,...,1.0,1.2,-0.1,-0.1,0.0,0.08,0,0.2,0.09,0.2
20,Napoli,Atalanta,2025-01-18,W,A,3,2,1,3,0,...,0.7,0.6,2.2,2.2,1.3,0.13,0,2.6,0.44,0.6
21,Napoli,Juventus,2025-01-25,W,H,2,1,1,1,1,...,1.4,1.7,-0.3,-0.5,-0.4,0.12,1,1.1,0.56,0.1
22,Napoli,Roma,2025-02-02,D,A,1,1,0,1,0,...,0.1,0.5,0.6,0.6,0.9,0.07,0,0.7,0.34,-0.3
23,Napoli,Udinese,2025-02-09,D,H,1,1,0,1,0,...,0.7,1.0,-0.1,-0.1,0.3,0.06,1,0.5,0.12,-0.5
24,Napoli,Lazio,2025-02-15,D,A,2,2,0,1,0,...,0.3,0.4,0.7,0.7,0.7,0.06,0,1.4,0.29,-0.6

In [176]:
df_vs_away= pd.read_csv(f"../Data/vs {away}.csv")
df_vs_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Hellas Verona,Napoli,2024-08-18,W,H,3,0,3,3,0,...,1.8,0.5,1.3,1.3,1.2,0.21,0,0.7,0.17,0.7
1,Bologna,Napoli,2024-08-25,L,A,0,3,-3,0,0,...,0.6,0.4,-0.6,-0.6,-0.6,0.08,0,2.4,0.49,-0.6
2,Parma,Napoli,2024-08-31,L,A,1,2,-1,0,1,...,0.9,0.9,-0.7,-1.0,-0.9,0.08,1,1.3,0.18,-0.7
3,Cagliari,Napoli,2024-09-15,L,H,0,4,-4,0,0,...,0.8,0.9,-1.0,-1.0,-0.8,0.05,1,2.6,0.51,-1.4
4,Juventus,Napoli,2024-09-21,D,H,0,0,0,0,0,...,0.3,0.4,-0.3,-0.3,-0.3,0.03,0,0.1,0.06,0.1
5,Monza,Napoli,2024-09-29,L,A,0,2,-2,0,0,...,0.2,0.2,-0.3,-0.3,-0.2,0.06,2,0.6,0.28,-1.4
6,Como,Napoli,2024-10-04,L,A,1,3,-2,1,0,...,0.3,0.5,0.6,0.6,0.7,0.03,0,2.6,0.28,-0.4
7,Empoli,Napoli,2024-10-20,L,H,0,1,-1,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.06,1,0.8,0.00,-0.2
8,Lecce,Napoli,2024-10-26,L,A,0,1,-1,0,0,...,0.3,0.4,-0.7,-0.7,-0.3,0.06,1,1.7,0.25,0.7
9,Milan,Napoli,2024-10-29,L,H,0,2,-2,0,0,...,0.6,1.2,-0.7,-0.7,-0.6,0.05,0,1.4,0.35,-0.6
10,Atalanta,Napoli,2024-11-03,W,A,3,0,3,3,0,...,1.0,0.7,1.8,1.8,2.0,0.10,0,0.6,0.19,0.6
11,Inter,Napoli,2024-11-10,D,H,1,1,0,1,0,...,0.3,0.5,-0.5,0.2,0.7,0.06,1,1.1,0.57,0.1
12,Roma,Napoli,2024-11-24,L,A,0,1,-1,0,0,...,0.5,0.7,-0.6,-0.6,-0.5,0.10,0,0.9,0.46,-0.1
13,Torino,Napoli,2024-12-01,L,H,0,1,-1,0,0,...,0.2,1.5,-0.3,-0.3,-0.2,0.05,0,1.3,0.21,0.3
14,Lazio,Napoli,2024-12-08,W,A,1,0,1,1,0,...,0.3,0.3,0.7,0.7,0.7,0.04,0,0.1,0.14,0.1
15,Udinese,Napoli,2024-12-14,L,H,1,3,-2,1,0,...,0.5,0.4,-0.4,0.5,-0.5,0.09,0,1.6,0.40,-0.4
16,Genoa,Napoli,2024-12-21,L,H,1,2,-1,1,0,...,1.0,1.0,0.0,0.0,0.0,0.10,1,1.7,0.87,-0.3
17,Venezia,Napoli,2024-12-29,L,A,0,1,-1,0,0,...,0.2,0.2,-0.2,-0.2,-0.2,0.05,1,2.0,0.15,1.0
18,Fiorentina,Napoli,2025-01-04,L,H,0,3,-3,0,0,...,0.6,1.2,-1.0,-1.0,-0.6,0.08,0,1.7,0.23,-1.3
19,Hellas Verona,Napoli,2025-01-12,L,A,0,2,-2,0,0,...,0.2,0.3,-0.3,-0.3,-0.2,0.04,0,0.3,0.13,-0.7
20,Atalanta,Napoli,2025-01-18,L,H,2,3,-1,2,0,...,0.5,1.0,1.3,1.3,-0.5,0.05,0,1.4,0.48,-1.6
21,Juventus,Napoli,2025-01-25,L,A,1,2,-1,1,0,...,0.4,0.2,0.2,0.2,-0.4,0.16,0,2.0,0.42,0.0
22,Roma,Napoli,2025-02-02,D,H,1,1,0,1,0,...,0.2,0.4,0.5,0.5,0.8,0.04,2,0.2,0.11,-0.8
23,Udinese,Napoli,2025-02-09,D,A,1,1,0,1,0,...,0.8,1.0,0.2,0.2,0.2,0.10,0,0.8,0.21,-0.2
24,Lazio,Napoli,2025-02-15,D,H,2,2,0,2,0,...,0.4,0.3,1.3,1.3,0.6,0.06,2,0.1,0.04,-0.9

In [177]:
print(list(df_away.columns))

['Team', 'Opp', 'Date', 'Result', 'H/A', 'GF', 'GA', 'GD', 'G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att (GK)', 'Thr', 'Pa Launch%', 'Pa AvgLen', 'Won', 'Lost', 'Won%', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 'PrgC', 'Last3rd Car', 'OppCr', 'Stp', 'Stp%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'GK Att', 'Launch%', 'AvgLen', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'PKcon', 'OG', 'Recov', '#OPA', 'AvgDist', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'PKdef', 'PKA', 'PKms', 'Missed PK%', 'PKAg', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 'Fld Sc', 'Def-Sc', 'SoTA', 'Saves', 'Save%', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'xG', 'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'PSxG', 'PSxG/SoT', 'PSxG+/-']

# Features

## Offense

In [178]:
offense= ['G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 
          'PrgC', 'Last3rd Car', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'Sh', 'G/Sh', 
          'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 
          'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 
          'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 
          'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 
          'Fld Sc', 'Def-Sc', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'xG', 
          'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'GF']

In [179]:
df_home_off= df_home[offense]
df_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,0,0,0,43,0,10,2,20.0,6,60.0,...,-1.0,-1.0,0.2,0.3,-0.2,-0.2,-0.2,0.06,0,0
1,1,0,0,53,0,12,7,58.3,5,41.7,...,0.7,0.7,1.2,0.7,-0.5,-0.5,-0.2,0.11,0,1
2,0,0,1,56,1,15,11,73.3,4,26.7,...,0.6,-0.1,0.7,0.8,-1.6,-0.9,-0.7,0.04,0,0
3,1,0,0,44,0,19,9,47.4,10,52.6,...,0.0,0.0,1.1,0.5,-0.2,-0.2,-0.1,0.08,0,2
4,2,0,0,41,0,9,4,44.4,3,33.3,...,-0.5,0.3,1.0,0.4,0.9,0.9,1.0,0.08,0,3
5,3,0,0,71,0,19,6,31.6,10,52.6,...,1.1,1.9,2.2,2.1,0.8,0.8,0.8,0.09,0,3
6,1,0,0,59,0,10,5,50.0,3,30.0,...,-1.5,-0.8,0.3,0.5,0.6,0.6,0.7,0.03,0,1
7,1,0,0,61,0,9,4,44.4,5,55.6,...,0.8,0.8,1.1,0.9,-0.3,-0.3,-0.1,0.11,0,1
8,0,0,0,68,0,16,8,50.0,7,43.8,...,0.1,0.1,1.1,0.6,-1.4,-1.4,-1.1,0.07,0,0
9,1,0,0,51,0,8,6,75.0,2,25.0,...,-1.9,-1.1,0.9,0.6,-0.1,-0.1,-0.9,0.08,1,1
10,0,0,0,58,0,22,10,45.5,9,40.9,...,-0.2,-0.2,0.3,0.4,-0.4,-0.4,-0.3,0.03,0,0
11,1,0,0,58,0,26,15,57.7,7,26.9,...,0.4,0.4,0.9,0.6,-0.4,-0.4,0.1,0.08,2,1
12,0,0,0,57,0,16,6,37.5,8,50.0,...,0.3,0.3,0.9,0.9,-1.1,-1.1,-0.9,0.12,0,0
13,1,0,0,55,0,14,9,64.3,2,14.3,...,-0.1,0.7,1.0,1.4,-0.3,-0.3,-1.0,0.08,0,1
14,1,0,0,65,0,21,11,52.4,9,42.9,...,0.7,0.7,1.0,0.4,0.0,0.0,0.0,0.10,0,2
15,2,0,0,38,0,8,3,37.5,3,37.5,...,0.9,0.9,1.0,0.7,0.8,0.8,1.0,0.07,2,2
16,0,0,0,38,0,20,5,25.0,12,60.0,...,-1.3,-1.3,0.3,0.6,-0.3,-0.3,-0.3,0.04,1,0
17,2,0,1,56,1,12,4,33.3,7,58.3,...,1.6,0.8,0.9,0.4,0.0,0.8,0.1,0.09,1,2
18,1,0,0,63,0,16,7,43.8,8,50.0,...,1.5,1.5,1.9,2.0,-1.0,-1.0,-0.9,0.12,1,1
19,1,0,0,52,0,24,8,33.3,11,45.8,...,0.1,0.1,1.4,1.3,-0.4,-0.4,-0.4,0.12,1,1
20,3,0,0,51,0,21,9,42.9,9,42.9,...,0.9,0.9,1.4,1.3,1.6,1.6,1.6,0.13,0,4
21,1,0,0,54,0,25,11,44.0,13,52.0,...,-0.2,-0.2,0.5,0.5,0.2,0.2,0.5,0.05,1,1
22,0,0,0,50,0,29,14,48.3,13,44.8,...,-1.0,-1.0,0.3,0.4,-0.5,-0.5,-0.3,0.07,1,0
23,1,0,0,52,0,14,6,42.9,8,57.1,...,-0.2,0.6,0.9,1.0,0.1,0.1,0.1,0.06,0,1
24,2,0,0,49,0,12,3,25.0,7,58.3,...,0.5,0.5,0.8,0.3,1.2,1.2,1.2,0.10,0,2

In [180]:
df_vs_home_off= df_vs_home[offense]
df_vs_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,3,0,0,57,0,11,7,63.6,3,27.3,...,1.0,1.0,0.9,0.5,1.8,1.8,1.1,0.09,1,3
1,1,0,0,47,0,11,5,45.5,5,45.5,...,-0.7,-0.7,0.7,1.1,0.2,0.2,0.3,0.07,0,1
2,1,0,0,44,0,26,14,53.8,12,46.2,...,-0.6,0.1,0.8,1.4,0.0,0.0,0.2,0.10,0,1
3,2,0,0,56,0,21,10,47.6,10,47.6,...,0.0,0.0,0.6,0.6,0.8,0.8,0.4,0.09,2,2
4,1,1,0,59,1,25,10,40.0,11,44.0,...,0.5,-0.3,0.6,0.7,0.4,0.2,-0.6,0.11,0,2
5,1,1,0,29,1,15,7,46.7,8,53.3,...,-1.1,-1.9,0.2,0.2,0.9,0.6,0.8,0.07,1,2
6,2,1,0,41,1,19,10,52.6,8,42.1,...,1.5,0.8,1.1,0.4,1.1,0.9,0.9,0.14,0,3
7,1,0,0,39,0,19,9,47.4,9,47.4,...,-0.8,-0.8,0.4,0.5,0.5,0.5,0.6,0.05,2,1
8,1,0,0,32,0,15,6,40.0,8,53.3,...,-0.1,-0.1,0.4,0.3,-0.3,-0.3,-0.4,0.16,0,1
9,4,1,0,49,1,22,10,45.5,10,45.5,...,1.9,1.1,2.1,1.0,2.1,1.8,1.9,0.19,2,5
10,1,0,0,42,0,9,3,33.3,5,55.6,...,0.2,0.2,0.5,0.2,0.4,0.4,-0.5,0.07,0,1
11,1,0,0,42,0,8,3,37.5,4,50.0,...,-0.4,-0.4,0.9,0.7,0.1,0.1,0.1,0.11,0,1
12,2,0,0,43,0,13,7,53.8,6,46.2,...,-0.3,-0.3,0.7,0.5,1.2,1.2,1.3,0.10,0,2
13,0,1,0,45,1,14,2,14.3,8,57.1,...,0.1,-0.7,0.4,0.6,-0.3,-0.5,-0.4,0.07,0,1
14,2,0,0,35,0,18,4,22.2,11,61.1,...,-0.7,-0.7,0.1,0.3,1.7,1.7,0.9,0.04,3,2
15,0,0,0,62,0,22,7,31.8,6,27.3,...,-0.9,-0.9,0.2,0.2,-0.3,-0.3,-0.2,0.06,1,0
16,2,0,0,62,0,12,2,16.7,9,75.0,...,1.3,1.3,1.3,1.0,0.4,0.4,0.7,0.10,0,2
17,0,0,0,44,0,12,6,50.0,6,50.0,...,-1.6,-0.8,0.4,0.4,-0.4,-0.4,-0.4,0.04,0,0
18,1,0,0,37,0,20,10,50.0,10,50.0,...,-1.5,-1.5,0.4,0.3,0.5,0.5,0.6,0.04,1,1
19,2,0,0,48,0,27,16,59.3,8,29.6,...,-0.1,-0.1,0.9,0.6,0.7,0.7,0.1,0.11,0,2
20,1,0,0,49,0,21,10,47.6,10,47.6,...,-0.9,-0.9,0.3,0.7,0.4,0.4,-0.3,0.10,0,1
21,2,0,0,46,0,22,8,36.4,11,50.0,...,0.2,0.2,1.0,0.8,1.0,1.0,1.0,0.19,0,2
22,2,0,0,50,0,23,11,47.8,10,43.5,...,1.0,1.0,1.3,0.9,0.5,0.5,0.7,0.10,2,2
23,1,1,0,48,1,16,9,56.3,7,43.8,...,0.2,-0.6,0.3,0.7,0.9,0.6,0.7,0.05,0,2
24,0,0,0,51,0,18,8,44.4,5,27.8,...,-0.5,-0.5,0.3,0.4,-0.3,-0.3,-0.3,0.05,0,0

In [181]:
df_away_off= df_away[offense]
df_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,0,0,0,67,0,20,8,40.0,7,35.0,...,-0.8,-0.8,0.6,0.6,-1.0,-1.0,-0.6,0.07,0,0
1,3,0,0,39,0,23,10,43.5,10,43.5,...,1.8,1.8,2.5,1.4,0.5,0.5,0.5,0.15,0,3
2,2,0,0,55,0,18,6,33.3,7,38.9,...,0.4,1.2,1.8,2.0,-0.2,-0.2,0.2,0.08,1,2
3,4,0,0,49,0,19,6,31.6,11,57.9,...,0.9,0.9,1.9,1.9,2.1,2.1,2.1,0.15,0,4
4,0,0,0,36,0,12,6,50.0,5,41.7,...,0.0,0.0,0.3,0.4,-0.3,-0.3,-0.3,0.04,0,0
5,2,0,0,49,0,12,4,33.3,8,66.7,...,0.8,0.8,1.0,0.9,0.9,0.9,0.0,0.11,0,2
6,2,1,0,41,1,19,10,52.6,8,42.1,...,1.5,0.8,1.1,0.4,1.1,0.9,0.9,0.14,0,3
7,0,1,0,50,1,20,8,40.0,10,50.0,...,0.6,-0.1,0.6,0.5,-0.3,-0.6,-0.6,0.08,0,1
8,1,0,0,64,0,22,8,36.4,13,59.1,...,2.0,2.0,1.5,1.6,-1.7,-1.7,-1.5,0.13,0,1
9,2,0,0,39,0,17,5,29.4,10,58.8,...,0.4,0.4,1.1,0.4,0.9,0.9,0.9,0.13,0,2
10,0,0,0,50,0,15,2,13.3,11,73.3,...,-0.4,-0.4,0.7,0.8,-0.8,-0.8,-0.7,0.06,0,0
11,1,0,0,47,0,15,4,26.7,9,60.0,...,-0.9,-0.1,0.7,0.3,0.3,0.3,0.3,0.14,0,1
12,1,0,0,63,0,17,4,23.5,12,70.6,...,0.8,0.8,1.3,1.3,-0.4,-0.4,-0.3,0.10,1,1
13,1,0,0,52,0,18,7,38.9,10,55.6,...,1.2,1.2,1.3,1.1,-0.4,-0.4,-0.3,0.09,0,1
14,0,0,0,56,0,20,9,45.0,10,50.0,...,0.3,0.3,0.4,1.2,-0.5,-0.5,-0.4,0.05,1,0
15,2,0,0,70,0,21,11,52.4,9,42.9,...,0.7,1.6,1.8,0.9,-0.2,-0.2,0.2,0.13,0,3
16,2,0,0,62,0,18,8,44.4,7,38.9,...,0.2,0.2,1.1,0.8,0.8,0.8,0.9,0.11,0,2
17,1,0,1,66,1,23,8,34.8,12,52.2,...,1.7,1.0,0.7,0.8,-0.9,-0.2,-0.7,0.05,0,1
18,2,1,0,52,1,26,10,38.5,16,61.5,...,0.6,-0.2,0.7,0.5,1.4,1.2,0.3,0.09,0,3
19,1,0,0,69,0,19,6,31.6,10,52.6,...,0.9,0.9,1.0,1.2,-0.1,-0.1,0.0,0.08,0,2
20,3,0,0,44,0,17,6,35.3,7,41.2,...,0.1,0.1,0.7,0.6,2.2,2.2,1.3,0.13,0,3
21,1,1,0,49,1,14,8,57.1,3,21.4,...,1.5,0.7,1.4,1.7,-0.3,-0.5,-0.4,0.12,1,2
22,1,0,0,49,0,12,5,41.7,6,50.0,...,-0.2,-0.2,0.1,0.5,0.6,0.6,0.9,0.07,0,1
23,1,0,0,62,0,8,2,25.0,6,75.0,...,0.3,0.3,0.7,1.0,-0.1,-0.1,0.3,0.06,1,1
24,1,0,0,47,0,3,1,33.3,1,33.3,...,-0.4,-0.4,0.3,0.4,0.7,0.7,0.7,0.06,0,2

In [182]:
df_vs_away_off= df_vs_away[offense]
df_vs_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,3,0,0,33,0,11,6,54.5,3,27.3,...,0.8,0.8,1.8,0.5,1.3,1.3,1.2,0.21,0,3
1,0,0,0,61,0,22,3,13.6,16,72.7,...,-1.8,-1.8,0.6,0.4,-0.6,-0.6,-0.6,0.08,0,0
2,0,1,0,45,1,9,3,33.3,4,44.4,...,-0.4,-1.2,0.9,0.9,-0.7,-1.0,-0.9,0.08,1,1
3,0,0,0,51,0,21,7,33.3,11,52.4,...,-0.9,-0.9,0.8,0.9,-1.0,-1.0,-0.8,0.05,1,0
4,0,0,0,64,0,19,8,42.1,10,52.6,...,0.0,0.0,0.3,0.4,-0.3,-0.3,-0.3,0.03,0,0
5,0,0,0,51,0,9,6,66.7,3,33.3,...,-0.8,-0.8,0.2,0.2,-0.3,-0.3,-0.2,0.06,2,0
6,1,0,0,59,0,10,5,50.0,3,30.0,...,-1.5,-0.8,0.3,0.5,0.6,0.6,0.7,0.03,0,1
7,0,0,0,50,0,19,8,42.1,9,47.4,...,-0.6,0.1,0.6,0.5,-0.7,-0.7,-0.6,0.06,1,0
8,0,0,0,36,0,12,6,50.0,6,50.0,...,-2.0,-2.0,0.3,0.4,-0.7,-0.7,-0.3,0.06,1,0
9,0,0,0,61,0,24,9,37.5,15,62.5,...,-0.4,-0.4,0.6,1.2,-0.7,-0.7,-0.6,0.05,0,0
10,3,0,0,50,0,15,5,33.3,9,60.0,...,0.4,0.4,1.0,0.7,1.8,1.8,2.0,0.10,0,3
11,1,0,1,53,1,11,4,36.4,7,63.6,...,0.9,0.1,0.3,0.5,-0.5,0.2,0.7,0.06,1,1
12,0,0,0,37,0,8,4,50.0,3,37.5,...,-0.8,-0.8,0.5,0.7,-0.6,-0.6,-0.5,0.10,0,0
13,0,0,0,48,0,12,7,58.3,4,33.3,...,-1.2,-1.2,0.2,1.5,-0.3,-0.3,-0.2,0.05,0,0
14,1,0,0,44,0,20,11,55.0,7,35.0,...,-0.3,-0.3,0.3,0.3,0.7,0.7,0.7,0.04,0,1
15,1,0,1,30,1,13,4,30.8,8,61.5,...,-0.7,-1.6,0.5,0.4,-0.4,0.5,-0.5,0.09,0,1
16,1,0,0,38,0,14,4,28.6,10,71.4,...,-0.2,-0.2,1.0,1.0,0.0,0.0,0.0,0.10,1,1
17,0,0,0,34,0,16,7,43.8,7,43.8,...,-1.7,-1.0,0.2,0.2,-0.2,-0.2,-0.2,0.05,1,0
18,0,0,0,48,0,12,5,41.7,7,58.3,...,-0.6,0.2,0.6,1.2,-1.0,-1.0,-0.6,0.08,0,0
19,0,0,0,31,0,20,11,55.0,9,45.0,...,-0.9,-0.9,0.2,0.3,-0.3,-0.3,-0.2,0.04,0,0
20,2,0,0,56,0,14,5,35.7,8,57.1,...,-0.1,-0.1,0.5,1.0,1.3,1.3,-0.5,0.05,0,2
21,1,0,0,51,0,14,6,42.9,6,42.9,...,-1.5,-0.7,0.4,0.2,0.2,0.2,-0.4,0.16,0,1
22,1,0,0,51,0,9,3,33.3,5,55.6,...,0.2,0.2,0.2,0.4,0.5,0.5,0.8,0.04,2,1
23,1,0,0,38,0,11,7,63.6,2,18.2,...,-0.3,-0.3,0.8,1.0,0.2,0.2,0.2,0.10,0,1
24,2,0,0,53,0,20,10,50.0,10,50.0,...,0.4,0.4,0.4,0.3,1.3,1.3,0.6,0.06,2,2

## Defence

In [183]:
defence= ['OppCr', 'Stp', 'Stp%', 'PKcon', '#OPA', 'AvgDist', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'SoTA', 'Saves', 
          'Save%', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 
          'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',  'PSxG', 'PSxG/SoT', 'PSxG+/-', 'GA']

In [184]:
df_home_def= df_home[defence]
df_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,9,0,0.0,0,2,16.0,0,NaN,0,0,...,1,3,4,11,10,2,2.3,0.38,-0.7,3
1,18,1,5.6,0,0,12.0,0,NaN,0,0,...,2,11,9,21,34,0,1.4,0.28,0.4,1
2,11,0,0.0,0,0,18.0,0,NaN,0,0,...,3,7,11,37,21,0,0.6,0.31,-0.4,1
3,12,1,8.3,0,0,1.0,0,NaN,0,0,...,5,11,8,31,21,0,1.3,0.33,-0.7,2
4,26,2,7.7,1,0,7.7,0,0.0,0,1,...,0,6,13,42,32,0,1.5,0.17,-0.5,2
5,4,1,25.0,1,1,14.3,0,0.0,0,0,...,1,4,7,22,7,1,1.3,0.19,-0.7,2
6,7,0,0.0,1,3,15.2,0,0.0,0,0,...,3,8,10,27,16,0,2.6,0.28,-0.4,3
7,10,0,0.0,0,1,16.5,0,NaN,0,0,...,0,6,10,28,17,0,1.0,0.34,0.0,1
8,15,1,6.7,0,3,15.4,0,NaN,0,0,...,3,4,6,24,19,1,1.1,0.53,0.1,1
9,12,0,0.0,1,0,5.0,0,0.0,0,1,...,3,4,6,23,19,2,2.7,0.28,-2.3,5
10,10,0,0.0,0,0,10.8,0,NaN,0,0,...,1,5,10,29,17,1,0.5,0.13,-0.5,1
11,16,0,0.0,0,0,NaN,0,NaN,0,1,...,1,5,10,18,33,0,1.3,0.31,0.3,1
12,9,0,0.0,0,0,10.0,0,NaN,0,0,...,2,7,4,21,19,0,0.9,0.21,-1.1,2
13,12,1,8.3,1,0,8.3,0,0.0,0,0,...,0,6,3,22,15,0,0.7,0.02,-0.3,1
14,11,0,0.0,0,0,2.0,0,NaN,0,1,...,2,6,3,28,31,0,1.0,0.25,-1.0,2
15,14,0,0.0,0,2,19.3,0,NaN,0,0,...,1,7,8,23,26,0,0.1,0.09,0.1,0
16,13,0,0.0,0,0,7.0,0,NaN,0,1,...,5,6,8,26,30,0,1.7,0.35,-0.3,2
17,17,0,0.0,0,1,9.7,0,NaN,0,0,...,3,11,8,19,21,0,0.1,0.07,0.1,0
18,12,1,8.3,0,0,9.3,0,NaN,0,0,...,5,9,9,30,20,0,0.9,0.23,-0.1,1
19,8,0,0.0,0,1,15.4,0,NaN,0,1,...,3,5,9,27,18,1,1.6,0.29,-0.4,2
20,13,1,7.7,0,0,9.0,0,NaN,0,0,...,1,11,5,20,18,2,0.4,0.22,-0.6,1
21,10,3,30.0,0,3,18.2,0,NaN,0,0,...,1,6,7,29,13,0,1.6,0.54,-0.4,2
22,15,1,6.7,0,4,28.8,0,NaN,0,0,...,5,11,8,30,17,1,1.8,0.45,-0.2,2
23,7,0,0.0,1,2,18.5,0,0.0,0,0,...,2,8,8,24,19,0,1.4,0.21,-0.6,2
24,8,1,12.5,0,0,6.0,0,NaN,0,0,...,1,8,16,37,24,0,0.3,0.10,0.3,0

In [185]:
df_vs_home_def= df_vs_home[defence]
df_vs_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,10,1,10.0,0,0,4.0,0,NaN,0,0,...,2,8,4,19,10,0,0.0,NaN,0.0,0
1,17,0,0.0,0,2,15.4,0,NaN,0,1,...,6,4,3,17,32,1,1.1,0.27,0.1,1
2,17,0,0.0,1,0,8.5,0,NaN,0,0,...,6,16,11,33,27,1,0.3,0.08,0.3,0
3,9,0,0.0,0,2,15.5,0,NaN,0,0,...,4,6,5,26,9,1,1.0,0.24,0.0,2
4,6,1,16.7,0,2,16.8,0,NaN,0,0,...,3,10,6,20,9,0,2.2,0.33,0.2,3
5,14,0,0.0,0,0,4.0,0,NaN,0,0,...,6,9,10,27,19,1,1.7,0.16,-1.3,3
6,4,1,25.0,0,0,8.5,0,NaN,0,0,...,1,5,8,20,12,0,0.4,0.21,-0.6,1
7,14,1,7.1,0,1,20.5,0,NaN,0,0,...,5,14,10,19,16,0,1.0,0.34,0.0,1
8,18,0,0.0,0,3,19.0,0,NaN,0,0,...,6,10,10,26,24,2,0.6,0.10,0.6,0
9,12,0,0.0,0,1,17.0,0,NaN,0,0,...,5,4,8,16,13,1,1.2,0.59,0.2,1
10,16,3,18.8,0,0,10.6,0,NaN,0,0,...,4,5,12,24,29,1,0.6,0.32,0.6,0
11,11,1,9.1,0,0,4.5,0,NaN,0,0,...,5,8,11,28,24,1,1.7,0.22,0.7,1
12,15,0,0.0,0,0,NaN,0,NaN,0,0,...,1,5,9,21,27,0,0.8,0.25,0.8,0
13,17,1,5.9,0,0,12.8,0,NaN,0,1,...,6,8,6,16,23,1,1.4,0.45,0.4,1
14,22,1,4.5,0,1,13.8,0,NaN,0,0,...,2,10,8,29,26,0,1.1,0.27,0.1,2
15,12,2,16.7,0,1,13.7,0,NaN,0,0,...,1,8,9,19,20,0,1.9,0.27,-0.1,2
16,8,1,12.5,0,0,3.0,0,NaN,0,0,...,2,8,6,25,13,0,0.4,0.10,0.4,0
17,10,1,10.0,1,2,15.0,1,100.0,0,0,...,5,4,6,24,27,1,2.9,0.33,0.9,2
18,20,2,10.0,0,0,7.8,0,NaN,0,0,...,2,9,18,34,25,2,1.6,0.52,0.6,1
19,13,0,0.0,0,0,16.0,0,NaN,0,0,...,2,11,4,33,18,0,0.5,0.12,-0.5,1
20,8,0,0.0,0,2,25.5,0,NaN,0,1,...,1,14,13,32,13,1,2.1,0.27,-0.9,4
21,11,2,18.2,0,2,13.3,0,NaN,0,0,...,5,12,11,35,13,1,0.9,0.19,-0.1,1
22,4,0,0.0,0,1,21.0,0,NaN,0,0,...,2,13,17,46,16,0,0.4,0.38,0.4,0
23,21,1,4.8,0,0,4.0,0,NaN,0,1,...,5,10,10,31,27,2,1.8,0.30,0.8,1
24,1,0,0.0,0,0,NaN,0,NaN,0,0,...,2,9,5,22,16,0,1.1,0.28,-0.9,2

In [186]:
df_away_def= df_away[defence]
df_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,5,1,20.0,0,2,21.2,0,NaN,0,0,...,0,3,5,13,8,0,3.0,0.75,0.0,3
1,14,0,0.0,0,1,23.0,0,NaN,0,0,...,2,7,6,28,21,0,0.4,0.20,0.4,0
2,5,0,0.0,1,0,16.0,0,0.0,0,0,...,5,8,5,19,11,1,1.1,0.25,0.1,1
3,21,0,0.0,0,0,NaN,0,NaN,0,0,...,4,5,10,34,37,0,1.1,0.22,1.1,0
4,13,2,15.4,0,0,4.5,0,NaN,0,0,...,4,5,7,24,18,1,0.0,0.01,0.0,0
5,9,1,11.1,0,0,6.5,0,NaN,0,0,...,2,6,5,13,15,0,0.8,0.81,0.8,0
6,4,1,25.0,0,0,8.5,0,NaN,0,0,...,1,5,8,20,12,0,0.4,0.21,-0.6,1
7,11,1,9.1,0,3,17.3,0,NaN,0,0,...,4,10,6,24,23,0,0.9,0.23,0.9,0
8,9,1,11.1,0,4,16.3,0,NaN,0,0,...,6,4,8,19,16,0,0.0,0.04,0.0,0
9,15,1,6.7,0,2,14.3,0,NaN,0,0,...,2,4,10,29,31,1,0.8,0.17,0.8,0
10,5,0,0.0,0,1,25.0,0,NaN,0,0,...,2,9,10,27,9,0,1.0,0.32,-2.0,3
11,18,2,11.1,1,0,6.0,0,NaN,0,0,...,5,4,8,22,23,0,0.3,0.08,-0.7,1
12,7,0,0.0,0,2,24.7,0,NaN,0,0,...,0,7,9,17,21,0,0.0,0.02,0.0,0
13,16,2,12.5,0,1,15.8,0,NaN,0,0,...,2,6,9,17,25,0,0.4,0.37,0.4,0
14,4,0,0.0,0,0,NaN,0,NaN,0,0,...,0,4,9,30,9,0,0.8,0.28,-0.2,1
15,8,2,25.0,1,2,15.7,1,100.0,0,0,...,1,2,5,22,14,1,1.0,0.01,0.0,1
16,17,1,5.9,0,2,13.8,0,NaN,0,0,...,2,7,8,20,22,0,1.0,0.34,0.0,1
17,7,1,14.3,0,0,10.3,0,NaN,0,0,...,1,7,15,27,21,0,0.4,0.22,0.4,0
18,15,0,0.0,0,0,17.0,0,NaN,0,0,...,6,5,4,16,20,0,0.5,0.24,0.5,0
19,6,2,33.3,0,3,17.2,0,NaN,0,0,...,2,6,9,24,9,0,0.2,0.09,0.2,0
20,17,0,0.0,0,1,14.0,0,NaN,0,0,...,2,12,7,25,20,0,2.6,0.44,0.6,2
21,5,0,0.0,0,0,10.2,0,NaN,0,0,...,0,3,8,22,17,1,1.1,0.56,0.1,1
22,18,1,5.6,0,1,15.3,0,NaN,0,0,...,5,2,6,21,30,0,0.7,0.34,-0.3,1
23,12,1,8.3,0,1,15.0,0,NaN,0,0,...,1,9,4,9,14,0,0.5,0.12,-0.5,1
24,19,0,0.0,0,0,16.0,0,NaN,0,0,...,1,1,7,25,27,2,1.4,0.29,-0.6,2

In [187]:
df_vs_away_def= df_vs_away[defence]
df_vs_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,17,0,0.0,0,1,13.5,0,NaN,0,0,...,2,11,10,28,23,2,0.7,0.17,0.7,0
1,10,2,20.0,0,2,11.7,0,NaN,0,0,...,7,10,10,29,7,0,2.4,0.49,-0.6,3
2,22,3,13.6,0,1,9.7,0,NaN,0,1,...,12,12,8,27,40,0,1.3,0.18,-0.7,2
3,9,1,11.1,0,1,12.0,0,NaN,0,1,...,5,8,5,24,20,2,2.6,0.51,-1.4,4
4,7,0,0.0,0,1,20.0,0,NaN,0,0,...,5,9,8,22,6,1,0.1,0.06,0.1,0
5,7,0,0.0,0,0,9.0,0,NaN,0,0,...,3,7,11,26,11,3,0.6,0.28,-1.4,2
6,7,0,0.0,1,3,15.2,0,0.0,0,0,...,3,8,10,27,16,0,2.6,0.28,-0.4,3
7,7,1,14.3,1,2,14.7,0,0.0,0,0,...,3,7,10,30,10,0,0.8,0.00,-0.2,1
8,24,2,8.3,0,0,7.0,0,NaN,0,1,...,9,4,10,29,32,0,1.7,0.25,0.7,1
9,6,0,0.0,0,1,11.3,0,NaN,0,0,...,0,1,6,31,8,0,1.4,0.35,-0.6,2
10,12,1,8.3,0,2,16.3,0,NaN,0,0,...,5,12,8,33,22,1,0.6,0.19,0.6,0
11,7,1,14.3,0,1,15.0,0,NaN,0,1,...,0,15,13,29,10,0,1.1,0.57,0.1,1
12,17,1,5.9,0,0,3.0,0,NaN,0,0,...,3,8,7,28,26,0,0.9,0.46,-0.1,1
13,13,0,0.0,0,2,22.8,0,NaN,0,0,...,3,7,13,29,16,0,1.3,0.21,0.3,1
14,19,3,15.8,0,2,13.6,0,NaN,0,0,...,6,5,8,21,21,0,0.1,0.14,0.1,0
15,24,0,0.0,0,3,18.4,0,NaN,0,0,...,2,6,12,33,38,2,1.6,0.40,-0.4,3
16,14,0,0.0,0,0,6.5,0,NaN,0,0,...,3,9,15,36,17,0,1.7,0.87,-0.3,2
17,31,1,3.2,1,0,4.3,1,100.0,0,0,...,5,8,12,35,44,2,2.0,0.15,1.0,1
18,10,0,0.0,1,3,22.3,0,0.0,0,0,...,0,8,6,30,15,1,1.7,0.23,-1.3,3
19,22,2,9.1,0,1,7.8,0,NaN,0,0,...,3,3,14,32,31,1,0.3,0.13,-0.7,2
20,7,0,0.0,0,2,22.0,0,NaN,0,0,...,1,9,7,29,11,1,1.4,0.48,-1.6,3
21,17,1,5.9,1,0,4.0,0,0.0,0,0,...,6,4,7,23,22,0,2.0,0.42,0.0,2
22,8,1,12.5,0,0,10.8,0,NaN,0,0,...,1,7,4,13,17,1,0.2,0.11,-0.8,1
23,14,1,7.1,0,0,6.5,0,NaN,0,1,...,10,8,6,19,26,0,0.8,0.21,-0.2,1
24,7,0,0.0,0,0,NaN,0,NaN,0,0,...,2,7,13,20,11,0,0.1,0.04,-0.9,2

## Combined

In [188]:
combined= ['Won', 'Lost', 'Won%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Recov']

In [189]:
df_home_cmb= df_home[combined]
df_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0     3    12  20.0     4     0      0   12   11     24
1    22    22  50.0     2     0      0   10   10     40
2    15    18  45.5     0     0      0    9   13     48
3     7    11  38.9     2     0      0   17   12     57
4    13    22  37.1     3     0      0   17   12     46
5    16    15  51.6     2     0      0   10   16     36
6    13     6  68.4     1     0      0   10    7     44
7     6     4  60.0     1     0      0   14    9     51
8    20     9  69.0     3     0      0   12   13     41
9    12    17  41.4     2     1      1   14   18     41
10   15    12  55.6     0     0      0    9   16     46
11   26    23  53.1     3     0      0   15   16     40
12   12    11  52.2     2     1      0   11   15     43
13   12    22  35.3     3     0      0   16   11     38
14    4     9  30.8     1     0      0   10   11     45
15    8    12  40.0     6     0      0   18   17     39
16   16    14  53.3     2     0      0   15   13     38
17   13    13  50.0     3     0      0   12   15     50
18   24     7  77.4     3     0      0   15   12     49
19    9     7  56.3     1     0      0   11   17     37
20   11    13  45.8     2     1      1   10   14     31
21    8    13  38.1     2     0      0   15    9     43
22    7     7  50.0     4     1      0   18   15     39
23   18    16  52.9     3     0      0   15   14     28
24   13    12  52.0     2     0      0   24   14     48

In [190]:
df_vs_home_cmb= df_vs_home[combined]
df_vs_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    12     3  80.0     2     0      0   11   12     34
1    22    22  50.0     2     0      0   12   10     42
2    18    15  54.5     3     0      0   16    7     34
3    11     7  61.1     1     0      0   12   15     53
4    22    13  62.9     1     0      0   12   16     41
5    15    16  48.4     5     1      1   19   10     28
6     6    13  31.6     1     0      0    7    9     38
7     4     6  40.0     2     0      0   10   14     43
8     9    20  31.0     3     0      0   13   12     36
9    17    12  58.6     5     1      1   18   12     36
10   12    15  44.4     1     0      0   17    9     44
11   23    26  46.9     4     0      0   17   13     35
12   11    12  47.8     1     0      0   15    8     40
13   22    12  64.7     0     0      0   11   14     34
14    9     4  69.2     1     0      0   12   10     47
15   12     8  60.0     1     0      0   17   18     28
16   14    16  46.7     2     0      0   13   14     42
17   13    13  50.0     2     0      0   15   11     47
18    7    24  22.6     4     1      1   14   14     35
19    7     9  43.8     6     0      0   17   11     41
20   13    11  54.2     4     1      1   16   10     36
21   13     8  61.9     3     0      0   10   14     43
22    7     7  50.0     3     0      0   16   17     48
23   16    18  47.1     1     0      0   15   15     45
24   12    13  48.0     3     0      0   14   24     36

In [191]:
df_away_cmb= df_away[combined]
df_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    23    13  63.9     1     0      0   13   15     39
1     3    12  20.0     2     0      0   11   15     40
2    15     6  71.4     2     0      0   12    6     43
3    15    20  42.9     2     0      0   11   21     51
4    10     7  58.8     0     0      0   13   10     31
5     7     7  50.0     1     0      0   16    7     41
6     6    13  31.6     1     0      0    7    9     38
7     7     6  53.8     2     0      0   13   14     35
8    30    19  61.2     3     0      0   13    5     41
9    12     8  60.0     1     0      0    6   14     27
10    8     7  53.3     1     0      0   10    8     41
11    9    12  42.9     0     0      0   12   14     37
12   15    12  55.6     0     0      0    8    9     41
13   18     2  90.0     1     0      0    9   14     36
14   11     7  61.1     2     0      0   16   12     42
15    9    16  36.0     1     0      0    8   12     37
16   18    17  51.4     1     0      0    8    8     37
17   17     8  68.0     0     0      0   10   11     45
18   19    11  63.3     1     0      0   15   14     42
19   10    19  34.5     0     0      0    6    4     46
20   14    14  50.0     2     0      0    9   18     43
21   17     8  68.0     2     0      0    9   15     33
22   15    14  51.7     1     0      0   13    7     33
23   11     7  61.1     0     0      0   11    9     37
24   11    12  47.8     2     0      0   19    8     36

In [192]:
df_vs_away_cmb= df_vs_away[combined]
df_vs_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    13    23  36.1     4     0      0   15   13     44
1    12     3  80.0     2     0      0   17   10     43
2     6    15  28.6     4     1      1    6   12     25
3    20    15  57.1     1     0      0   22    9     55
4     7    10  41.2     1     0      0   10   13     37
5     7     7  50.0     2     0      0    8   16     33
6    13     6  68.4     1     0      0   10    7     44
7     6     7  46.2     2     0      0   14   13     44
8    19    30  38.8     2     0      0    7   13     25
9     8    12  40.0     0     0      0   14    6     38
10    7     8  46.7     3     0      0    8   10     44
11   12     9  57.1     1     0      0   15   12     46
12   12    15  44.4     3     0      0    9    8     38
13    2    18  10.0     4     0      0   15    9     31
14    7    11  38.9     3     0      0   12   16     37
15   16     9  64.0     1     0      0   14    6     35
16   17    18  48.6     2     0      0    8    7     38
17    8    17  32.0     3     0      0   12   10     32
18   11    19  36.7     0     0      0   17   14     47
19   19    10  65.5     0     0      0    5    6     47
20   14    14  50.0     4     0      0   18    7     48
21    8    17  32.0     2     0      0   15    9     40
22   14    15  48.3     2     0      0    9   10     38
23    7    11  38.9     1     0      0   10   11     40
24   12    11  52.2     2     0      0    9   17     38

## By Team

In [193]:
def compute_rolling_averages(df, features, window=5):
    """
    Compute rolling averages for a list of features in a team-level dataset.

    Parameters:
    df (pd.DataFrame): Dataframe containing team-level data sorted by date.
    features (list): List of features to compute rolling averages for.
    window (int): Rolling window size (default=5).

    Returns:
    pd.DataFrame: Dataframe with new rolling average features.
    """
    df = df.copy()
    
    for feature in features:
        df[f"{feature}_rolling_avg"] = df[feature].rolling(window, min_periods=1).mean()
    
    return df[[i for i in df.columns if i[-12:]=='_rolling_avg']]

In [194]:
df_home_off= compute_rolling_averages(df_home_off, offense)
df_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,0.000000,0.0,0.000000,43.000000,0.000000,10.000000,2.000000,20.000000,6.00,60.00,...,-1.000000e+00,-1.000000e+00,0.20,0.300,-0.200000,-0.200000,-0.200000,0.0600,0.0,0.000000
1,0.500000,0.0,0.000000,48.000000,0.000000,11.000000,4.500000,39.150000,5.50,50.85,...,-1.500000e-01,-1.500000e-01,0.70,0.500,-0.350000,-0.350000,-0.200000,0.0850,0.0,0.500000
2,0.333333,0.0,0.333333,50.666667,0.333333,12.333333,6.666667,50.533333,5.00,42.80,...,1.000000e-01,-1.333333e-01,0.70,0.600,-0.766667,-0.533333,-0.366667,0.0700,0.0,0.333333
3,0.500000,0.0,0.250000,49.000000,0.250000,14.000000,7.250000,49.750000,6.25,45.25,...,7.500000e-02,-1.000000e-01,0.80,0.575,-0.625000,-0.450000,-0.300000,0.0725,0.0,0.750000
4,0.800000,0.0,0.200000,47.400000,0.200000,13.000000,6.600000,48.680000,5.60,42.86,...,-4.000000e-02,-2.000000e-02,0.84,0.540,-0.320000,-0.180000,-0.040000,0.0740,0.0,1.200000
5,1.400000,0.0,0.200000,53.000000,0.200000,14.800000,7.400000,51.000000,6.40,41.38,...,3.800000e-01,5.600000e-01,1.24,0.900,-0.120000,0.020000,0.160000,0.0800,0.0,1.800000
6,1.400000,0.0,0.200000,54.200000,0.200000,14.400000,7.000000,49.340000,6.00,39.04,...,-6.000000e-02,2.600000e-01,1.06,0.860,0.100000,0.240000,0.340000,0.0640,0.0,1.800000
7,1.600000,0.0,0.000000,55.200000,0.000000,13.200000,5.600000,43.560000,6.20,44.82,...,-2.000000e-02,4.400000e-01,1.14,0.880,0.360000,0.360000,0.460000,0.0780,0.0,2.000000
8,1.400000,0.0,0.000000,60.000000,0.000000,12.600000,5.400000,44.080000,5.60,43.06,...,5.551115e-18,4.600000e-01,1.14,0.900,0.120000,0.120000,0.260000,0.0760,0.0,1.600000
9,1.200000,0.0,0.000000,62.000000,0.000000,12.400000,5.800000,50.200000,5.40,41.40,...,-2.800000e-01,1.800000e-01,1.12,0.940,-0.080000,-0.080000,-0.120000,0.0760,0.2,1.200000
10,0.600000,0.0,0.000000,59.400000,0.000000,13.000000,6.600000,52.980000,5.20,39.06,...,-5.400000e-01,-2.400000e-01,0.74,0.600,-0.320000,-0.320000,-0.340000,0.0640,0.2,0.600000
11,0.600000,0.0,0.000000,59.200000,0.000000,16.200000,8.600000,54.520000,6.00,38.44,...,-1.600000e-01,1.110223e-17,0.86,0.620,-0.520000,-0.520000,-0.460000,0.0740,0.6,0.600000
12,0.400000,0.0,0.000000,58.400000,0.000000,17.600000,9.000000,53.140000,6.60,37.32,...,-2.600000e-01,-1.000000e-01,0.82,0.620,-0.680000,-0.680000,-0.620000,0.0760,0.6,0.400000
13,0.600000,0.0,0.000000,55.800000,0.000000,17.200000,9.200000,56.000000,5.60,31.42,...,-3.000000e-01,2.000000e-02,0.80,0.780,-0.460000,-0.460000,-0.600000,0.0780,0.6,0.600000
14,0.600000,0.0,0.000000,58.600000,0.000000,19.800000,10.200000,51.480000,7.00,35.00,...,2.200000e-01,3.800000e-01,0.82,0.740,-0.440000,-0.440000,-0.420000,0.0820,0.4,0.800000
15,1.000000,0.0,0.000000,54.600000,0.000000,17.000000,8.800000,49.880000,5.80,34.32,...,4.400000e-01,6.000000e-01,0.96,0.800,-0.200000,-0.200000,-0.160000,0.0900,0.8,1.200000
16,0.800000,0.0,0.000000,50.600000,0.000000,15.800000,6.800000,43.340000,6.80,40.94,...,1.000000e-01,2.600000e-01,0.84,0.800,-0.180000,-0.180000,-0.240000,0.0820,0.6,1.000000
17,1.200000,0.0,0.200000,50.400000,0.200000,15.000000,6.400000,42.500000,6.60,42.60,...,3.600000e-01,3.600000e-01,0.84,0.700,0.040000,0.200000,-0.040000,0.0760,0.8,1.400000
18,1.200000,0.0,0.200000,52.000000,0.200000,15.400000,6.000000,38.400000,7.80,49.74,...,6.800000e-01,5.200000e-01,1.02,0.820,-0.100000,0.060000,-0.020000,0.0840,1.0,1.400000
19,1.200000,0.0,0.200000,49.400000,0.200000,16.000000,5.400000,34.580000,8.20,50.32,...,5.600000e-01,4.000000e-01,1.10,1.000,-0.180000,-0.020000,-0.100000,0.0880,1.2,1.200000
20,1.400000,0.0,0.200000,52.000000,0.200000,18.600000,6.600000,35.660000,9.40,51.40,...,5.600000e-01,4.000000e-01,1.18,1.120,-0.020000,0.140000,0.020000,0.1000,0.8,1.600000
21,1.600000,0.0,0.200000,55.200000,0.200000,19.600000,7.800000,39.460000,9.60,49.80,...,7.800000e-01,6.200000e-01,1.22,1.100,0.080000,0.240000,0.180000,0.1020,0.8,1.800000
22,1.200000,0.0,0.000000,54.000000,0.000000,23.000000,9.800000,42.460000,10.80,47.10,...,2.600000e-01,2.600000e-01,1.10,1.100,-0.020000,-0.020000,0.100000,0.0980,0.8,1.400000
23,1.200000,0.0,0.000000,51.800000,0.000000,22.600000,9.600000,42.280000,10.80,48.52,...,-8.000000e-02,8.000000e-02,0.90,0.900,0.200000,0.200000,0.300000,0.0860,0.6,1.400000
24,1.400000,0.0,0.000000,51.200000,0.000000,20.200000,8.600000,40.620000,10.00,51.02,...,-4.440892e-17,1.600000e-01,0.78,0.700,0.520000,0.520000,0.620000,0.0820,0.4,1.600000

In [195]:
df_vs_home_off= compute_rolling_averages(df_vs_home_off, offense)
df_vs_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,3.000000,0.0,0.0,57.000000,0.0,11.00,7.000000,63.600,3.000000,27.300000,...,1.000000e+00,1.000000e+00,0.90,0.50,1.800000,1.800000,1.100000,0.090000,1.000000,3.000000
1,2.000000,0.0,0.0,52.000000,0.0,11.00,6.000000,54.550,4.000000,36.400000,...,1.500000e-01,1.500000e-01,0.80,0.80,1.000000,1.000000,0.700000,0.080000,0.500000,2.000000
2,1.666667,0.0,0.0,49.333333,0.0,16.00,8.666667,54.300,6.666667,39.666667,...,-1.000000e-01,1.333333e-01,0.80,1.00,0.666667,0.666667,0.533333,0.086667,0.333333,1.666667
3,1.750000,0.0,0.0,51.000000,0.0,17.25,9.000000,52.625,7.500000,41.650000,...,-7.500000e-02,1.000000e-01,0.75,0.90,0.700000,0.700000,0.500000,0.087500,0.750000,1.750000
4,1.600000,0.2,0.0,52.600000,0.2,18.80,9.200000,50.100,8.200000,42.120000,...,4.000000e-02,2.000000e-02,0.72,0.86,0.640000,0.600000,0.280000,0.092000,0.600000,1.800000
5,1.200000,0.4,0.0,47.000000,0.4,19.60,9.200000,46.720,9.200000,47.320000,...,-3.800000e-01,-5.600000e-01,0.58,0.80,0.460000,0.360000,0.220000,0.088000,0.600000,1.600000
6,1.400000,0.6,0.0,45.800000,0.6,21.20,10.200000,48.140,9.800000,46.640000,...,6.000000e-02,-2.600000e-01,0.66,0.66,0.640000,0.500000,0.340000,0.102000,0.600000,2.000000
7,1.400000,0.6,0.0,44.800000,0.6,19.80,9.200000,46.860,9.200000,46.880000,...,2.000000e-02,-4.400000e-01,0.58,0.48,0.740000,0.600000,0.420000,0.092000,1.000000,2.000000
8,1.200000,0.6,0.0,40.000000,0.6,18.60,8.400000,45.340,8.800000,48.020000,...,-5.551115e-18,-4.600000e-01,0.54,0.42,0.520000,0.380000,0.260000,0.106000,0.600000,1.800000
9,1.800000,0.6,0.0,38.000000,0.6,18.00,8.400000,46.440,8.600000,48.320000,...,2.800000e-01,-1.800000e-01,0.84,0.48,0.860000,0.700000,0.760000,0.122000,1.000000,2.400000
10,1.800000,0.4,0.0,40.600000,0.4,16.80,7.600000,43.760,8.000000,48.780000,...,5.400000e-01,2.400000e-01,0.90,0.48,0.760000,0.660000,0.500000,0.122000,0.800000,2.200000
11,1.600000,0.2,0.0,40.800000,0.2,14.60,6.200000,40.740,7.200000,50.360000,...,1.600000e-01,-1.110223e-17,0.86,0.54,0.560000,0.500000,0.340000,0.116000,0.800000,1.800000
12,1.800000,0.2,0.0,41.600000,0.2,13.40,5.800000,42.020,6.600000,50.120000,...,2.600000e-01,1.000000e-01,0.92,0.54,0.700000,0.640000,0.480000,0.126000,0.400000,2.000000
13,1.600000,0.4,0.0,44.200000,0.4,13.20,5.000000,36.880,6.600000,50.880000,...,3.000000e-01,-2.000000e-02,0.92,0.60,0.700000,0.600000,0.480000,0.108000,0.400000,2.000000
14,1.200000,0.2,0.0,41.400000,0.2,12.40,3.800000,32.220,6.800000,54.000000,...,-2.200000e-01,-3.800000e-01,0.52,0.46,0.620000,0.580000,0.280000,0.078000,0.600000,1.400000
15,1.000000,0.2,0.0,45.400000,0.2,15.00,4.600000,31.920,7.000000,48.340000,...,-4.400000e-01,-6.000000e-01,0.46,0.46,0.480000,0.440000,0.340000,0.076000,0.800000,1.200000
16,1.200000,0.2,0.0,49.400000,0.2,15.80,4.400000,27.760,8.000000,53.340000,...,-1.000000e-01,-2.600000e-01,0.54,0.52,0.540000,0.500000,0.460000,0.074000,0.800000,1.400000
17,0.800000,0.2,0.0,49.600000,0.2,15.60,4.200000,27.000,8.000000,54.100000,...,-3.600000e-01,-3.600000e-01,0.48,0.50,0.220000,0.180000,0.120000,0.062000,0.800000,1.000000
18,1.000000,0.0,0.0,48.000000,0.0,16.80,5.800000,34.140,8.400000,52.680000,...,-6.800000e-01,-5.200000e-01,0.48,0.44,0.380000,0.380000,0.320000,0.056000,1.000000,1.000000
19,1.000000,0.0,0.0,50.600000,0.0,18.60,8.200000,41.560,7.800000,46.380000,...,-5.600000e-01,-4.000000e-01,0.64,0.50,0.180000,0.180000,0.160000,0.070000,0.400000,1.000000
20,1.200000,0.0,0.0,48.000000,0.0,18.40,8.800000,44.720,8.600000,50.440000,...,-5.600000e-01,-4.000000e-01,0.66,0.60,0.320000,0.320000,0.140000,0.078000,0.200000,1.200000
21,1.200000,0.0,0.0,44.800000,0.0,20.40,10.000000,48.660,9.000000,45.440000,...,-7.800000e-01,-6.200000e-01,0.60,0.56,0.440000,0.440000,0.200000,0.096000,0.200000,1.200000
22,1.600000,0.0,0.0,46.000000,0.0,22.60,11.000000,48.220,9.800000,44.140000,...,-2.600000e-01,-2.600000e-01,0.78,0.66,0.620000,0.620000,0.420000,0.108000,0.600000,1.600000
23,1.600000,0.2,0.0,48.200000,0.2,21.80,10.800000,49.480,9.200000,42.900000,...,8.000000e-02,-8.000000e-02,0.76,0.74,0.700000,0.640000,0.440000,0.110000,0.400000,1.800000
24,1.200000,0.2,0.0,48.800000,0.2,20.00,9.200000,46.500,8.600000,42.540000,...,4.440892e-17,-1.600000e-01,0.64,0.70,0.500000,0.440000,0.360000,0.098000,0.400000,1.400000

In [196]:
df_away_def= compute_rolling_averages(df_away_def, defence)
df_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,5.00,1.000000,20.000000,0.000000,2.00,21.200000,0.0,NaN,0.0,0.0,...,0.000000,3.00,5.000000,13.0,8.000000,0.000000,3.00,0.750,0.000000,3.000000
1,9.50,0.500000,10.000000,0.000000,1.50,22.100000,0.0,NaN,0.0,0.0,...,1.000000,5.00,5.500000,20.5,14.500000,0.000000,1.70,0.475,0.200000,1.500000
2,8.00,0.333333,6.666667,0.333333,1.00,20.066667,0.0,0.0,0.0,0.0,...,2.333333,6.00,5.333333,20.0,13.333333,0.333333,1.50,0.400,0.166667,1.333333
3,11.25,0.250000,5.000000,0.250000,0.75,20.066667,0.0,0.0,0.0,0.0,...,2.750000,5.75,6.500000,23.5,19.250000,0.250000,1.40,0.355,0.400000,1.000000
4,11.60,0.600000,7.080000,0.200000,0.60,16.175000,0.0,0.0,0.0,0.0,...,3.000000,5.60,6.600000,23.6,19.000000,0.400000,1.12,0.286,0.320000,0.800000
5,12.40,0.600000,5.300000,0.200000,0.20,12.500000,0.0,0.0,0.0,0.0,...,3.400000,6.20,6.600000,23.6,20.400000,0.400000,0.68,0.298,0.480000,0.200000
6,10.40,0.800000,10.300000,0.200000,0.00,8.875000,0.0,0.0,0.0,0.0,...,3.200000,5.80,7.000000,22.0,18.600000,0.400000,0.68,0.300,0.280000,0.400000
7,11.60,1.000000,12.120000,0.000000,0.60,9.200000,0.0,NaN,0.0,0.0,...,3.000000,6.20,7.200000,23.0,21.000000,0.200000,0.64,0.296,0.440000,0.200000
8,9.20,1.200000,14.340000,0.000000,1.40,10.620000,0.0,NaN,0.0,0.0,...,3.400000,6.00,6.800000,20.0,16.800000,0.200000,0.42,0.260,0.220000,0.200000
9,9.60,1.000000,12.600000,0.000000,1.80,12.580000,0.0,NaN,0.0,0.0,...,3.000000,5.80,7.400000,21.0,19.400000,0.200000,0.58,0.292,0.380000,0.200000
10,8.80,0.800000,10.380000,0.000000,2.00,16.280000,0.0,NaN,0.0,0.0,...,3.000000,6.40,8.400000,23.8,18.200000,0.200000,0.62,0.194,-0.180000,0.800000
11,11.60,1.000000,7.600000,0.200000,2.00,15.780000,0.0,NaN,0.0,0.0,...,3.800000,6.20,8.400000,24.2,20.400000,0.200000,0.60,0.168,-0.200000,0.800000
12,10.80,0.800000,5.780000,0.200000,1.80,17.260000,0.0,NaN,0.0,0.0,...,3.000000,5.60,9.000000,22.8,20.000000,0.200000,0.42,0.126,-0.380000,0.800000
13,12.20,1.000000,6.060000,0.200000,1.20,17.160000,0.0,NaN,0.0,0.0,...,2.200000,6.00,9.200000,22.4,21.800000,0.200000,0.50,0.192,-0.300000,0.800000
14,10.00,0.800000,4.720000,0.200000,0.80,17.875000,0.0,NaN,0.0,0.0,...,1.800000,6.00,9.000000,22.6,17.400000,0.000000,0.50,0.214,-0.500000,1.000000
15,10.60,1.200000,9.720000,0.400000,1.00,15.550000,0.2,100.0,0.0,0.0,...,1.600000,4.60,8.000000,21.6,18.400000,0.200000,0.50,0.152,-0.100000,0.600000
16,10.40,1.000000,8.680000,0.200000,1.40,17.500000,0.2,100.0,0.0,0.0,...,1.000000,5.20,8.000000,21.2,18.200000,0.200000,0.64,0.204,0.040000,0.600000
17,10.40,1.200000,11.540000,0.200000,1.00,13.900000,0.2,100.0,0.0,0.0,...,1.200000,5.20,9.200000,23.2,18.200000,0.200000,0.72,0.244,0.120000,0.600000
18,10.20,0.800000,9.040000,0.200000,0.80,14.200000,0.2,100.0,0.0,0.0,...,2.000000,5.00,8.200000,23.0,17.200000,0.200000,0.74,0.218,0.140000,0.600000
19,10.60,1.200000,15.700000,0.200000,1.40,14.800000,0.2,100.0,0.0,0.0,...,2.400000,5.40,8.200000,21.8,17.200000,0.200000,0.62,0.180,0.220000,0.400000
20,12.40,0.800000,10.700000,0.000000,1.20,14.460000,0.0,NaN,0.0,0.0,...,2.600000,7.40,8.600000,22.4,18.400000,0.000000,0.94,0.266,0.340000,0.600000
21,10.00,0.600000,9.520000,0.000000,0.80,13.740000,0.0,NaN,0.0,0.0,...,2.200000,6.60,8.600000,22.8,17.400000,0.200000,0.96,0.310,0.360000,0.600000
22,12.20,0.600000,7.780000,0.000000,1.00,14.740000,0.0,NaN,0.0,0.0,...,3.000000,5.60,6.800000,21.6,19.200000,0.200000,1.02,0.334,0.220000,0.800000
23,11.60,0.800000,9.440000,0.000000,1.20,14.340000,0.0,NaN,0.0,0.0,...,2.000000,6.40,6.800000,20.2,18.000000,0.200000,1.02,0.310,0.020000,1.000000
24,14.20,0.400000,2.780000,0.000000,0.60,14.100000,0.0,NaN,0.0,0.0,...,1.800000,5.40,6.400000,20.4,21.600000,0.600000,1.26,0.350,-0.140000,1.400000

In [197]:
df_vs_away_def= compute_rolling_averages(df_vs_away_def, defence)
df_vs_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,17.000000,0.000000,0.000,0.0,1.000000,13.500000,0.0,NaN,0.0,0.000000,...,2.0,11.00,10.000000,28.0,23.000000,2.000000,0.700000,0.1700,7.000000e-01,0.000000
1,13.500000,1.000000,10.000,0.0,1.500000,12.600000,0.0,NaN,0.0,0.000000,...,4.5,10.50,10.000000,28.5,15.000000,1.000000,1.550000,0.3300,5.000000e-02,1.500000
2,16.333333,1.666667,11.200,0.0,1.333333,11.633333,0.0,NaN,0.0,0.333333,...,7.0,11.00,9.333333,28.0,23.333333,0.666667,1.466667,0.2800,-2.000000e-01,1.666667
3,14.500000,1.500000,11.175,0.0,1.250000,11.725000,0.0,NaN,0.0,0.500000,...,6.5,10.25,8.250000,27.0,22.500000,1.000000,1.750000,0.3375,-5.000000e-01,2.250000
4,13.000000,1.200000,8.940,0.0,1.200000,13.380000,0.0,NaN,0.0,0.400000,...,6.2,10.00,8.200000,26.0,19.200000,1.000000,1.420000,0.2820,-3.800000e-01,1.800000
5,11.000000,1.200000,8.940,0.0,1.000000,12.480000,0.0,NaN,0.0,0.400000,...,6.4,9.20,8.400000,25.6,16.800000,1.200000,1.400000,0.3040,-8.000000e-01,2.200000
6,10.400000,0.800000,4.940,0.2,1.200000,13.180000,0.0,0.000000,0.0,0.400000,...,5.6,8.80,8.400000,25.2,18.600000,1.200000,1.440000,0.2620,-7.600000e-01,2.200000
7,7.400000,0.400000,5.080,0.4,1.400000,14.180000,0.0,0.000000,0.0,0.200000,...,3.8,7.80,8.800000,25.8,12.600000,1.200000,1.340000,0.2260,-6.600000e-01,2.000000
8,10.400000,0.600000,4.520,0.4,1.200000,13.180000,0.0,0.000000,0.0,0.200000,...,4.6,7.00,9.800000,26.8,15.000000,0.800000,1.160000,0.1740,-2.400000e-01,1.400000
9,10.200000,0.600000,4.520,0.4,1.200000,11.440000,0.0,0.000000,0.0,0.200000,...,3.6,5.40,9.400000,28.6,15.400000,0.600000,1.420000,0.2320,-3.800000e-01,1.800000
10,11.200000,0.800000,6.180,0.4,1.600000,12.900000,0.0,0.000000,0.0,0.200000,...,4.0,6.40,8.800000,30.0,17.600000,0.200000,1.420000,0.2140,2.000000e-02,1.400000
11,11.200000,1.000000,9.040,0.2,1.200000,12.860000,0.0,0.000000,0.0,0.400000,...,3.4,7.80,9.400000,30.4,16.400000,0.200000,1.120000,0.2720,1.200000e-01,1.000000
12,13.200000,1.000000,7.360,0.0,0.800000,10.520000,0.0,NaN,0.0,0.400000,...,3.4,8.00,8.800000,30.0,19.600000,0.200000,1.140000,0.3640,1.400000e-01,1.000000
13,11.000000,0.600000,5.700,0.0,1.200000,13.680000,0.0,NaN,0.0,0.200000,...,2.2,8.60,9.400000,30.0,16.400000,0.200000,1.060000,0.3560,6.000000e-02,1.000000
14,13.600000,1.200000,8.860,0.0,1.400000,14.140000,0.0,NaN,0.0,0.200000,...,3.4,9.40,9.800000,28.0,19.000000,0.200000,0.800000,0.3140,2.000000e-01,0.600000
15,16.000000,1.000000,7.200,0.0,1.600000,14.560000,0.0,NaN,0.0,0.200000,...,2.8,8.20,10.600000,28.0,22.200000,0.400000,1.000000,0.3560,-4.440892e-17,1.200000
16,17.400000,0.800000,4.340,0.0,1.400000,12.860000,0.0,NaN,0.0,0.000000,...,3.4,7.00,11.000000,29.4,23.600000,0.400000,1.120000,0.4160,-8.000000e-02,1.400000
17,20.200000,0.800000,3.800,0.2,1.400000,13.120000,0.2,100.000000,0.0,0.000000,...,3.8,7.00,12.000000,30.8,27.200000,0.800000,1.340000,0.3540,1.400000e-01,1.400000
18,19.600000,0.800000,3.800,0.4,1.600000,13.020000,0.2,50.000000,0.0,0.000000,...,3.2,7.20,10.600000,31.0,27.000000,1.000000,1.420000,0.3580,-1.800000e-01,1.800000
19,20.200000,0.600000,2.460,0.4,1.400000,11.860000,0.2,50.000000,0.0,0.000000,...,2.6,6.80,11.800000,33.2,29.000000,1.200000,1.460000,0.3560,-3.400000e-01,2.200000
20,16.800000,0.600000,2.460,0.4,1.200000,12.580000,0.2,50.000000,0.0,0.000000,...,2.4,7.40,10.800000,32.4,23.600000,1.000000,1.420000,0.3720,-5.800000e-01,2.200000
21,17.400000,0.800000,3.640,0.6,1.200000,12.080000,0.2,33.333333,0.0,0.000000,...,3.0,6.40,9.200000,29.8,24.600000,1.000000,1.480000,0.2820,-5.200000e-01,2.200000
22,12.800000,0.800000,5.500,0.4,1.200000,13.380000,0.0,0.000000,0.0,0.000000,...,2.2,6.20,7.600000,25.4,19.200000,0.800000,1.120000,0.2740,-8.800000e-01,2.200000
23,13.600000,1.000000,6.920,0.2,0.600000,10.220000,0.0,0.000000,0.0,0.200000,...,4.2,6.20,7.600000,23.2,21.400000,0.600000,0.940000,0.2700,-6.600000e-01,1.800000
24,10.600000,0.600000,5.100,0.2,0.400000,10.825000,0.0,0.000000,0.0,0.200000,...,4.0,7.00,7.400000,20.8,17.400000,0.400000,0.900000,0.2520,-7.000000e-01,1.800000

In [198]:
df_away_off= compute_rolling_averages(df_away_off, offense)
df_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,0.000000,0.0,0.0,67.000000,0.0,20.000000,8.0,40.000000,7.00,35.000000,...,-0.800000,-0.800000,0.600000,0.600000,-1.000000,-1.000000,-0.600000,0.0700,0.000000,0.000000
1,1.500000,0.0,0.0,53.000000,0.0,21.500000,9.0,41.750000,8.50,39.250000,...,0.500000,0.500000,1.550000,1.000000,-0.250000,-0.250000,-0.050000,0.1100,0.000000,1.500000
2,1.666667,0.0,0.0,53.666667,0.0,20.333333,8.0,38.933333,8.00,39.133333,...,0.466667,0.733333,1.633333,1.333333,-0.233333,-0.233333,0.033333,0.1000,0.333333,1.666667
3,2.250000,0.0,0.0,52.500000,0.0,20.000000,7.5,37.100000,8.75,43.825000,...,0.575000,0.775000,1.700000,1.475000,0.350000,0.350000,0.550000,0.1125,0.250000,2.250000
4,1.800000,0.0,0.0,49.200000,0.0,18.400000,7.2,39.680000,8.00,43.400000,...,0.460000,0.620000,1.420000,1.260000,0.220000,0.220000,0.380000,0.0980,0.200000,1.800000
5,2.200000,0.0,0.0,45.600000,0.0,16.800000,6.4,38.340000,8.20,49.740000,...,0.780000,0.940000,1.500000,1.320000,0.600000,0.600000,0.500000,0.1060,0.200000,2.200000
6,2.000000,0.2,0.0,46.000000,0.2,16.000000,6.4,40.160000,7.80,49.460000,...,0.720000,0.740000,1.220000,1.120000,0.720000,0.680000,0.580000,0.1040,0.200000,2.200000
7,1.600000,0.4,0.0,45.000000,0.4,16.400000,6.8,41.500000,8.40,51.680000,...,0.760000,0.480000,0.980000,0.820000,0.700000,0.600000,0.420000,0.1040,0.000000,2.000000
8,1.000000,0.4,0.0,48.000000,0.4,17.000000,7.2,42.460000,8.80,51.920000,...,0.980000,0.700000,0.900000,0.760000,-0.060000,-0.160000,-0.300000,0.1000,0.000000,1.400000
9,1.400000,0.4,0.0,48.600000,0.4,18.000000,7.0,38.340000,9.80,55.340000,...,1.060000,0.780000,1.060000,0.760000,0.180000,0.080000,-0.060000,0.1180,0.000000,1.800000
10,1.000000,0.4,0.0,48.800000,0.4,18.600000,6.6,34.340000,10.40,56.660000,...,0.820000,0.540000,1.000000,0.740000,-0.160000,-0.260000,-0.200000,0.1080,0.000000,1.400000
11,0.800000,0.2,0.0,50.000000,0.2,17.800000,5.4,29.160000,10.60,60.240000,...,0.340000,0.360000,0.920000,0.720000,-0.320000,-0.380000,-0.320000,0.1080,0.000000,1.000000
12,1.000000,0.0,0.0,52.600000,0.0,17.200000,4.6,25.860000,11.00,64.360000,...,0.380000,0.540000,1.060000,0.880000,-0.340000,-0.340000,-0.260000,0.1120,0.200000,1.000000
13,1.000000,0.0,0.0,50.200000,0.0,16.400000,4.4,26.360000,10.40,63.660000,...,0.220000,0.380000,1.020000,0.780000,-0.080000,-0.080000,-0.020000,0.1040,0.200000,1.000000
14,0.600000,0.0,0.0,53.600000,0.0,17.000000,5.2,29.480000,10.40,61.900000,...,0.200000,0.360000,0.880000,0.940000,-0.360000,-0.360000,-0.280000,0.0880,0.400000,0.600000
15,1.000000,0.0,0.0,57.600000,0.0,18.200000,7.0,37.300000,10.00,55.820000,...,0.420000,0.760000,1.100000,0.960000,-0.240000,-0.240000,-0.100000,0.1020,0.400000,1.200000
16,1.200000,0.0,0.0,60.600000,0.0,18.800000,7.8,40.840000,9.60,51.600000,...,0.640000,0.820000,1.180000,1.060000,-0.140000,-0.140000,0.020000,0.0960,0.400000,1.400000
17,1.200000,0.0,0.2,61.200000,0.2,20.000000,8.6,43.100000,9.60,47.920000,...,0.820000,0.860000,1.060000,0.960000,-0.240000,-0.100000,-0.060000,0.0860,0.200000,1.400000
18,1.400000,0.2,0.2,61.200000,0.4,21.600000,9.2,43.020000,10.80,49.100000,...,0.700000,0.580000,0.940000,0.840000,0.120000,0.220000,0.060000,0.0860,0.200000,1.800000
19,1.600000,0.2,0.2,63.800000,0.4,21.400000,8.6,40.340000,10.80,49.620000,...,0.820000,0.700000,1.060000,0.840000,0.200000,0.300000,0.140000,0.0920,0.000000,2.200000
20,1.800000,0.2,0.2,58.600000,0.4,20.600000,7.6,36.920000,10.40,49.280000,...,0.700000,0.400000,0.840000,0.780000,0.680000,0.780000,0.360000,0.0920,0.000000,2.200000
21,1.600000,0.4,0.2,56.000000,0.6,19.800000,7.6,39.460000,9.60,45.780000,...,0.960000,0.500000,0.900000,0.960000,0.460000,0.520000,0.100000,0.0940,0.200000,2.200000
22,1.600000,0.4,0.0,52.600000,0.4,17.600000,7.0,40.840000,8.40,45.340000,...,0.580000,0.260000,0.780000,0.900000,0.760000,0.680000,0.420000,0.0980,0.200000,2.200000
23,1.400000,0.2,0.0,54.600000,0.2,14.000000,5.4,38.140000,6.40,48.040000,...,0.520000,0.360000,0.780000,1.000000,0.460000,0.420000,0.420000,0.0920,0.400000,1.800000
24,1.400000,0.2,0.0,50.200000,0.2,10.800000,4.4,38.480000,4.60,44.180000,...,0.260000,0.100000,0.640000,0.840000,0.620000,0.580000,0.560000,0.0880,0.400000,1.800000

In [199]:
df_vs_away_off= compute_rolling_averages(df_vs_away_off, offense)
df_vs_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,3.00,0.000000,0.0,33.000000,0.000000,11.00,6.00,54.500,3.000000,27.300000,...,0.800000,0.800000,1.800,0.500,1.300000e+00,1.300000e+00,1.200,0.210000,0.000000,3.000000
1,1.50,0.000000,0.0,47.000000,0.000000,16.50,4.50,34.050,9.500000,50.000000,...,-0.500000,-0.500000,1.200,0.450,3.500000e-01,3.500000e-01,0.300,0.145000,0.000000,1.500000
2,1.00,0.333333,0.0,46.333333,0.333333,14.00,4.00,33.800,7.666667,48.133333,...,-0.466667,-0.733333,1.100,0.600,3.700743e-17,-1.000000e-01,-0.100,0.123333,0.333333,1.333333
3,0.75,0.250000,0.0,47.500000,0.250000,15.75,4.75,33.675,8.500000,49.200000,...,-0.575000,-0.775000,1.025,0.675,-2.500000e-01,-3.250000e-01,-0.275,0.105000,0.500000,1.000000
4,0.60,0.200000,0.0,50.800000,0.200000,16.40,5.40,35.360,8.800000,49.880000,...,-0.460000,-0.620000,0.880,0.620,-2.600000e-01,-3.200000e-01,-0.280,0.090000,0.400000,0.800000
5,0.00,0.200000,0.0,54.400000,0.200000,16.00,5.40,37.800,8.800000,51.080000,...,-0.780000,-0.940000,0.560,0.560,-5.800000e-01,-6.400000e-01,-0.560,0.060000,0.800000,0.200000
6,0.20,0.200000,0.0,54.000000,0.200000,13.60,5.80,45.080,6.200000,42.540000,...,-0.720000,-0.740000,0.500,0.580,-3.400000e-01,-4.000000e-01,-0.300,0.050000,0.800000,0.400000
7,0.20,0.000000,0.0,55.000000,0.000000,15.60,6.80,46.840,7.200000,43.140000,...,-0.760000,-0.480000,0.440,0.500,-3.400000e-01,-3.400000e-01,-0.240,0.046000,0.800000,0.200000
8,0.20,0.000000,0.0,52.000000,0.000000,13.80,6.60,50.180,6.200000,42.660000,...,-0.980000,-0.700000,0.340,0.400,-2.800000e-01,-2.800000e-01,-0.140,0.048000,0.800000,0.200000
9,0.20,0.000000,0.0,51.400000,0.000000,14.80,6.80,49.260,7.200000,44.640000,...,-1.060000,-0.780000,0.400,0.560,-3.600000e-01,-3.600000e-01,-0.200,0.052000,0.800000,0.200000
10,0.80,0.000000,0.0,51.200000,0.000000,16.00,6.60,42.580,8.400000,49.980000,...,-0.820000,-0.540000,0.560,0.660,6.000000e-02,6.000000e-02,0.240,0.060000,0.400000,0.800000
11,0.80,0.000000,0.2,50.000000,0.200000,16.20,6.40,39.860,9.200000,56.700000,...,-0.340000,-0.360000,0.560,0.660,-1.600000e-01,-2.000000e-02,0.240,0.066000,0.600000,0.800000
12,0.80,0.000000,0.2,47.400000,0.200000,14.00,5.60,41.440,8.000000,54.720000,...,-0.380000,-0.540000,0.540,0.700,-1.400000e-01,2.220446e-17,0.260,0.074000,0.400000,0.800000
13,0.80,0.000000,0.2,49.800000,0.200000,14.00,5.80,43.100,7.600000,51.380000,...,-0.220000,-0.380000,0.520,0.920,-6.000000e-02,8.000000e-02,0.280,0.072000,0.200000,0.800000
14,1.00,0.000000,0.2,46.400000,0.200000,13.20,6.20,46.600,6.000000,45.880000,...,-0.200000,-0.360000,0.460,0.740,2.200000e-01,3.600000e-01,0.540,0.070000,0.200000,1.000000
15,0.60,0.000000,0.4,42.400000,0.400000,12.80,6.00,46.100,5.800000,46.180000,...,-0.420000,-0.760000,0.360,0.680,-2.200000e-01,1.000000e-01,0.040,0.068000,0.200000,0.600000
16,0.60,0.000000,0.2,39.400000,0.200000,13.40,6.00,44.540,6.400000,47.740000,...,-0.640000,-0.820000,0.500,0.780,-1.200000e-01,6.000000e-02,-0.100,0.076000,0.200000,0.600000
17,0.60,0.000000,0.2,38.800000,0.200000,15.00,6.60,43.300,7.200000,49.000000,...,-0.820000,-0.860000,0.440,0.680,-4.000000e-02,1.400000e-01,-0.040,0.066000,0.400000,0.600000
18,0.60,0.000000,0.2,38.800000,0.200000,15.00,6.20,39.980,7.800000,54.000000,...,-0.700000,-0.580000,0.520,0.620,-1.800000e-01,0.000000e+00,-0.120,0.072000,0.400000,0.600000
19,0.40,0.000000,0.2,36.200000,0.200000,15.00,6.20,39.980,8.200000,56.000000,...,-0.820000,-0.700000,0.500,0.620,-3.800000e-01,-2.000000e-01,-0.300,0.072000,0.400000,0.400000
20,0.60,0.000000,0.0,41.400000,0.000000,15.20,6.40,40.960,8.200000,55.120000,...,-0.700000,-0.400000,0.500,0.740,-4.000000e-02,-4.000000e-02,-0.300,0.064000,0.400000,0.600000
21,0.60,0.000000,0.0,44.000000,0.000000,15.20,6.80,43.820,7.400000,49.420000,...,-0.960000,-0.500000,0.380,0.580,1.110223e-17,1.110223e-17,-0.380,0.076000,0.200000,0.600000
22,0.80,0.000000,0.0,47.400000,0.000000,13.80,6.00,41.720,7.000000,51.780000,...,-0.580000,-0.260000,0.380,0.620,1.400000e-01,1.400000e-01,-0.180,0.074000,0.400000,0.800000
23,1.00,0.000000,0.0,45.400000,0.000000,13.60,6.40,46.100,6.000000,43.760000,...,-0.520000,-0.360000,0.420,0.580,3.800000e-01,3.800000e-01,-0.020,0.078000,0.400000,1.000000
24,1.40,0.000000,0.0,49.800000,0.000000,13.60,6.20,45.100,6.200000,44.760000,...,-0.260000,-0.100000,0.460,0.580,7.000000e-01,7.000000e-01,0.140,0.082000,0.800000,1.400000

In [200]:
df_home_def= compute_rolling_averages(df_home_def, defence)
df_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,9.000000,0.000000,0.000000,0.0,2.000000,16.000000,0.0,NaN,0.0,0.0,...,1.00,3.0,4.0,11.0,10.000000,2.000000,2.300000,0.380000,-0.700000,3.000000
1,13.500000,0.500000,2.800000,0.0,1.000000,14.000000,0.0,NaN,0.0,0.0,...,1.50,7.0,6.5,16.0,22.000000,1.000000,1.850000,0.330000,-0.150000,2.000000
2,12.666667,0.333333,1.866667,0.0,0.666667,15.333333,0.0,NaN,0.0,0.0,...,2.00,7.0,8.0,23.0,21.666667,0.666667,1.433333,0.323333,-0.233333,1.666667
3,12.500000,0.500000,3.475000,0.0,0.500000,11.750000,0.0,NaN,0.0,0.0,...,2.75,8.0,8.0,25.0,21.500000,0.500000,1.400000,0.325000,-0.350000,1.750000
4,15.200000,0.800000,4.320000,0.2,0.400000,10.940000,0.0,0.0,0.0,0.2,...,2.20,7.6,9.0,28.4,23.600000,0.400000,1.420000,0.294000,-0.380000,1.800000
5,14.200000,1.000000,9.320000,0.4,0.200000,10.600000,0.0,0.0,0.0,0.2,...,2.20,7.8,9.6,30.6,23.000000,0.200000,1.220000,0.256000,-0.380000,1.600000
6,12.000000,0.800000,8.200000,0.6,0.800000,11.240000,0.0,0.0,0.0,0.2,...,2.40,7.2,9.8,31.8,19.400000,0.200000,1.460000,0.256000,-0.540000,2.000000
7,11.800000,0.800000,8.200000,0.6,1.000000,10.940000,0.0,0.0,0.0,0.2,...,1.80,7.0,9.6,30.0,18.600000,0.200000,1.540000,0.262000,-0.460000,2.000000
8,12.400000,0.800000,7.880000,0.6,1.600000,13.820000,0.0,0.0,0.0,0.2,...,1.40,5.6,9.2,28.6,18.200000,0.400000,1.500000,0.302000,-0.300000,1.800000
9,9.600000,0.400000,6.340000,0.6,1.600000,13.280000,0.0,0.0,0.0,0.2,...,2.00,5.2,7.8,24.8,15.600000,0.800000,1.740000,0.324000,-0.660000,2.400000
10,10.800000,0.200000,1.340000,0.4,1.400000,12.580000,0.0,0.0,0.0,0.2,...,2.00,5.4,8.4,26.2,17.600000,0.800000,1.580000,0.312000,-0.620000,2.200000
11,12.600000,0.200000,1.340000,0.2,0.800000,11.925000,0.0,0.0,0.0,0.4,...,1.60,4.8,8.4,24.4,21.000000,0.800000,1.320000,0.318000,-0.480000,1.800000
12,12.400000,0.200000,1.340000,0.2,0.600000,10.300000,0.0,0.0,0.0,0.4,...,2.00,5.0,7.2,23.0,21.400000,0.800000,1.300000,0.292000,-0.700000,2.000000
13,11.800000,0.200000,1.660000,0.4,0.000000,8.525000,0.0,0.0,0.0,0.4,...,1.40,5.4,6.6,22.6,20.600000,0.600000,1.220000,0.190000,-0.780000,2.000000
14,11.600000,0.200000,1.660000,0.2,0.000000,7.775000,0.0,0.0,0.0,0.4,...,1.20,5.8,6.0,23.6,23.000000,0.200000,0.880000,0.184000,-0.520000,1.400000
15,12.400000,0.200000,1.660000,0.2,0.400000,9.900000,0.0,0.0,0.0,0.4,...,1.20,6.2,5.6,22.4,24.800000,0.000000,0.800000,0.176000,-0.400000,1.200000
16,11.800000,0.200000,1.660000,0.2,0.400000,9.320000,0.0,0.0,0.0,0.4,...,2.00,6.4,5.2,24.0,24.200000,0.000000,0.880000,0.184000,-0.520000,1.400000
17,13.400000,0.200000,1.660000,0.2,0.600000,9.260000,0.0,0.0,0.0,0.4,...,2.20,7.2,6.0,23.6,24.600000,0.000000,0.720000,0.156000,-0.280000,1.000000
18,13.400000,0.200000,1.660000,0.0,0.600000,9.460000,0.0,NaN,0.0,0.4,...,3.20,7.8,7.2,25.2,25.600000,0.000000,0.760000,0.198000,-0.240000,1.000000
19,12.800000,0.200000,1.660000,0.0,0.800000,12.140000,0.0,NaN,0.0,0.4,...,3.40,7.6,8.4,25.0,23.000000,0.200000,0.880000,0.206000,-0.120000,1.000000
20,12.600000,0.400000,3.200000,0.0,0.400000,10.080000,0.0,NaN,0.0,0.4,...,3.40,8.4,7.8,24.4,21.400000,0.600000,0.940000,0.232000,-0.260000,1.200000
21,12.000000,1.000000,9.200000,0.0,1.000000,12.320000,0.0,NaN,0.0,0.2,...,2.60,8.4,7.6,25.0,18.000000,0.600000,0.920000,0.270000,-0.280000,1.200000
22,11.600000,1.200000,10.540000,0.0,1.600000,16.140000,0.0,NaN,0.0,0.2,...,3.00,8.4,7.6,27.2,17.200000,0.800000,1.260000,0.346000,-0.340000,1.600000
23,10.600000,1.000000,8.880000,0.2,2.000000,17.980000,0.0,0.0,0.0,0.2,...,2.40,8.2,7.4,26.0,17.000000,0.800000,1.360000,0.342000,-0.440000,1.800000
24,10.600000,1.200000,11.380000,0.2,1.800000,16.100000,0.0,0.0,0.0,0.0,...,2.00,8.8,8.8,28.0,18.200000,0.600000,1.100000,0.304000,-0.300000,1.400000

In [201]:
df_vs_home_def= compute_rolling_averages(df_vs_home_def, defence)
df_vs_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,10.000000,1.000000,10.000000,0.000000,0.000000,4.000,0.0,NaN,0.0,0.000000,...,2.000000,8.000000,4.00,19.00,10.0,0.000000,0.000000,NaN,0.000000e+00,0.000000
1,13.500000,0.500000,5.000000,0.000000,1.000000,9.700,0.0,NaN,0.0,0.500000,...,4.000000,6.000000,3.50,18.00,21.0,0.500000,0.550000,0.270000,5.000000e-02,0.500000
2,14.666667,0.333333,3.333333,0.333333,0.666667,9.300,0.0,NaN,0.0,0.333333,...,4.666667,9.333333,6.00,23.00,23.0,0.666667,0.466667,0.175000,1.333333e-01,0.333333
3,13.250000,0.250000,2.500000,0.250000,1.000000,10.850,0.0,NaN,0.0,0.250000,...,4.500000,8.500000,5.75,23.75,19.5,0.750000,0.600000,0.196667,1.000000e-01,0.750000
4,11.800000,0.400000,5.340000,0.200000,1.200000,12.040,0.0,NaN,0.0,0.200000,...,4.200000,8.800000,5.80,23.00,17.4,0.600000,0.920000,0.230000,1.200000e-01,1.200000
5,12.600000,0.200000,3.340000,0.200000,1.200000,12.040,0.0,NaN,0.0,0.200000,...,5.000000,9.000000,7.00,24.60,19.2,0.800000,1.260000,0.216000,-1.400000e-01,1.800000
6,10.000000,0.400000,8.340000,0.200000,0.800000,10.660,0.0,NaN,0.0,0.000000,...,4.000000,9.200000,8.00,25.20,15.2,0.600000,1.120000,0.204000,-2.800000e-01,1.800000
7,9.400000,0.600000,9.760000,0.000000,1.000000,13.060,0.0,NaN,0.0,0.000000,...,3.800000,8.800000,7.80,22.40,13.0,0.400000,1.260000,0.256000,-3.400000e-01,2.000000
8,11.200000,0.600000,9.760000,0.000000,1.200000,13.760,0.0,NaN,0.0,0.000000,...,4.200000,9.600000,8.80,22.40,16.0,0.600000,1.180000,0.228000,-2.200000e-01,1.600000
9,12.400000,0.400000,6.420000,0.000000,1.000000,13.800,0.0,NaN,0.0,0.000000,...,4.600000,8.400000,9.20,21.60,16.8,0.800000,0.980000,0.280000,-2.200000e-01,1.200000
10,12.800000,1.000000,10.180000,0.000000,1.000000,15.120,0.0,NaN,0.0,0.000000,...,4.200000,7.600000,9.60,21.00,18.8,0.800000,0.760000,0.312000,1.600000e-01,0.600000
11,14.200000,1.000000,7.000000,0.000000,1.000000,14.320,0.0,NaN,0.0,0.000000,...,5.000000,8.200000,10.20,22.60,21.2,1.000000,1.020000,0.314000,4.200000e-01,0.600000
12,14.400000,0.800000,5.580000,0.000000,0.800000,12.775,0.0,NaN,0.0,0.000000,...,4.200000,6.400000,10.00,23.00,23.4,1.000000,0.980000,0.296000,5.800000e-01,0.400000
13,14.200000,1.000000,6.760000,0.000000,0.200000,11.225,0.0,NaN,0.0,0.200000,...,4.200000,6.000000,9.20,21.00,23.2,0.800000,1.140000,0.366000,5.400000e-01,0.600000
14,16.200000,1.200000,7.660000,0.000000,0.200000,10.425,0.0,NaN,0.0,0.200000,...,3.600000,7.200000,9.20,23.60,25.8,0.600000,1.120000,0.302000,5.200000e-01,0.800000
15,15.400000,1.000000,7.240000,0.000000,0.400000,11.200,0.0,NaN,0.0,0.200000,...,3.000000,7.800000,8.60,22.60,24.0,0.400000,1.380000,0.292000,3.800000e-01,1.200000
16,14.800000,1.000000,7.920000,0.000000,0.400000,10.825,0.0,NaN,0.0,0.200000,...,2.400000,7.800000,7.60,22.00,21.8,0.200000,1.120000,0.268000,3.200000e-01,1.000000
17,13.800000,1.200000,9.920000,0.200000,0.800000,11.660,0.2,100.0,0.0,0.200000,...,3.200000,7.600000,7.00,22.60,21.8,0.400000,1.540000,0.284000,3.400000e-01,1.400000
18,14.400000,1.400000,10.740000,0.200000,0.800000,10.660,0.2,100.0,0.0,0.000000,...,2.400000,7.800000,9.40,26.20,22.2,0.600000,1.580000,0.298000,3.800000e-01,1.400000
19,12.600000,1.200000,9.840000,0.200000,0.600000,11.100,0.2,100.0,0.0,0.000000,...,2.400000,8.000000,8.60,27.00,20.6,0.600000,1.460000,0.268000,2.600000e-01,1.200000
20,11.800000,0.800000,6.500000,0.200000,0.800000,13.460,0.2,100.0,0.0,0.200000,...,2.400000,9.200000,9.40,29.60,19.2,0.800000,1.500000,0.268000,1.000000e-01,1.600000
21,12.400000,1.000000,7.640000,0.200000,1.200000,15.520,0.2,100.0,0.0,0.200000,...,3.000000,10.000000,10.40,31.60,19.2,1.000000,1.600000,0.286000,-5.551115e-18,1.800000
22,11.200000,0.800000,5.640000,0.000000,1.000000,16.720,0.0,NaN,0.0,0.200000,...,2.400000,11.800000,12.60,36.00,17.0,0.800000,1.100000,0.296000,-1.000000e-01,1.400000
23,11.400000,0.600000,4.600000,0.000000,1.000000,15.960,0.0,NaN,0.0,0.400000,...,3.000000,12.000000,11.00,35.40,17.4,0.800000,1.140000,0.252000,-6.000000e-02,1.400000
24,9.000000,0.600000,4.600000,0.000000,1.000000,15.950,0.0,NaN,0.0,0.400000,...,3.000000,11.600000,11.20,33.20,17.0,0.800000,1.260000,0.284000,-1.400000e-01,1.600000

In [202]:
df_away_cmb= compute_rolling_averages(df_away_cmb, combined)
df_away_cmb['H/A']= df_away['H/A']
df_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,23.000000,13.000000,63.900000,1.000000,0.0,0.0,13.00,15.00,39.000000,A
1,13.000000,12.500000,41.950000,1.500000,0.0,0.0,12.00,15.00,39.500000,H
2,13.666667,10.333333,51.766667,1.666667,0.0,0.0,12.00,12.00,40.666667,H
3,14.000000,12.750000,49.550000,1.750000,0.0,0.0,11.75,14.25,43.250000,A
4,13.200000,11.600000,51.400000,1.400000,0.0,0.0,12.00,13.40,40.800000,A
5,10.000000,10.400000,48.620000,1.400000,0.0,0.0,12.60,11.80,41.200000,H
6,10.600000,10.600000,50.940000,1.200000,0.0,0.0,11.80,10.60,40.800000,H
7,9.000000,10.600000,47.420000,1.200000,0.0,0.0,12.00,12.20,39.200000,A
8,12.000000,10.400000,51.080000,1.400000,0.0,0.0,12.40,9.00,37.200000,H
9,12.400000,10.600000,51.320000,1.600000,0.0,0.0,11.00,9.80,36.400000,A
10,12.600000,10.600000,51.980000,1.600000,0.0,0.0,9.80,10.00,36.400000,H
11,13.200000,10.400000,54.240000,1.400000,0.0,0.0,10.80,11.00,36.200000,A
12,14.800000,11.600000,54.600000,1.000000,0.0,0.0,9.80,10.00,37.400000,H
13,12.400000,8.200000,60.360000,0.600000,0.0,0.0,9.00,11.80,36.400000,A
14,12.200000,8.000000,60.580000,0.800000,0.0,0.0,11.00,11.40,39.400000,H
15,12.400000,9.800000,57.120000,0.800000,0.0,0.0,10.60,12.20,38.600000,A
16,14.200000,10.800000,58.820000,1.000000,0.0,0.0,9.80,11.00,38.600000,A
17,14.600000,10.000000,61.300000,1.000000,0.0,0.0,10.20,11.40,39.400000,H
18,14.800000,11.800000,55.960000,1.000000,0.0,0.0,11.40,11.40,40.600000,A
19,14.600000,14.200000,50.640000,0.600000,0.0,0.0,9.40,9.80,41.400000,H
20,15.600000,13.800000,53.440000,0.800000,0.0,0.0,9.60,11.00,42.600000,A
21,15.400000,12.000000,56.760000,1.000000,0.0,0.0,9.80,12.40,41.800000,H
22,15.000000,13.200000,53.500000,1.200000,0.0,0.0,10.40,11.60,39.400000,A
23,13.400000,12.400000,53.060000,1.000000,0.0,0.0,9.60,10.60,38.400000,H
24,13.600000,11.000000,55.720000,1.400000,0.0,0.0,12.20,11.40,36.400000,A

In [203]:
df_vs_away_cmb= compute_rolling_averages(df_vs_away_cmb, combined)
#df_away_cmb['H/A']= df_away['H/A']
df_vs_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,13.000000,23.000000,36.100000,4.000000,0.000000,0.000000,15.000000,13.000000,44.000000
1,12.500000,13.000000,58.050000,3.000000,0.000000,0.000000,16.000000,11.500000,43.500000
2,10.333333,13.666667,48.233333,3.333333,0.333333,0.333333,12.666667,11.666667,37.333333
3,12.750000,14.000000,50.450000,2.750000,0.250000,0.250000,15.000000,11.000000,41.750000
4,11.600000,13.200000,48.600000,2.400000,0.200000,0.200000,14.000000,11.400000,40.800000
5,10.400000,10.000000,51.380000,2.000000,0.200000,0.200000,12.600000,12.000000,38.600000
6,10.600000,10.600000,49.060000,1.800000,0.200000,0.200000,11.200000,11.400000,38.800000
7,10.600000,9.000000,52.580000,1.400000,0.000000,0.000000,12.800000,11.600000,42.600000
8,10.400000,12.000000,48.920000,1.600000,0.000000,0.000000,9.800000,12.400000,36.600000
9,10.600000,12.400000,48.680000,1.400000,0.000000,0.000000,10.600000,11.000000,36.800000
10,10.600000,12.600000,48.020000,1.600000,0.000000,0.000000,10.600000,9.800000,39.000000
11,10.400000,13.200000,45.760000,1.600000,0.000000,0.000000,11.600000,10.800000,39.400000
12,11.600000,14.800000,45.400000,1.800000,0.000000,0.000000,10.600000,9.800000,38.200000
13,8.200000,12.400000,39.640000,2.200000,0.000000,0.000000,12.200000,9.000000,39.400000
14,8.000000,12.200000,39.420000,2.800000,0.000000,0.000000,11.800000,11.000000,39.200000
15,9.800000,12.400000,42.880000,2.400000,0.000000,0.000000,13.000000,10.200000,37.400000
16,10.800000,14.200000,41.180000,2.600000,0.000000,0.000000,11.600000,9.200000,35.800000
17,10.000000,14.600000,38.700000,2.600000,0.000000,0.000000,12.200000,9.600000,34.600000
18,11.800000,14.800000,44.040000,1.800000,0.000000,0.000000,12.600000,10.600000,37.800000
19,14.200000,14.600000,49.360000,1.200000,0.000000,0.000000,11.200000,8.600000,39.800000
20,13.800000,15.600000,46.560000,1.800000,0.000000,0.000000,12.000000,8.800000,42.400000
21,12.000000,15.400000,43.240000,1.800000,0.000000,0.000000,13.400000,9.200000,42.800000
22,13.200000,15.000000,46.500000,1.600000,0.000000,0.000000,12.800000,9.200000,44.000000
23,12.400000,13.400000,46.940000,1.800000,0.000000,0.000000,11.400000,8.600000,42.600000
24,11.000000,13.600000,44.280000,2.200000,0.000000,0.000000,12.200000,10.800000,40.800000

In [204]:
df_home_cmb= compute_rolling_averages(df_home_cmb, combined)
df_home_cmb['H/A']= df_home['H/A']
df_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,3.000000,12.000000,20.00,4.0,0.0,0.0,12.000000,11.000000,24.000000,A
1,12.500000,17.000000,35.00,3.0,0.0,0.0,11.000000,10.500000,32.000000,A
2,13.333333,17.333333,38.50,2.0,0.0,0.0,10.333333,11.333333,37.333333,A
3,11.750000,15.750000,38.60,2.0,0.0,0.0,12.000000,11.500000,42.250000,H
4,12.000000,17.000000,38.30,2.2,0.0,0.0,13.000000,11.600000,43.000000,A
5,14.600000,17.600000,44.62,1.8,0.0,0.0,12.600000,12.600000,45.400000,H
6,12.800000,14.400000,48.30,1.6,0.0,0.0,12.600000,12.000000,46.200000,A
7,11.000000,11.600000,51.20,1.8,0.0,0.0,13.600000,11.200000,46.800000,H
8,13.600000,11.200000,57.22,2.0,0.0,0.0,12.600000,11.400000,43.600000,A
9,13.400000,10.200000,58.08,1.8,0.2,0.2,12.000000,12.600000,42.600000,H
10,13.200000,9.600000,58.88,1.4,0.2,0.2,11.800000,12.600000,44.600000,A
11,15.800000,13.000000,55.82,1.8,0.2,0.2,12.800000,14.400000,43.800000,A
12,17.000000,14.400000,54.26,2.0,0.4,0.2,12.200000,15.600000,42.200000,H
13,15.400000,17.000000,47.52,2.0,0.4,0.2,13.000000,15.200000,41.600000,H
14,13.800000,15.400000,45.40,1.8,0.2,0.0,12.200000,13.800000,42.400000,A
15,12.400000,15.400000,42.28,3.0,0.2,0.0,14.000000,14.000000,41.000000,H
16,10.400000,13.600000,42.32,2.8,0.2,0.0,14.000000,13.400000,40.600000,A
17,10.600000,14.000000,41.88,3.0,0.0,0.0,14.200000,13.400000,42.000000,H
18,13.000000,11.000000,50.30,3.0,0.0,0.0,14.000000,13.600000,44.200000,A
19,14.000000,10.600000,55.40,3.0,0.0,0.0,14.200000,14.800000,42.600000,H
20,14.600000,10.800000,56.56,2.2,0.2,0.2,12.600000,14.200000,41.000000,H
21,13.000000,10.600000,53.52,2.2,0.2,0.2,12.600000,13.400000,42.000000,H
22,11.800000,9.400000,53.52,2.4,0.4,0.2,13.800000,13.400000,39.800000,A
23,10.600000,11.200000,48.62,2.4,0.4,0.2,13.800000,13.800000,35.600000,H
24,11.400000,12.200000,47.76,2.6,0.4,0.2,16.400000,13.200000,37.800000,A

In [205]:
df_vs_home_cmb= compute_rolling_averages(df_vs_home_cmb, combined)
#df_home_cmb['H/A']= df_home['H/A']
df_vs_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,12.000000,3.000000,80.00,2.000000,0.0,0.0,11.00,12.000000,34.000000
1,17.000000,12.500000,65.00,2.000000,0.0,0.0,11.50,11.000000,38.000000
2,17.333333,13.333333,61.50,2.333333,0.0,0.0,13.00,9.666667,36.666667
3,15.750000,11.750000,61.40,2.000000,0.0,0.0,12.75,11.000000,40.750000
4,17.000000,12.000000,61.70,1.800000,0.0,0.0,12.60,12.000000,40.800000
5,17.600000,14.600000,55.38,2.400000,0.2,0.2,14.20,11.600000,39.600000
6,14.400000,12.800000,51.70,2.200000,0.2,0.2,13.20,11.400000,38.800000
7,11.600000,11.000000,48.80,2.000000,0.2,0.2,12.00,12.800000,40.600000
8,11.200000,13.600000,42.78,2.400000,0.2,0.2,12.20,12.200000,37.200000
9,10.200000,13.400000,41.92,3.200000,0.4,0.4,13.40,11.400000,36.200000
10,9.600000,13.200000,41.12,2.400000,0.2,0.2,13.00,11.200000,39.400000
11,13.000000,15.800000,44.18,3.000000,0.2,0.2,15.00,12.000000,38.800000
12,14.400000,17.000000,45.74,2.800000,0.2,0.2,16.00,10.800000,38.200000
13,17.000000,15.400000,52.48,2.200000,0.2,0.2,15.60,11.200000,37.800000
14,15.400000,13.800000,54.60,1.400000,0.0,0.0,14.40,10.800000,40.000000
15,15.400000,12.400000,57.72,1.400000,0.0,0.0,14.40,12.600000,36.800000
16,13.600000,10.400000,57.68,1.000000,0.0,0.0,13.60,12.800000,38.200000
17,14.000000,10.600000,58.12,1.200000,0.0,0.0,13.60,13.400000,39.600000
18,11.000000,13.000000,49.70,2.000000,0.2,0.2,14.20,13.400000,39.800000
19,10.600000,14.000000,44.62,3.000000,0.2,0.2,15.20,13.600000,38.600000
20,10.800000,14.600000,43.46,3.600000,0.4,0.4,15.00,12.000000,40.200000
21,10.600000,13.000000,46.50,3.800000,0.4,0.4,14.40,12.000000,40.400000
22,9.400000,11.800000,46.50,4.000000,0.4,0.4,14.60,13.200000,40.600000
23,11.200000,10.600000,51.40,3.400000,0.2,0.2,14.80,13.400000,42.600000
24,12.200000,11.400000,52.24,2.800000,0.2,0.2,14.20,16.000000,41.600000

In [206]:
df_vs_away_cmb = df_vs_away_cmb.rename(columns=lambda x: 'vs_' + x)
df_vs_home_cmb = df_vs_home_cmb.rename(columns=lambda x: 'vs_' + x)

## Final DFs

In [207]:
df_home_gf= pd.concat([df_home_off, df_home_cmb, df_vs_home_cmb, df_vs_home_def, df_home[['GF']]], axis= 1)
df_home_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,0.000000,0.0,0.000000,43.000000,0.000000,10.000000,2.000000,20.000000,6.00,60.00,...,8.000000,4.00,19.00,10.0,0.000000,0.000000,NaN,0.000000e+00,0.000000,0
1,0.500000,0.0,0.000000,48.000000,0.000000,11.000000,4.500000,39.150000,5.50,50.85,...,6.000000,3.50,18.00,21.0,0.500000,0.550000,0.270000,5.000000e-02,0.500000,1
2,0.333333,0.0,0.333333,50.666667,0.333333,12.333333,6.666667,50.533333,5.00,42.80,...,9.333333,6.00,23.00,23.0,0.666667,0.466667,0.175000,1.333333e-01,0.333333,0
3,0.500000,0.0,0.250000,49.000000,0.250000,14.000000,7.250000,49.750000,6.25,45.25,...,8.500000,5.75,23.75,19.5,0.750000,0.600000,0.196667,1.000000e-01,0.750000,2
4,0.800000,0.0,0.200000,47.400000,0.200000,13.000000,6.600000,48.680000,5.60,42.86,...,8.800000,5.80,23.00,17.4,0.600000,0.920000,0.230000,1.200000e-01,1.200000,3
5,1.400000,0.0,0.200000,53.000000,0.200000,14.800000,7.400000,51.000000,6.40,41.38,...,9.000000,7.00,24.60,19.2,0.800000,1.260000,0.216000,-1.400000e-01,1.800000,3
6,1.400000,0.0,0.200000,54.200000,0.200000,14.400000,7.000000,49.340000,6.00,39.04,...,9.200000,8.00,25.20,15.2,0.600000,1.120000,0.204000,-2.800000e-01,1.800000,1
7,1.600000,0.0,0.000000,55.200000,0.000000,13.200000,5.600000,43.560000,6.20,44.82,...,8.800000,7.80,22.40,13.0,0.400000,1.260000,0.256000,-3.400000e-01,2.000000,1
8,1.400000,0.0,0.000000,60.000000,0.000000,12.600000,5.400000,44.080000,5.60,43.06,...,9.600000,8.80,22.40,16.0,0.600000,1.180000,0.228000,-2.200000e-01,1.600000,0
9,1.200000,0.0,0.000000,62.000000,0.000000,12.400000,5.800000,50.200000,5.40,41.40,...,8.400000,9.20,21.60,16.8,0.800000,0.980000,0.280000,-2.200000e-01,1.200000,1
10,0.600000,0.0,0.000000,59.400000,0.000000,13.000000,6.600000,52.980000,5.20,39.06,...,7.600000,9.60,21.00,18.8,0.800000,0.760000,0.312000,1.600000e-01,0.600000,0
11,0.600000,0.0,0.000000,59.200000,0.000000,16.200000,8.600000,54.520000,6.00,38.44,...,8.200000,10.20,22.60,21.2,1.000000,1.020000,0.314000,4.200000e-01,0.600000,1
12,0.400000,0.0,0.000000,58.400000,0.000000,17.600000,9.000000,53.140000,6.60,37.32,...,6.400000,10.00,23.00,23.4,1.000000,0.980000,0.296000,5.800000e-01,0.400000,0
13,0.600000,0.0,0.000000,55.800000,0.000000,17.200000,9.200000,56.000000,5.60,31.42,...,6.000000,9.20,21.00,23.2,0.800000,1.140000,0.366000,5.400000e-01,0.600000,1
14,0.600000,0.0,0.000000,58.600000,0.000000,19.800000,10.200000,51.480000,7.00,35.00,...,7.200000,9.20,23.60,25.8,0.600000,1.120000,0.302000,5.200000e-01,0.800000,2
15,1.000000,0.0,0.000000,54.600000,0.000000,17.000000,8.800000,49.880000,5.80,34.32,...,7.800000,8.60,22.60,24.0,0.400000,1.380000,0.292000,3.800000e-01,1.200000,2
16,0.800000,0.0,0.000000,50.600000,0.000000,15.800000,6.800000,43.340000,6.80,40.94,...,7.800000,7.60,22.00,21.8,0.200000,1.120000,0.268000,3.200000e-01,1.000000,0
17,1.200000,0.0,0.200000,50.400000,0.200000,15.000000,6.400000,42.500000,6.60,42.60,...,7.600000,7.00,22.60,21.8,0.400000,1.540000,0.284000,3.400000e-01,1.400000,2
18,1.200000,0.0,0.200000,52.000000,0.200000,15.400000,6.000000,38.400000,7.80,49.74,...,7.800000,9.40,26.20,22.2,0.600000,1.580000,0.298000,3.800000e-01,1.400000,1
19,1.200000,0.0,0.200000,49.400000,0.200000,16.000000,5.400000,34.580000,8.20,50.32,...,8.000000,8.60,27.00,20.6,0.600000,1.460000,0.268000,2.600000e-01,1.200000,1
20,1.400000,0.0,0.200000,52.000000,0.200000,18.600000,6.600000,35.660000,9.40,51.40,...,9.200000,9.40,29.60,19.2,0.800000,1.500000,0.268000,1.000000e-01,1.600000,4
21,1.600000,0.0,0.200000,55.200000,0.200000,19.600000,7.800000,39.460000,9.60,49.80,...,10.000000,10.40,31.60,19.2,1.000000,1.600000,0.286000,-5.551115e-18,1.800000,1
22,1.200000,0.0,0.000000,54.000000,0.000000,23.000000,9.800000,42.460000,10.80,47.10,...,11.800000,12.60,36.00,17.0,0.800000,1.100000,0.296000,-1.000000e-01,1.400000,0
23,1.200000,0.0,0.000000,51.800000,0.000000,22.600000,9.600000,42.280000,10.80,48.52,...,12.000000,11.00,35.40,17.4,0.800000,1.140000,0.252000,-6.000000e-02,1.400000,1
24,1.400000,0.0,0.000000,51.200000,0.000000,20.200000,8.600000,40.620000,10.00,51.02,...,11.600000,11.20,33.20,17.0,0.800000,1.260000,0.284000,-1.400000e-01,1.600000,2

In [208]:
df_away_gf= pd.concat([df_away_off, df_away_cmb, df_vs_away_cmb, df_vs_away_def, df_away[['GF']]], axis= 1)
df_away_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,0.000000,0.0,0.0,67.000000,0.0,20.000000,8.0,40.000000,7.00,35.000000,...,11.00,10.000000,28.0,23.000000,2.000000,0.700000,0.1700,7.000000e-01,0.000000,0
1,1.500000,0.0,0.0,53.000000,0.0,21.500000,9.0,41.750000,8.50,39.250000,...,10.50,10.000000,28.5,15.000000,1.000000,1.550000,0.3300,5.000000e-02,1.500000,3
2,1.666667,0.0,0.0,53.666667,0.0,20.333333,8.0,38.933333,8.00,39.133333,...,11.00,9.333333,28.0,23.333333,0.666667,1.466667,0.2800,-2.000000e-01,1.666667,2
3,2.250000,0.0,0.0,52.500000,0.0,20.000000,7.5,37.100000,8.75,43.825000,...,10.25,8.250000,27.0,22.500000,1.000000,1.750000,0.3375,-5.000000e-01,2.250000,4
4,1.800000,0.0,0.0,49.200000,0.0,18.400000,7.2,39.680000,8.00,43.400000,...,10.00,8.200000,26.0,19.200000,1.000000,1.420000,0.2820,-3.800000e-01,1.800000,0
5,2.200000,0.0,0.0,45.600000,0.0,16.800000,6.4,38.340000,8.20,49.740000,...,9.20,8.400000,25.6,16.800000,1.200000,1.400000,0.3040,-8.000000e-01,2.200000,2
6,2.000000,0.2,0.0,46.000000,0.2,16.000000,6.4,40.160000,7.80,49.460000,...,8.80,8.400000,25.2,18.600000,1.200000,1.440000,0.2620,-7.600000e-01,2.200000,3
7,1.600000,0.4,0.0,45.000000,0.4,16.400000,6.8,41.500000,8.40,51.680000,...,7.80,8.800000,25.8,12.600000,1.200000,1.340000,0.2260,-6.600000e-01,2.000000,1
8,1.000000,0.4,0.0,48.000000,0.4,17.000000,7.2,42.460000,8.80,51.920000,...,7.00,9.800000,26.8,15.000000,0.800000,1.160000,0.1740,-2.400000e-01,1.400000,1
9,1.400000,0.4,0.0,48.600000,0.4,18.000000,7.0,38.340000,9.80,55.340000,...,5.40,9.400000,28.6,15.400000,0.600000,1.420000,0.2320,-3.800000e-01,1.800000,2
10,1.000000,0.4,0.0,48.800000,0.4,18.600000,6.6,34.340000,10.40,56.660000,...,6.40,8.800000,30.0,17.600000,0.200000,1.420000,0.2140,2.000000e-02,1.400000,0
11,0.800000,0.2,0.0,50.000000,0.2,17.800000,5.4,29.160000,10.60,60.240000,...,7.80,9.400000,30.4,16.400000,0.200000,1.120000,0.2720,1.200000e-01,1.000000,1
12,1.000000,0.0,0.0,52.600000,0.0,17.200000,4.6,25.860000,11.00,64.360000,...,8.00,8.800000,30.0,19.600000,0.200000,1.140000,0.3640,1.400000e-01,1.000000,1
13,1.000000,0.0,0.0,50.200000,0.0,16.400000,4.4,26.360000,10.40,63.660000,...,8.60,9.400000,30.0,16.400000,0.200000,1.060000,0.3560,6.000000e-02,1.000000,1
14,0.600000,0.0,0.0,53.600000,0.0,17.000000,5.2,29.480000,10.40,61.900000,...,9.40,9.800000,28.0,19.000000,0.200000,0.800000,0.3140,2.000000e-01,0.600000,0
15,1.000000,0.0,0.0,57.600000,0.0,18.200000,7.0,37.300000,10.00,55.820000,...,8.20,10.600000,28.0,22.200000,0.400000,1.000000,0.3560,-4.440892e-17,1.200000,3
16,1.200000,0.0,0.0,60.600000,0.0,18.800000,7.8,40.840000,9.60,51.600000,...,7.00,11.000000,29.4,23.600000,0.400000,1.120000,0.4160,-8.000000e-02,1.400000,2
17,1.200000,0.0,0.2,61.200000,0.2,20.000000,8.6,43.100000,9.60,47.920000,...,7.00,12.000000,30.8,27.200000,0.800000,1.340000,0.3540,1.400000e-01,1.400000,1
18,1.400000,0.2,0.2,61.200000,0.4,21.600000,9.2,43.020000,10.80,49.100000,...,7.20,10.600000,31.0,27.000000,1.000000,1.420000,0.3580,-1.800000e-01,1.800000,3
19,1.600000,0.2,0.2,63.800000,0.4,21.400000,8.6,40.340000,10.80,49.620000,...,6.80,11.800000,33.2,29.000000,1.200000,1.460000,0.3560,-3.400000e-01,2.200000,2
20,1.800000,0.2,0.2,58.600000,0.4,20.600000,7.6,36.920000,10.40,49.280000,...,7.40,10.800000,32.4,23.600000,1.000000,1.420000,0.3720,-5.800000e-01,2.200000,3
21,1.600000,0.4,0.2,56.000000,0.6,19.800000,7.6,39.460000,9.60,45.780000,...,6.40,9.200000,29.8,24.600000,1.000000,1.480000,0.2820,-5.200000e-01,2.200000,2
22,1.600000,0.4,0.0,52.600000,0.4,17.600000,7.0,40.840000,8.40,45.340000,...,6.20,7.600000,25.4,19.200000,0.800000,1.120000,0.2740,-8.800000e-01,2.200000,1
23,1.400000,0.2,0.0,54.600000,0.2,14.000000,5.4,38.140000,6.40,48.040000,...,6.20,7.600000,23.2,21.400000,0.600000,0.940000,0.2700,-6.600000e-01,1.800000,1
24,1.400000,0.2,0.0,50.200000,0.2,10.800000,4.4,38.480000,4.60,44.180000,...,7.00,7.400000,20.8,17.400000,0.400000,0.900000,0.2520,-7.000000e-01,1.800000,2

In [209]:
nan_counts = df_home_gf.isna().sum()
for i in df_home_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 1
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 20
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 1
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 1
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [210]:
nan_counts = df_away_gf.isna().sum()
for i in df_away_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 11
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [211]:
df_home_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [212]:
df_away_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [213]:
df_home_gf = df_home_gf.fillna(0)

In [214]:
df_away_gf = df_away_gf.fillna(0)

# Model Home

In [215]:
target = "GF"  # Goals For

# Separate features and target
X = df_home_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
y = df_home_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [216]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [217]:
model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [218]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=25)

# Train the model
model_pipeline.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 0.933
RMSE: 0.943

In [219]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline.predict(X_test)
    y_cur= model_pipeline.predict(df_home_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 19, number of used features: 0
[LightGBM] [Info] Start training from score 1.315789
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [220]:
results_df

                        MAE      RMSE                   pred
Random Forest           0.6  0.689928                  [1.3]
XGBoost            0.862263  1.178987           [0.72708726]
LightGBM           0.589474  0.706911   [1.3157894736842106]
Linear Regression  2.243428  3.162124  [-0.5294449395172767]

# Model Away

In [221]:
target = "GF"  # Goals For

# Separate features and target
Xa = df_away_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
ya = df_away_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [222]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [223]:
model_pipeline2 = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [224]:
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.1, random_state=25)

# Train the model
model_pipeline2.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline2.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 1.317
RMSE: 1.541

In [225]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline2 = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline2.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline2.predict(X_test)
    y_cur= model_pipeline2.predict(df_away_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 19, number of used features: 0
[LightGBM] [Info] Start training from score 1.684211
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [226]:
results_df

                        MAE      RMSE                  pred
Random Forest          0.76  0.929516                 [1.0]
XGBoost            1.154151  1.301717          [0.21588196]
LightGBM           0.663158  0.757237  [1.6842105263157894]
Linear Regression  1.929364  2.308689  [0.6634193066070165]