In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error
sns.set_theme(style="darkgrid")

# Teams

In [6]:
home= "Manchester City"
away= "Liverpool"

In [7]:
df_home= pd.read_csv(f"../Data/{home}.csv")
df_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Manchester City,Chelsea,2024-08-18,W,A,2,0,2,2,0,...,0.6,0.9,1.2,1.2,0.4,0.07,0,0.7,0.23,0.7
1,Manchester City,Ipswich Town,2024-08-24,W,H,4,1,3,3,1,...,2.3,1.9,0.7,0.4,-0.3,0.20,1,0.3,0.29,-0.7
2,Manchester City,West Ham,2024-08-31,W,A,3,1,2,3,0,...,2.7,2.7,0.0,0.0,0.3,0.13,1,0.2,0.09,0.2
3,Manchester City,Brentford,2024-09-14,W,H,2,1,1,2,0,...,2.0,1.5,-0.1,-0.1,-1.0,0.12,0,2.1,0.46,1.1
4,Manchester City,Arsenal,2024-09-22,D,H,2,2,0,2,0,...,1.7,2.9,-0.1,-0.1,-0.7,0.07,1,1.5,0.49,-0.5
5,Manchester City,Newcastle Utd,2024-09-28,D,A,1,1,0,1,0,...,0.8,1.4,0.1,0.1,0.2,0.06,0,1.1,0.11,0.1
6,Manchester City,Fulham,2024-10-05,W,H,3,2,1,3,0,...,1.3,1.3,1.4,1.4,0.7,0.08,1,2.5,0.62,0.5
7,Manchester City,Wolves,2024-10-20,W,A,2,1,1,2,0,...,1.5,2.5,0.4,0.4,0.5,0.07,2,1.3,0.64,0.3
8,Manchester City,Southampton,2024-10-26,W,H,1,0,1,1,0,...,2.8,2.7,-1.9,-1.9,-1.8,0.13,0,0.1,0.03,0.1
9,Manchester City,Bournemouth,2024-11-02,L,A,1,2,-1,1,0,...,1.0,1.9,-0.6,-0.6,0.0,0.09,0,2.4,0.42,0.4
10,Manchester City,Brighton,2024-11-09,L,A,1,2,-1,1,0,...,1.9,0.7,-1.1,-1.1,-1.9,0.18,0,1.6,0.39,-0.4
11,Manchester City,Tottenham,2024-11-23,L,H,0,4,-4,0,0,...,2.1,1.6,-2.1,-2.1,-2.1,0.09,0,3.4,0.49,-0.6
12,Manchester City,Liverpool,2024-12-01,L,A,0,2,-2,0,0,...,0.4,0.4,-0.8,-0.8,-0.4,0.10,0,2.3,0.29,0.3
13,Manchester City,Nott'ham Forest,2024-12-04,W,H,3,0,3,3,0,...,2.3,1.4,0.6,0.6,0.7,0.14,1,0.5,0.18,0.5
14,Manchester City,Crystal Palace,2024-12-07,D,A,2,2,0,2,0,...,1.3,1.9,0.6,0.6,0.7,0.12,0,1.3,0.42,-0.7
15,Manchester City,Manchester Utd,2024-12-15,L,H,1,2,-1,1,0,...,0.8,0.7,0.1,0.1,-0.8,0.10,0,2.1,0.49,0.1
16,Manchester City,Aston Villa,2024-12-21,L,A,1,2,-1,1,0,...,0.7,0.7,0.0,0.0,-0.7,0.09,0,2.1,0.42,0.1
17,Manchester City,Everton,2024-12-26,D,H,1,1,0,1,0,...,1.0,2.3,-1.1,-0.2,0.0,0.05,1,0.9,0.29,-0.1
18,Manchester City,Leicester City,2024-12-29,W,A,2,0,2,2,0,...,0.9,1.3,0.7,0.7,0.1,0.09,1,0.6,0.18,0.6
19,Manchester City,West Ham,2025-01-04,W,H,4,1,3,3,0,...,1.9,1.1,1.1,1.1,1.1,0.19,0,1.2,0.31,0.2
20,Manchester City,Brentford,2025-01-14,D,A,2,2,0,2,0,...,2.0,1.5,-0.2,-0.2,-1.0,0.11,0,1.5,0.30,-0.5
21,Manchester City,Ipswich Town,2025-01-19,W,A,6,0,6,6,0,...,2.6,1.8,3.0,3.0,2.4,0.18,0,0.5,0.12,0.5
22,Manchester City,Chelsea,2025-01-25,W,H,3,1,2,3,0,...,2.2,0.5,0.8,0.8,0.8,0.17,1,1.8,0.45,0.8
23,Manchester City,Arsenal,2025-02-02,L,A,1,5,-4,1,0,...,0.8,1.2,0.2,0.2,0.2,0.12,0,3.0,0.43,-2.0
24,Manchester City,Newcastle Utd,2025-02-15,W,H,4,0,4,4,0,...,1.9,1.1,2.1,2.1,2.1,0.17,0,0.4,0.38,0.4

In [8]:
df_vs_home= pd.read_csv(f"../Data/vs {home}.csv")
df_vs_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Chelsea,Manchester City,2024-08-18,L,H,0,2,-2,0,0,...,1.0,0.9,-1.0,-1.0,-1.0,0.10,0,0.8,0.16,-1.2
1,Ipswich Town,Manchester City,2024-08-24,L,A,1,4,-3,1,0,...,0.3,0.3,0.7,0.7,0.7,0.29,0,3.5,0.52,-0.5
2,West Ham,Manchester City,2024-08-31,L,H,1,3,-2,0,0,...,0.4,0.6,-0.7,-0.7,-0.4,0.07,0,2.9,0.36,-0.1
3,Brentford,Manchester City,2024-09-14,L,A,1,2,-1,1,0,...,0.6,0.8,0.0,0.0,-0.6,0.12,0,2.0,0.30,0.0
4,Arsenal,Manchester City,2024-09-22,D,A,2,2,0,2,0,...,0.6,0.5,1.3,1.3,1.4,0.13,0,2.2,0.20,0.2
5,Newcastle Utd,Manchester City,2024-09-28,D,H,1,1,0,0,1,...,0.8,0.7,-0.6,-0.8,-0.8,0.08,0,1.4,0.23,0.4
6,Fulham,Manchester City,2024-10-05,L,A,2,3,-1,2,0,...,2.6,2.1,-0.6,-0.6,-0.6,0.24,0,1.3,0.18,-1.7
7,Wolves,Manchester City,2024-10-20,L,H,1,2,-1,1,0,...,0.8,0.3,0.2,0.2,0.2,0.26,0,1.8,0.26,-0.2
8,Southampton,Manchester City,2024-10-26,L,A,0,1,-1,0,0,...,0.2,0.3,-0.2,-0.2,-0.2,0.04,0,0.8,0.11,-0.2
9,Bournemouth,Manchester City,2024-11-02,W,H,2,1,1,2,0,...,1.2,1.0,0.0,0.0,0.8,0.18,0,1.9,0.48,0.9
10,Brighton,Manchester City,2024-11-09,W,H,2,1,1,2,0,...,1.9,1.2,-0.3,-0.3,-0.9,0.23,1,2.6,0.50,1.6
11,Tottenham,Manchester City,2024-11-23,W,A,4,0,4,4,0,...,2.5,1.0,1.5,1.5,1.5,0.28,0,1.1,0.22,1.1
12,Liverpool,Manchester City,2024-12-01,W,H,2,0,2,1,1,...,2.1,1.2,-1.4,-1.6,-1.1,0.16,0,0.9,0.47,0.9
13,Nott'ham Forest,Manchester City,2024-12-04,L,A,0,3,-3,0,0,...,0.6,0.8,-1.0,-1.0,-0.6,0.09,0,3.2,0.53,0.2
14,Crystal Palace,Manchester City,2024-12-07,D,H,2,2,0,2,0,...,1.0,0.8,0.7,0.7,1.0,0.11,0,2.3,0.58,0.3
15,Manchester Utd,Manchester City,2024-12-15,W,A,2,1,1,1,1,...,1.3,0.9,-0.1,-0.3,-0.3,0.14,0,0.9,0.29,-0.1
16,Aston Villa,Manchester City,2024-12-21,W,H,2,1,1,2,0,...,1.2,0.9,0.4,0.4,0.8,0.15,0,1.3,0.22,0.3
17,Everton,Manchester City,2024-12-26,D,A,1,1,0,1,0,...,0.4,0.3,0.3,0.3,-0.4,0.08,0,1.7,0.20,0.7
18,Leicester City,Manchester City,2024-12-29,L,H,0,2,-2,0,0,...,1.0,1.7,-1.3,-1.3,-1.0,0.11,0,1.3,0.27,-0.7
19,West Ham,Manchester City,2025-01-04,L,A,1,4,-3,1,0,...,1.3,1.1,-0.4,-0.4,-0.3,0.08,1,2.5,0.36,-0.5
20,Brentford,Manchester City,2025-01-14,D,H,2,2,0,2,0,...,2.5,1.7,-0.5,-0.5,-0.5,0.14,0,2.2,0.28,0.2
21,Ipswich Town,Manchester City,2025-01-19,L,H,0,6,-6,0,0,...,0.5,0.3,-0.5,-0.5,-0.5,0.06,0,3.8,0.43,-2.2
22,Chelsea,Manchester City,2025-01-25,L,A,1,3,-2,1,0,...,1.7,1.2,-0.8,-0.8,-0.7,0.18,0,2.1,0.39,-0.9
23,Arsenal,Manchester City,2025-02-02,W,H,5,1,4,5,0,...,0.9,0.7,4.0,4.0,3.1,0.08,0,1.0,0.26,0.0
24,Newcastle Utd,Manchester City,2025-02-15,L,A,0,4,-4,0,0,...,0.5,0.2,-0.5,-0.5,-0.5,0.16,0,2.8,0.39,-1.2

In [9]:
df_away= pd.read_csv(f"../Data/{away}.csv")
df_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Liverpool,Ipswich Town,2024-08-17,W,A,2,0,2,2,0,...,2.0,2.4,-0.6,-0.6,-1.0,0.15,0,0.2,0.12,0.2
1,Liverpool,Brentford,2024-08-25,W,H,2,0,2,2,0,...,2.5,1.6,-0.5,-0.5,-0.5,0.14,1,0.8,0.39,0.8
2,Liverpool,Manchester Utd,2024-09-01,W,A,3,0,3,3,0,...,1.4,1.1,1.2,1.2,1.6,0.16,0,0.6,0.21,0.6
3,Liverpool,Nott'ham Forest,2024-09-14,L,H,0,1,-1,0,0,...,0.9,1.4,-0.9,-0.9,-0.9,0.07,0,0.7,0.25,-0.3
4,Liverpool,Bournemouth,2024-09-21,W,H,3,0,3,3,0,...,1.9,1.0,1.0,1.0,1.1,0.11,0,1.5,0.25,1.5
5,Liverpool,Wolves,2024-09-28,W,A,2,1,1,1,1,...,1.1,1.2,-0.5,-0.7,-0.1,0.19,1,1.1,0.37,0.1
6,Liverpool,Crystal Palace,2024-10-05,W,A,1,0,1,1,0,...,1.4,1.5,-0.4,-0.4,-0.4,0.09,0,1.0,0.23,1.0
7,Liverpool,Chelsea,2024-10-20,W,H,2,1,1,1,1,...,1.0,0.3,0.1,-0.1,0.0,0.14,1,0.9,0.43,-0.1
8,Liverpool,Arsenal,2024-10-27,D,A,2,2,0,2,0,...,0.7,1.1,1.2,1.2,1.3,0.09,0,1.7,0.58,-0.3
9,Liverpool,Brighton,2024-11-02,W,H,2,1,1,2,0,...,1.3,1.0,0.4,0.4,0.7,0.10,0,0.5,0.10,-0.5
10,Liverpool,Aston Villa,2024-11-09,W,H,2,0,2,2,0,...,1.3,1.0,0.0,0.0,-0.3,0.14,0,0.6,0.30,0.6
11,Liverpool,Southampton,2024-11-24,W,A,3,2,1,2,1,...,1.5,1.3,-0.1,-0.3,-0.5,0.09,1,1.7,0.19,-0.3
12,Liverpool,Manchester City,2024-12-01,W,H,2,0,2,1,1,...,2.1,1.2,-1.4,-1.6,-1.1,0.16,0,0.9,0.47,0.9
13,Liverpool,Newcastle Utd,2024-12-04,D,A,3,3,0,3,0,...,1.2,1.1,1.1,1.1,1.8,0.12,0,2.5,0.42,-0.5
14,Liverpool,Fulham,2024-12-14,D,H,2,2,0,2,0,...,1.9,1.4,-0.1,-0.1,0.1,0.13,0,1.8,0.60,-0.2
15,Liverpool,Tottenham,2024-12-22,W,A,6,3,3,6,0,...,3.9,2.6,0.4,0.4,0.1,0.26,0,1.9,0.39,-1.1
16,Liverpool,Leicester City,2024-12-26,W,H,3,1,2,3,0,...,1.8,3.0,1.0,1.0,1.2,0.11,0,0.9,0.90,-0.1
17,Liverpool,West Ham,2024-12-29,W,A,5,0,5,5,0,...,2.8,1.5,1.9,1.9,1.2,0.14,0,0.0,NaN,0.0
18,Liverpool,Manchester Utd,2025-01-05,D,H,2,2,0,1,1,...,1.5,1.2,-0.7,-0.9,-0.5,0.11,1,0.4,0.10,-1.6
19,Liverpool,Nott'ham Forest,2025-01-14,D,A,1,1,0,1,0,...,1.6,2.0,-1.0,-1.0,-0.6,0.09,0,0.9,0.31,-0.1
20,Liverpool,Brentford,2025-01-18,W,A,2,0,2,2,0,...,3.3,3.0,-1.4,-1.4,-1.3,0.09,0,0.7,0.11,0.7
21,Liverpool,Ipswich Town,2025-01-25,W,H,4,1,3,4,0,...,1.6,1.5,2.0,2.0,1.4,0.14,0,0.9,0.32,-0.1
22,Liverpool,Bournemouth,2025-02-01,W,A,2,0,2,1,1,...,1.4,1.6,-0.5,-0.7,-0.4,0.10,0,0.8,0.26,0.8
23,Liverpool,Everton,2025-02-12,D,A,2,2,0,2,0,...,0.4,0.3,1.4,1.4,0.6,0.10,0,1.2,0.40,-0.8
24,Liverpool,Wolves,2025-02-16,W,H,2,1,1,1,1,...,0.2,0.6,0.3,0.1,-0.2,0.10,0,1.5,0.37,0.5
25,Liverpool,Aston Villa,2025-02-19,D,A,2,2,0,2,0,...,2.4,1.9,-0.5,-0.5,-0.4,0.15,0,1.4,0.48,-0.6

In [10]:
df_vs_away= pd.read_csv(f"../Data/vs {away}.csv")
df_vs_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Ipswich Town,Liverpool,2024-08-17,L,H,0,2,-2,0,0,...,0.3,0.2,-0.5,-0.5,-0.3,0.06,0,2.3,0.47,0.3
1,Brentford,Liverpool,2024-08-25,L,A,0,2,-2,0,0,...,0.5,0.4,-0.5,-0.5,-0.5,0.07,0,2.8,0.35,0.8
2,Manchester Utd,Liverpool,2024-09-01,L,H,0,3,-3,0,0,...,1.3,1.0,-1.4,-1.4,-1.3,0.17,0,2.4,0.81,-0.6
3,Nott'ham Forest,Liverpool,2024-09-14,W,A,1,0,1,1,0,...,0.4,0.2,0.6,0.6,0.6,0.09,0,0.6,0.11,0.6
4,Bournemouth,Liverpool,2024-09-21,L,A,0,3,-3,0,0,...,0.9,0.7,-1.1,-1.1,-0.9,0.06,1,3.8,0.32,0.8
5,Wolves,Liverpool,2024-09-28,L,H,1,2,-1,1,0,...,0.2,0.3,0.4,0.4,-0.2,0.08,0,1.5,0.15,-0.5
6,Crystal Palace,Liverpool,2024-10-05,L,H,0,1,-1,0,0,...,0.6,0.5,-0.6,-0.6,-0.6,0.07,0,0.5,0.13,-0.5
7,Chelsea,Liverpool,2024-10-20,L,A,1,2,-1,1,0,...,0.7,0.9,0.0,0.0,0.3,0.08,1,2.0,0.24,0.0
8,Arsenal,Liverpool,2024-10-27,D,H,2,2,0,2,0,...,0.9,1.2,1.1,1.1,1.1,0.10,0,1.8,0.45,-0.2
9,Brighton,Liverpool,2024-11-02,L,A,1,2,-1,1,0,...,0.8,1.0,0.0,0.0,0.2,0.08,2,1.8,0.23,-0.2
10,Aston Villa,Liverpool,2024-11-09,L,A,0,2,-2,0,0,...,0.9,0.6,-1.2,-1.2,-0.9,0.12,0,1.2,0.25,-0.8
11,Southampton,Liverpool,2024-11-24,L,H,2,3,-1,2,0,...,0.3,0.7,0.7,1.7,0.7,0.06,0,4.1,0.28,1.1
12,Manchester City,Liverpool,2024-12-01,L,A,0,2,-2,0,0,...,0.4,0.4,-0.8,-0.8,-0.4,0.10,0,2.3,0.29,0.3
13,Newcastle Utd,Liverpool,2024-12-04,D,H,3,3,0,3,0,...,1.6,0.8,0.9,0.9,1.4,0.12,1,3.4,0.69,0.4
14,Fulham,Liverpool,2024-12-14,D,A,2,2,0,2,0,...,1.1,0.7,0.8,0.8,0.9,0.10,1,1.4,0.36,-0.6
15,Tottenham,Liverpool,2024-12-22,L,H,3,6,-3,3,0,...,1.1,0.8,1.7,1.7,0.9,0.14,0,5.4,0.49,-0.6
16,Leicester City,Liverpool,2024-12-26,L,A,1,3,-2,1,0,...,0.3,0.2,0.7,0.7,0.7,0.09,0,2.3,0.33,-0.7
17,West Ham,Liverpool,2024-12-29,L,H,0,5,-5,0,0,...,0.3,0.4,-0.4,-0.4,-0.3,0.05,0,4.1,0.31,-0.9
18,Manchester Utd,Liverpool,2025-01-05,D,A,2,2,0,2,0,...,0.7,1.2,1.0,1.0,0.3,0.08,0,1.8,0.20,-0.2
19,Nott'ham Forest,Liverpool,2025-01-14,D,H,1,1,0,1,0,...,0.2,0.2,0.7,0.7,0.8,0.05,1,1.9,0.32,0.9
20,Brentford,Liverpool,2025-01-18,L,H,0,2,-2,0,0,...,0.6,1.0,-0.7,-0.7,-0.6,0.07,0,2.2,0.28,0.2
21,Ipswich Town,Liverpool,2025-01-25,L,A,1,4,-3,1,0,...,0.4,0.3,0.5,0.5,0.6,0.16,0,2.8,0.51,-1.2
22,Bournemouth,Liverpool,2025-02-01,L,H,0,2,-2,0,0,...,0.9,0.7,-1.6,-1.6,-0.9,0.11,0,2.3,0.21,0.3
23,Everton,Liverpool,2025-02-12,D,H,2,2,0,2,0,...,0.9,0.4,1.0,1.0,1.1,0.10,0,1.6,0.39,-0.4
24,Wolves,Liverpool,2025-02-16,L,A,1,2,-1,1,0,...,1.3,1.0,-0.5,-0.5,-0.3,0.09,2,1.4,0.16,-0.6
25,Aston Villa,Liverpool,2025-02-19,D,H,2,2,0,2,0,...,0.4,0.7,1.4,1.4,0.6,0.07,0,1.4,0.47,-0.6

In [11]:
print(list(df_away.columns))

['Team', 'Opp', 'Date', 'Result', 'H/A', 'GF', 'GA', 'GD', 'G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att (GK)', 'Thr', 'Pa Launch%', 'Pa AvgLen', 'Won', 'Lost', 'Won%', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 'PrgC', 'Last3rd Car', 'OppCr', 'Stp', 'Stp%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'GK Att', 'Launch%', 'AvgLen', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'PKcon', 'OG', 'Recov', '#OPA', 'AvgDist', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'PKdef', 'PKA', 'PKms', 'Missed PK%', 'PKAg', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 'Fld Sc', 'Def-Sc', 'SoTA', 'Saves', 'Save%', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'xG', 'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'PSxG', 'PSxG/SoT', 'PSxG+/-']

# Features

## Offense

In [12]:
offense= ['G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 
          'PrgC', 'Last3rd Car', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'Sh', 'G/Sh', 
          'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 
          'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 
          'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 
          'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 
          'Fld Sc', 'Def-Sc', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'xG', 
          'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'GF']

In [13]:
df_home_off= df_home[offense]
df_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,2,0,0,52,0,30,15,50.0,8,26.7,...,-0.2,-0.2,0.6,0.9,1.2,1.2,0.4,0.07,0,2
1,3,1,0,75,1,20,11,55.0,7,35.0,...,3.1,2.3,2.3,1.9,0.7,0.4,-0.3,0.20,1,4
2,3,0,0,67,0,19,12,63.2,3,15.8,...,2.3,2.3,2.7,2.7,0.0,0.0,0.3,0.13,1,3
3,2,0,0,54,0,14,3,21.4,8,57.1,...,1.1,1.1,2.0,1.5,-0.1,-0.1,-1.0,0.12,0,2
4,2,0,0,77,0,21,10,47.6,9,42.9,...,1.5,1.5,1.7,2.9,-0.1,-0.1,-0.7,0.07,1,2
5,1,0,0,62,0,24,13,54.2,7,29.2,...,-0.7,0.1,0.8,1.4,0.1,0.1,0.2,0.06,0,1
6,3,0,0,58,0,28,11,39.3,13,46.4,...,-1.0,-1.0,1.3,1.3,1.4,1.4,0.7,0.08,1,3
7,2,0,0,77,0,30,10,33.3,12,40.0,...,0.8,0.8,1.5,2.5,0.4,0.4,0.5,0.07,2,2
8,1,0,0,57,0,12,9,75.0,2,16.7,...,2.7,2.7,2.8,2.7,-1.9,-1.9,-1.8,0.13,0,1
9,1,0,0,64,0,17,6,35.3,6,35.3,...,-0.5,-0.5,1.0,1.9,-0.6,-0.6,0.0,0.09,0,1
10,1,0,0,60,0,25,15,60.0,4,16.0,...,-0.1,-0.1,1.9,0.7,-1.1,-1.1,-1.9,0.18,0,1
11,0,0,0,58,0,15,9,60.0,5,33.3,...,-0.4,-0.4,2.1,1.6,-2.1,-2.1,-2.1,0.09,0,0
12,0,0,0,56,0,25,13,52.0,10,40.0,...,-2.6,-1.8,0.4,0.4,-0.8,-0.8,-0.4,0.10,0,0
13,3,0,0,66,0,27,13,48.1,9,33.3,...,1.3,1.3,2.3,1.4,0.6,0.6,0.7,0.14,1,3
14,2,0,0,68,0,12,5,41.7,6,50.0,...,0.1,0.1,1.3,1.9,0.6,0.6,0.7,0.12,0,2
15,1,0,0,52,0,22,9,40.9,12,54.5,...,-1.2,-0.4,0.8,0.7,0.1,0.1,-0.8,0.10,0,1
16,1,0,0,56,0,20,8,40.0,9,45.0,...,-0.5,-0.5,0.7,0.7,0.0,0.0,-0.7,0.09,0,1
17,1,0,1,66,1,24,13,54.2,8,33.3,...,1.4,0.6,1.0,2.3,-1.1,-0.2,0.0,0.05,1,1
18,2,0,0,47,0,12,5,41.7,7,58.3,...,0.0,0.0,0.9,1.3,0.7,0.7,0.1,0.09,1,2
19,3,0,0,56,0,12,6,50.0,3,25.0,...,0.5,0.5,1.9,1.1,1.1,1.1,1.1,0.19,0,4
20,2,0,0,55,0,12,6,50.0,5,41.7,...,-0.4,-0.4,2.0,1.5,-0.2,-0.2,-1.0,0.11,0,2
21,6,0,0,67,0,15,9,60.0,5,33.3,...,2.5,2.5,2.6,1.8,3.0,3.0,2.4,0.18,0,6
22,3,0,0,56,0,16,9,56.3,7,43.8,...,0.4,0.4,2.2,0.5,0.8,0.8,0.8,0.17,1,3
23,1,0,0,54,0,8,2,25.0,4,50.0,...,-0.2,-0.2,0.8,1.2,0.2,0.2,0.2,0.12,0,1
24,4,0,0,61,0,28,8,28.6,17,60.7,...,1.4,1.4,1.9,1.1,2.1,2.1,2.1,0.17,0,4

In [14]:
df_vs_home_off= df_vs_home[offense]
df_vs_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,0,0,0,48,0,11,4,36.4,7,63.6,...,0.2,0.2,1.0,0.9,-1.0,-1.0,-1.0,0.10,0,0
1,1,0,0,25,0,8,2,25.0,6,75.0,...,-3.1,-2.3,0.3,0.3,0.7,0.7,0.7,0.29,0,1
2,0,0,0,33,0,17,10,58.8,5,29.4,...,-2.3,-2.3,0.4,0.6,-0.7,-0.7,-0.4,0.07,0,1
3,1,0,0,46,0,11,3,27.3,6,54.5,...,-1.1,-1.1,0.6,0.8,0.0,0.0,-0.6,0.12,0,1
4,2,0,0,23,0,11,4,36.4,4,36.4,...,-1.5,-1.5,0.6,0.5,1.3,1.3,1.4,0.13,0,2
5,0,1,0,38,1,12,8,66.7,2,16.7,...,0.7,-0.1,0.8,0.7,-0.6,-0.8,-0.8,0.08,0,1
6,2,0,0,42,0,12,5,41.7,6,50.0,...,1.0,1.0,2.6,2.1,-0.6,-0.6,-0.6,0.24,0,2
7,1,0,0,23,0,9,4,44.4,4,44.4,...,-0.8,-0.8,0.8,0.3,0.2,0.2,0.2,0.26,0,1
8,0,0,0,43,0,17,6,35.3,9,52.9,...,-2.7,-2.7,0.2,0.3,-0.2,-0.2,-0.2,0.04,0,0
9,2,0,0,36,0,20,11,55.0,5,25.0,...,0.5,0.5,1.2,1.0,0.0,0.0,0.8,0.18,0,2
10,2,0,0,40,0,11,2,18.2,5,45.5,...,0.1,0.1,1.9,1.2,-0.3,-0.3,-0.9,0.23,1,2
11,4,0,0,42,0,16,8,50.0,8,50.0,...,0.4,0.4,2.5,1.0,1.5,1.5,1.5,0.28,0,4
12,1,1,0,44,1,16,5,31.3,9,56.3,...,2.6,1.8,2.1,1.2,-1.4,-1.6,-1.1,0.16,0,2
13,0,0,0,34,0,13,5,38.5,5,38.5,...,-1.3,-1.3,0.6,0.8,-1.0,-1.0,-0.6,0.09,0,0
14,2,0,0,32,0,11,6,54.5,3,27.3,...,-0.1,-0.1,1.0,0.8,0.7,0.7,1.0,0.11,0,2
15,1,1,0,48,1,16,8,50.0,7,43.8,...,1.2,0.4,1.3,0.9,-0.1,-0.3,-0.3,0.14,0,2
16,2,0,0,44,0,11,6,54.5,3,27.3,...,0.5,0.5,1.2,0.9,0.4,0.4,0.8,0.15,0,2
17,1,0,0,34,0,19,7,36.8,9,47.4,...,-1.4,-0.6,0.4,0.3,0.3,0.3,-0.4,0.08,0,1
18,0,0,0,53,0,16,9,56.3,6,37.5,...,0.0,0.0,1.0,1.7,-1.3,-1.3,-1.0,0.11,0,0
19,1,0,0,44,0,17,6,35.3,9,52.9,...,-0.5,-0.5,1.3,1.1,-0.4,-0.4,-0.3,0.08,1,1
20,2,0,0,45,0,9,4,44.4,5,55.6,...,0.4,0.4,2.5,1.7,-0.5,-0.5,-0.5,0.14,0,2
21,0,0,0,33,0,19,7,36.8,7,36.8,...,-2.5,-2.5,0.5,0.3,-0.5,-0.5,-0.5,0.06,0,0
22,1,0,0,44,0,20,11,55.0,8,40.0,...,-0.4,-0.4,1.7,1.2,-0.8,-0.8,-0.7,0.18,0,1
23,5,0,0,46,0,12,9,75.0,2,16.7,...,0.2,0.2,0.9,0.7,4.0,4.0,3.1,0.08,0,5
24,0,0,0,39,0,5,1,20.0,3,60.0,...,-1.4,-1.4,0.5,0.2,-0.5,-0.5,-0.5,0.16,0,0

In [15]:
df_away_off= df_away[offense]
df_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,2,0,0,62,0,23,11,47.8,11,47.8,...,2.1,2.1,2.0,2.4,-0.6,-0.6,-1.0,0.15,0,2
1,2,0,0,62,0,16,8,50.0,5,31.3,...,2.0,2.0,2.5,1.6,-0.5,-0.5,-0.5,0.14,1,2
2,3,0,0,47,0,20,5,25.0,14,70.0,...,0.4,0.4,1.4,1.1,1.2,1.2,1.6,0.16,0,3
3,0,0,0,68,0,20,6,30.0,13,65.0,...,0.5,0.5,0.9,1.4,-0.9,-0.9,-0.9,0.07,0,0
4,3,0,0,58,0,21,16,76.2,5,23.8,...,0.9,0.9,1.9,1.0,1.0,1.0,1.1,0.11,0,3
5,1,1,0,55,1,12,4,33.3,7,58.3,...,1.9,1.1,1.1,1.2,-0.5,-0.7,-0.1,0.19,1,2
6,1,0,0,68,0,9,8,88.9,0,0.0,...,0.8,0.8,1.4,1.5,-0.4,-0.4,-0.4,0.09,0,1
7,1,1,0,43,1,10,5,50.0,4,40.0,...,0.9,0.2,1.0,0.3,0.1,-0.1,0.0,0.14,1,2
8,2,0,0,55,0,18,9,50.0,4,22.2,...,-0.1,-0.1,0.7,1.1,1.2,1.2,1.3,0.09,0,2
9,2,0,0,49,0,16,8,50.0,8,50.0,...,0.6,0.6,1.3,1.0,0.4,0.4,0.7,0.10,0,2
10,2,0,0,62,0,15,9,60.0,6,40.0,...,0.8,0.8,1.3,1.0,0.0,0.0,-0.3,0.14,0,2
11,2,1,0,62,1,17,10,58.8,4,23.5,...,1.8,2.0,1.5,1.3,-0.1,-0.3,-0.5,0.09,1,3
12,1,1,0,44,1,16,5,31.3,9,56.3,...,2.6,1.8,2.1,1.2,-1.4,-1.6,-1.1,0.16,0,2
13,3,0,0,58,0,17,7,41.2,9,52.9,...,-0.1,-0.1,1.2,1.1,1.1,1.1,1.8,0.12,0,3
14,2,0,0,61,0,23,12,52.2,10,43.5,...,0.9,0.9,1.9,1.4,-0.1,-0.1,0.1,0.13,0,2
15,6,0,0,48,0,14,5,35.7,7,50.0,...,4.3,4.3,3.9,2.6,0.4,0.4,0.1,0.26,0,6
16,3,0,0,68,0,9,5,55.6,4,44.4,...,1.7,1.7,1.8,3.0,1.0,1.0,1.2,0.11,0,3
17,5,0,0,54,0,17,10,58.8,7,41.2,...,2.8,2.8,2.8,1.5,1.9,1.9,1.2,0.14,0,5
18,1,1,0,53,1,23,13,56.5,9,39.1,...,1.7,0.9,1.5,1.2,-0.7,-0.9,-0.5,0.11,1,2
19,1,0,0,70,0,19,4,21.1,13,68.4,...,1.7,1.7,1.6,2.0,-1.0,-1.0,-0.6,0.09,0,1
20,2,0,0,60,0,19,7,36.8,9,47.4,...,2.7,2.7,3.3,3.0,-1.4,-1.4,-1.3,0.09,0,2
21,4,0,0,70,0,24,16,66.7,7,29.2,...,1.5,1.5,1.6,1.5,2.0,2.0,1.4,0.14,0,4
22,1,1,0,51,1,15,6,40.0,6,40.0,...,0.9,0.1,1.4,1.6,-0.5,-0.7,-0.4,0.10,0,2
23,2,0,0,63,0,15,8,53.3,7,46.7,...,-0.4,-0.4,0.4,0.3,1.4,1.4,0.6,0.10,0,2
24,1,1,0,50,1,16,4,25.0,8,50.0,...,0.2,-0.6,0.2,0.6,0.3,0.1,-0.2,0.10,0,2
25,2,0,0,48,0,22,7,31.8,15,68.2,...,1.9,1.9,2.4,1.9,-0.5,-0.5,-0.4,0.15,0,2

In [16]:
df_vs_away_off= df_vs_away[offense]
df_vs_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,0,0,0,38,0,10,3,30.0,5,50.0,...,-2.1,-2.1,0.3,0.2,-0.5,-0.5,-0.3,0.06,0,0
1,0,0,0,38,0,22,6,27.3,13,59.1,...,-2.0,-2.0,0.5,0.4,-0.5,-0.5,-0.5,0.07,0,0
2,0,0,0,53,0,22,8,36.4,13,59.1,...,-0.4,-0.4,1.3,1.0,-1.4,-1.4,-1.3,0.17,0,0
3,1,0,0,32,0,14,6,42.9,5,35.7,...,-0.5,-0.5,0.4,0.2,0.6,0.6,0.6,0.09,0,1
4,0,0,0,42,0,23,11,47.8,12,52.2,...,-0.9,-0.9,0.9,0.7,-1.1,-1.1,-0.9,0.06,1,0
5,1,0,0,45,0,12,7,58.3,4,33.3,...,-1.9,-1.1,0.2,0.3,0.4,0.4,-0.2,0.08,0,1
6,0,0,0,32,0,11,4,36.4,7,63.6,...,-0.8,-0.8,0.6,0.5,-0.6,-0.6,-0.6,0.07,0,0
7,1,0,0,57,0,29,10,34.5,17,58.6,...,-0.9,-0.2,0.7,0.9,0.0,0.0,0.3,0.08,1,1
8,2,0,0,45,0,13,6,46.2,6,46.2,...,0.1,0.1,0.9,1.2,1.1,1.1,1.1,0.10,0,2
9,1,0,0,51,0,26,8,30.8,17,65.4,...,-0.6,-0.6,0.8,1.0,0.0,0.0,0.2,0.08,2,1
10,0,0,0,38,0,16,11,68.8,3,18.8,...,-0.8,-0.8,0.9,0.6,-1.2,-1.2,-0.9,0.12,0,0
11,2,0,1,38,1,26,9,34.6,13,50.0,...,-1.8,-2.0,0.3,0.7,0.7,1.7,0.7,0.06,0,2
12,0,0,0,56,0,25,13,52.0,10,40.0,...,-2.6,-1.8,0.4,0.4,-0.8,-0.8,-0.4,0.10,0,0
13,3,0,0,42,0,31,12,38.7,9,29.0,...,0.1,0.1,1.6,0.8,0.9,0.9,1.4,0.12,1,3
14,2,0,0,39,0,19,7,36.8,9,47.4,...,-0.9,-0.9,1.1,0.7,0.8,0.8,0.9,0.10,1,2
15,3,0,0,52,0,26,10,38.5,15,57.7,...,-4.3,-4.3,1.1,0.8,1.7,1.7,0.9,0.14,0,3
16,1,0,0,32,0,12,1,8.3,9,75.0,...,-1.7,-1.7,0.3,0.2,0.7,0.7,0.7,0.09,0,1
17,0,0,0,46,0,19,7,36.8,9,47.4,...,-2.8,-2.8,0.3,0.4,-0.4,-0.4,-0.3,0.05,0,0
18,2,0,0,47,0,17,10,58.8,5,29.4,...,-1.7,-0.9,0.7,1.2,1.0,1.0,0.3,0.08,0,2
19,1,0,0,30,0,18,6,33.3,7,38.9,...,-1.7,-1.7,0.2,0.2,0.7,0.7,0.8,0.05,1,1
20,0,0,0,40,0,14,8,57.1,1,7.1,...,-2.7,-2.7,0.6,1.0,-0.7,-0.7,-0.6,0.07,0,0
21,1,0,0,30,0,17,8,47.1,8,47.1,...,-1.5,-1.5,0.4,0.3,0.5,0.5,0.6,0.16,0,1
22,0,0,0,49,0,27,12,44.4,12,44.4,...,-0.9,-0.1,0.9,0.7,-1.6,-1.6,-0.9,0.11,0,0
23,2,0,0,37,0,14,4,28.6,10,71.4,...,0.4,0.4,0.9,0.4,1.0,1.0,1.1,0.10,0,2
24,1,0,0,50,0,27,10,37.0,13,48.1,...,-0.2,0.6,1.3,1.0,-0.5,-0.5,-0.3,0.09,2,1
25,2,0,0,52,0,23,14,60.9,9,39.1,...,-1.9,-1.9,0.4,0.7,1.4,1.4,0.6,0.07,0,2

## Defence

In [17]:
defence= ['OppCr', 'Stp', 'Stp%', 'PKcon', '#OPA', 'AvgDist', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'SoTA', 'Saves', 
          'Save%', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 
          'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',  'PSxG', 'PSxG/SoT', 'PSxG+/-', 'GA']

In [18]:
df_home_def= df_home[defence]
df_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,12,1,8.3,0,0,11.0,0,NaN,0,0,...,4,2,10,26,18,0,0.7,0.23,0.7,0
1,5,0,0.0,0,1,19.5,0,NaN,0,0,...,0,8,6,20,9,0,0.3,0.29,-0.7,1
2,10,0,0.0,0,2,24.0,0,NaN,0,0,...,3,11,7,22,19,1,0.2,0.09,0.2,1
3,9,0,0.0,0,6,16.3,0,NaN,0,0,...,1,7,5,17,13,3,2.1,0.46,1.1,1
4,7,0,0.0,0,2,23.3,0,NaN,0,1,...,0,2,3,13,9,1,1.5,0.49,-0.5,2
5,13,0,0.0,1,0,11.0,0,0.0,0,0,...,3,5,7,22,21,0,1.1,0.11,0.1,1
6,11,0,0.0,0,3,23.8,0,NaN,0,0,...,4,7,4,14,20,1,2.5,0.62,0.5,2
7,3,0,0.0,0,3,22.0,0,NaN,0,0,...,0,6,3,17,5,0,1.3,0.64,0.3,1
8,1,0,0.0,0,1,17.0,0,NaN,0,0,...,1,5,10,22,14,0,0.1,0.03,0.1,0
9,12,1,8.3,0,0,11.5,0,NaN,0,0,...,2,7,5,19,9,1,2.4,0.42,0.4,2
10,6,2,33.3,0,5,20.4,0,NaN,0,0,...,2,5,4,16,8,0,1.6,0.39,-0.4,2
11,5,0,0.0,0,0,9.0,0,NaN,0,0,...,0,10,9,22,13,2,3.4,0.49,-0.6,4
12,12,0,0.0,1,4,30.3,0,0.0,0,0,...,4,6,5,22,23,3,2.3,0.29,0.3,2
13,11,0,0.0,0,2,14.3,0,NaN,0,0,...,2,7,5,21,15,2,0.5,0.18,0.5,0
14,11,1,9.1,0,0,12.5,0,NaN,0,1,...,8,7,7,21,18,1,1.3,0.42,-0.7,2
15,9,0,0.0,1,0,11.8,0,0.0,0,0,...,3,8,10,24,10,0,2.1,0.49,0.1,2
16,6,0,0.0,0,1,18.5,0,NaN,0,0,...,2,9,5,11,15,1,2.1,0.42,0.1,2
17,8,0,0.0,0,2,17.3,0,NaN,0,0,...,2,5,1,17,13,1,0.9,0.29,-0.1,1
18,13,0,0.0,0,0,NaN,0,NaN,0,0,...,3,3,5,15,17,1,0.6,0.18,0.6,0
19,11,0,0.0,0,0,5.5,0,NaN,0,0,...,3,6,6,18,18,0,1.2,0.31,0.2,1
20,14,1,7.1,0,0,13.3,0,NaN,0,0,...,4,7,9,21,32,0,1.5,0.30,-0.5,2
21,11,4,36.4,0,2,13.0,0,NaN,0,0,...,3,2,7,21,11,0,0.5,0.12,0.5,0
22,5,1,20.0,0,3,20.3,0,NaN,0,0,...,3,7,6,19,17,1,1.8,0.45,0.8,1
23,10,0,0.0,0,0,7.8,0,NaN,0,0,...,3,5,6,20,20,4,3.0,0.43,-2.0,5
24,12,0,0.0,0,2,19.7,0,NaN,0,0,...,1,10,6,16,20,1,0.4,0.38,0.4,0

In [19]:
df_vs_home_def= df_vs_home[defence]
df_vs_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,6,1,16.7,0,0,9.8,0,NaN,0,0,...,3,7,10,30,13,1,0.8,0.16,-1.2,2
1,15,0,0.0,1,3,20.0,0,0.0,0,0,...,3,13,10,27,41,2,3.5,0.52,-0.5,4
2,15,1,6.7,0,0,5.5,0,NaN,0,0,...,5,8,6,17,20,1,2.9,0.36,-0.1,3
3,9,2,22.2,0,3,19.4,0,NaN,0,0,...,4,9,9,29,24,1,2.0,0.30,0.0,2
4,18,3,16.7,0,0,6.0,0,NaN,0,1,...,13,8,4,20,41,1,2.2,0.20,0.2,2
5,16,1,6.3,0,1,14.0,0,NaN,0,0,...,6,6,10,25,23,1,1.4,0.23,0.4,1
6,12,1,8.3,0,0,7.3,0,NaN,0,1,...,6,13,7,30,22,1,1.3,0.18,-1.7,3
7,28,3,10.7,0,0,4.3,0,NaN,0,1,...,7,17,6,32,50,0,1.8,0.26,-0.2,2
8,19,1,5.3,0,0,6.8,0,NaN,0,0,...,8,8,6,20,30,1,0.8,0.11,-0.2,1
9,19,0,0.0,0,0,5.0,0,NaN,0,1,...,4,4,12,28,39,0,1.9,0.48,0.9,1
10,10,1,10.0,0,3,18.6,0,NaN,0,0,...,3,11,12,28,21,0,2.6,0.50,1.6,1
11,25,3,12.0,0,0,3.5,0,NaN,0,0,...,7,5,5,18,29,1,1.1,0.22,1.1,0
12,6,0,0.0,0,0,NaN,0,NaN,0,0,...,3,8,6,28,13,2,0.9,0.47,0.9,0
13,12,0,0.0,0,1,16.5,0,NaN,0,0,...,3,7,14,38,19,0,3.2,0.53,0.2,3
14,14,1,7.1,0,1,17.0,0,NaN,0,0,...,4,11,6,24,24,0,2.3,0.58,0.3,2
15,13,0,0.0,0,1,11.3,0,NaN,0,1,...,3,11,17,41,19,1,0.9,0.29,-0.1,1
16,10,1,10.0,0,0,10.7,0,NaN,0,0,...,1,6,4,26,16,1,1.3,0.22,0.3,1
17,15,2,13.3,1,2,14.2,1,100.0,0,0,...,10,3,7,24,37,0,1.7,0.20,0.7,1
18,7,0,0.0,0,0,NaN,0,NaN,0,0,...,3,7,9,23,12,0,1.3,0.27,-0.7,2
19,10,1,10.0,0,1,10.6,0,NaN,0,0,...,3,8,7,20,18,2,2.5,0.36,-0.5,4
20,14,0,0.0,0,0,9.0,0,NaN,0,0,...,2,6,9,19,22,1,2.2,0.28,0.2,2
21,6,1,16.7,0,0,6.5,0,NaN,0,0,...,4,7,8,21,20,4,3.8,0.43,-2.2,6
22,5,0,0.0,0,3,22.4,0,NaN,0,0,...,3,7,4,16,12,2,2.1,0.39,-0.9,3
23,9,0,0.0,0,0,3.0,0,NaN,0,0,...,0,5,5,21,22,0,1.0,0.26,0.0,1
24,10,2,20.0,0,3,17.8,0,NaN,0,1,...,2,7,7,33,21,1,2.8,0.39,-1.2,4

In [20]:
df_away_def= df_away[defence]
df_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,4,0,0.0,0,1,19.5,0,NaN,0,0,...,2,12,5,14,17,1,0.2,0.12,0.2,0
1,6,0,0.0,0,0,7.5,0,NaN,0,0,...,3,11,7,24,12,0,0.8,0.39,0.8,0
2,14,1,7.1,0,5,17.7,0,NaN,0,0,...,0,13,10,34,28,0,0.6,0.21,0.6,0
3,5,0,0.0,0,1,21.3,0,NaN,0,0,...,0,5,11,23,16,0,0.7,0.25,-0.3,1
4,17,1,5.9,0,0,10.0,0,NaN,0,0,...,4,6,6,26,24,1,1.5,0.25,1.5,0
5,13,1,7.7,0,2,14.6,0,NaN,0,0,...,2,9,7,17,12,1,1.1,0.37,0.1,1
6,8,0,0.0,0,1,13.1,0,NaN,0,0,...,0,4,13,26,15,0,1.0,0.23,1.0,0
7,14,0,0.0,0,1,17.0,0,NaN,0,0,...,4,7,6,31,18,0,0.9,0.43,-0.1,1
8,7,0,0.0,0,0,8.3,0,NaN,0,0,...,2,7,5,21,22,0,1.7,0.58,-0.3,2
9,10,0,0.0,0,2,20.8,0,NaN,0,0,...,4,8,10,38,15,0,0.5,0.10,-0.5,1
10,17,2,11.8,0,0,7.0,0,NaN,0,0,...,2,9,7,19,19,1,0.6,0.30,0.6,0
11,3,0,0.0,1,4,24.2,1,100.0,0,0,...,0,3,8,24,6,0,1.7,0.19,-0.3,2
12,6,0,0.0,0,0,NaN,0,NaN,0,0,...,3,8,6,28,13,2,0.9,0.47,0.9,0
13,13,1,7.7,0,1,13.5,0,NaN,0,0,...,4,9,10,33,23,3,2.5,0.42,-0.5,3
14,9,1,11.1,0,5,21.6,0,NaN,0,0,...,4,3,9,24,8,0,1.8,0.60,-0.2,2
15,9,0,0.0,0,1,16.2,0,NaN,0,0,...,1,11,15,42,22,1,1.9,0.39,-1.1,3
16,6,0,0.0,0,0,11.0,0,NaN,0,0,...,1,8,8,26,9,0,0.9,0.90,-0.1,1
17,6,0,0.0,0,1,8.8,0,NaN,0,0,...,3,8,4,27,13,0,0.0,NaN,0.0,0
18,19,1,5.3,0,4,13.6,0,NaN,0,0,...,8,8,14,20,26,0,0.4,0.10,-1.6,2
19,4,0,0.0,0,1,28.0,0,NaN,0,0,...,2,3,2,12,32,0,0.9,0.31,-0.1,1
20,8,0,0.0,0,1,19.0,0,NaN,0,0,...,1,4,4,14,19,0,0.7,0.11,0.7,0
21,7,0,0.0,0,0,9.7,0,NaN,0,1,...,0,10,3,19,8,0,0.9,0.32,-0.1,1
22,13,1,7.7,0,4,13.0,0,NaN,0,0,...,3,8,11,29,26,4,0.8,0.26,0.8,0
23,14,0,0.0,0,1,12.0,0,NaN,0,0,...,2,5,8,26,37,0,1.2,0.40,-0.8,2
24,7,0,0.0,0,2,15.0,0,NaN,0,0,...,5,3,15,31,19,3,1.5,0.37,0.5,1
25,14,2,14.3,0,2,11.7,0,NaN,0,0,...,3,9,8,24,25,0,1.4,0.48,-0.6,2

In [21]:
df_vs_away_def= df_vs_away[defence]
df_vs_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,16,1,6.3,0,1,13.8,0,NaN,0,0,...,6,9,9,29,28,0,2.3,0.47,0.3,2
1,14,0,0.0,0,2,17.5,0,NaN,0,0,...,7,4,5,15,15,0,2.8,0.35,0.8,2
2,6,0,0.0,0,3,27.3,0,NaN,0,0,...,1,5,7,39,10,4,2.4,0.81,-0.6,3
3,16,1,6.3,0,1,12.0,0,NaN,0,0,...,3,8,11,33,32,2,0.6,0.11,0.6,0
4,6,1,16.7,0,2,10.5,0,NaN,0,0,...,4,8,7,27,16,1,3.8,0.32,0.8,3
5,16,2,12.5,1,2,12.3,0,0.0,0,1,...,1,6,9,23,23,1,1.5,0.15,-0.5,2
6,11,0,0.0,0,3,17.5,0,NaN,0,0,...,5,10,5,13,27,0,0.5,0.13,-0.5,1
7,3,0,0.0,1,1,14.3,0,0.0,0,0,...,0,7,8,20,12,0,2.0,0.24,0.0,2
8,21,1,4.8,0,0,6.5,0,NaN,0,1,...,2,8,7,24,28,1,1.8,0.45,-0.2,2
9,18,0,0.0,0,2,19.0,0,NaN,0,0,...,6,6,9,27,27,0,1.8,0.23,-0.2,2
10,8,0,0.0,0,0,NaN,0,NaN,0,0,...,3,7,6,22,18,1,1.2,0.25,-0.8,2
11,28,3,10.7,1,0,6.5,0,0.0,0,0,...,9,8,5,20,33,5,4.1,0.28,1.1,3
12,12,0,0.0,1,4,30.3,0,0.0,0,0,...,4,6,5,22,23,3,2.3,0.29,0.3,2
13,13,3,23.1,0,2,16.2,0,NaN,0,0,...,6,6,5,19,17,1,3.4,0.69,0.4,3
14,26,1,3.8,0,2,12.5,0,NaN,0,0,...,5,6,7,22,30,1,1.4,0.36,-0.6,2
15,15,0,0.0,0,0,7.3,0,NaN,0,0,...,5,7,8,28,24,4,5.4,0.49,-0.6,6
16,44,3,6.8,0,0,4.4,0,NaN,0,0,...,6,7,15,28,49,0,2.3,0.33,-0.7,3
17,17,0,0.0,0,2,16.0,0,NaN,0,0,...,2,8,11,28,21,2,4.1,0.31,-0.9,5
18,13,1,7.7,1,0,3.7,0,0.0,0,0,...,4,5,13,33,26,0,1.8,0.20,-0.2,2
19,27,1,3.7,0,0,11.0,0,NaN,0,1,...,7,11,9,29,59,0,1.9,0.32,0.9,1
20,30,2,6.7,0,0,4.3,0,NaN,0,0,...,14,13,10,22,36,0,2.2,0.28,0.2,2
21,19,3,15.8,0,0,4.2,0,NaN,0,0,...,3,7,13,35,37,0,2.8,0.51,-1.2,4
22,7,1,14.3,1,3,20.0,0,0.0,0,0,...,7,6,10,29,27,1,2.3,0.21,0.3,2
23,10,0,0.0,0,0,17.0,0,NaN,0,0,...,2,5,8,27,43,0,1.6,0.39,-0.4,2
24,10,0,0.0,1,1,14.4,0,0.0,0,0,...,1,6,9,24,22,1,1.4,0.16,-0.6,2
25,15,1,6.7,0,3,18.8,0,NaN,0,0,...,4,10,3,25,25,2,1.4,0.47,-0.6,2

## Combined

In [22]:
combined= ['Won', 'Lost', 'Won%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Recov']

In [23]:
df_home_cmb= df_home[combined]
df_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0     5     3  62.5     1     0      0    9   12     41
1     5     7  41.7     2     0      0    4   15     32
2     7     9  43.8     2     0      0    3   10     43
3     6    11  35.3     3     0      0    9    3     38
4    16    11  59.3     3     0      0    7   10     39
5     6    13  31.6     4     0      0   10   14     45
6     7     5  58.3     2     0      0    4   10     39
7    13    14  48.1     1     0      0    5    8     43
8     6     8  42.9     1     0      0    9    9     32
9    14    13  51.9     1     0      0    6   11     30
10    5     6  45.5     3     0      0   10   12     36
11   10     5  66.7     4     0      0   19    9     44
12    5     7  41.7     3     0      0    8    9     38
13    7     5  58.3     2     0      0    7   15     43
14   12     6  66.7     2     1      1   10    4     43
15   10    12  45.5     1     0      0    5   14     33
16    2     2  50.0     3     0      0    7   14     35
17    9     9  50.0     1     0      0    5   10     37
18    6     5  54.5     1     0      0    6   11     28
19    7    14  33.3     2     0      0    8   13     37
20   17    16  51.5     0     0      0    4    4     38
21    6    10  37.5     1     0      0    7    4     35
22    7     8  46.7     3     0      0    6    8     39
23    7     6  53.8     0     0      0    7    6     35
24    8     5  61.5     0     0      0    5   13     38

In [24]:
df_vs_home_cmb= df_vs_home[combined]
df_vs_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0     3     5  37.5     1     0      0   12    9     43
1     7     5  58.3     3     0      0   15    3     24
2     9     7  56.3     3     0      0   10    2     29
3    11     6  64.7     1     0      0    3    8     32
4    11    16  40.7     6     1      1   10    6     25
5    13     6  68.4     4     0      0   14   10     45
6     5     7  41.7     1     0      0   10    4     32
7    14    13  51.9     4     0      0    8    4     31
8     8     6  57.1     3     0      0    9    9     18
9    13    14  48.1     2     0      0   11    5     36
10    6     5  54.5     3     0      0   12   10     40
11    5    10  33.3     2     0      0    9   19     39
12    7     5  58.3     1     0      0    9    8     48
13    5     7  41.7     4     0      0   15    7     44
14    6    12  33.3     1     0      0    4    9     44
15   12    10  54.5     1     0      0   14    5     38
16    2     2  50.0     3     0      0   14    7     32
17    9     9  50.0     4     0      0   10    5     37
18    5     6  45.5     2     0      0   11    6     31
19   14     7  66.7     1     0      0   13    7     41
20   16    17  48.5     0     0      0    4    4     36
21   10     6  62.5     0     0      0    4    7     28
22    8     7  53.3     2     0      0    8    6     33
23    6     7  46.2     2     0      0    6    7     39
24    5     8  38.5     1     0      0   13    5     32

In [25]:
df_away_cmb= df_away[combined]
df_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    18    11  62.1     1     0      0   18    8     40
1     6     8  42.9     2     0      0   10    7     47
2    13     5  72.2     1     0      0    7    7     53
3    21    12  63.6     4     0      0   15    6     47
4     9     6  60.0     1     0      0   10   11     44
5    10    10  50.0     3     0      0    8   15     45
6    27     7  79.4     2     0      0   15    7     43
7     6    10  37.5     4     0      0   12   13     40
8    11    18  37.9     2     0      0   14   14     31
9    10     8  55.6     1     0      0   10   16     46
10    6     6  50.0     0     0      0   11   15     47
11    3     4  42.9     4     0      0    9   10     42
12    7     5  58.3     1     0      0    9    8     48
13    9     9  50.0     5     0      0   17    9     40
14   13     9  59.1     3     1      0   10    7     39
15    8     5  61.5     2     0      0    9    7     58
16   11    15  42.3     3     0      0   17    5     43
17    7     6  53.8     0     0      0   10    7     45
18   11     8  57.9     2     0      0   10   12     41
19   18    10  64.3     1     0      0   10    7     40
20   12    13  48.0     3     0      0   14    6     45
21   11     5  68.8     0     0      0   10   11     47
22    7     6  53.8     3     0      0    9   14     43
23   22    20  52.4     4     1      1   20    9     35
24    8    10  44.4     2     0      0   15   12     38
25   13    10  56.5     0     0      0    6    8     34

In [26]:
df_vs_away_cmb= df_vs_away[combined]
df_vs_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    11    18  37.9     3     0      0    9   17     36
1     8     6  57.1     3     0      0    7   10     42
2     5    13  27.8     4     0      0    7    7     51
3    12    21  36.4     4     0      0    6   15     44
4     6     9  40.0     4     0      0   12    9     48
5    10    10  50.0     2     0      0   16    8     38
6     7    27  20.6     4     0      0    7   15     49
7    10     6  62.5     3     0      0   13   12     39
8    18    11  62.1     2     0      0   14   14     34
9     8    10  44.4     1     0      0   18   10     46
10    6     6  50.0     3     0      0   15   11     46
11    4     3  57.1     3     0      0   11    9     32
12    5     7  41.7     3     0      0    8    9     38
13    9     9  50.0     2     0      0    9   17     41
14    9    13  40.9     4     0      0    7    8     32
15    5     8  38.5     1     0      0    7    9     51
16   15    11  57.7     2     0      0    5   17     30
17    6     7  46.2     0     0      0    7   10     42
18    8    11  42.1     4     0      0   13   10     41
19   10    18  35.7     2     0      0    7   10     39
20   13    12  52.0     2     0      0    6   13     38
21    5    11  31.3     2     0      0   11   10     41
22    6     7  46.2     2     0      0   15    8     48
23   20    22  47.6     4     1      1    9   19     43
24   10     8  55.6     2     0      0   13   15     45
25   10    13  43.5     1     0      0    8    6     30

## By Team

In [27]:
def compute_rolling_averages(df, features, window=5):
    """
    Compute rolling averages for a list of features in a team-level dataset.

    Parameters:
    df (pd.DataFrame): Dataframe containing team-level data sorted by date.
    features (list): List of features to compute rolling averages for.
    window (int): Rolling window size (default=5).

    Returns:
    pd.DataFrame: Dataframe with new rolling average features.
    """
    df = df.copy()
    
    for feature in features:
        df[f"{feature}_rolling_avg"] = df[feature].rolling(window, min_periods=1).mean()
    
    return df[[i for i in df.columns if i[-12:]=='_rolling_avg']]

In [28]:
df_home_off= compute_rolling_averages(df_home_off, offense)
df_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,2.000000,0.000000,0.0,52.000000,0.000000,30.00,15.000000,50.000000,8.0,26.700000,...,-0.200000,-0.200000,0.600000,0.900000,1.200000,1.200000,0.400000,0.070000,0.000000,2.00
1,2.500000,0.500000,0.0,63.500000,0.500000,25.00,13.000000,52.500000,7.5,30.850000,...,1.450000,1.050000,1.450000,1.400000,0.950000,0.800000,0.050000,0.135000,0.500000,3.00
2,2.666667,0.333333,0.0,64.666667,0.333333,23.00,12.666667,56.066667,6.0,25.833333,...,1.733333,1.466667,1.866667,1.833333,0.633333,0.533333,0.133333,0.133333,0.666667,3.00
3,2.500000,0.250000,0.0,62.000000,0.250000,20.75,10.250000,47.400000,6.5,33.650000,...,1.575000,1.375000,1.900000,1.750000,0.450000,0.375000,-0.150000,0.130000,0.500000,2.75
4,2.400000,0.200000,0.0,65.000000,0.200000,20.80,10.200000,47.440000,7.0,35.500000,...,1.560000,1.400000,1.860000,1.980000,0.340000,0.280000,-0.260000,0.118000,0.600000,2.60
5,2.200000,0.200000,0.0,67.000000,0.200000,19.60,9.800000,48.280000,6.8,36.000000,...,1.460000,1.460000,1.900000,2.080000,0.120000,0.060000,-0.300000,0.116000,0.600000,2.40
6,2.200000,0.000000,0.0,63.600000,0.000000,21.20,9.800000,45.140000,8.0,38.280000,...,0.640000,0.800000,1.700000,1.960000,0.260000,0.260000,-0.100000,0.092000,0.600000,2.20
7,2.000000,0.000000,0.0,65.600000,0.000000,23.40,9.400000,39.160000,9.8,43.120000,...,0.340000,0.500000,1.460000,1.920000,0.340000,0.340000,-0.060000,0.080000,0.800000,2.00
8,1.800000,0.000000,0.0,66.200000,0.000000,23.00,10.600000,49.880000,8.6,35.040000,...,0.660000,0.820000,1.620000,2.160000,-0.020000,-0.020000,-0.220000,0.082000,0.800000,1.80
9,1.600000,0.000000,0.0,63.600000,0.000000,22.20,9.800000,47.420000,8.0,33.520000,...,0.260000,0.420000,1.480000,1.960000,-0.120000,-0.120000,-0.080000,0.086000,0.600000,1.60
10,1.600000,0.000000,0.0,63.200000,0.000000,22.40,10.200000,48.580000,7.4,30.880000,...,0.380000,0.380000,1.700000,1.820000,-0.360000,-0.360000,-0.500000,0.110000,0.600000,1.60
11,1.000000,0.000000,0.0,63.200000,0.000000,19.80,9.800000,52.720000,5.8,28.260000,...,0.500000,0.500000,1.860000,1.880000,-1.060000,-1.060000,-1.060000,0.112000,0.400000,1.00
12,0.600000,0.000000,0.0,59.000000,0.000000,18.80,10.400000,56.460000,5.4,28.260000,...,-0.180000,-0.020000,1.640000,1.460000,-1.300000,-1.300000,-1.240000,0.118000,0.000000,0.60
13,1.000000,0.000000,0.0,60.800000,0.000000,21.80,11.200000,51.080000,6.8,31.580000,...,-0.460000,-0.300000,1.540000,1.200000,-0.800000,-0.800000,-0.740000,0.120000,0.200000,1.00
14,1.200000,0.000000,0.0,61.600000,0.000000,20.80,11.000000,52.360000,6.8,34.520000,...,-0.340000,-0.180000,1.600000,1.200000,-0.560000,-0.560000,-0.600000,0.126000,0.200000,1.20
15,1.200000,0.000000,0.0,60.000000,0.000000,20.20,9.800000,48.540000,8.4,42.220000,...,-0.560000,-0.240000,1.380000,1.200000,-0.320000,-0.320000,-0.380000,0.110000,0.200000,1.20
16,1.400000,0.000000,0.0,59.600000,0.000000,21.20,9.600000,44.540000,9.2,44.560000,...,-0.580000,-0.260000,1.100000,1.020000,0.100000,0.100000,-0.100000,0.110000,0.200000,1.40
17,1.600000,0.000000,0.2,61.600000,0.200000,21.00,9.600000,44.980000,8.8,43.220000,...,0.220000,0.220000,1.220000,1.400000,0.040000,0.220000,-0.020000,0.100000,0.400000,1.60
18,1.400000,0.000000,0.2,57.800000,0.200000,18.00,8.000000,43.700000,8.4,48.220000,...,-0.040000,-0.040000,0.940000,1.380000,0.060000,0.240000,-0.140000,0.090000,0.400000,1.40
19,1.600000,0.000000,0.2,55.400000,0.200000,18.00,8.200000,45.360000,7.8,43.220000,...,0.040000,0.040000,1.060000,1.220000,0.160000,0.340000,-0.060000,0.104000,0.400000,1.80
20,1.800000,0.000000,0.2,56.000000,0.200000,16.00,7.600000,47.180000,6.4,40.660000,...,0.200000,0.040000,1.300000,1.380000,0.100000,0.280000,-0.100000,0.106000,0.400000,2.00
21,2.800000,0.000000,0.2,58.200000,0.200000,15.00,7.800000,51.180000,5.6,38.320000,...,0.800000,0.640000,1.680000,1.600000,0.700000,0.880000,0.520000,0.124000,0.400000,3.00
22,3.200000,0.000000,0.0,56.200000,0.000000,13.40,7.000000,51.600000,5.4,40.420000,...,0.600000,0.600000,1.920000,1.240000,1.080000,1.080000,0.680000,0.148000,0.400000,3.40
23,3.000000,0.000000,0.0,57.600000,0.000000,12.60,6.400000,48.260000,4.8,38.760000,...,0.560000,0.560000,1.900000,1.220000,0.980000,0.980000,0.700000,0.154000,0.200000,3.20
24,3.200000,0.000000,0.0,58.600000,0.000000,15.80,6.800000,43.980000,7.6,45.900000,...,0.740000,0.740000,1.900000,1.220000,1.180000,1.180000,0.900000,0.150000,0.200000,3.20

In [29]:
df_vs_home_off= compute_rolling_averages(df_vs_home_off, offense)
df_vs_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,0.000000,0.0,0.0,48.000000,0.0,11.00,4.000000,36.400000,7.0,63.600,...,0.200000,0.200000,1.000000,0.90,-1.000000,-1.000000,-1.000000e+00,0.100000,0.0,0.000000
1,0.500000,0.0,0.0,36.500000,0.0,9.50,3.000000,30.700000,6.5,69.300,...,-1.450000,-1.050000,0.650000,0.60,-0.150000,-0.150000,-1.500000e-01,0.195000,0.0,0.500000
2,0.333333,0.0,0.0,35.333333,0.0,12.00,5.333333,40.066667,6.0,56.000,...,-1.733333,-1.466667,0.566667,0.60,-0.333333,-0.333333,-2.333333e-01,0.153333,0.0,0.666667
3,0.500000,0.0,0.0,38.000000,0.0,11.75,4.750000,36.875000,6.0,55.625,...,-1.575000,-1.375000,0.575000,0.65,-0.250000,-0.250000,-3.250000e-01,0.145000,0.0,0.750000
4,0.800000,0.0,0.0,35.000000,0.0,11.60,4.600000,36.780000,5.6,51.780,...,-1.560000,-1.400000,0.580000,0.62,0.060000,0.060000,2.000000e-02,0.142000,0.0,1.000000
5,0.800000,0.2,0.0,33.000000,0.2,11.80,5.400000,42.840000,4.6,42.400,...,-1.460000,-1.460000,0.540000,0.58,0.140000,0.100000,6.000000e-02,0.138000,0.0,1.200000
6,1.000000,0.2,0.0,36.400000,0.2,12.60,6.000000,46.180000,4.6,37.400,...,-0.640000,-0.800000,1.000000,0.94,-0.120000,-0.160000,-2.000000e-01,0.128000,0.0,1.400000
7,1.200000,0.2,0.0,34.400000,0.2,11.00,4.800000,43.300000,4.4,40.400,...,-0.340000,-0.500000,1.080000,0.88,0.060000,0.020000,-8.000000e-02,0.166000,0.0,1.400000
8,1.000000,0.2,0.0,33.800000,0.2,12.20,5.400000,44.900000,5.0,40.080,...,-0.660000,-0.820000,1.000000,0.78,0.020000,-0.020000,-2.220446e-17,0.150000,0.0,1.200000
9,1.000000,0.2,0.0,36.400000,0.2,14.00,6.800000,48.620000,5.2,37.800,...,-0.260000,-0.420000,1.120000,0.88,-0.240000,-0.280000,-1.200000e-01,0.160000,0.0,1.200000
10,1.400000,0.0,0.0,36.800000,0.0,13.80,5.600000,38.920000,5.8,43.560,...,-0.380000,-0.380000,1.340000,0.98,-0.180000,-0.180000,-1.400000e-01,0.190000,0.2,1.400000
11,1.800000,0.0,0.0,36.800000,0.0,14.60,6.200000,40.580000,6.2,43.560,...,-0.500000,-0.500000,1.320000,0.76,0.240000,0.240000,2.800000e-01,0.198000,0.2,1.800000
12,1.800000,0.2,0.0,41.000000,0.2,16.00,6.400000,37.960000,7.2,45.940,...,0.180000,0.020000,1.580000,0.94,-0.080000,-0.120000,2.000000e-02,0.178000,0.2,2.000000
13,1.800000,0.2,0.0,39.200000,0.2,15.20,6.200000,38.600000,6.4,43.060,...,0.460000,0.300000,1.660000,1.04,-0.240000,-0.280000,-6.000000e-02,0.188000,0.2,2.000000
14,1.800000,0.2,0.0,38.400000,0.2,13.40,5.200000,38.500000,6.0,43.520,...,0.340000,0.180000,1.620000,1.00,-0.100000,-0.140000,-2.000000e-02,0.174000,0.2,2.000000
15,1.600000,0.4,0.0,40.000000,0.4,14.40,6.400000,44.860000,6.4,43.180,...,0.560000,0.240000,1.500000,0.94,-0.060000,-0.140000,1.000000e-01,0.156000,0.0,2.000000
16,1.200000,0.4,0.0,40.400000,0.4,13.40,6.000000,45.760000,5.4,38.640,...,0.580000,0.260000,1.240000,0.92,-0.280000,-0.360000,-4.000000e-02,0.130000,0.0,1.600000
17,1.200000,0.2,0.0,38.400000,0.2,14.00,6.400000,46.860000,5.4,36.860,...,-0.220000,-0.220000,0.900000,0.74,0.060000,0.020000,1.000000e-01,0.114000,0.0,1.400000
18,1.200000,0.2,0.0,42.200000,0.2,14.60,7.200000,50.420000,5.6,36.660,...,0.040000,0.040000,0.980000,0.92,0.000000,-0.040000,2.000000e-02,0.118000,0.0,1.400000
19,1.000000,0.2,0.0,44.600000,0.2,15.80,7.200000,46.580000,6.8,41.780,...,-0.040000,-0.040000,1.040000,0.98,-0.220000,-0.260000,-2.400000e-01,0.112000,0.2,1.200000
20,1.200000,0.0,0.0,44.000000,0.0,14.40,6.400000,45.460000,6.4,44.140,...,-0.200000,-0.040000,1.280000,1.14,-0.300000,-0.300000,-2.800000e-01,0.112000,0.2,1.200000
21,0.800000,0.0,0.0,41.800000,0.0,16.00,6.600000,41.920000,7.2,46.040,...,-0.800000,-0.640000,1.140000,1.02,-0.480000,-0.480000,-5.400000e-01,0.094000,0.2,0.800000
22,0.800000,0.0,0.0,43.800000,0.0,16.20,7.400000,45.560000,7.0,44.560,...,-0.600000,-0.600000,1.400000,1.20,-0.700000,-0.700000,-6.000000e-01,0.114000,0.2,0.800000
23,1.800000,0.0,0.0,42.400000,0.0,15.40,7.400000,49.300000,6.2,40.400,...,-0.560000,-0.560000,1.380000,1.00,0.360000,0.360000,2.200000e-01,0.108000,0.2,1.800000
24,1.600000,0.0,0.0,41.400000,0.0,13.00,6.400000,46.240000,5.0,41.820,...,-0.740000,-0.740000,1.220000,0.82,0.340000,0.340000,1.800000e-01,0.124000,0.0,1.600000

In [30]:
df_away_def= compute_rolling_averages(df_away_def, defence)
df_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,4.00,0.000000,0.000000,0.0,1.00,19.500,0.0,NaN,0.0,0.0,...,2.000000,12.00,5.000000,14.00,17.00,1.000000,0.200000,0.1200,0.200000,0.00
1,5.00,0.000000,0.000000,0.0,0.50,13.500,0.0,NaN,0.0,0.0,...,2.500000,11.50,6.000000,19.00,14.50,0.500000,0.500000,0.2550,0.500000,0.00
2,8.00,0.333333,2.366667,0.0,2.00,14.900,0.0,NaN,0.0,0.0,...,1.666667,12.00,7.333333,24.00,19.00,0.333333,0.533333,0.2400,0.533333,0.00
3,7.25,0.250000,1.775000,0.0,1.75,16.500,0.0,NaN,0.0,0.0,...,1.250000,10.25,8.250000,23.75,18.25,0.250000,0.575000,0.2425,0.325000,0.25
4,9.20,0.400000,2.600000,0.0,1.40,15.200,0.0,NaN,0.0,0.0,...,1.800000,9.40,7.800000,24.20,19.40,0.400000,0.760000,0.2440,0.560000,0.20
5,11.00,0.600000,4.140000,0.0,1.60,14.220,0.0,NaN,0.0,0.0,...,1.800000,8.80,8.200000,24.80,18.40,0.400000,0.940000,0.2940,0.540000,0.40
6,11.40,0.600000,4.140000,0.0,1.80,15.340,0.0,NaN,0.0,0.0,...,1.200000,7.40,9.400000,25.20,19.00,0.400000,0.980000,0.2620,0.580000,0.40
7,11.40,0.400000,2.720000,0.0,1.00,15.200,0.0,NaN,0.0,0.0,...,2.000000,6.20,8.600000,24.60,17.00,0.400000,1.040000,0.3060,0.440000,0.60
8,11.80,0.400000,2.720000,0.0,0.80,12.600,0.0,NaN,0.0,0.0,...,2.400000,6.60,7.400000,24.20,18.20,0.400000,1.240000,0.3720,0.440000,0.80
9,10.40,0.200000,1.540000,0.0,1.20,14.760,0.0,NaN,0.0,0.0,...,2.400000,7.00,8.200000,26.60,16.40,0.200000,1.040000,0.3420,0.040000,1.00
10,11.20,0.400000,2.360000,0.0,0.80,13.240,0.0,NaN,0.0,0.0,...,2.400000,7.00,8.200000,27.00,17.80,0.200000,0.940000,0.3280,0.140000,0.80
11,10.20,0.400000,2.360000,0.2,1.40,15.460,0.2,100.0,0.0,0.0,...,2.400000,6.80,7.200000,26.60,16.00,0.200000,1.080000,0.3200,-0.120000,1.20
12,8.60,0.400000,2.360000,0.2,1.20,15.075,0.2,100.0,0.0,0.0,...,2.200000,7.00,7.200000,26.00,15.00,0.600000,1.080000,0.3280,0.080000,1.00
13,9.80,0.600000,3.900000,0.2,1.40,16.375,0.2,100.0,0.0,0.0,...,2.600000,7.40,8.200000,28.40,15.20,1.200000,1.240000,0.2960,0.040000,1.20
14,9.60,0.800000,6.120000,0.2,2.00,16.575,0.2,100.0,0.0,0.0,...,2.600000,6.40,8.000000,25.60,13.80,1.200000,1.500000,0.3960,0.100000,1.40
15,8.00,0.400000,3.760000,0.2,2.20,18.875,0.2,100.0,0.0,0.0,...,2.400000,6.80,9.600000,30.20,14.40,1.200000,1.760000,0.4140,-0.240000,2.00
16,8.60,0.400000,3.760000,0.0,1.40,15.575,0.0,NaN,0.0,0.0,...,2.600000,7.80,9.600000,30.60,15.00,1.200000,1.600000,0.5560,-0.200000,1.80
17,8.60,0.400000,3.760000,0.0,1.60,14.220,0.0,NaN,0.0,0.0,...,2.600000,7.80,9.200000,30.40,15.00,0.800000,1.420000,0.5775,-0.380000,1.80
18,9.80,0.400000,3.280000,0.0,2.20,14.240,0.0,NaN,0.0,0.0,...,3.400000,7.60,10.000000,27.80,15.60,0.200000,1.000000,0.4975,-0.600000,1.60
19,8.80,0.200000,1.060000,0.0,1.40,15.520,0.0,NaN,0.0,0.0,...,3.000000,7.60,8.600000,25.40,20.40,0.200000,0.820000,0.4250,-0.580000,1.40
20,8.60,0.200000,1.060000,0.0,1.40,16.080,0.0,NaN,0.0,0.0,...,3.000000,6.20,6.400000,19.80,19.80,0.000000,0.580000,0.3550,-0.220000,0.80
21,8.80,0.200000,1.060000,0.0,1.40,15.820,0.0,NaN,0.0,0.2,...,2.800000,6.60,5.400000,18.40,19.60,0.000000,0.580000,0.2100,-0.220000,0.80
22,10.20,0.400000,2.600000,0.0,2.00,16.660,0.0,NaN,0.0,0.2,...,2.800000,6.60,6.800000,18.80,22.20,0.800000,0.740000,0.2200,-0.060000,0.80
23,9.20,0.200000,1.540000,0.0,1.40,16.340,0.0,NaN,0.0,0.2,...,1.600000,6.00,5.600000,20.00,24.40,0.800000,0.900000,0.2800,0.100000,0.80
24,9.80,0.200000,1.540000,0.0,1.60,13.740,0.0,NaN,0.0,0.2,...,2.200000,6.00,8.200000,23.80,21.80,1.400000,1.020000,0.2920,0.220000,0.80
25,11.00,0.600000,4.400000,0.0,1.80,12.280,0.0,NaN,0.0,0.2,...,2.600000,7.00,9.000000,25.80,23.00,1.400000,1.160000,0.3660,-0.040000,1.20

In [31]:
df_vs_away_def= compute_rolling_averages(df_vs_away_def, defence)
df_vs_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,16.0,1.000000,6.30,0.0,1.00,13.800000,0.0,NaN,0.0,0.0,...,6.000000,9.0,9.0,29.000000,28.000000,0.000000,2.300,0.470000,3.000000e-01,2.000000
1,15.0,0.500000,3.15,0.0,1.50,15.650000,0.0,NaN,0.0,0.0,...,6.500000,6.5,7.0,22.000000,21.500000,0.000000,2.550,0.410000,5.500000e-01,2.000000
2,12.0,0.333333,2.10,0.0,2.00,19.533333,0.0,NaN,0.0,0.0,...,4.666667,6.0,7.0,27.666667,17.666667,1.333333,2.500,0.543333,1.666667e-01,2.333333
3,13.0,0.500000,3.15,0.0,1.75,17.650000,0.0,NaN,0.0,0.0,...,4.250000,6.5,8.0,29.000000,21.250000,1.500000,2.025,0.435000,2.750000e-01,1.750000
4,11.6,0.600000,5.86,0.0,1.80,16.220000,0.0,NaN,0.0,0.0,...,4.200000,6.8,7.8,28.600000,20.200000,1.400000,2.380,0.412000,3.800000e-01,2.000000
5,11.6,0.800000,7.10,0.2,2.00,15.920000,0.0,0.0,0.0,0.2,...,3.200000,6.2,7.8,27.400000,19.200000,1.600000,2.220,0.348000,2.200000e-01,2.000000
6,11.0,0.800000,7.10,0.2,2.20,15.920000,0.0,0.0,0.0,0.2,...,2.800000,7.4,7.8,27.000000,21.600000,1.600000,1.760,0.304000,-4.000000e-02,1.800000
7,10.4,0.800000,7.10,0.4,1.80,13.320000,0.0,0.0,0.0,0.2,...,2.600000,7.8,8.0,23.200000,22.000000,0.800000,1.680,0.190000,8.000000e-02,1.600000
8,11.4,0.800000,6.80,0.4,1.60,12.220000,0.0,0.0,0.0,0.4,...,2.400000,7.8,7.2,21.400000,21.200000,0.600000,1.920,0.258000,-8.000000e-02,2.000000
9,13.8,0.600000,3.46,0.4,1.60,13.920000,0.0,0.0,0.0,0.4,...,2.800000,7.4,7.6,21.400000,23.400000,0.400000,1.520,0.240000,-2.800000e-01,1.800000
10,12.2,0.200000,0.96,0.2,1.20,14.325000,0.0,0.0,0.0,0.2,...,3.200000,7.6,7.0,21.200000,22.400000,0.400000,1.460,0.260000,-3.400000e-01,1.800000
11,15.6,0.800000,3.10,0.4,0.60,11.575000,0.0,0.0,0.0,0.2,...,4.000000,7.2,7.0,22.600000,23.600000,1.400000,2.180,0.290000,-2.000000e-02,2.200000
12,17.4,0.800000,3.10,0.4,1.20,15.575000,0.0,0.0,0.0,0.2,...,4.800000,7.0,6.4,23.000000,25.800000,2.000000,2.240,0.300000,4.000000e-02,2.200000
13,15.8,1.200000,6.76,0.4,1.60,18.000000,0.0,0.0,0.0,0.0,...,5.600000,6.6,6.0,22.000000,23.600000,2.000000,2.560,0.348000,1.600000e-01,2.400000
14,17.4,1.400000,7.52,0.4,1.60,16.375000,0.0,0.0,0.0,0.0,...,5.400000,6.6,5.6,21.000000,24.200000,2.200000,2.480,0.374000,8.000000e-02,2.400000
15,18.8,1.400000,7.52,0.4,1.60,14.560000,0.0,0.0,0.0,0.0,...,5.800000,6.6,6.0,22.200000,25.400000,2.800000,3.320,0.422000,1.200000e-01,3.200000
16,22.0,1.400000,6.74,0.2,1.60,14.140000,0.0,0.0,0.0,0.0,...,5.200000,6.4,8.0,23.800000,28.600000,1.800000,2.960,0.432000,-2.400000e-01,3.200000
17,23.0,1.400000,6.74,0.0,1.20,11.280000,0.0,NaN,0.0,0.0,...,4.800000,6.8,9.2,25.000000,28.200000,1.600000,3.320,0.436000,-4.800000e-01,3.800000
18,23.0,1.000000,3.66,0.2,0.80,8.780000,0.0,0.0,0.0,0.0,...,4.400000,6.6,10.8,27.800000,30.000000,1.400000,3.000,0.338000,-6.000000e-01,3.600000
19,23.2,1.000000,3.64,0.2,0.40,8.480000,0.0,0.0,0.0,0.2,...,4.800000,7.6,11.2,29.200000,35.800000,1.200000,3.100,0.330000,-3.000000e-01,3.400000
20,26.2,1.400000,4.98,0.2,0.40,7.880000,0.0,0.0,0.0,0.2,...,6.600000,8.8,11.6,28.000000,38.200000,0.400000,2.460,0.288000,-1.400000e-01,2.600000
21,21.2,1.400000,6.78,0.2,0.40,7.840000,0.0,0.0,0.0,0.2,...,6.000000,8.8,11.2,29.400000,35.800000,0.400000,2.560,0.324000,-2.400000e-01,2.800000
22,19.2,1.600000,9.64,0.4,0.60,8.640000,0.0,0.0,0.0,0.2,...,7.000000,8.4,11.0,29.600000,37.000000,0.200000,2.200,0.304000,1.110223e-17,2.200000
23,18.6,1.400000,8.10,0.2,0.60,11.300000,0.0,0.0,0.0,0.2,...,6.600000,8.4,10.0,28.400000,40.400000,0.200000,2.160,0.342000,-4.000000e-02,2.200000
24,15.2,1.200000,7.36,0.4,0.80,11.980000,0.0,0.0,0.0,0.0,...,5.400000,7.4,10.0,27.400000,33.000000,0.400000,2.060,0.310000,-3.400000e-01,2.400000
25,12.2,1.000000,7.36,0.4,1.40,14.880000,0.0,0.0,0.0,0.0,...,3.400000,6.8,8.6,28.000000,30.800000,0.800000,1.900,0.348000,-5.000000e-01,2.400000

In [32]:
df_away_off= compute_rolling_averages(df_away_off, offense)
df_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,2.000000,0.0,0.0,62.00,0.0,23.000000,11.0,47.800000,11.00,47.800,...,2.10,2.10,2.000000,2.400,-6.000000e-01,-0.600000,-1.000000e+00,0.150,0.000000,2.000000
1,2.000000,0.0,0.0,62.00,0.0,19.500000,9.5,48.900000,8.00,39.550,...,2.05,2.05,2.250000,2.000,-5.500000e-01,-0.550000,-7.500000e-01,0.145,0.500000,2.000000
2,2.333333,0.0,0.0,57.00,0.0,19.666667,8.0,40.933333,10.00,49.700,...,1.50,1.50,1.966667,1.700,3.333333e-02,0.033333,3.333333e-02,0.150,0.333333,2.333333
3,1.750000,0.0,0.0,59.75,0.0,19.750000,7.5,38.200000,10.75,53.525,...,1.25,1.25,1.700000,1.625,-2.000000e-01,-0.200000,-2.000000e-01,0.130,0.250000,1.750000
4,2.000000,0.0,0.0,59.40,0.0,20.000000,9.2,45.800000,9.60,47.580,...,1.18,1.18,1.740000,1.500,4.000000e-02,0.040000,6.000000e-02,0.126,0.200000,2.000000
5,1.800000,0.2,0.0,58.00,0.2,17.800000,7.8,42.900000,8.80,49.680,...,1.14,0.98,1.560000,1.260,6.000000e-02,0.020000,2.400000e-01,0.134,0.400000,2.000000
6,1.600000,0.2,0.0,59.20,0.2,16.400000,7.8,50.680000,7.80,43.420,...,0.90,0.74,1.340000,1.240,8.000000e-02,0.040000,2.600000e-01,0.124,0.200000,1.800000
7,1.200000,0.4,0.0,58.40,0.4,14.400000,7.8,55.680000,5.80,37.420,...,1.00,0.70,1.260000,1.080,-1.400000e-01,-0.220000,-6.000000e-02,0.120,0.400000,1.600000
8,1.600000,0.4,0.0,55.80,0.4,14.000000,8.4,59.680000,4.00,28.860,...,0.88,0.58,1.220000,1.020,2.800000e-01,0.200000,3.800000e-01,0.124,0.400000,2.000000
9,1.400000,0.4,0.0,54.00,0.4,13.000000,6.8,54.440000,4.60,34.100,...,0.82,0.52,1.100000,1.020,1.600000e-01,0.080000,3.000000e-01,0.122,0.400000,1.800000
10,1.600000,0.2,0.0,55.40,0.2,13.600000,7.8,59.780000,4.40,30.440,...,0.60,0.46,1.140000,0.980,2.600000e-01,0.220000,2.600000e-01,0.112,0.200000,1.800000
11,1.800000,0.4,0.0,54.20,0.4,15.200000,8.2,53.760000,5.20,35.140,...,0.80,0.70,1.160000,0.940,3.200000e-01,0.240000,2.400000e-01,0.112,0.400000,2.200000
12,1.800000,0.4,0.0,54.40,0.4,16.400000,8.2,50.020000,6.20,38.400,...,1.14,1.02,1.380000,1.120,2.000000e-02,-0.060000,2.000000e-02,0.116,0.200000,2.200000
13,2.000000,0.4,0.0,55.00,0.4,16.200000,7.8,48.260000,7.20,44.540,...,1.14,1.02,1.480000,1.120,4.440892e-17,-0.080000,1.200000e-01,0.122,0.200000,2.400000
14,2.000000,0.4,0.0,57.40,0.4,17.600000,8.6,48.700000,7.60,43.240,...,1.20,1.08,1.600000,1.200,-1.000000e-01,-0.180000,-1.665335e-17,0.128,0.200000,2.400000
15,2.800000,0.4,0.0,54.60,0.4,17.400000,7.8,43.840000,7.80,45.240,...,1.90,1.78,2.120000,1.520,-2.000000e-02,-0.100000,8.000000e-02,0.152,0.200000,3.200000
16,3.000000,0.2,0.0,55.80,0.2,15.800000,6.8,43.200000,7.80,49.420,...,1.88,1.72,2.180000,1.860,2.000000e-01,0.160000,4.200000e-01,0.156,0.000000,3.200000
17,3.800000,0.0,0.0,57.80,0.0,16.000000,7.8,48.700000,7.40,46.400,...,1.92,1.92,2.320000,1.920,8.600000e-01,0.860000,8.800000e-01,0.152,0.000000,3.800000
18,3.400000,0.2,0.0,56.80,0.2,17.200000,9.0,51.760000,7.40,43.640,...,2.28,2.12,2.380000,1.940,5.000000e-01,0.460000,4.200000e-01,0.150,0.200000,3.600000
19,3.200000,0.2,0.0,58.60,0.2,16.400000,7.4,45.540000,8.00,48.620,...,2.44,2.28,2.320000,2.060,3.200000e-01,0.280000,2.800000e-01,0.142,0.200000,3.400000
20,2.400000,0.2,0.0,61.00,0.2,17.400000,7.8,45.760000,8.40,48.100,...,2.12,1.96,2.200000,2.140,-4.000000e-02,-0.080000,-4.440892e-17,0.108,0.200000,2.600000
21,2.600000,0.2,0.0,61.40,0.2,20.400000,10.0,47.980000,9.00,45.060,...,2.08,1.92,2.160000,1.840,1.600000e-01,0.120000,4.000000e-02,0.114,0.200000,2.800000
22,1.800000,0.4,0.0,60.80,0.4,20.000000,9.2,44.220000,8.80,44.820,...,1.70,1.38,1.880000,1.860,-3.200000e-01,-0.400000,-2.800000e-01,0.106,0.200000,2.200000
23,2.000000,0.2,0.0,62.80,0.2,18.400000,8.2,43.580000,8.40,46.340,...,1.28,1.12,1.660000,1.680,1.000000e-01,0.060000,-6.000000e-02,0.104,0.000000,2.200000
24,2.000000,0.4,0.0,58.80,0.4,17.800000,8.2,44.360000,7.40,42.660,...,0.98,0.66,1.380000,1.400,3.600000e-01,0.280000,2.000000e-02,0.106,0.000000,2.400000
25,2.000000,0.4,0.0,56.40,0.4,18.400000,8.2,43.360000,8.60,46.820,...,0.82,0.50,1.200000,1.180,5.400000e-01,0.460000,2.000000e-01,0.118,0.000000,2.400000

In [33]:
df_vs_away_off= compute_rolling_averages(df_vs_away_off, offense)
df_vs_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,0.00,0.0,0.0,38.00,0.0,10.0,3.000000,30.000000,5.000000,50.000000,...,-2.10,-2.10,0.300,0.200000,-0.50,-0.50,-0.300,0.0600,0.0,0.00
1,0.00,0.0,0.0,38.00,0.0,16.0,4.500000,28.650000,9.000000,54.550000,...,-2.05,-2.05,0.400,0.300000,-0.50,-0.50,-0.400,0.0650,0.0,0.00
2,0.00,0.0,0.0,43.00,0.0,18.0,5.666667,31.233333,10.333333,56.066667,...,-1.50,-1.50,0.700,0.533333,-0.80,-0.80,-0.700,0.1000,0.0,0.00
3,0.25,0.0,0.0,40.25,0.0,17.0,5.750000,34.150000,9.000000,50.975000,...,-1.25,-1.25,0.625,0.450000,-0.45,-0.45,-0.375,0.0975,0.0,0.25
4,0.20,0.0,0.0,40.60,0.0,18.2,6.800000,36.880000,9.600000,51.220000,...,-1.18,-1.18,0.680,0.500000,-0.58,-0.58,-0.480,0.0900,0.2,0.20
5,0.40,0.0,0.0,42.00,0.0,18.6,7.600000,42.540000,9.400000,47.880000,...,-1.14,-0.98,0.660,0.520000,-0.40,-0.40,-0.460,0.0940,0.2,0.40
6,0.40,0.0,0.0,40.80,0.0,16.4,7.200000,44.360000,8.200000,48.780000,...,-0.90,-0.74,0.680,0.540000,-0.42,-0.42,-0.480,0.0940,0.2,0.40
7,0.60,0.0,0.0,41.60,0.0,17.8,7.600000,43.980000,9.000000,48.680000,...,-1.00,-0.70,0.560,0.520000,-0.14,-0.14,-0.160,0.0760,0.4,0.60
8,0.80,0.0,0.0,44.20,0.0,17.6,7.600000,44.640000,9.200000,50.780000,...,-0.88,-0.58,0.660,0.720000,-0.04,-0.04,-0.060,0.0780,0.4,0.80
9,1.00,0.0,0.0,46.00,0.0,18.2,7.000000,41.240000,10.200000,53.420000,...,-0.82,-0.52,0.640,0.780000,0.18,0.18,0.160,0.0820,0.6,1.00
10,0.80,0.0,0.0,44.60,0.0,19.0,7.800000,43.340000,10.000000,50.520000,...,-0.60,-0.46,0.780,0.840000,-0.14,-0.14,0.020,0.0900,0.6,0.80
11,1.20,0.0,0.2,45.80,0.2,22.0,8.800000,42.980000,11.200000,47.800000,...,-0.80,-0.70,0.720,0.880000,0.12,0.32,0.280,0.0880,0.6,1.20
12,1.00,0.0,0.2,45.60,0.2,21.2,9.400000,46.480000,9.800000,44.080000,...,-1.14,-1.02,0.660,0.780000,-0.04,0.16,0.140,0.0920,0.4,1.00
13,1.20,0.0,0.2,45.00,0.2,24.8,10.600000,44.980000,10.400000,40.640000,...,-1.14,-1.02,0.800,0.700000,-0.08,0.12,0.200,0.0960,0.6,1.20
14,1.40,0.0,0.2,42.60,0.2,23.4,10.400000,46.180000,8.800000,37.040000,...,-1.20,-1.08,0.860,0.640000,0.08,0.28,0.340,0.1000,0.4,1.40
15,2.00,0.0,0.2,45.40,0.2,25.4,10.200000,40.120000,11.200000,44.820000,...,-1.90,-1.78,0.900,0.680000,0.66,0.86,0.700,0.1040,0.4,2.00
16,1.80,0.0,0.0,44.20,0.0,22.6,8.600000,34.860000,10.400000,49.820000,...,-1.88,-1.72,0.900,0.580000,0.66,0.66,0.700,0.1100,0.4,1.80
17,1.80,0.0,0.0,42.20,0.0,21.4,7.400000,31.820000,10.200000,51.300000,...,-1.92,-1.92,0.880,0.580000,0.74,0.74,0.720,0.1000,0.4,1.80
18,1.60,0.0,0.0,43.20,0.0,18.6,7.000000,35.840000,9.400000,51.380000,...,-2.28,-2.12,0.700,0.660000,0.76,0.76,0.500,0.0920,0.2,1.60
19,1.40,0.0,0.0,41.40,0.0,18.4,6.800000,35.140000,9.000000,49.680000,...,-2.44,-2.28,0.520,0.560000,0.74,0.74,0.480,0.0820,0.2,1.40
20,0.80,0.0,0.0,39.00,0.0,16.0,6.400000,38.860000,6.200000,39.560000,...,-2.12,-1.96,0.420,0.600000,0.26,0.26,0.180,0.0680,0.2,0.80
21,0.80,0.0,0.0,38.60,0.0,17.0,7.800000,46.620000,6.000000,33.980000,...,-2.08,-1.92,0.440,0.620000,0.22,0.22,0.160,0.0820,0.2,0.80
22,0.80,0.0,0.0,39.20,0.0,18.6,8.800000,48.140000,6.600000,33.380000,...,-1.70,-1.38,0.560,0.680000,-0.02,-0.02,0.040,0.0940,0.2,0.80
23,0.80,0.0,0.0,37.20,0.0,18.0,7.600000,42.100000,7.600000,41.780000,...,-1.28,-1.12,0.600,0.520000,-0.02,-0.02,0.200,0.0980,0.2,0.80
24,0.80,0.0,0.0,41.20,0.0,19.8,8.400000,42.840000,8.800000,43.620000,...,-0.98,-0.66,0.820,0.680000,-0.26,-0.26,-0.020,0.1060,0.4,0.80
25,1.20,0.0,0.0,43.60,0.0,21.6,9.600000,43.600000,10.400000,50.020000,...,-0.82,-0.50,0.780,0.620000,0.16,0.16,0.220,0.1060,0.4,1.20

In [34]:
df_home_def= compute_rolling_averages(df_home_def, defence)
df_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,12.0,1.000000,8.300000,0.0,0.00,11.000000,0.0,NaN,0.0,0.0,...,4.000000,2.0,10.000000,26.000000,18.000000,0.000000,0.700,0.230000,7.000000e-01,0.000000
1,8.5,0.500000,4.150000,0.0,0.50,15.250000,0.0,NaN,0.0,0.0,...,2.000000,5.0,8.000000,23.000000,13.500000,0.000000,0.500,0.260000,0.000000e+00,0.500000
2,9.0,0.333333,2.766667,0.0,1.00,18.166667,0.0,NaN,0.0,0.0,...,2.333333,7.0,7.666667,22.666667,15.333333,0.333333,0.400,0.203333,6.666667e-02,0.666667
3,9.0,0.250000,2.075000,0.0,2.25,17.700000,0.0,NaN,0.0,0.0,...,2.000000,7.0,7.000000,21.250000,14.750000,1.000000,0.825,0.267500,3.250000e-01,0.750000
4,8.6,0.200000,1.660000,0.0,2.20,18.820000,0.0,NaN,0.0,0.2,...,1.600000,6.0,6.200000,19.600000,13.600000,1.000000,0.960,0.312000,1.600000e-01,1.000000
5,8.8,0.000000,0.000000,0.2,2.20,18.820000,0.0,0.0,0.0,0.2,...,1.400000,6.6,5.600000,18.800000,14.200000,1.000000,1.040,0.288000,4.000000e-02,1.200000
6,10.0,0.000000,0.000000,0.2,2.60,19.680000,0.0,0.0,0.0,0.2,...,2.200000,6.4,5.200000,17.600000,16.400000,1.200000,1.480,0.354000,2.800000e-01,1.400000
7,8.6,0.000000,0.000000,0.2,2.80,19.280000,0.0,0.0,0.0,0.2,...,1.600000,5.4,4.400000,16.600000,13.600000,1.000000,1.700,0.464000,3.000000e-01,1.400000
8,7.0,0.000000,0.000000,0.2,1.80,19.420000,0.0,0.0,0.0,0.2,...,1.600000,5.0,5.400000,17.600000,13.800000,0.400000,1.300,0.378000,1.000000e-01,1.200000
9,8.0,0.200000,1.660000,0.2,1.40,17.060000,0.0,0.0,0.0,0.0,...,2.000000,6.0,5.800000,18.800000,13.800000,0.400000,1.480,0.364000,2.800000e-01,1.200000
10,6.6,0.600000,8.320000,0.0,2.40,18.940000,0.0,NaN,0.0,0.0,...,1.800000,6.0,5.200000,17.600000,11.200000,0.400000,1.580,0.420000,1.800000e-01,1.400000
11,5.4,0.600000,8.320000,0.0,1.80,15.980000,0.0,NaN,0.0,0.0,...,1.000000,6.6,6.200000,19.200000,9.800000,0.600000,1.760,0.394000,-4.000000e-02,1.800000
12,7.2,0.600000,8.320000,0.2,2.00,17.640000,0.0,0.0,0.0,0.0,...,1.800000,6.6,6.600000,20.200000,13.400000,1.200000,1.960,0.324000,-4.000000e-02,2.000000
13,9.2,0.600000,8.320000,0.2,2.20,17.100000,0.0,0.0,0.0,0.0,...,2.000000,7.0,5.600000,20.000000,13.600000,1.600000,2.040,0.354000,4.000000e-02,2.000000
14,9.0,0.600000,8.480000,0.2,2.20,17.300000,0.0,0.0,0.0,0.2,...,3.200000,7.0,6.000000,20.400000,15.400000,1.600000,1.820,0.354000,-1.800000e-01,2.000000
15,9.6,0.200000,1.820000,0.4,1.20,15.580000,0.0,0.0,0.0,0.2,...,3.400000,7.6,7.200000,22.000000,15.800000,1.600000,1.920,0.374000,-8.000000e-02,2.000000
16,9.8,0.200000,1.820000,0.4,1.40,17.480000,0.0,0.0,0.0,0.2,...,3.800000,7.4,6.400000,19.800000,16.200000,1.400000,1.660,0.360000,6.000000e-02,1.600000
17,9.0,0.200000,1.820000,0.2,1.00,14.880000,0.0,0.0,0.0,0.2,...,3.400000,7.2,5.600000,18.800000,14.200000,1.000000,1.380,0.360000,-2.000000e-02,1.400000
18,9.4,0.200000,1.820000,0.2,0.60,15.025000,0.0,0.0,0.0,0.2,...,3.600000,6.4,5.600000,17.600000,14.600000,0.800000,1.400,0.360000,2.220446e-17,1.400000
19,9.4,0.000000,0.000000,0.2,0.60,13.275000,0.0,0.0,0.0,0.0,...,2.600000,6.2,5.400000,17.000000,14.600000,0.600000,1.380,0.338000,1.800000e-01,1.200000
20,10.4,0.200000,1.420000,0.0,0.60,13.650000,0.0,NaN,0.0,0.0,...,2.800000,6.0,5.200000,16.400000,19.000000,0.600000,1.260,0.300000,6.000000e-02,1.200000
21,11.4,1.000000,8.700000,0.0,0.80,12.275000,0.0,NaN,0.0,0.0,...,3.000000,4.6,5.600000,18.400000,18.200000,0.400000,0.940,0.240000,1.400000e-01,0.800000
22,10.8,1.200000,12.700000,0.0,1.00,13.025000,0.0,NaN,0.0,0.0,...,3.200000,5.0,6.600000,18.800000,19.000000,0.400000,1.120,0.272000,3.200000e-01,0.800000
23,10.2,1.200000,12.700000,0.0,1.00,11.980000,0.0,NaN,0.0,0.0,...,3.200000,5.4,6.800000,19.800000,19.600000,1.000000,1.600,0.322000,-2.000000e-01,1.800000
24,10.4,1.200000,12.700000,0.0,1.40,14.820000,0.0,NaN,0.0,0.0,...,2.800000,6.2,6.800000,19.400000,20.000000,1.200000,1.440,0.336000,-1.600000e-01,1.600000

In [35]:
df_vs_home_def= compute_rolling_averages(df_vs_home_def, defence)
df_vs_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,6.00,1.000000,16.70,0.000000,0.0,9.800000,0.0,NaN,0.0,0.0,...,3.000000,7.000000,10.000000,30.000000,13.000000,1.000000,0.80,0.160000,-1.200000e+00,2.00
1,10.50,0.500000,8.35,0.500000,1.5,14.900000,0.0,0.0,0.0,0.0,...,3.000000,10.000000,10.000000,28.500000,27.000000,1.500000,2.15,0.340000,-8.500000e-01,3.00
2,12.00,0.666667,7.80,0.333333,1.0,11.766667,0.0,0.0,0.0,0.0,...,3.666667,9.333333,8.666667,24.666667,24.666667,1.333333,2.40,0.346667,-6.000000e-01,3.00
3,11.25,1.000000,11.40,0.250000,1.5,13.675000,0.0,0.0,0.0,0.0,...,3.750000,9.250000,8.750000,25.750000,24.500000,1.250000,2.30,0.335000,-4.500000e-01,2.75
4,12.60,1.400000,12.46,0.200000,1.2,12.140000,0.0,0.0,0.0,0.2,...,5.600000,9.000000,7.800000,24.600000,27.800000,1.200000,2.28,0.308000,-3.200000e-01,2.60
5,14.60,1.400000,10.38,0.200000,1.4,12.980000,0.0,0.0,0.0,0.2,...,6.200000,8.800000,7.800000,23.600000,29.800000,1.200000,2.40,0.322000,0.000000e+00,2.40
6,14.00,1.600000,12.04,0.000000,0.8,10.440000,0.0,NaN,0.0,0.4,...,6.800000,8.800000,7.200000,24.200000,26.000000,1.000000,1.96,0.254000,-2.400000e-01,2.20
7,16.60,2.000000,12.84,0.000000,0.8,10.200000,0.0,NaN,0.0,0.6,...,7.200000,10.600000,7.200000,27.200000,32.000000,0.800000,1.74,0.234000,-2.600000e-01,2.00
8,18.60,1.800000,9.46,0.000000,0.2,7.680000,0.0,NaN,0.0,0.6,...,8.000000,10.400000,6.600000,25.400000,33.200000,0.800000,1.50,0.196000,-3.000000e-01,1.80
9,18.80,1.200000,6.12,0.000000,0.2,7.480000,0.0,NaN,0.0,0.6,...,6.200000,9.600000,8.200000,27.000000,32.800000,0.600000,1.44,0.252000,-1.600000e-01,1.60
10,17.60,1.200000,6.86,0.000000,0.6,8.400000,0.0,NaN,0.0,0.6,...,5.600000,10.600000,8.600000,27.600000,32.400000,0.400000,1.68,0.306000,8.000000e-02,1.60
11,20.20,1.600000,7.60,0.000000,0.6,7.640000,0.0,NaN,0.0,0.4,...,5.800000,9.000000,8.200000,25.200000,33.800000,0.400000,1.64,0.314000,6.400000e-01,1.00
12,15.80,1.000000,5.46,0.000000,0.6,8.475000,0.0,NaN,0.0,0.2,...,5.000000,7.200000,8.200000,24.400000,26.400000,0.800000,1.46,0.356000,8.600000e-01,0.60
13,14.40,0.800000,4.40,0.000000,0.8,10.900000,0.0,NaN,0.0,0.2,...,4.000000,7.000000,9.800000,28.000000,24.200000,0.600000,1.94,0.440000,9.400000e-01,1.00
14,13.40,1.000000,5.82,0.000000,1.0,13.900000,0.0,NaN,0.0,0.0,...,4.000000,8.400000,8.600000,27.200000,21.200000,0.600000,2.02,0.460000,8.200000e-01,1.20
15,14.00,0.800000,3.82,0.000000,0.6,12.075000,0.0,NaN,0.0,0.2,...,4.000000,8.400000,9.600000,29.800000,20.800000,0.800000,1.68,0.418000,4.800000e-01,1.20
16,11.00,0.400000,3.42,0.000000,0.6,13.875000,0.0,NaN,0.0,0.2,...,2.800000,8.600000,9.400000,31.400000,18.200000,0.800000,1.72,0.418000,3.200000e-01,1.40
17,12.80,0.800000,6.08,0.200000,1.0,13.940000,0.2,100.0,0.0,0.2,...,4.200000,7.600000,9.600000,30.600000,23.000000,0.400000,1.88,0.364000,2.800000e-01,1.60
18,11.80,0.800000,6.08,0.200000,0.8,13.300000,0.2,100.0,0.0,0.2,...,4.200000,7.600000,8.600000,27.600000,21.600000,0.400000,1.50,0.312000,1.000000e-01,1.40
19,11.00,0.800000,6.66,0.200000,0.8,11.700000,0.2,100.0,0.0,0.2,...,4.000000,7.000000,8.800000,26.800000,20.400000,0.800000,1.54,0.268000,-6.000000e-02,1.80
20,11.20,0.800000,6.66,0.200000,0.6,11.125000,0.2,100.0,0.0,0.0,...,3.800000,6.000000,7.200000,22.400000,21.000000,0.800000,1.80,0.266000,-5.551115e-18,2.00
21,10.40,0.800000,8.00,0.200000,0.6,10.075000,0.2,100.0,0.0,0.0,...,4.400000,6.200000,8.000000,21.400000,21.800000,1.400000,2.30,0.308000,-5.000000e-01,3.00
22,8.40,0.400000,5.34,0.000000,0.8,12.125000,0.0,NaN,0.0,0.0,...,3.000000,7.000000,7.400000,19.800000,16.800000,1.800000,2.38,0.346000,-8.200000e-01,3.40
23,8.80,0.400000,5.34,0.000000,0.8,10.300000,0.0,NaN,0.0,0.0,...,2.400000,6.600000,6.600000,19.400000,18.800000,1.800000,2.32,0.344000,-6.800000e-01,3.20
24,8.80,0.600000,7.34,0.000000,1.2,11.740000,0.0,NaN,0.0,0.2,...,2.200000,6.400000,6.600000,22.000000,19.400000,1.600000,2.38,0.350000,-8.200000e-01,3.20

In [36]:
df_away_cmb= compute_rolling_averages(df_away_cmb, combined)
df_away_cmb['H/A']= df_away['H/A']
df_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,18.000000,11.0,62.100000,1.000000,0.0,0.0,18.000000,8.000000,40.000000,A
1,12.000000,9.5,52.500000,1.500000,0.0,0.0,14.000000,7.500000,43.500000,H
2,12.333333,8.0,59.066667,1.333333,0.0,0.0,11.666667,7.333333,46.666667,A
3,14.500000,9.0,60.200000,2.000000,0.0,0.0,12.500000,7.000000,46.750000,H
4,13.400000,8.4,60.160000,1.800000,0.0,0.0,12.000000,7.800000,46.200000,H
5,11.800000,8.2,57.740000,2.200000,0.0,0.0,10.000000,9.200000,47.200000,A
6,16.000000,8.0,65.040000,2.200000,0.0,0.0,11.000000,9.200000,46.400000,A
7,14.600000,9.0,58.100000,2.800000,0.0,0.0,12.000000,10.400000,43.800000,H
8,12.600000,10.2,52.960000,2.400000,0.0,0.0,11.800000,12.000000,40.600000,A
9,12.800000,10.6,52.080000,2.400000,0.0,0.0,11.800000,13.000000,41.000000,H
10,12.000000,9.8,52.080000,1.800000,0.0,0.0,12.400000,13.000000,41.400000,H
11,7.200000,9.2,44.780000,2.200000,0.0,0.0,11.200000,13.600000,41.200000,A
12,7.400000,8.2,48.940000,1.600000,0.0,0.0,10.600000,12.600000,42.800000,H
13,7.000000,6.4,51.360000,2.200000,0.0,0.0,11.200000,11.600000,44.600000,A
14,7.600000,6.6,52.060000,2.600000,0.2,0.0,11.200000,9.800000,43.200000,H
15,8.000000,6.4,54.360000,3.000000,0.2,0.0,10.800000,8.200000,45.400000,A
16,9.600000,8.6,54.240000,2.800000,0.2,0.0,12.400000,7.200000,45.600000,H
17,9.600000,8.8,53.340000,2.600000,0.2,0.0,12.600000,7.000000,45.000000,A
18,10.000000,8.6,54.920000,2.000000,0.2,0.0,11.200000,7.600000,45.200000,H
19,11.000000,8.8,55.960000,1.600000,0.0,0.0,11.200000,7.600000,45.400000,A
20,11.800000,10.4,53.260000,1.800000,0.0,0.0,12.200000,7.400000,42.800000,A
21,11.800000,8.4,58.560000,1.200000,0.0,0.0,10.800000,8.600000,43.600000,H
22,11.800000,8.4,58.560000,1.800000,0.0,0.0,10.600000,10.000000,43.200000,A
23,14.000000,10.8,57.460000,2.200000,0.2,0.2,12.600000,9.400000,42.000000,A
24,12.000000,10.8,53.480000,2.400000,0.2,0.2,13.600000,10.400000,41.600000,H
25,12.200000,10.2,55.180000,1.800000,0.2,0.2,12.000000,10.800000,39.400000,A

In [37]:
df_vs_away_cmb= compute_rolling_averages(df_vs_away_cmb, combined)
#df_away_cmb['H/A']= df_away['H/A']
df_vs_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,11.0,18.000000,37.900000,3.000000,0.0,0.0,9.000000,17.000000,36.00
1,9.5,12.000000,47.500000,3.000000,0.0,0.0,8.000000,13.500000,39.00
2,8.0,12.333333,40.933333,3.333333,0.0,0.0,7.666667,11.333333,43.00
3,9.0,14.500000,39.800000,3.500000,0.0,0.0,7.250000,12.250000,43.25
4,8.4,13.400000,39.840000,3.600000,0.0,0.0,8.200000,11.600000,44.20
5,8.2,11.800000,42.260000,3.400000,0.0,0.0,9.600000,9.800000,44.60
6,8.0,16.000000,34.960000,3.600000,0.0,0.0,9.600000,10.800000,46.00
7,9.0,14.600000,41.900000,3.400000,0.0,0.0,10.800000,11.800000,43.60
8,10.2,12.600000,47.040000,3.000000,0.0,0.0,12.400000,11.600000,41.60
9,10.6,12.800000,47.920000,2.400000,0.0,0.0,13.600000,11.800000,41.20
10,9.8,12.000000,47.920000,2.600000,0.0,0.0,13.400000,12.400000,42.80
11,9.2,7.200000,55.220000,2.400000,0.0,0.0,14.200000,11.200000,39.40
12,8.2,7.400000,51.060000,2.400000,0.0,0.0,13.200000,10.600000,39.20
13,6.4,7.000000,48.640000,2.400000,0.0,0.0,12.200000,11.200000,40.60
14,6.6,7.600000,47.940000,3.000000,0.0,0.0,10.000000,10.800000,37.80
15,6.4,8.000000,45.640000,2.600000,0.0,0.0,8.400000,10.400000,38.80
16,8.6,9.600000,45.760000,2.400000,0.0,0.0,7.200000,12.000000,38.40
17,8.8,9.600000,46.660000,1.800000,0.0,0.0,7.000000,12.200000,39.20
18,8.6,10.000000,45.080000,2.200000,0.0,0.0,7.800000,10.800000,39.20
19,8.8,11.000000,44.040000,1.800000,0.0,0.0,7.800000,11.200000,40.60
20,10.4,11.800000,46.740000,2.000000,0.0,0.0,7.600000,12.000000,38.00
21,8.4,11.800000,41.460000,2.000000,0.0,0.0,8.800000,10.600000,40.20
22,8.4,11.800000,41.460000,2.400000,0.0,0.0,10.400000,10.200000,41.40
23,10.8,14.000000,42.560000,2.400000,0.2,0.2,9.600000,12.000000,41.80
24,10.8,12.000000,46.540000,2.400000,0.2,0.2,10.800000,13.000000,43.00
25,10.2,12.200000,44.840000,2.200000,0.2,0.2,11.200000,11.600000,41.40

In [38]:
df_home_cmb= compute_rolling_averages(df_home_cmb, combined)
df_home_cmb['H/A']= df_home['H/A']
df_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,5.000000,3.000000,62.500000,1.000000,0.0,0.0,9.000000,12.000000,41.000000,A
1,5.000000,5.000000,52.100000,1.500000,0.0,0.0,6.500000,13.500000,36.500000,H
2,5.666667,6.333333,49.333333,1.666667,0.0,0.0,5.333333,12.333333,38.666667,A
3,5.750000,7.500000,45.825000,2.000000,0.0,0.0,6.250000,10.000000,38.500000,H
4,7.800000,8.200000,48.520000,2.200000,0.0,0.0,6.400000,10.000000,38.600000,H
5,8.000000,10.200000,42.340000,2.800000,0.0,0.0,6.600000,10.400000,39.400000,A
6,8.400000,9.800000,45.660000,2.800000,0.0,0.0,6.600000,9.400000,40.800000,H
7,9.600000,10.800000,46.520000,2.600000,0.0,0.0,7.000000,9.000000,40.800000,A
8,9.600000,10.200000,48.040000,2.200000,0.0,0.0,7.000000,10.200000,39.600000,H
9,9.200000,10.600000,46.560000,1.800000,0.0,0.0,6.800000,10.400000,37.800000,A
10,9.000000,9.200000,49.340000,1.600000,0.0,0.0,6.800000,10.000000,36.000000,A
11,9.600000,9.200000,51.020000,2.000000,0.0,0.0,9.800000,9.800000,37.000000,H
12,8.000000,7.800000,49.740000,2.400000,0.0,0.0,10.400000,10.000000,36.000000,A
13,8.200000,7.200000,52.820000,2.600000,0.0,0.0,10.000000,11.200000,38.200000,H
14,7.800000,5.800000,55.780000,2.800000,0.2,0.2,10.800000,9.800000,40.800000,A
15,8.800000,7.000000,55.780000,2.400000,0.2,0.2,9.800000,10.200000,40.200000,H
16,7.200000,6.400000,52.440000,2.200000,0.2,0.2,7.400000,11.200000,38.400000,A
17,8.000000,6.800000,54.100000,1.800000,0.2,0.2,6.800000,11.400000,38.200000,H
18,7.800000,6.800000,53.340000,1.600000,0.2,0.2,6.600000,10.600000,35.200000,A
19,6.800000,8.400000,46.660000,1.600000,0.0,0.0,6.200000,12.400000,34.000000,H
20,8.200000,9.200000,47.860000,1.400000,0.0,0.0,6.000000,10.400000,35.000000,A
21,9.000000,10.800000,45.360000,1.000000,0.0,0.0,6.000000,8.400000,35.000000,A
22,8.600000,10.600000,44.700000,1.400000,0.0,0.0,6.200000,8.000000,35.400000,H
23,8.800000,10.800000,44.560000,1.200000,0.0,0.0,6.400000,7.000000,36.800000,A
24,9.000000,9.000000,50.200000,0.800000,0.0,0.0,5.800000,7.000000,37.000000,H

In [39]:
df_vs_home_cmb= compute_rolling_averages(df_vs_home_cmb, combined)
#df_home_cmb['H/A']= df_home['H/A']
df_vs_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,3.000000,5.000000,37.50,1.000000,0.0,0.0,12.000000,9.000000,43.0
1,5.000000,5.000000,47.90,2.000000,0.0,0.0,13.500000,6.000000,33.5
2,6.333333,5.666667,50.70,2.333333,0.0,0.0,12.333333,4.666667,32.0
3,7.500000,5.750000,54.20,2.000000,0.0,0.0,10.000000,5.500000,32.0
4,8.200000,7.800000,51.50,2.800000,0.2,0.2,10.000000,5.600000,30.6
5,10.200000,8.000000,57.68,3.400000,0.2,0.2,10.400000,5.800000,31.0
6,9.800000,8.400000,54.36,3.000000,0.2,0.2,9.400000,6.000000,32.6
7,10.800000,9.600000,53.48,3.200000,0.2,0.2,9.000000,6.400000,33.0
8,10.200000,9.600000,51.96,3.600000,0.2,0.2,10.200000,6.600000,30.2
9,10.600000,9.200000,53.44,2.800000,0.0,0.0,10.400000,6.400000,32.4
10,9.200000,9.000000,50.66,2.600000,0.0,0.0,10.000000,6.400000,31.4
11,9.200000,9.600000,48.98,2.800000,0.0,0.0,9.800000,9.400000,32.8
12,7.800000,8.000000,50.26,2.200000,0.0,0.0,10.000000,10.200000,36.2
13,7.200000,8.200000,47.18,2.400000,0.0,0.0,11.200000,9.800000,41.4
14,5.800000,7.800000,44.22,2.200000,0.0,0.0,9.800000,10.600000,43.0
15,7.000000,8.800000,44.22,1.800000,0.0,0.0,10.200000,9.600000,42.6
16,6.400000,7.200000,47.56,2.000000,0.0,0.0,11.200000,7.200000,41.2
17,6.800000,8.000000,45.90,2.600000,0.0,0.0,11.400000,6.600000,39.0
18,6.800000,7.800000,46.66,2.200000,0.0,0.0,10.600000,6.400000,36.4
19,8.400000,6.800000,53.34,2.200000,0.0,0.0,12.400000,6.000000,35.8
20,9.200000,8.200000,52.14,2.000000,0.0,0.0,10.400000,5.800000,35.4
21,10.800000,9.000000,54.64,1.400000,0.0,0.0,8.400000,5.800000,34.6
22,10.600000,8.600000,55.30,1.000000,0.0,0.0,8.000000,6.000000,33.8
23,10.800000,8.800000,55.44,1.000000,0.0,0.0,7.000000,6.200000,35.4
24,9.000000,9.000000,49.80,1.000000,0.0,0.0,7.000000,5.800000,33.6

In [40]:
df_vs_away_cmb = df_vs_away_cmb.rename(columns=lambda x: 'vs_' + x)
df_vs_home_cmb = df_vs_home_cmb.rename(columns=lambda x: 'vs_' + x)

## Final DFs

In [41]:
df_home_gf= pd.concat([df_home_off, df_home_cmb, df_vs_home_cmb, df_vs_home_def, df_home[['GF']]], axis= 1)
df_home_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,2.000000,0.000000,0.0,52.000000,0.000000,30.00,15.000000,50.000000,8.0,26.700000,...,7.000000,10.000000,30.000000,13.000000,1.000000,0.80,0.160000,-1.200000e+00,2.00,2
1,2.500000,0.500000,0.0,63.500000,0.500000,25.00,13.000000,52.500000,7.5,30.850000,...,10.000000,10.000000,28.500000,27.000000,1.500000,2.15,0.340000,-8.500000e-01,3.00,4
2,2.666667,0.333333,0.0,64.666667,0.333333,23.00,12.666667,56.066667,6.0,25.833333,...,9.333333,8.666667,24.666667,24.666667,1.333333,2.40,0.346667,-6.000000e-01,3.00,3
3,2.500000,0.250000,0.0,62.000000,0.250000,20.75,10.250000,47.400000,6.5,33.650000,...,9.250000,8.750000,25.750000,24.500000,1.250000,2.30,0.335000,-4.500000e-01,2.75,2
4,2.400000,0.200000,0.0,65.000000,0.200000,20.80,10.200000,47.440000,7.0,35.500000,...,9.000000,7.800000,24.600000,27.800000,1.200000,2.28,0.308000,-3.200000e-01,2.60,2
5,2.200000,0.200000,0.0,67.000000,0.200000,19.60,9.800000,48.280000,6.8,36.000000,...,8.800000,7.800000,23.600000,29.800000,1.200000,2.40,0.322000,0.000000e+00,2.40,1
6,2.200000,0.000000,0.0,63.600000,0.000000,21.20,9.800000,45.140000,8.0,38.280000,...,8.800000,7.200000,24.200000,26.000000,1.000000,1.96,0.254000,-2.400000e-01,2.20,3
7,2.000000,0.000000,0.0,65.600000,0.000000,23.40,9.400000,39.160000,9.8,43.120000,...,10.600000,7.200000,27.200000,32.000000,0.800000,1.74,0.234000,-2.600000e-01,2.00,2
8,1.800000,0.000000,0.0,66.200000,0.000000,23.00,10.600000,49.880000,8.6,35.040000,...,10.400000,6.600000,25.400000,33.200000,0.800000,1.50,0.196000,-3.000000e-01,1.80,1
9,1.600000,0.000000,0.0,63.600000,0.000000,22.20,9.800000,47.420000,8.0,33.520000,...,9.600000,8.200000,27.000000,32.800000,0.600000,1.44,0.252000,-1.600000e-01,1.60,1
10,1.600000,0.000000,0.0,63.200000,0.000000,22.40,10.200000,48.580000,7.4,30.880000,...,10.600000,8.600000,27.600000,32.400000,0.400000,1.68,0.306000,8.000000e-02,1.60,1
11,1.000000,0.000000,0.0,63.200000,0.000000,19.80,9.800000,52.720000,5.8,28.260000,...,9.000000,8.200000,25.200000,33.800000,0.400000,1.64,0.314000,6.400000e-01,1.00,0
12,0.600000,0.000000,0.0,59.000000,0.000000,18.80,10.400000,56.460000,5.4,28.260000,...,7.200000,8.200000,24.400000,26.400000,0.800000,1.46,0.356000,8.600000e-01,0.60,0
13,1.000000,0.000000,0.0,60.800000,0.000000,21.80,11.200000,51.080000,6.8,31.580000,...,7.000000,9.800000,28.000000,24.200000,0.600000,1.94,0.440000,9.400000e-01,1.00,3
14,1.200000,0.000000,0.0,61.600000,0.000000,20.80,11.000000,52.360000,6.8,34.520000,...,8.400000,8.600000,27.200000,21.200000,0.600000,2.02,0.460000,8.200000e-01,1.20,2
15,1.200000,0.000000,0.0,60.000000,0.000000,20.20,9.800000,48.540000,8.4,42.220000,...,8.400000,9.600000,29.800000,20.800000,0.800000,1.68,0.418000,4.800000e-01,1.20,1
16,1.400000,0.000000,0.0,59.600000,0.000000,21.20,9.600000,44.540000,9.2,44.560000,...,8.600000,9.400000,31.400000,18.200000,0.800000,1.72,0.418000,3.200000e-01,1.40,1
17,1.600000,0.000000,0.2,61.600000,0.200000,21.00,9.600000,44.980000,8.8,43.220000,...,7.600000,9.600000,30.600000,23.000000,0.400000,1.88,0.364000,2.800000e-01,1.60,1
18,1.400000,0.000000,0.2,57.800000,0.200000,18.00,8.000000,43.700000,8.4,48.220000,...,7.600000,8.600000,27.600000,21.600000,0.400000,1.50,0.312000,1.000000e-01,1.40,2
19,1.600000,0.000000,0.2,55.400000,0.200000,18.00,8.200000,45.360000,7.8,43.220000,...,7.000000,8.800000,26.800000,20.400000,0.800000,1.54,0.268000,-6.000000e-02,1.80,4
20,1.800000,0.000000,0.2,56.000000,0.200000,16.00,7.600000,47.180000,6.4,40.660000,...,6.000000,7.200000,22.400000,21.000000,0.800000,1.80,0.266000,-5.551115e-18,2.00,2
21,2.800000,0.000000,0.2,58.200000,0.200000,15.00,7.800000,51.180000,5.6,38.320000,...,6.200000,8.000000,21.400000,21.800000,1.400000,2.30,0.308000,-5.000000e-01,3.00,6
22,3.200000,0.000000,0.0,56.200000,0.000000,13.40,7.000000,51.600000,5.4,40.420000,...,7.000000,7.400000,19.800000,16.800000,1.800000,2.38,0.346000,-8.200000e-01,3.40,3
23,3.000000,0.000000,0.0,57.600000,0.000000,12.60,6.400000,48.260000,4.8,38.760000,...,6.600000,6.600000,19.400000,18.800000,1.800000,2.32,0.344000,-6.800000e-01,3.20,1
24,3.200000,0.000000,0.0,58.600000,0.000000,15.80,6.800000,43.980000,7.6,45.900000,...,6.400000,6.600000,22.000000,19.400000,1.600000,2.38,0.350000,-8.200000e-01,3.20,4

In [42]:
df_away_gf= pd.concat([df_away_off, df_away_cmb, df_vs_away_cmb, df_vs_away_def, df_away[['GF']]], axis= 1)
df_away_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,2.000000,0.0,0.0,62.00,0.0,23.000000,11.0,47.800000,11.00,47.800,...,9.0,9.0,29.000000,28.000000,0.000000,2.300,0.470000,3.000000e-01,2.000000,2
1,2.000000,0.0,0.0,62.00,0.0,19.500000,9.5,48.900000,8.00,39.550,...,6.5,7.0,22.000000,21.500000,0.000000,2.550,0.410000,5.500000e-01,2.000000,2
2,2.333333,0.0,0.0,57.00,0.0,19.666667,8.0,40.933333,10.00,49.700,...,6.0,7.0,27.666667,17.666667,1.333333,2.500,0.543333,1.666667e-01,2.333333,3
3,1.750000,0.0,0.0,59.75,0.0,19.750000,7.5,38.200000,10.75,53.525,...,6.5,8.0,29.000000,21.250000,1.500000,2.025,0.435000,2.750000e-01,1.750000,0
4,2.000000,0.0,0.0,59.40,0.0,20.000000,9.2,45.800000,9.60,47.580,...,6.8,7.8,28.600000,20.200000,1.400000,2.380,0.412000,3.800000e-01,2.000000,3
5,1.800000,0.2,0.0,58.00,0.2,17.800000,7.8,42.900000,8.80,49.680,...,6.2,7.8,27.400000,19.200000,1.600000,2.220,0.348000,2.200000e-01,2.000000,2
6,1.600000,0.2,0.0,59.20,0.2,16.400000,7.8,50.680000,7.80,43.420,...,7.4,7.8,27.000000,21.600000,1.600000,1.760,0.304000,-4.000000e-02,1.800000,1
7,1.200000,0.4,0.0,58.40,0.4,14.400000,7.8,55.680000,5.80,37.420,...,7.8,8.0,23.200000,22.000000,0.800000,1.680,0.190000,8.000000e-02,1.600000,2
8,1.600000,0.4,0.0,55.80,0.4,14.000000,8.4,59.680000,4.00,28.860,...,7.8,7.2,21.400000,21.200000,0.600000,1.920,0.258000,-8.000000e-02,2.000000,2
9,1.400000,0.4,0.0,54.00,0.4,13.000000,6.8,54.440000,4.60,34.100,...,7.4,7.6,21.400000,23.400000,0.400000,1.520,0.240000,-2.800000e-01,1.800000,2
10,1.600000,0.2,0.0,55.40,0.2,13.600000,7.8,59.780000,4.40,30.440,...,7.6,7.0,21.200000,22.400000,0.400000,1.460,0.260000,-3.400000e-01,1.800000,2
11,1.800000,0.4,0.0,54.20,0.4,15.200000,8.2,53.760000,5.20,35.140,...,7.2,7.0,22.600000,23.600000,1.400000,2.180,0.290000,-2.000000e-02,2.200000,3
12,1.800000,0.4,0.0,54.40,0.4,16.400000,8.2,50.020000,6.20,38.400,...,7.0,6.4,23.000000,25.800000,2.000000,2.240,0.300000,4.000000e-02,2.200000,2
13,2.000000,0.4,0.0,55.00,0.4,16.200000,7.8,48.260000,7.20,44.540,...,6.6,6.0,22.000000,23.600000,2.000000,2.560,0.348000,1.600000e-01,2.400000,3
14,2.000000,0.4,0.0,57.40,0.4,17.600000,8.6,48.700000,7.60,43.240,...,6.6,5.6,21.000000,24.200000,2.200000,2.480,0.374000,8.000000e-02,2.400000,2
15,2.800000,0.4,0.0,54.60,0.4,17.400000,7.8,43.840000,7.80,45.240,...,6.6,6.0,22.200000,25.400000,2.800000,3.320,0.422000,1.200000e-01,3.200000,6
16,3.000000,0.2,0.0,55.80,0.2,15.800000,6.8,43.200000,7.80,49.420,...,6.4,8.0,23.800000,28.600000,1.800000,2.960,0.432000,-2.400000e-01,3.200000,3
17,3.800000,0.0,0.0,57.80,0.0,16.000000,7.8,48.700000,7.40,46.400,...,6.8,9.2,25.000000,28.200000,1.600000,3.320,0.436000,-4.800000e-01,3.800000,5
18,3.400000,0.2,0.0,56.80,0.2,17.200000,9.0,51.760000,7.40,43.640,...,6.6,10.8,27.800000,30.000000,1.400000,3.000,0.338000,-6.000000e-01,3.600000,2
19,3.200000,0.2,0.0,58.60,0.2,16.400000,7.4,45.540000,8.00,48.620,...,7.6,11.2,29.200000,35.800000,1.200000,3.100,0.330000,-3.000000e-01,3.400000,1
20,2.400000,0.2,0.0,61.00,0.2,17.400000,7.8,45.760000,8.40,48.100,...,8.8,11.6,28.000000,38.200000,0.400000,2.460,0.288000,-1.400000e-01,2.600000,2
21,2.600000,0.2,0.0,61.40,0.2,20.400000,10.0,47.980000,9.00,45.060,...,8.8,11.2,29.400000,35.800000,0.400000,2.560,0.324000,-2.400000e-01,2.800000,4
22,1.800000,0.4,0.0,60.80,0.4,20.000000,9.2,44.220000,8.80,44.820,...,8.4,11.0,29.600000,37.000000,0.200000,2.200,0.304000,1.110223e-17,2.200000,2
23,2.000000,0.2,0.0,62.80,0.2,18.400000,8.2,43.580000,8.40,46.340,...,8.4,10.0,28.400000,40.400000,0.200000,2.160,0.342000,-4.000000e-02,2.200000,2
24,2.000000,0.4,0.0,58.80,0.4,17.800000,8.2,44.360000,7.40,42.660,...,7.4,10.0,27.400000,33.000000,0.400000,2.060,0.310000,-3.400000e-01,2.400000,2
25,2.000000,0.4,0.0,56.40,0.4,18.400000,8.2,43.360000,8.60,46.820,...,6.8,8.6,28.000000,30.800000,0.800000,1.900,0.348000,-5.000000e-01,2.400000,2

In [43]:
nan_counts = df_home_gf.isna().sum()
for i in df_home_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 15
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [44]:
nan_counts = df_away_gf.isna().sum()
for i in df_away_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 6
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [45]:
df_home_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [46]:
df_away_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [47]:
df_home_gf = df_home_gf.fillna(0)

In [48]:
df_away_gf = df_away_gf.fillna(0)

# Model Home

In [49]:
target = "GF"  # Goals For

# Separate features and target
X = df_home_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
y = df_home_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [50]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [51]:
model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=25)

# Train the model
model_pipeline.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 0.117
RMSE: 0.150

In [53]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline.predict(X_test)
    y_cur= model_pipeline.predict(df_home_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 19, number of used features: 0
[LightGBM] [Info] Start training from score 2.105263
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [54]:
results_df

                        MAE      RMSE                  pred
Random Forest          1.14  1.222293                 [3.1]
XGBoost            0.814805  1.023665            [3.673575]
LightGBM           1.621053  1.676628  [2.1052631578947367]
Linear Regression  1.402726  2.208991   [5.048377744054651]

# Model Away

In [55]:
target = "GF"  # Goals For

# Separate features and target
Xa = df_away_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
ya = df_away_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [56]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [57]:
model_pipeline2 = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [58]:
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.1, random_state=25)

# Train the model
model_pipeline2.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline2.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 1.533
RMSE: 1.798

In [59]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline2 = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline2.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline2.predict(X_test)
    y_cur= model_pipeline2.predict(df_away_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 20, number of used features: 0
[LightGBM] [Info] Start training from score 2.350000
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [60]:
results_df

                        MAE      RMSE                 pred
Random Forest          0.74  0.906642                [1.8]
XGBoost             0.91008  1.219255          [2.0102968]
LightGBM               0.81  1.225765               [2.35]
Linear Regression  1.369528  1.995904  [3.260212695781221]