In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error
sns.set_theme(style="darkgrid")

# Teams

In [10]:
home= "Newcastle Utd"
away= "Nott'ham Forest"

In [11]:
df_home= pd.read_csv(f"../Data/{home}.csv")
df_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Newcastle Utd,Southampton,2024-08-17,W,H,1,0,1,1,0,...,0.3,0.2,0.7,0.7,0.7,0.08,0,0.4,0.14,0.4
1,Newcastle Utd,Bournemouth,2024-08-25,D,A,1,1,0,1,0,...,1.7,1.4,-0.6,-0.6,-0.7,0.12,0,1.1,0.28,0.1
2,Newcastle Utd,Tottenham,2024-09-01,W,H,2,1,1,2,0,...,1.8,1.4,0.2,0.2,0.2,0.20,0,1.5,0.26,1.5
3,Newcastle Utd,Wolves,2024-09-15,W,A,2,1,1,2,0,...,1.5,1.2,0.5,0.5,0.5,0.11,0,1.3,0.25,0.3
4,Newcastle Utd,Fulham,2024-09-21,L,A,1,3,-2,1,0,...,0.9,0.8,-0.5,-0.5,0.1,0.10,1,3.0,0.29,0.0
5,Newcastle Utd,Manchester City,2024-09-28,D,H,1,1,0,0,1,...,0.8,0.7,-0.6,-0.8,-0.8,0.08,0,1.4,0.23,0.4
6,Newcastle Utd,Everton,2024-10-05,D,A,0,0,0,0,0,...,1.1,1.0,-2.1,-1.3,-1.1,0.10,0,0.6,0.28,0.6
7,Newcastle Utd,Brighton,2024-10-19,L,H,0,1,-1,0,0,...,1.8,1.3,-2.0,-2.0,-1.8,0.10,2,1.7,0.34,0.7
8,Newcastle Utd,Chelsea,2024-10-27,L,A,1,2,-1,1,0,...,1.7,1.3,-0.8,-0.8,-0.7,0.16,1,1.9,0.28,-0.1
9,Newcastle Utd,Arsenal,2024-11-02,W,H,1,0,1,1,0,...,0.4,0.7,0.5,0.5,0.6,0.06,0,0.0,NaN,0.0
10,Newcastle Utd,Nott'ham Forest,2024-11-10,W,A,3,1,2,3,0,...,1.3,1.4,1.4,1.4,0.7,0.10,0,0.9,0.30,-0.1
11,Newcastle Utd,West Ham,2024-11-25,L,H,0,2,-2,0,0,...,1.0,0.9,-1.6,-1.6,-1.0,0.09,0,1.2,0.20,-0.8
12,Newcastle Utd,Crystal Palace,2024-11-30,D,A,1,1,0,0,0,...,0.0,0.2,0.0,0.0,0.0,0.04,0,0.9,0.31,-0.1
13,Newcastle Utd,Liverpool,2024-12-04,D,H,3,3,0,3,0,...,1.6,0.8,0.9,0.9,1.4,0.12,1,3.4,0.69,0.4
14,Newcastle Utd,Brentford,2024-12-07,L,A,2,4,-2,2,0,...,1.2,1.4,0.5,0.5,0.8,0.09,0,2.3,0.34,-1.7
15,Newcastle Utd,Leicester City,2024-12-14,W,H,4,0,4,4,0,...,2.8,2.2,0.2,0.2,0.2,0.14,1,0.1,0.09,0.1
16,Newcastle Utd,Ipswich Town,2024-12-21,W,A,4,0,4,4,0,...,2.2,2.1,1.7,1.7,0.8,0.16,0,0.2,0.12,0.2
17,Newcastle Utd,Aston Villa,2024-12-26,W,H,3,0,3,3,0,...,1.7,2.5,0.3,0.3,0.3,0.13,1,0.2,0.18,0.2
18,Newcastle Utd,Manchester Utd,2024-12-30,W,A,2,0,2,2,0,...,1.4,0.8,0.1,0.1,-0.4,0.16,0,0.0,NaN,0.0
19,Newcastle Utd,Tottenham,2025-01-04,W,A,2,1,1,2,0,...,2.3,1.0,-0.5,-0.5,-1.3,0.18,0,1.2,0.31,0.2
20,Newcastle Utd,Wolves,2025-01-15,W,H,3,0,3,3,0,...,1.9,1.7,0.9,0.9,0.1,0.12,0,1.6,0.23,1.6
21,Newcastle Utd,Bournemouth,2025-01-18,L,H,1,4,-3,1,0,...,0.4,0.6,0.2,0.2,0.6,0.06,1,4.1,0.41,0.1
22,Newcastle Utd,Southampton,2025-01-25,W,A,3,1,2,2,1,...,1.8,1.5,0.1,-0.1,0.2,0.13,0,1.1,0.23,0.1
23,Newcastle Utd,Fulham,2025-02-01,L,H,1,2,-1,1,0,...,0.6,1.2,0.2,0.2,-0.6,0.07,0,1.5,0.39,-0.5
24,Newcastle Utd,Manchester City,2025-02-15,L,A,0,4,-4,0,0,...,0.5,0.2,-0.5,-0.5,-0.5,0.16,0,2.8,0.39,-1.2

In [12]:
df_vs_home= pd.read_csv(f"../Data/vs {home}.csv")
df_vs_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Southampton,Newcastle Utd,2024-08-17,L,A,0,1,-1,0,0,...,1.5,1.6,-1.8,-1.8,-1.5,0.10,1,0.6,0.63,-0.4
1,Bournemouth,Newcastle Utd,2024-08-25,D,H,1,1,0,1,0,...,2.2,1.8,-1.2,-1.2,-1.2,0.14,1,2.6,0.53,1.6
2,Tottenham,Newcastle Utd,2024-09-01,L,A,1,2,-1,0,0,...,0.6,0.9,-1.2,-1.2,-0.6,0.06,1,2.1,0.71,0.1
3,Wolves,Newcastle Utd,2024-09-15,L,H,1,2,-1,1,0,...,0.9,1.0,-0.2,-0.2,0.1,0.10,0,1.7,0.29,-0.3
4,Fulham,Newcastle Utd,2024-09-21,W,H,3,1,2,3,0,...,2.0,1.2,0.8,0.8,1.0,0.10,0,1.0,0.21,0.0
5,Manchester City,Newcastle Utd,2024-09-28,D,A,1,1,0,1,0,...,0.8,1.4,0.1,0.1,0.2,0.06,0,1.1,0.11,0.1
6,Everton,Newcastle Utd,2024-10-05,D,H,0,0,0,0,0,...,0.3,0.2,-0.7,-0.7,-0.3,0.09,1,0.9,0.04,0.9
7,Brighton,Newcastle Utd,2024-10-19,W,A,1,0,1,1,0,...,0.7,0.5,-0.1,-0.1,0.3,0.11,0,0.9,0.15,0.9
8,Chelsea,Newcastle Utd,2024-10-27,W,H,2,1,1,2,0,...,1.5,0.9,0.4,0.4,0.5,0.09,0,1.2,0.58,0.2
9,Arsenal,Newcastle Utd,2024-11-02,L,A,0,1,-1,0,0,...,1.1,1.7,-1.1,-1.1,-1.1,0.11,0,1.3,0.32,0.3
10,Nott'ham Forest,Newcastle Utd,2024-11-10,L,H,1,3,-2,1,0,...,0.5,0.7,0.4,0.4,0.5,0.06,0,2.3,0.39,-0.7
11,West Ham,Newcastle Utd,2024-11-25,W,A,2,0,2,2,0,...,0.6,0.4,1.1,1.1,1.4,0.06,1,0.4,0.21,0.4
12,Crystal Palace,Newcastle Utd,2024-11-30,D,H,1,1,0,1,0,...,1.5,1.6,-0.7,-0.7,-0.5,0.11,0,0.0,NaN,0.0
13,Liverpool,Newcastle Utd,2024-12-04,D,A,3,3,0,3,0,...,1.2,1.1,1.1,1.1,1.8,0.12,0,2.5,0.42,-0.5
14,Brentford,Newcastle Utd,2024-12-07,W,H,4,2,2,4,0,...,0.9,0.8,2.8,2.8,2.1,0.11,0,1.3,0.43,-0.7
15,Leicester City,Newcastle Utd,2024-12-14,L,A,0,4,-4,0,0,...,0.2,0.3,-0.2,-0.2,-0.2,0.05,0,4.3,0.39,0.3
16,Ipswich Town,Newcastle Utd,2024-12-21,L,H,0,4,-4,0,0,...,0.5,0.5,-0.7,-0.7,-0.5,0.07,0,1.8,0.26,-2.2
17,Aston Villa,Newcastle Utd,2024-12-26,L,A,0,3,-3,0,0,...,0.2,0.4,-0.3,-0.3,-0.2,0.09,1,3.3,0.47,0.3
18,Manchester Utd,Newcastle Utd,2024-12-30,L,H,0,2,-2,0,0,...,0.7,0.7,-0.8,-0.8,-0.7,0.09,0,1.7,0.42,-0.3
19,Tottenham,Newcastle Utd,2025-01-04,L,H,1,2,-1,1,0,...,0.7,1.0,0.1,0.1,0.3,0.07,0,2.2,0.55,0.2
20,Wolves,Newcastle Utd,2025-01-15,L,A,0,3,-3,0,0,...,1.5,0.7,-1.6,-1.6,-1.5,0.12,0,1.8,0.36,-1.2
21,Bournemouth,Newcastle Utd,2025-01-18,W,A,4,1,3,4,0,...,1.6,1.2,2.0,2.0,2.4,0.11,0,0.6,0.16,-0.4
22,Southampton,Newcastle Utd,2025-01-25,L,H,1,3,-2,1,0,...,0.5,0.5,0.2,0.2,0.5,0.06,0,2.7,0.24,-0.3
23,Fulham,Newcastle Utd,2025-02-01,W,A,2,1,1,2,0,...,1.5,1.0,0.4,0.4,0.5,0.10,0,1.7,0.42,0.7
24,Manchester City,Newcastle Utd,2025-02-15,W,H,4,0,4,4,0,...,1.9,1.1,2.1,2.1,2.1,0.17,0,0.4,0.38,0.4

In [13]:
df_away= pd.read_csv(f"../Data/{away}.csv")
df_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Nott'ham Forest,Bournemouth,2024-08-17,D,H,1,1,0,1,0,...,0.5,0.8,-0.3,-0.3,-0.5,0.10,0,1.2,0.30,0.2
1,Nott'ham Forest,Southampton,2024-08-24,W,A,1,0,1,1,0,...,1.9,1.0,-1.2,-1.2,-1.9,0.11,0,0.0,0.02,0.0
2,Nott'ham Forest,Wolves,2024-08-31,D,H,1,1,0,1,0,...,1.0,1.2,0.0,0.0,0.0,0.06,1,0.6,0.29,-0.4
3,Nott'ham Forest,Liverpool,2024-09-14,W,A,1,0,1,1,0,...,0.4,0.2,0.6,0.6,0.6,0.09,0,0.6,0.11,0.6
4,Nott'ham Forest,Brighton,2024-09-22,D,A,2,2,0,1,1,...,0.6,0.4,0.6,0.4,0.4,0.21,0,1.1,0.36,-0.9
5,Nott'ham Forest,Fulham,2024-09-28,L,H,0,1,-1,0,0,...,0.6,1.0,-0.8,-0.8,-0.6,0.07,0,0.8,0.05,-0.2
6,Nott'ham Forest,Chelsea,2024-10-06,D,A,1,1,0,1,0,...,0.5,0.4,0.1,0.1,0.5,0.05,2,1.9,0.25,0.9
7,Nott'ham Forest,Crystal Palace,2024-10-21,W,H,1,0,1,1,0,...,1.5,1.2,-0.7,-0.7,-1.5,0.09,0,0.9,0.12,0.9
8,Nott'ham Forest,Leicester City,2024-10-25,W,A,3,1,2,3,0,...,0.8,0.4,1.3,1.3,0.2,0.09,1,1.0,0.97,0.0
9,Nott'ham Forest,West Ham,2024-11-02,W,H,3,0,3,3,0,...,1.7,1.5,0.8,0.8,0.3,0.11,1,0.0,0.03,0.0
10,Nott'ham Forest,Newcastle Utd,2024-11-10,L,H,1,3,-2,1,0,...,0.5,0.7,0.4,0.4,0.5,0.06,0,2.3,0.39,-0.7
11,Nott'ham Forest,Arsenal,2024-11-23,L,A,0,3,-3,0,0,...,0.2,0.4,-0.3,-0.3,-0.2,0.05,1,1.4,0.24,-1.6
12,Nott'ham Forest,Ipswich Town,2024-11-30,W,H,1,0,1,0,1,...,0.8,1.1,-0.6,-0.9,-0.8,0.08,1,0.4,0.19,0.4
13,Nott'ham Forest,Manchester City,2024-12-04,L,A,0,3,-3,0,0,...,0.6,0.8,-1.0,-1.0,-0.6,0.09,0,3.2,0.53,0.2
14,Nott'ham Forest,Manchester Utd,2024-12-07,W,A,3,2,1,3,0,...,0.7,1.1,2.2,2.2,2.3,0.08,0,1.6,0.26,-0.4
15,Nott'ham Forest,Aston Villa,2024-12-14,W,H,2,1,1,2,0,...,1.5,1.7,0.3,0.3,0.5,0.10,0,0.3,0.13,-0.7
16,Nott'ham Forest,Brentford,2024-12-21,W,A,2,0,2,2,0,...,0.7,0.6,1.1,1.1,0.3,0.09,0,1.0,0.33,1.0
17,Nott'ham Forest,Tottenham,2024-12-26,W,H,1,0,1,1,0,...,0.5,0.6,-0.1,-0.1,0.5,0.11,0,0.9,0.23,0.9
18,Nott'ham Forest,Everton,2024-12-29,W,A,2,0,2,2,0,...,1.1,0.8,0.5,0.5,0.9,0.15,0,0.2,0.09,0.2
19,Nott'ham Forest,Wolves,2025-01-06,W,A,3,0,3,3,0,...,1.9,1.3,0.9,0.9,1.1,0.19,1,1.0,0.20,1.0
20,Nott'ham Forest,Liverpool,2025-01-14,D,H,1,1,0,1,0,...,0.2,0.2,0.7,0.7,0.8,0.05,1,1.9,0.32,0.9
21,Nott'ham Forest,Southampton,2025-01-19,W,H,3,2,1,3,0,...,1.3,1.1,1.2,1.2,1.7,0.15,1,1.7,0.58,-0.3
22,Nott'ham Forest,Bournemouth,2025-01-25,L,A,0,5,-5,0,0,...,0.8,0.9,-1.0,-1.0,-0.8,0.05,2,3.8,0.38,-1.2
23,Nott'ham Forest,Brighton,2025-02-01,W,H,7,0,7,5,1,...,2.6,1.5,2.7,2.5,1.4,0.20,0,1.3,0.27,1.3
24,Nott'ham Forest,Fulham,2025-02-15,L,A,1,2,-1,1,0,...,0.3,0.3,0.6,0.6,0.7,0.05,0,3.4,0.38,1.4

In [14]:
df_vs_away= pd.read_csv(f"../Data/vs {away}.csv")
df_vs_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Bournemouth,Nott'ham Forest,2024-08-17,D,A,1,1,0,1,0,...,0.5,0.5,-0.2,-0.2,-0.5,0.09,1,1.7,0.23,0.7
1,Southampton,Nott'ham Forest,2024-08-24,L,H,0,1,-1,0,0,...,0.1,0.4,-0.1,-0.1,-0.1,0.03,0,1.6,0.20,0.6
2,Wolves,Nott'ham Forest,2024-08-31,D,A,1,1,0,1,0,...,0.5,0.5,0.3,0.3,0.5,0.07,0,1.7,0.35,0.7
3,Liverpool,Nott'ham Forest,2024-09-14,L,H,0,1,-1,0,0,...,0.9,1.4,-0.9,-0.9,-0.9,0.07,0,0.7,0.25,-0.3
4,Brighton,Nott'ham Forest,2024-09-22,D,H,2,2,0,2,0,...,0.7,0.9,1.0,1.0,0.3,0.07,1,1.7,0.27,-0.3
5,Fulham,Nott'ham Forest,2024-09-28,W,A,1,0,1,0,1,...,0.3,0.4,-0.3,-0.5,-0.3,0.04,0,0.0,0.01,0.0
6,Chelsea,Nott'ham Forest,2024-10-06,D,H,1,1,0,1,0,...,2.3,1.7,-1.3,-1.3,-1.3,0.11,0,1.6,0.18,0.6
7,Crystal Palace,Nott'ham Forest,2024-10-21,L,A,0,1,-1,0,0,...,0.8,0.4,-1.0,-1.0,-0.8,0.05,0,1.8,0.30,0.8
8,Leicester City,Nott'ham Forest,2024-10-25,L,H,1,3,-2,1,0,...,0.7,1.0,0.2,0.2,0.3,0.07,0,1.7,0.34,-1.3
9,West Ham,Nott'ham Forest,2024-11-02,L,A,0,3,-3,0,0,...,0.0,0.3,-0.1,-0.1,0.0,0.03,0,2.9,0.48,-0.1
10,Newcastle Utd,Nott'ham Forest,2024-11-10,W,A,3,1,2,3,0,...,1.3,1.4,1.4,1.4,0.7,0.10,0,0.9,0.30,-0.1
11,Arsenal,Nott'ham Forest,2024-11-23,W,H,3,0,3,3,0,...,1.2,0.8,1.8,1.8,1.8,0.06,0,0.0,NaN,0.0
12,Ipswich Town,Nott'ham Forest,2024-11-30,L,A,0,1,-1,0,0,...,0.6,0.6,-0.6,-0.6,-0.6,0.08,0,1.5,0.11,0.5
13,Manchester City,Nott'ham Forest,2024-12-04,W,H,3,0,3,3,0,...,2.3,1.4,0.6,0.6,0.7,0.14,1,0.5,0.18,0.5
14,Manchester Utd,Nott'ham Forest,2024-12-07,L,H,2,3,-1,2,0,...,0.8,0.8,0.4,0.4,0.2,0.10,1,1.5,0.51,-1.5
15,Aston Villa,Nott'ham Forest,2024-12-14,L,A,1,2,-1,1,0,...,0.4,1.1,0.6,0.6,0.6,0.05,0,1.9,0.34,-0.1
16,Brentford,Nott'ham Forest,2024-12-21,L,H,0,2,-2,0,0,...,0.5,1.0,-0.7,-0.7,-0.5,0.10,0,1.4,0.23,-0.6
17,Tottenham,Nott'ham Forest,2024-12-26,L,A,0,1,-1,0,0,...,0.8,0.7,-0.9,-0.9,-0.8,0.07,1,1.4,0.45,0.4
18,Everton,Nott'ham Forest,2024-12-29,L,H,0,2,-2,0,0,...,0.8,0.9,-0.9,-0.9,-0.8,0.07,1,1.6,0.24,-0.4
19,Wolves,Nott'ham Forest,2025-01-06,L,H,0,3,-3,0,0,...,0.7,1.0,-1.5,-1.5,-0.7,0.12,0,2.7,0.90,-0.3
20,Liverpool,Nott'ham Forest,2025-01-14,D,A,1,1,0,1,0,...,1.6,2.0,-1.0,-1.0,-0.6,0.09,0,0.9,0.31,-0.1
21,Southampton,Nott'ham Forest,2025-01-19,L,A,2,3,-1,2,0,...,0.9,0.8,1.1,1.1,1.1,0.09,0,1.1,0.27,-1.9
22,Bournemouth,Nott'ham Forest,2025-01-25,W,H,5,0,5,5,0,...,0.8,0.9,3.3,3.3,3.2,0.11,1,1.0,0.25,1.0
23,Brighton,Nott'ham Forest,2025-02-01,L,A,0,7,-7,0,0,...,0.7,0.9,-0.9,-0.9,-0.7,0.09,1,4.3,0.43,-1.7
24,Fulham,Nott'ham Forest,2025-02-15,W,H,2,1,1,2,0,...,1.6,1.6,-0.1,-0.1,0.4,0.09,0,1.1,0.53,0.1

In [15]:
print(list(df_away.columns))

['Team', 'Opp', 'Date', 'Result', 'H/A', 'GF', 'GA', 'GD', 'G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att (GK)', 'Thr', 'Pa Launch%', 'Pa AvgLen', 'Won', 'Lost', 'Won%', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 'PrgC', 'Last3rd Car', 'OppCr', 'Stp', 'Stp%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'GK Att', 'Launch%', 'AvgLen', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'PKcon', 'OG', 'Recov', '#OPA', 'AvgDist', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'PKdef', 'PKA', 'PKms', 'Missed PK%', 'PKAg', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 'Fld Sc', 'Def-Sc', 'SoTA', 'Saves', 'Save%', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'xG', 'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'PSxG', 'PSxG/SoT', 'PSxG+/-']

# Features

## Offense

In [16]:
offense= ['G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 
          'PrgC', 'Last3rd Car', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'Sh', 'G/Sh', 
          'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 
          'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 
          'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 
          'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 
          'Fld Sc', 'Def-Sc', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'xG', 
          'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'GF']

In [17]:
df_home_off= df_home[offense]
df_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,23,0,7,1,14.3,5,71.4,...,-1.5,-1.5,0.3,0.2,0.7,0.7,0.7,0.08,0,1
1,1,0,0,61,0,15,6,40.0,7,46.7,...,-0.6,-0.6,1.7,1.4,-0.6,-0.6,-0.7,0.12,0,1
2,2,0,0,35,0,20,8,40.0,10,50.0,...,0.6,0.6,1.8,1.4,0.2,0.2,0.2,0.20,0,2
3,2,0,0,51,0,22,12,54.5,8,36.4,...,0.3,0.3,1.5,1.2,0.5,0.5,0.5,0.11,0,2
4,1,0,0,61,0,15,7,46.7,5,33.3,...,-0.7,-0.7,0.9,0.8,-0.5,-0.5,0.1,0.10,1,1
5,0,1,0,38,1,12,8,66.7,2,16.7,...,0.7,-0.1,0.8,0.7,-0.6,-0.8,-0.8,0.08,0,1
6,0,0,1,67,1,20,6,30.0,9,45.0,...,1.4,0.6,1.1,1.0,-2.1,-1.3,-1.1,0.10,0,0
7,0,0,0,60,0,21,10,47.6,8,38.1,...,0.9,0.9,1.8,1.3,-2.0,-2.0,-1.8,0.10,2,0
8,1,0,0,50,0,13,6,46.2,4,30.8,...,0.2,0.2,1.7,1.3,-0.8,-0.8,-0.7,0.16,1,1
9,1,0,0,37,0,10,6,60.0,3,30.0,...,-0.5,-0.5,0.4,0.7,0.5,0.5,0.6,0.06,0,1
10,3,0,0,56,0,16,2,12.5,12,75.0,...,1.1,1.1,1.3,1.4,1.4,1.4,0.7,0.10,0,3
11,0,0,0,53,0,13,5,38.5,8,61.5,...,0.8,0.8,1.0,0.9,-1.6,-1.6,-1.0,0.09,0,0
12,0,0,0,51,0,26,6,23.1,16,61.5,...,-1.7,-1.7,0.0,0.2,0.0,0.0,0.0,0.04,0,1
13,3,0,0,42,0,31,12,38.7,9,29.0,...,0.1,0.1,1.6,0.8,0.9,0.9,1.4,0.12,1,3
14,2,0,0,57,0,26,14,53.8,12,46.2,...,0.2,0.2,1.2,1.4,0.5,0.5,0.8,0.09,0,2
15,4,0,0,59,0,25,11,44.0,11,44.0,...,3.6,3.6,2.8,2.2,0.2,0.2,0.2,0.14,1,4
16,4,0,0,58,0,16,11,68.8,4,25.0,...,1.6,1.6,2.2,2.1,1.7,1.7,0.8,0.16,0,4
17,3,0,0,62,0,9,6,66.7,2,22.2,...,2.3,2.3,1.7,2.5,0.3,0.3,0.3,0.13,1,3
18,2,0,0,48,0,20,6,30.0,13,65.0,...,1.1,1.1,1.4,0.8,0.1,0.1,-0.4,0.16,0,2
19,2,0,0,44,0,21,7,33.3,10,47.6,...,1.6,1.6,2.3,1.0,-0.5,-0.5,-1.3,0.18,0,2
20,3,0,0,60,0,27,16,59.3,6,22.2,...,0.5,0.5,1.9,1.7,0.9,0.9,0.1,0.12,0,3
21,1,0,0,56,0,18,8,44.4,8,44.4,...,-1.2,-1.2,0.4,0.6,0.2,0.2,0.6,0.06,1,1
22,2,1,0,47,1,16,7,43.8,9,56.3,...,2.2,1.4,1.8,1.5,0.1,-0.1,0.2,0.13,0,3
23,1,0,0,49,0,13,3,23.1,7,53.8,...,-0.8,-0.8,0.6,1.2,0.2,0.2,-0.6,0.07,0,1
24,0,0,0,39,0,5,1,20.0,3,60.0,...,-1.4,-1.4,0.5,0.2,-0.5,-0.5,-0.5,0.16,0,0

In [18]:
df_vs_home_off= df_vs_home[offense]
df_vs_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,0,0,0,77,0,14,6,42.9,7,50.0,...,1.5,1.5,1.5,1.6,-1.8,-1.8,-1.5,0.10,1,0
1,1,0,0,39,0,14,2,14.3,12,85.7,...,0.6,0.6,2.2,1.8,-1.2,-1.2,-1.2,0.14,1,1
2,0,0,0,65,0,26,10,38.5,13,50.0,...,-0.6,-0.6,0.6,0.9,-1.2,-1.2,-0.6,0.06,1,1
3,1,0,0,49,0,23,15,65.2,8,34.8,...,-0.3,-0.3,0.9,1.0,-0.2,-0.2,0.1,0.10,0,1
4,3,0,0,39,0,17,4,23.5,7,41.2,...,0.7,0.7,2.0,1.2,0.8,0.8,1.0,0.10,0,3
5,1,0,0,62,0,24,13,54.2,7,29.2,...,-0.7,0.1,0.8,1.4,0.1,0.1,0.2,0.06,0,1
6,0,0,0,33,0,24,13,54.2,9,37.5,...,-1.4,-0.6,0.3,0.2,-0.7,-0.7,-0.3,0.09,1,0
7,1,0,0,40,0,19,3,15.8,14,73.7,...,-0.9,-0.9,0.7,0.5,-0.1,-0.1,0.3,0.11,0,1
8,2,0,0,50,0,17,7,41.2,7,41.2,...,-0.2,-0.2,1.5,0.9,0.4,0.4,0.5,0.09,0,2
9,0,0,0,63,0,17,3,17.6,10,58.8,...,0.5,0.5,1.1,1.7,-1.1,-1.1,-1.1,0.11,0,0
10,1,0,0,44,0,15,6,40.0,6,40.0,...,-1.1,-1.1,0.5,0.7,0.4,0.4,0.5,0.06,0,1
11,2,0,0,47,0,22,8,36.4,11,50.0,...,-0.8,-0.8,0.6,0.4,1.1,1.1,1.4,0.06,1,2
12,1,0,0,49,0,14,9,64.3,3,21.4,...,1.7,1.7,1.5,1.6,-0.7,-0.7,-0.5,0.11,0,1
13,3,0,0,58,0,17,7,41.2,9,52.9,...,-0.1,-0.1,1.2,1.1,1.1,1.1,1.8,0.12,0,3
14,4,0,0,43,0,16,9,56.3,7,43.8,...,-0.2,-0.2,0.9,0.8,2.8,2.8,2.1,0.11,0,4
15,0,0,0,41,0,12,8,66.7,4,33.3,...,-3.6,-3.6,0.2,0.3,-0.2,-0.2,-0.2,0.05,0,0
16,0,0,0,42,0,13,4,30.8,8,61.5,...,-1.6,-1.6,0.5,0.5,-0.7,-0.7,-0.5,0.07,0,0
17,0,0,0,38,0,17,10,58.8,4,23.5,...,-2.3,-2.3,0.2,0.4,-0.3,-0.3,-0.2,0.09,1,0
18,0,0,0,52,0,15,4,26.7,10,66.7,...,-1.1,-1.1,0.7,0.7,-0.8,-0.8,-0.7,0.09,0,0
19,1,0,0,56,0,18,5,27.8,6,33.3,...,-1.6,-1.6,0.7,1.0,0.1,0.1,0.3,0.07,0,1
20,0,0,0,40,0,21,9,42.9,8,38.1,...,-0.5,-0.5,1.5,0.7,-1.6,-1.6,-1.5,0.12,0,0
21,4,0,0,44,0,26,16,61.5,6,23.1,...,1.2,1.2,1.6,1.2,2.0,2.0,2.4,0.11,0,4
22,1,0,0,53,0,19,9,47.4,8,42.1,...,-2.2,-1.4,0.5,0.5,0.2,0.2,0.5,0.06,0,1
23,2,0,0,51,0,14,9,64.3,2,14.3,...,0.8,0.8,1.5,1.0,0.4,0.4,0.5,0.10,0,2
24,4,0,0,61,0,28,8,28.6,17,60.7,...,1.4,1.4,1.9,1.1,2.1,2.1,2.1,0.17,0,4

In [19]:
df_away_off= df_away[offense]
df_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,53,0,23,9,39.1,10,43.5,...,0.1,0.1,0.5,0.8,-0.3,-0.3,-0.5,0.10,0,1
1,1,0,0,36,0,20,7,35.0,11,55.0,...,2.1,2.1,1.9,1.0,-1.2,-1.2,-1.9,0.11,0,1
2,1,0,0,52,0,21,8,38.1,8,38.1,...,0.3,0.3,1.0,1.2,0.0,0.0,0.0,0.06,1,1
3,1,0,0,32,0,14,6,42.9,5,35.7,...,-0.5,-0.5,0.4,0.2,0.6,0.6,0.6,0.09,0,1
4,1,1,0,30,1,14,8,57.1,3,21.4,...,0.4,-0.4,0.6,0.4,0.6,0.4,0.4,0.21,0,2
5,0,0,0,41,0,6,4,66.7,1,16.7,...,-0.5,0.3,0.6,1.0,-0.8,-0.8,-0.6,0.07,0,0
6,1,0,0,35,0,19,9,47.4,7,36.8,...,-1.4,-1.4,0.5,0.4,0.1,0.1,0.5,0.05,2,1
7,1,0,0,51,0,27,16,59.3,8,29.6,...,0.7,0.7,1.5,1.2,-0.7,-0.7,-1.5,0.09,0,1
8,3,0,0,35,0,24,15,62.5,5,20.8,...,0.9,0.9,0.8,0.4,1.3,1.3,0.2,0.09,1,3
9,3,0,0,54,0,12,6,50.0,4,33.3,...,2.0,2.0,1.7,1.5,0.8,0.8,0.3,0.11,1,3
10,1,0,0,44,0,15,6,40.0,6,40.0,...,-1.1,-1.1,0.5,0.7,0.4,0.4,0.5,0.06,0,1
11,0,0,0,34,0,14,4,28.6,6,42.9,...,-0.8,-0.8,0.2,0.4,-0.3,-0.3,-0.2,0.05,1,0
12,0,1,0,45,1,20,7,35.0,9,45.0,...,1.1,0.3,0.8,1.1,-0.6,-0.9,-0.8,0.08,1,1
13,0,0,0,34,0,13,5,38.5,5,38.5,...,-1.3,-1.3,0.6,0.8,-1.0,-1.0,-0.6,0.09,0,0
14,3,0,0,29,0,16,8,50.0,8,50.0,...,-0.8,-0.8,0.7,1.1,2.2,2.2,2.3,0.08,0,3
15,2,0,0,50,0,15,10,66.7,5,33.3,...,1.3,1.3,1.5,1.7,0.3,0.3,0.5,0.10,0,2
16,2,0,0,36,0,19,4,21.1,10,52.6,...,0.2,0.2,0.7,0.6,1.1,1.1,0.3,0.09,0,2
17,1,0,0,30,0,16,9,56.3,4,25.0,...,0.2,0.2,0.5,0.6,-0.1,-0.1,0.5,0.11,0,1
18,2,0,0,36,0,7,4,57.1,3,42.9,...,0.6,0.6,1.1,0.8,0.5,0.5,0.9,0.15,0,2
19,3,0,0,40,0,14,4,28.6,7,50.0,...,0.6,0.6,1.9,1.3,0.9,0.9,1.1,0.19,1,3
20,1,0,0,30,0,18,6,33.3,7,38.9,...,-1.7,-1.7,0.2,0.2,0.7,0.7,0.8,0.05,1,1
21,3,0,0,45,0,17,7,41.2,5,29.4,...,0.9,0.9,1.3,1.1,1.2,1.2,1.7,0.15,1,3
22,0,0,0,50,0,16,8,50.0,6,37.5,...,-0.7,-0.7,0.8,0.9,-1.0,-1.0,-0.8,0.05,2,0
23,5,1,0,38,1,23,15,65.2,8,34.8,...,2.4,1.6,2.6,1.5,2.7,2.5,1.4,0.20,0,7
24,1,0,0,45,0,12,7,58.3,5,41.7,...,-1.7,-1.7,0.3,0.3,0.6,0.6,0.7,0.05,0,1

In [20]:
df_vs_away_off= df_vs_away[offense]
df_vs_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,47,0,20,5,25.0,10,50.0,...,-0.1,-0.1,0.5,0.5,-0.2,-0.2,-0.5,0.09,1,1
1,0,0,0,64,0,22,7,31.8,12,54.5,...,-2.1,-2.1,0.1,0.4,-0.1,-0.1,-0.1,0.03,0,0
2,1,0,0,48,0,19,8,42.1,6,31.6,...,-0.3,-0.3,0.5,0.5,0.3,0.3,0.5,0.07,0,1
3,0,0,0,68,0,20,6,30.0,13,65.0,...,0.5,0.5,0.9,1.4,-0.9,-0.9,-0.9,0.07,0,0
4,2,0,0,70,0,20,10,50.0,7,35.0,...,-0.4,0.4,0.7,0.9,1.0,1.0,0.3,0.07,1,2
5,0,1,0,59,1,16,9,56.3,5,31.3,...,0.5,-0.3,0.3,0.4,-0.3,-0.5,-0.3,0.04,0,1
6,1,0,0,65,0,16,11,68.8,4,25.0,...,1.4,1.4,2.3,1.7,-1.3,-1.3,-1.3,0.11,0,1
7,0,0,0,49,0,9,6,66.7,3,33.3,...,-0.7,-0.7,0.8,0.4,-1.0,-1.0,-0.8,0.05,0,0
8,1,0,0,65,0,20,6,30.0,11,55.0,...,-0.9,-0.9,0.7,1.0,0.2,0.2,0.3,0.07,0,1
9,0,0,0,46,0,20,10,50.0,7,35.0,...,-2.0,-2.0,0.0,0.3,-0.1,-0.1,0.0,0.03,0,0
10,3,0,0,56,0,16,2,12.5,12,75.0,...,1.1,1.1,1.3,1.4,1.4,1.4,0.7,0.10,0,3
11,3,0,0,66,0,19,8,42.1,10,52.6,...,0.8,0.8,1.2,0.8,1.8,1.8,1.8,0.06,0,3
12,0,0,0,55,0,19,8,42.1,10,52.6,...,-1.1,-0.3,0.6,0.6,-0.6,-0.6,-0.6,0.08,0,0
13,3,0,0,66,0,27,13,48.1,9,33.3,...,1.3,1.3,2.3,1.4,0.6,0.6,0.7,0.14,1,3
14,2,0,0,71,0,15,7,46.7,6,40.0,...,0.8,0.8,0.8,0.8,0.4,0.4,0.2,0.10,1,2
15,1,0,0,50,0,16,5,31.3,10,62.5,...,-1.3,-1.3,0.4,1.1,0.6,0.6,0.6,0.05,0,1
16,0,0,0,64,0,25,11,44.0,10,40.0,...,-0.2,-0.2,0.5,1.0,-0.7,-0.7,-0.5,0.10,0,0
17,0,0,0,70,0,22,10,45.5,10,45.5,...,-0.2,-0.2,0.8,0.7,-0.9,-0.9,-0.8,0.07,1,0
18,0,0,0,64,0,21,12,57.1,8,38.1,...,-0.6,-0.6,0.8,0.9,-0.9,-0.9,-0.8,0.07,1,0
19,0,0,0,60,0,14,4,28.6,9,64.3,...,-0.6,-0.6,0.7,1.0,-1.5,-1.5,-0.7,0.12,0,0
20,1,0,0,70,0,19,4,21.1,13,68.4,...,1.7,1.7,1.6,2.0,-1.0,-1.0,-0.6,0.09,0,1
21,2,0,0,55,0,19,12,63.2,7,36.8,...,-0.9,-0.9,0.9,0.8,1.1,1.1,1.1,0.09,0,2
22,5,0,0,50,0,17,11,64.7,3,17.6,...,0.7,0.7,0.8,0.9,3.3,3.3,3.2,0.11,1,5
23,0,0,0,62,0,30,14,46.7,15,50.0,...,-2.4,-1.6,0.7,0.9,-0.9,-0.9,-0.7,0.09,1,0
24,2,0,0,55,0,12,5,41.7,6,50.0,...,1.7,1.7,1.6,1.6,-0.1,-0.1,0.4,0.09,0,2

## Defence

In [21]:
defence= ['OppCr', 'Stp', 'Stp%', 'PKcon', '#OPA', 'AvgDist', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'SoTA', 'Saves', 
          'Save%', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 
          'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',  'PSxG', 'PSxG/SoT', 'PSxG+/-', 'GA']

In [22]:
df_home_def= df_home[defence]
df_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,24,1,4.2,0,1,20.5,0,NaN,0,0,...,11,13,4,20,39,0,0.4,0.14,0.4,0
1,14,1,7.1,0,6,19.2,0,NaN,0,0,...,4,6,4,25,16,1,1.1,0.28,0.1,1
2,22,1,4.5,0,2,15.7,0,NaN,0,0,...,7,15,14,31,32,1,1.5,0.26,1.5,1
3,13,1,7.7,0,2,17.0,0,NaN,0,0,...,1,9,5,19,25,1,1.3,0.25,0.3,1
4,13,0,0.0,0,0,2.0,0,NaN,0,0,...,2,4,10,19,15,3,3.0,0.29,0.0,3
5,16,1,6.3,0,1,14.0,0,NaN,0,0,...,6,6,10,25,23,1,1.4,0.23,0.4,1
6,2,1,50.0,0,0,11.8,0,NaN,0,0,...,1,13,8,33,8,0,0.6,0.28,0.6,0
7,8,0,0.0,0,1,15.0,0,NaN,0,0,...,2,9,13,39,7,1,1.7,0.34,0.7,1
8,16,2,12.5,0,5,12.2,0,NaN,0,0,...,4,6,6,19,13,2,1.9,0.28,-0.1,2
9,21,2,9.5,0,0,6.9,0,NaN,0,0,...,4,5,6,29,26,0,0.0,NaN,0.0,0
10,18,3,16.7,0,1,9.7,0,NaN,0,0,...,3,7,14,27,23,1,0.9,0.30,-0.1,1
11,8,0,0.0,0,3,19.8,0,NaN,0,1,...,5,5,7,28,21,0,1.2,0.20,-0.8,2
12,19,3,15.8,0,2,15.4,0,NaN,0,0,...,5,8,8,20,27,1,0.9,0.31,-0.1,1
13,13,3,23.1,0,2,16.2,0,NaN,0,0,...,6,6,5,19,17,1,3.4,0.69,0.4,3
14,11,2,18.2,0,5,20.7,0,NaN,0,0,...,2,6,3,15,24,2,2.3,0.34,-1.7,4
15,6,2,33.3,0,1,10.8,0,NaN,0,0,...,3,14,6,14,15,0,0.1,0.09,0.1,0
16,8,0,0.0,0,0,17.0,0,NaN,0,0,...,4,8,6,21,18,0,0.2,0.12,0.2,0
17,13,2,15.4,0,0,9.4,0,NaN,0,0,...,1,4,8,19,25,0,0.2,0.18,0.2,0
18,10,1,10.0,0,0,9.5,0,NaN,0,0,...,5,5,8,27,18,1,0.0,NaN,0.0,0
19,21,2,9.5,0,0,6.7,0,NaN,0,0,...,3,6,9,26,35,0,1.2,0.31,0.2,1
20,8,0,0.0,0,3,27.4,0,NaN,0,0,...,2,9,12,26,16,0,1.6,0.23,1.6,0
21,19,0,0.0,0,2,16.3,0,NaN,0,0,...,3,7,3,20,33,3,4.1,0.41,0.1,4
22,11,0,0.0,0,2,22.0,0,NaN,0,0,...,3,4,11,30,21,0,1.1,0.23,0.1,1
23,21,1,4.8,0,0,6.7,0,NaN,0,0,...,7,6,4,11,28,0,1.5,0.39,-0.5,2
24,10,2,20.0,0,3,17.8,0,NaN,0,1,...,2,7,7,33,21,1,2.8,0.39,-1.2,4

In [23]:
df_vs_home_def= df_vs_home[defence]
df_vs_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,12,2,16.7,0,0,7.2,0,NaN,0,0,...,2,6,3,16,13,1,0.6,0.63,-0.4,1
1,19,2,10.5,0,0,4.5,0,NaN,0,0,...,5,19,6,27,35,0,2.6,0.53,1.6,1
2,10,1,10.0,0,0,9.8,0,NaN,0,0,...,3,13,7,29,12,0,2.1,0.71,0.1,2
3,10,1,10.0,0,1,10.0,0,NaN,0,0,...,4,8,10,33,20,0,1.7,0.29,-0.3,2
4,11,1,9.1,0,0,11.0,0,NaN,0,0,...,3,3,6,25,21,1,1.0,0.21,0.0,1
5,13,0,0.0,1,0,11.0,0,0.0,0,0,...,3,5,7,22,21,0,1.1,0.11,0.1,1
6,18,1,5.6,1,1,12.8,1,100.0,0,0,...,4,6,10,29,30,0,0.9,0.04,0.9,0
7,17,1,5.9,0,1,10.1,0,NaN,0,0,...,8,8,9,35,38,0,0.9,0.15,0.9,0
8,9,1,11.1,0,2,15.0,0,NaN,0,0,...,4,11,16,28,25,0,1.2,0.58,0.2,1
9,11,2,18.2,0,3,18.7,0,NaN,0,0,...,3,13,6,23,18,0,1.3,0.32,0.3,1
10,23,1,4.3,0,0,6.4,0,NaN,0,1,...,4,4,7,36,27,1,2.3,0.39,-0.7,3
11,28,0,0.0,0,4,22.6,0,NaN,0,0,...,6,8,10,36,33,1,0.4,0.21,0.4,0
12,18,0,0.0,0,5,24.8,0,NaN,0,0,...,1,6,13,43,24,0,0.0,NaN,0.0,1
13,13,1,7.7,0,1,13.5,0,NaN,0,0,...,4,9,10,33,23,3,2.5,0.42,-0.5,3
14,14,1,7.1,0,0,9.3,0,NaN,0,0,...,2,7,4,28,29,1,1.3,0.43,-0.7,2
15,10,0,0.0,0,1,18.5,0,NaN,0,1,...,7,3,13,36,25,2,4.3,0.39,0.3,4
16,6,1,16.7,0,3,15.0,0,NaN,0,0,...,1,4,4,14,14,2,1.8,0.26,-2.2,4
17,16,2,12.5,0,0,6.5,0,NaN,0,0,...,8,2,5,20,18,4,3.3,0.47,0.3,3
18,9,0,0.0,0,1,11.0,0,NaN,0,0,...,4,10,8,34,9,0,1.7,0.42,-0.3,2
19,15,5,33.3,0,2,12.4,0,NaN,0,0,...,7,10,9,34,17,3,2.2,0.55,0.2,2
20,12,1,8.3,0,3,24.0,0,NaN,0,0,...,6,12,10,35,13,0,1.8,0.36,-1.2,3
21,21,1,4.8,0,1,13.3,0,NaN,0,1,...,6,14,13,34,35,0,0.6,0.16,-0.4,1
22,8,2,25.0,1,0,6.0,0,0.0,0,0,...,4,5,5,26,23,1,2.7,0.24,-0.3,3
23,14,0,0.0,0,1,12.5,0,NaN,0,0,...,1,11,7,27,27,0,1.7,0.42,0.7,1
24,12,0,0.0,0,2,19.7,0,NaN,0,0,...,1,10,6,16,20,1,0.4,0.38,0.4,0

In [24]:
df_away_def= df_away[defence]
df_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,18,0,0.0,0,0,9.3,0,NaN,0,0,...,3,9,7,31,26,0,1.2,0.30,0.2,1
1,10,2,20.0,0,0,3.5,0,NaN,0,0,...,3,5,11,35,23,0,0.0,0.02,0.0,0
2,6,0,0.0,0,0,5.7,0,NaN,0,0,...,3,6,10,27,13,0,0.6,0.29,-0.4,1
3,16,1,6.3,0,1,12.0,0,NaN,0,0,...,3,8,11,33,32,2,0.6,0.11,0.6,0
4,34,0,0.0,0,0,1.0,0,NaN,1,0,...,7,5,8,26,51,0,1.1,0.36,-0.9,2
5,14,0,0.0,1,0,4.3,0,0.0,0,0,...,7,6,9,17,21,0,0.8,0.05,-0.2,1
6,23,0,0.0,0,0,2.0,0,NaN,0,0,...,5,13,6,18,33,1,1.9,0.25,0.9,1
7,12,0,0.0,0,0,7.0,0,NaN,0,0,...,5,11,14,23,18,0,0.9,0.12,0.9,0
8,20,1,5.0,0,0,5.4,0,NaN,0,0,...,3,7,10,29,28,1,1.0,0.97,0.0,1
9,10,0,0.0,0,0,14.0,0,NaN,0,0,...,1,6,6,24,25,0,0.0,0.03,0.0,0
10,23,1,4.3,0,0,6.4,0,NaN,0,1,...,4,4,7,36,27,1,2.3,0.39,-0.7,3
11,12,0,0.0,0,0,4.0,0,NaN,0,0,...,6,4,10,26,26,0,1.4,0.24,-1.6,3
12,13,1,7.7,0,0,3.0,0,NaN,0,0,...,3,11,8,28,22,0,0.4,0.19,0.4,0
13,12,0,0.0,0,1,16.5,0,NaN,0,0,...,3,7,14,38,19,0,3.2,0.53,0.2,3
14,20,1,5.0,0,1,15.0,0,NaN,0,0,...,5,6,8,24,32,0,1.6,0.26,-0.4,2
15,11,2,18.2,0,1,10.8,0,NaN,0,0,...,2,5,8,27,25,0,0.3,0.13,-0.7,1
16,30,1,3.3,0,0,6.3,0,NaN,0,0,...,2,10,18,38,50,2,1.0,0.33,1.0,0
17,17,1,5.9,0,0,5.3,0,NaN,0,0,...,5,14,10,31,31,0,0.9,0.23,0.9,0
18,27,2,7.4,0,0,2.0,0,NaN,0,0,...,2,7,10,28,40,0,0.2,0.09,0.2,0
19,23,0,0.0,0,0,2.8,0,NaN,0,0,...,6,4,10,28,33,2,1.0,0.20,1.0,0
20,27,1,3.7,0,0,11.0,0,NaN,0,1,...,7,11,9,29,59,0,1.9,0.32,0.9,1
21,22,1,4.5,0,0,4.5,0,NaN,0,1,...,5,4,8,27,22,0,1.7,0.58,-0.3,2
22,11,1,9.1,0,0,2.3,0,NaN,0,0,...,3,10,5,16,25,2,3.8,0.38,-1.2,5
23,21,0,0.0,0,1,23.3,0,NaN,0,0,...,2,10,7,28,39,0,1.3,0.27,1.3,0
24,25,0,0.0,0,1,15.5,0,NaN,0,1,...,6,4,8,18,31,0,3.4,0.38,1.4,2

In [25]:
df_vs_away_def= df_vs_away[defence]
df_vs_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,11,0,0.0,0,3,14.6,0,NaN,0,0,...,3,10,14,32,29,1,1.7,0.23,0.7,1
1,14,1,7.1,0,0,6.0,0,NaN,0,1,...,6,9,2,20,19,2,1.6,0.20,0.6,1
2,17,1,5.9,0,1,11.0,0,NaN,0,1,...,6,8,10,33,27,0,1.7,0.35,0.7,1
3,5,0,0.0,0,1,21.3,0,NaN,0,0,...,0,5,11,23,16,0,0.7,0.25,-0.3,1
4,3,1,33.3,1,6,22.5,0,0.0,0,0,...,1,13,7,19,8,0,1.7,0.27,-0.3,2
5,20,1,5.0,0,0,7.3,0,NaN,0,0,...,5,3,9,16,44,1,0.0,0.01,0.0,0
6,9,1,11.1,0,3,21.2,0,NaN,0,0,...,6,8,8,22,18,1,1.6,0.18,0.6,1
7,17,1,5.9,0,0,10.0,0,NaN,0,0,...,9,13,5,28,25,1,1.8,0.30,0.8,1
8,19,0,0.0,0,3,21.2,0,NaN,0,0,...,6,9,6,20,26,1,1.7,0.34,-1.3,3
9,15,1,6.7,0,0,7.0,0,NaN,0,0,...,3,6,11,24,32,1,2.9,0.48,-0.1,3
10,18,3,16.7,0,1,9.7,0,NaN,0,0,...,3,7,14,27,23,1,0.9,0.30,-0.1,1
11,11,1,9.1,0,3,19.8,0,NaN,0,0,...,1,5,4,19,13,0,0.0,NaN,0.0,0
12,18,2,11.1,1,0,4.0,0,0.0,0,0,...,2,2,4,20,21,1,1.5,0.11,0.5,1
13,11,0,0.0,0,2,14.3,0,NaN,0,0,...,2,7,5,21,15,2,0.5,0.18,0.5,0
14,6,0,0.0,0,1,14.0,0,NaN,0,1,...,4,4,9,22,5,2,1.5,0.51,-1.5,3
15,18,1,5.6,0,0,3.0,0,NaN,0,1,...,5,4,6,17,22,2,1.9,0.34,-0.1,2
16,12,0,0.0,0,0,5.0,0,NaN,0,0,...,1,2,13,30,17,1,1.4,0.23,-0.6,2
17,4,0,0.0,0,0,6.3,0,NaN,0,0,...,2,4,7,18,3,1,1.4,0.45,0.4,1
18,7,1,14.3,0,3,24.8,0,NaN,0,0,...,0,6,6,22,17,1,1.6,0.24,-0.4,2
19,9,0,0.0,0,3,17.6,0,NaN,0,0,...,2,6,10,23,24,1,2.7,0.90,-0.3,3
20,4,0,0.0,0,1,28.0,0,NaN,0,0,...,2,3,2,12,32,0,0.9,0.31,-0.1,1
21,13,1,7.7,0,0,9.5,0,NaN,0,0,...,3,6,6,17,32,1,1.1,0.27,-1.9,3
22,19,1,5.3,0,0,6.5,0,NaN,0,0,...,5,9,9,31,34,0,1.0,0.25,1.0,0
23,7,0,0.0,1,2,22.7,0,0.0,0,1,...,1,10,5,26,13,4,4.3,0.43,-1.7,7
24,15,0,0.0,0,2,14.2,0,NaN,0,0,...,3,3,7,15,25,0,1.1,0.53,0.1,1

## Combined

In [26]:
combined= ['Won', 'Lost', 'Won%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Recov']

In [27]:
df_home_cmb= df_home[combined]
df_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0     7     9  43.8     2     1      0   15   16     31
1    10    13  43.5     2     0      0    8   19     59
2     9    13  40.9     4     0      0   16   13     40
3    13     8  61.9     3     0      0    6   16     33
4    15     6  71.4     0     0      0    8   16     37
5    13     6  68.4     4     0      0   14   10     45
6    11    13  45.8     2     0      0    8   12     53
7    10    16  38.5     2     0      0   11    8     51
8    14    13  51.9     3     0      0   16   13     37
9    18    14  56.3     4     0      0   16   18     40
10   22    15  59.5     1     0      0    6   13     50
11    7    14  33.3     1     0      0   11    7     53
12   16    16  50.0     3     0      0   11   12     42
13    9     9  50.0     2     0      0    9   17     41
14    9    10  47.4     0     0      0    7   10     43
15   11    13  45.8     3     0      0    7   15     50
16    7     8  46.7     0     0      0    7    9     52
17   14     8  63.6     2     0      0   15   10     49
18    9    10  47.4     1     0      0    8   13     52
19   20    20  50.0     4     0      0   15   10     38
20   18     5  78.3     0     0      0   10   11     60
21   16    15  51.6     1     0      0    7   18     38
22    4    21  16.0     0     0      0    5   10     49
23   13    13  50.0     4     0      0   10   15     37
24    5     8  38.5     1     0      0   13    5     32

In [28]:
df_vs_home_cmb= df_vs_home[combined]
df_vs_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0     9     7  56.3     4     0      0   16   15     35
1    13    10  56.5     2     0      0   20    8     60
2    13     9  59.1     4     0      0   13   16     45
3     8    13  38.1     3     0      0   17    6     36
4     6    15  28.6     6     0      0   16    8     38
5     6    13  31.6     4     0      0   10   14     45
6    13    11  54.2     1     0      0   12    8     54
7    16    10  61.5     2     0      0    9   11     47
8    13    14  48.1     6     0      0   13   15     45
9    14    18  43.8     4     0      0   18   16     43
10   15    22  40.5     1     0      0   13    6     44
11   14     7  66.7     0     0      0    8   11     46
12   16    16  50.0     3     0      0   12   11     48
13    9     9  50.0     5     0      0   17    9     40
14   10     9  52.6     3     0      0   10    6     53
15   13    11  54.2     3     0      0   16    6     32
16    8     7  53.3     2     0      0    9    6     50
17    8    14  36.4     1     1      0   10   14     33
18   10     9  52.6     1     0      0   13    7     56
19   20    20  50.0     1     0      0   11   14     40
20    5    18  21.7     2     0      0   13   10     55
21   15    16  48.4     6     0      0   18    7     45
22   21     4  84.0     1     0      0   10    5     41
23   13    13  50.0     4     0      0   15   10     45
24    8     5  61.5     0     0      0    5   13     38

In [29]:
df_away_cmb= df_away[combined]
df_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    25    15  62.5     1     0      0   17    8     49
1    11     4  73.3     3     0      0   14   14     50
2    14    16  46.7     3     0      0   15   17     44
3    12    21  36.4     4     0      0    6   15     44
4     9    18  33.3     6     1      1   11   10     29
5    18     7  72.0     2     0      0   11   15     34
6    15    13  53.6     4     1      1   11   11     35
7    18    14  56.3     2     0      0    9   11     39
8    15    24  38.5     3     0      0    9   15     46
9    13    15  46.4     1     0      0    7    8     41
10   15    22  40.5     1     0      0   13    6     44
11   14    11  56.0     2     0      0   11   10     29
12   16    17  48.5     1     0      0    5   14     35
13    5     7  41.7     4     0      0   15    7     44
14   16    14  53.3     2     0      0   13   10     41
15   10     8  55.6     0     0      0   12    6     45
16   20    17  54.1     4     0      0   14   10     42
17   12    13  48.0     3     0      0   12   13     45
18   22    26  45.8     1     0      0   10   13     52
19   16    12  57.1     2     0      0    8   10     43
20   10    18  35.7     2     0      0    7   10     39
21   19    22  46.3     0     0      0    4   18     41
22   20     9  69.0     3     0      0   12    9     40
23   15     8  65.2     1     0      0    8   12     47
24   15    16  48.4     0     0      0    8   12     39

In [30]:
df_vs_away_cmb= df_vs_away[combined]
df_vs_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    15    25  37.5     3     0      0    8   17     57
1     4    11  26.7     3     0      0   14   13     39
2    16    14  53.3     4     0      0   18   13     44
3    21    12  63.6     4     0      0   15    6     47
4    18     9  66.7     3     0      0   12    9     30
5     7    18  28.0     4     0      0   15   11     29
6    13    15  46.4     6     0      0   12   10     39
7    14    18  43.8     3     0      0   12    9     45
8    24    15  61.5     5     0      0   16    9     45
9    15    13  53.6     4     1      1    9    7     33
10   22    15  59.5     1     0      0    6   13     50
11   11    14  44.0     3     0      0   10   11     31
12   17    16  51.5     3     0      0   16    5     24
13    7     5  58.3     2     0      0    7   15     43
14   14    16  46.7     0     0      0   10   13     47
15    8    10  44.4     1     0      0    6   12     36
16   17    20  45.9     3     0      0   10   14     47
17   13    12  52.0     4     1      1   13   12     50
18   26    22  54.2     4     0      0   13   10     44
19   12    16  42.9     1     0      0   10    8     42
20   18    10  64.3     1     0      0   10    7     40
21   22    19  53.7     4     0      0   18    4     40
22    9    20  31.0     2     0      0    9   12     43
23    8    15  34.8     3     0      0   13    8     44
24   16    15  51.6     0     0      0   13    8     45

## By Team

In [31]:
def compute_rolling_averages(df, features, window=5):
    """
    Compute rolling averages for a list of features in a team-level dataset.

    Parameters:
    df (pd.DataFrame): Dataframe containing team-level data sorted by date.
    features (list): List of features to compute rolling averages for.
    window (int): Rolling window size (default=5).

    Returns:
    pd.DataFrame: Dataframe with new rolling average features.
    """
    df = df.copy()
    
    for feature in features:
        df[f"{feature}_rolling_avg"] = df[feature].rolling(window, min_periods=1).mean()
    
    return df[[i for i in df.columns if i[-12:]=='_rolling_avg']]

In [32]:
df_home_off= compute_rolling_averages(df_home_off, offense)
df_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.000000,0.0,0.0,23.000000,0.0,7.0,1.00,14.300000,5.000000,71.400000,...,-1.50,-1.50,0.300000,0.20,7.000000e-01,7.000000e-01,0.700000,0.080000,0.0,1.000000
1,1.000000,0.0,0.0,42.000000,0.0,11.0,3.50,27.150000,6.000000,59.050000,...,-1.05,-1.05,1.000000,0.80,5.000000e-02,5.000000e-02,0.000000,0.100000,0.0,1.000000
2,1.333333,0.0,0.0,39.666667,0.0,14.0,5.00,31.433333,7.333333,56.033333,...,-0.50,-0.50,1.266667,1.00,1.000000e-01,1.000000e-01,0.066667,0.133333,0.0,1.333333
3,1.500000,0.0,0.0,42.500000,0.0,16.0,6.75,37.200000,7.500000,51.125000,...,-0.30,-0.30,1.325000,1.05,2.000000e-01,2.000000e-01,0.175000,0.127500,0.0,1.500000
4,1.400000,0.0,0.0,46.200000,0.0,15.8,6.80,39.100000,7.000000,47.560000,...,-0.38,-0.38,1.240000,1.00,6.000000e-02,6.000000e-02,0.160000,0.122000,0.2,1.400000
5,1.200000,0.2,0.0,49.200000,0.2,16.8,8.20,49.580000,6.400000,36.620000,...,0.06,-0.10,1.340000,1.10,-2.000000e-01,-2.400000e-01,-0.140000,0.122000,0.2,1.400000
6,1.000000,0.2,0.2,50.400000,0.4,17.8,8.20,47.580000,6.800000,36.280000,...,0.46,0.14,1.220000,1.02,-5.000000e-01,-3.800000e-01,-0.220000,0.118000,0.2,1.200000
7,0.600000,0.2,0.2,55.400000,0.4,18.0,8.60,49.100000,6.400000,33.900000,...,0.52,0.20,1.220000,1.00,-9.400000e-01,-8.200000e-01,-0.620000,0.098000,0.6,0.800000
8,0.400000,0.2,0.2,55.200000,0.4,16.2,7.40,47.440000,5.600000,32.780000,...,0.50,0.18,1.260000,1.02,-1.200000e+00,-1.080000e+00,-0.860000,0.108000,0.8,0.600000
9,0.400000,0.2,0.2,50.400000,0.4,15.2,7.20,50.100000,5.200000,32.120000,...,0.54,0.22,1.160000,1.00,-1.000000e+00,-8.800000e-01,-0.760000,0.100000,0.6,0.600000
10,1.000000,0.0,0.2,54.000000,0.2,16.0,6.00,39.260000,7.200000,43.780000,...,0.62,0.46,1.260000,1.14,-6.000000e-01,-4.400000e-01,-0.460000,0.104000,0.6,1.000000
11,1.000000,0.0,0.0,51.200000,0.0,14.6,5.80,40.960000,7.000000,47.080000,...,0.50,0.50,1.240000,1.12,-5.000000e-01,-5.000000e-01,-0.440000,0.102000,0.6,1.000000
12,1.000000,0.0,0.0,49.400000,0.0,15.6,5.00,36.060000,8.600000,51.760000,...,-0.02,-0.02,0.880000,0.90,-1.000000e-01,-1.000000e-01,-0.080000,0.090000,0.2,1.200000
13,1.400000,0.0,0.0,47.800000,0.0,19.2,6.20,34.560000,9.600000,51.400000,...,-0.04,-0.04,0.860000,0.80,2.400000e-01,2.400000e-01,0.340000,0.082000,0.2,1.600000
14,1.600000,0.0,0.0,51.800000,0.0,22.4,7.80,33.320000,11.400000,54.640000,...,0.10,0.10,1.020000,0.94,2.400000e-01,2.400000e-01,0.380000,0.088000,0.2,1.800000
15,1.800000,0.0,0.0,52.400000,0.0,24.2,9.60,39.620000,11.200000,48.440000,...,0.60,0.60,1.320000,1.10,-1.110223e-17,3.330669e-17,0.280000,0.096000,0.4,2.000000
16,2.600000,0.0,0.0,53.400000,0.0,24.8,10.80,45.680000,10.400000,41.140000,...,0.76,0.76,1.560000,1.34,6.600000e-01,6.600000e-01,0.640000,0.110000,0.4,2.800000
17,3.200000,0.0,0.0,55.600000,0.0,21.4,10.80,54.400000,7.600000,33.280000,...,1.56,1.56,1.900000,1.80,7.200000e-01,7.200000e-01,0.700000,0.128000,0.6,3.200000
18,3.000000,0.0,0.0,56.800000,0.0,19.2,9.60,52.660000,8.400000,40.480000,...,1.76,1.76,1.860000,1.80,5.600000e-01,5.600000e-01,0.340000,0.136000,0.4,3.000000
19,3.000000,0.0,0.0,54.200000,0.0,18.2,8.20,48.560000,8.000000,40.760000,...,2.04,2.04,2.080000,1.72,3.600000e-01,3.600000e-01,-0.080000,0.154000,0.4,3.000000
20,2.800000,0.0,0.0,54.400000,0.0,18.6,9.20,51.620000,7.000000,36.400000,...,1.42,1.42,1.900000,1.62,5.000000e-01,5.000000e-01,-0.100000,0.150000,0.2,2.800000
21,2.200000,0.0,0.0,54.000000,0.0,19.0,8.60,46.740000,7.800000,40.280000,...,0.86,0.86,1.540000,1.32,2.000000e-01,2.000000e-01,-0.140000,0.130000,0.4,2.200000
22,2.000000,0.2,0.0,51.000000,0.2,20.4,8.80,42.160000,9.200000,47.100000,...,0.84,0.68,1.560000,1.12,1.600000e-01,1.200000e-01,-0.160000,0.130000,0.2,2.200000
23,1.800000,0.2,0.0,51.200000,0.2,19.0,8.20,40.780000,8.000000,44.860000,...,0.46,0.30,1.400000,1.20,1.800000e-01,1.400000e-01,-0.200000,0.112000,0.2,2.000000
24,1.400000,0.2,0.0,50.200000,0.2,15.8,7.00,38.120000,6.600000,47.340000,...,-0.14,-0.30,1.040000,1.04,1.800000e-01,1.400000e-01,-0.040000,0.108000,0.2,1.600000

In [33]:
df_vs_home_off= compute_rolling_averages(df_vs_home_off, offense)
df_vs_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,0.000000,0.0,0.0,77.000000,0.0,14.00,6.00,42.900,7.000000,50.000,...,1.50,1.50,1.500000,1.600000,-1.80,-1.80,-1.50,0.100,1.00,0.000000
1,0.500000,0.0,0.0,58.000000,0.0,14.00,4.00,28.600,9.500000,67.850,...,1.05,1.05,1.850000,1.700000,-1.50,-1.50,-1.35,0.120,1.00,0.500000
2,0.333333,0.0,0.0,60.333333,0.0,18.00,6.00,31.900,10.666667,61.900,...,0.50,0.50,1.433333,1.433333,-1.40,-1.40,-1.10,0.100,1.00,0.666667
3,0.500000,0.0,0.0,57.500000,0.0,19.25,8.25,40.225,10.000000,55.125,...,0.30,0.30,1.300000,1.325000,-1.10,-1.10,-0.80,0.100,0.75,0.750000
4,1.000000,0.0,0.0,53.800000,0.0,18.80,7.40,36.880,9.400000,52.340,...,0.38,0.38,1.440000,1.300000,-0.72,-0.72,-0.44,0.100,0.60,1.200000
5,1.200000,0.0,0.0,50.800000,0.0,20.80,8.80,39.140,9.400000,48.180,...,-0.06,0.10,1.300000,1.260000,-0.34,-0.34,-0.10,0.092,0.40,1.400000
6,1.000000,0.0,0.0,49.600000,0.0,22.80,11.00,47.120,8.800000,38.540,...,-0.46,-0.14,0.920000,0.940000,-0.24,-0.24,0.08,0.082,0.40,1.200000
7,1.200000,0.0,0.0,44.600000,0.0,21.40,9.60,42.580,9.000000,43.280,...,-0.52,-0.20,0.940000,0.860000,-0.02,-0.02,0.26,0.092,0.20,1.200000
8,1.400000,0.0,0.0,44.800000,0.0,20.20,8.00,37.780,8.800000,44.560,...,-0.50,-0.18,1.060000,0.840000,0.10,0.10,0.34,0.090,0.20,1.400000
9,0.800000,0.0,0.0,49.600000,0.0,20.20,7.80,36.600,9.400000,48.080,...,-0.54,-0.22,0.880000,0.940000,-0.28,-0.28,-0.08,0.092,0.20,0.800000
10,0.800000,0.0,0.0,46.000000,0.0,18.40,6.40,33.760,9.200000,50.240,...,-0.62,-0.46,0.820000,0.800000,-0.22,-0.22,-0.02,0.092,0.20,0.800000
11,1.200000,0.0,0.0,48.800000,0.0,18.00,5.40,30.200,9.600000,52.740,...,-0.50,-0.50,0.880000,0.840000,0.14,0.14,0.32,0.086,0.20,1.200000
12,1.200000,0.0,0.0,50.600000,0.0,17.00,6.60,39.900,7.400000,42.280,...,0.02,0.02,1.040000,1.060000,0.02,0.02,0.16,0.086,0.20,1.200000
13,1.400000,0.0,0.0,52.200000,0.0,17.00,6.60,39.900,7.800000,44.620,...,0.04,0.04,0.980000,1.100000,0.16,0.16,0.42,0.092,0.20,1.400000
14,2.200000,0.0,0.0,48.200000,0.0,16.80,7.80,47.640,7.200000,41.620,...,-0.10,-0.10,0.940000,0.920000,0.94,0.94,1.06,0.092,0.20,2.200000
15,2.000000,0.0,0.0,47.600000,0.0,16.20,8.20,52.980,6.800000,40.280,...,-0.60,-0.60,0.880000,0.840000,0.82,0.82,0.92,0.090,0.20,2.000000
16,1.600000,0.0,0.0,46.600000,0.0,14.40,7.40,51.860,6.200000,42.580,...,-0.76,-0.76,0.860000,0.860000,0.46,0.46,0.54,0.092,0.00,1.600000
17,1.400000,0.0,0.0,44.400000,0.0,15.00,7.60,50.760,6.400000,43.000,...,-1.56,-1.56,0.600000,0.620000,0.54,0.54,0.60,0.088,0.20,1.400000
18,0.800000,0.0,0.0,43.200000,0.0,14.60,7.00,47.860,6.600000,45.760,...,-1.76,-1.76,0.500000,0.540000,0.16,0.16,0.10,0.082,0.20,0.800000
19,0.200000,0.0,0.0,45.800000,0.0,15.00,6.20,42.160,6.400000,43.660,...,-2.04,-2.04,0.460000,0.580000,-0.38,-0.38,-0.26,0.074,0.20,0.200000
20,0.200000,0.0,0.0,45.600000,0.0,16.80,6.40,37.400,7.200000,44.620,...,-1.42,-1.42,0.720000,0.660000,-0.66,-0.66,-0.52,0.088,0.20,0.200000
21,1.000000,0.0,0.0,46.000000,0.0,19.40,8.80,43.540,6.800000,36.940,...,-0.86,-0.86,0.940000,0.800000,-0.12,-0.12,0.06,0.096,0.20,1.000000
22,1.200000,0.0,0.0,49.000000,0.0,19.80,8.60,41.260,7.600000,40.660,...,-0.84,-0.68,1.000000,0.820000,-0.02,-0.02,0.20,0.090,0.00,1.200000
23,1.600000,0.0,0.0,48.800000,0.0,19.60,9.60,48.780,6.000000,30.180,...,-0.46,-0.30,1.160000,0.880000,0.22,0.22,0.44,0.092,0.00,1.600000
24,2.200000,0.0,0.0,49.800000,0.0,21.60,10.20,48.940,8.200000,35.660,...,0.14,0.30,1.400000,0.900000,0.62,0.62,0.80,0.112,0.00,2.200000

In [34]:
df_away_def= compute_rolling_averages(df_away_def, defence)
df_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,18.000000,0.000000,0.000000,0.0,0.00,9.300000,0.0,NaN,0.0,0.0,...,3.0,9.000000,7.000000,31.0,26.000000,0.0,1.20,0.300000,0.200000,1.000000
1,14.000000,1.000000,10.000000,0.0,0.00,6.400000,0.0,NaN,0.0,0.0,...,3.0,7.000000,9.000000,33.0,24.500000,0.0,0.60,0.160000,0.100000,0.500000
2,11.333333,0.666667,6.666667,0.0,0.00,6.166667,0.0,NaN,0.0,0.0,...,3.0,6.666667,9.333333,31.0,20.666667,0.0,0.60,0.203333,-0.066667,0.666667
3,12.500000,0.750000,6.575000,0.0,0.25,7.625000,0.0,NaN,0.0,0.0,...,3.0,7.000000,9.750000,31.5,23.500000,0.5,0.60,0.180000,0.100000,0.500000
4,16.800000,0.600000,5.260000,0.0,0.20,6.300000,0.0,NaN,0.2,0.0,...,3.8,6.600000,9.400000,30.4,29.000000,0.4,0.70,0.216000,-0.100000,0.800000
5,16.000000,0.600000,5.260000,0.2,0.20,5.300000,0.0,0.0,0.2,0.0,...,4.6,6.000000,9.800000,27.6,28.000000,0.4,0.62,0.166000,-0.180000,0.800000
6,18.600000,0.200000,1.260000,0.2,0.20,5.000000,0.0,0.0,0.2,0.0,...,5.0,7.600000,8.800000,24.2,30.000000,0.6,1.00,0.212000,0.000000,1.000000
7,19.800000,0.200000,1.260000,0.2,0.20,5.260000,0.0,0.0,0.2,0.0,...,5.4,8.600000,9.600000,23.4,31.000000,0.6,1.06,0.178000,0.260000,0.800000
8,20.600000,0.200000,1.000000,0.2,0.00,3.940000,0.0,0.0,0.2,0.0,...,5.4,8.400000,9.400000,22.6,30.200000,0.4,1.14,0.350000,0.140000,1.000000
9,15.800000,0.200000,1.000000,0.2,0.00,6.540000,0.0,0.0,0.0,0.0,...,4.2,8.600000,9.000000,22.2,25.000000,0.4,0.92,0.284000,0.320000,0.600000
10,17.600000,0.400000,1.860000,0.0,0.00,6.960000,0.0,NaN,0.0,0.2,...,3.6,8.200000,8.600000,26.0,26.200000,0.6,1.22,0.352000,0.220000,1.000000
11,15.400000,0.400000,1.860000,0.0,0.00,7.360000,0.0,NaN,0.0,0.2,...,3.8,6.400000,9.400000,27.6,24.800000,0.4,1.12,0.350000,-0.280000,1.400000
12,15.600000,0.600000,3.400000,0.0,0.00,6.560000,0.0,NaN,0.0,0.2,...,3.4,6.400000,8.200000,28.6,25.600000,0.4,1.02,0.364000,-0.380000,1.400000
13,14.000000,0.400000,2.400000,0.0,0.20,8.780000,0.0,NaN,0.0,0.2,...,3.4,6.400000,9.000000,30.4,23.800000,0.2,1.46,0.276000,-0.340000,1.800000
14,16.000000,0.600000,3.400000,0.0,0.40,8.980000,0.0,NaN,0.0,0.2,...,4.2,6.400000,9.400000,30.4,25.200000,0.2,1.78,0.322000,-0.420000,2.200000
15,13.600000,0.800000,6.180000,0.0,0.60,9.860000,0.0,NaN,0.0,0.0,...,3.8,6.600000,9.600000,28.6,24.800000,0.0,1.38,0.270000,-0.420000,1.800000
16,17.200000,1.000000,6.840000,0.0,0.60,10.320000,0.0,NaN,0.0,0.0,...,3.0,7.800000,11.200000,31.0,29.600000,0.4,1.30,0.288000,0.100000,1.200000
17,18.000000,1.000000,6.480000,0.0,0.60,10.780000,0.0,NaN,0.0,0.0,...,3.4,8.400000,11.600000,31.6,31.400000,0.4,1.40,0.296000,0.200000,1.200000
18,21.000000,1.400000,7.960000,0.0,0.40,7.880000,0.0,NaN,0.0,0.0,...,3.2,8.400000,10.800000,29.6,35.600000,0.4,0.80,0.208000,0.200000,0.600000
19,21.600000,1.200000,6.960000,0.0,0.20,5.440000,0.0,NaN,0.0,0.0,...,3.4,8.000000,11.200000,30.4,35.800000,0.8,0.68,0.196000,0.480000,0.200000
20,24.800000,1.000000,4.060000,0.0,0.00,5.480000,0.0,NaN,0.0,0.2,...,4.4,9.200000,11.400000,30.8,42.600000,0.8,1.00,0.234000,0.800000,0.200000
21,23.200000,1.000000,4.300000,0.0,0.00,5.120000,0.0,NaN,0.0,0.4,...,5.0,8.000000,9.400000,28.6,37.000000,0.4,1.14,0.284000,0.540000,0.600000
22,22.000000,1.000000,4.940000,0.0,0.00,4.520000,0.0,NaN,0.0,0.4,...,4.6,7.200000,8.400000,25.6,35.800000,0.8,1.72,0.314000,0.120000,1.600000
23,20.800000,0.600000,3.460000,0.0,0.20,8.780000,0.0,NaN,0.0,0.4,...,4.6,7.800000,7.800000,25.6,35.600000,0.8,1.94,0.350000,0.340000,1.600000
24,21.200000,0.600000,3.460000,0.0,0.40,11.320000,0.0,NaN,0.0,0.6,...,4.6,7.800000,7.400000,23.6,35.200000,0.4,2.42,0.386000,0.420000,2.000000

In [35]:
df_vs_away_def= compute_rolling_averages(df_vs_away_def, defence)
df_vs_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,11.00,0.000000,0.000000,0.0,3.000000,14.600000,0.0,NaN,0.0,0.000000,...,3.00,10.0,14.000000,32.000000,29.00,1.00,1.700000,0.2300,7.000000e-01,1.0
1,12.50,0.500000,3.550000,0.0,1.500000,10.300000,0.0,NaN,0.0,0.500000,...,4.50,9.5,8.000000,26.000000,24.00,1.50,1.650000,0.2150,6.500000e-01,1.0
2,14.00,0.666667,4.333333,0.0,1.333333,10.533333,0.0,NaN,0.0,0.666667,...,5.00,9.0,8.666667,28.333333,25.00,1.00,1.666667,0.2600,6.666667e-01,1.0
3,11.75,0.500000,3.250000,0.0,1.250000,13.225000,0.0,NaN,0.0,0.500000,...,3.75,8.0,9.250000,27.000000,22.75,0.75,1.425000,0.2575,4.250000e-01,1.0
4,10.00,0.600000,9.260000,0.2,2.200000,15.080000,0.0,0.0,0.0,0.400000,...,3.20,9.0,8.800000,25.400000,19.80,0.60,1.480000,0.2600,2.800000e-01,1.2
5,11.80,0.800000,10.260000,0.2,1.600000,13.620000,0.0,0.0,0.0,0.400000,...,3.60,7.6,7.800000,22.200000,22.80,0.60,1.140000,0.2160,1.400000e-01,1.0
6,10.80,0.800000,11.060000,0.2,2.200000,16.660000,0.0,0.0,0.0,0.200000,...,3.60,7.4,9.000000,22.600000,22.60,0.40,1.140000,0.2120,1.400000e-01,1.0
7,10.80,0.800000,11.060000,0.2,2.000000,16.460000,0.0,0.0,0.0,0.000000,...,4.20,8.4,8.000000,21.600000,22.20,0.60,1.160000,0.2020,1.600000e-01,1.0
8,13.60,0.800000,11.060000,0.2,2.400000,16.440000,0.0,0.0,0.0,0.000000,...,5.40,9.2,7.000000,21.000000,24.20,0.80,1.360000,0.2200,-4.000000e-02,1.4
9,16.00,0.800000,5.740000,0.0,1.200000,13.340000,0.0,NaN,0.0,0.000000,...,5.80,7.8,7.800000,22.000000,29.00,1.00,1.600000,0.2620,-5.551115e-18,1.6
10,15.60,1.200000,8.080000,0.0,1.400000,13.820000,0.0,NaN,0.0,0.000000,...,5.40,8.6,8.800000,24.200000,24.80,1.00,1.780000,0.3200,-2.000000e-02,1.8
11,16.00,1.200000,7.680000,0.0,1.400000,13.540000,0.0,NaN,0.0,0.000000,...,4.40,8.0,8.000000,23.600000,23.80,0.80,1.460000,0.3550,-1.400000e-01,1.6
12,16.20,1.400000,8.720000,0.2,1.400000,12.340000,0.0,0.0,0.0,0.000000,...,3.00,5.8,7.800000,22.000000,23.00,0.80,1.400000,0.3075,-2.000000e-01,1.6
13,14.60,1.400000,8.720000,0.2,1.200000,10.960000,0.0,0.0,0.0,0.000000,...,2.20,5.4,7.600000,22.200000,20.80,1.00,1.160000,0.2675,1.600000e-01,1.0
14,12.80,1.200000,7.380000,0.2,1.400000,12.360000,0.0,0.0,0.0,0.200000,...,2.40,5.0,7.200000,21.800000,15.40,1.20,0.880000,0.2750,-1.200000e-01,1.0
15,12.80,0.800000,5.160000,0.2,1.200000,11.020000,0.0,0.0,0.0,0.400000,...,2.80,4.4,5.600000,19.800000,15.20,1.40,1.080000,0.2850,-1.200000e-01,1.2
16,13.00,0.600000,3.340000,0.2,0.600000,8.060000,0.0,0.0,0.0,0.400000,...,2.80,3.8,7.400000,22.000000,16.00,1.60,1.360000,0.2740,-2.400000e-01,1.6
17,10.20,0.200000,1.120000,0.0,0.600000,8.520000,0.0,NaN,0.0,0.400000,...,2.80,4.2,8.000000,21.600000,12.40,1.60,1.340000,0.3420,-2.600000e-01,1.6
18,9.40,0.400000,3.980000,0.0,0.800000,10.620000,0.0,NaN,0.0,0.400000,...,2.40,4.0,8.200000,21.800000,12.80,1.40,1.560000,0.3540,-4.400000e-01,2.0
19,10.00,0.400000,3.980000,0.0,1.200000,11.340000,0.0,NaN,0.0,0.200000,...,2.00,4.4,8.400000,22.000000,16.60,1.20,1.800000,0.4320,-2.000000e-01,2.0
20,7.20,0.200000,2.860000,0.0,1.400000,16.340000,0.0,NaN,0.0,0.000000,...,1.40,4.2,7.600000,21.000000,18.60,0.80,1.600000,0.4260,-2.000000e-01,1.8
21,7.40,0.400000,4.400000,0.0,1.400000,17.240000,0.0,NaN,0.0,0.000000,...,1.80,5.0,6.200000,18.400000,21.60,0.80,1.540000,0.4340,-4.600000e-01,2.0
22,10.40,0.600000,5.460000,0.0,1.400000,17.280000,0.0,NaN,0.0,0.000000,...,2.40,6.0,6.600000,21.000000,27.80,0.60,1.460000,0.3940,-3.400000e-01,1.8
23,10.40,0.400000,2.600000,0.2,1.200000,16.860000,0.0,0.0,0.0,0.200000,...,2.60,6.8,6.400000,21.800000,27.00,1.20,2.000000,0.4320,-6.000000e-01,2.8
24,11.60,0.400000,2.600000,0.2,1.000000,16.180000,0.0,0.0,0.0,0.200000,...,2.80,6.2,5.800000,20.200000,27.20,1.00,1.680000,0.3580,-5.200000e-01,2.4

In [36]:
df_away_off= compute_rolling_averages(df_away_off, offense)
df_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.0,0.0,0.0,53.00,0.0,23.000000,9.0,39.100,10.000000,43.500000,...,0.100000,0.100000,0.500000,0.80,-0.300,-0.300,-0.50,0.100,0.000000,1.0
1,1.0,0.0,0.0,44.50,0.0,21.500000,8.0,37.050,10.500000,49.250000,...,1.100000,1.100000,1.200000,0.90,-0.750,-0.750,-1.20,0.105,0.000000,1.0
2,1.0,0.0,0.0,47.00,0.0,21.333333,8.0,37.400,9.666667,45.533333,...,0.833333,0.833333,1.133333,1.00,-0.500,-0.500,-0.80,0.090,0.333333,1.0
3,1.0,0.0,0.0,43.25,0.0,19.500000,7.5,38.775,8.500000,43.075000,...,0.500000,0.500000,0.950000,0.80,-0.225,-0.225,-0.45,0.090,0.250000,1.0
4,1.0,0.2,0.0,40.60,0.2,18.400000,7.6,42.440,7.400000,38.740000,...,0.480000,0.320000,0.880000,0.72,-0.060,-0.100,-0.28,0.114,0.200000,1.2
5,0.8,0.2,0.0,38.20,0.2,15.000000,6.6,47.960,5.600000,33.380000,...,0.360000,0.360000,0.900000,0.76,-0.160,-0.200,-0.30,0.108,0.200000,1.0
6,0.8,0.2,0.0,38.00,0.2,14.800000,7.0,50.440,4.800000,29.740000,...,-0.340000,-0.340000,0.620000,0.64,0.100,0.060,0.18,0.096,0.600000,1.0
7,0.8,0.2,0.0,37.80,0.2,16.000000,8.6,54.680,4.800000,28.040000,...,-0.260000,-0.260000,0.720000,0.64,-0.040,-0.080,-0.12,0.102,0.400000,1.0
8,1.2,0.2,0.0,38.40,0.2,18.000000,10.4,58.600,4.800000,25.060000,...,0.020000,0.020000,0.800000,0.68,0.100,0.060,-0.20,0.102,0.600000,1.4
9,1.6,0.0,0.0,43.20,0.0,17.600000,10.0,57.180,5.000000,27.440000,...,0.340000,0.500000,1.020000,0.90,0.140,0.140,-0.22,0.082,0.800000,1.6
10,1.8,0.0,0.0,43.80,0.0,19.400000,10.4,51.840,6.000000,32.100000,...,0.220000,0.220000,1.000000,0.84,0.380,0.380,0.00,0.080,0.800000,1.8
11,1.6,0.0,0.0,43.60,0.0,18.400000,9.4,48.080,5.800000,33.320000,...,0.340000,0.340000,0.940000,0.84,0.300,0.300,-0.14,0.080,0.600000,1.6
12,1.4,0.2,0.0,42.40,0.2,17.000000,7.6,43.220,6.000000,36.400000,...,0.420000,0.260000,0.800000,0.82,0.320,0.260,0.00,0.078,0.800000,1.6
13,0.8,0.2,0.0,42.20,0.2,14.800000,5.6,38.420,6.000000,39.940000,...,-0.020000,-0.180000,0.760000,0.90,-0.140,-0.200,-0.16,0.078,0.600000,1.0
14,0.8,0.2,0.0,37.20,0.2,15.600000,6.0,38.420,6.800000,43.280000,...,-0.580000,-0.740000,0.560000,0.82,0.140,0.080,0.24,0.072,0.400000,1.0
15,1.0,0.2,0.0,38.40,0.2,15.600000,6.8,43.760,6.600000,41.940000,...,-0.100000,-0.260000,0.760000,1.02,0.120,0.060,0.24,0.080,0.400000,1.2
16,1.4,0.2,0.0,38.80,0.2,16.600000,6.8,42.260,7.400000,43.880000,...,0.100000,-0.060000,0.860000,1.06,0.400,0.340,0.34,0.088,0.200000,1.6
17,1.6,0.0,0.0,35.80,0.0,15.800000,7.2,46.520,6.400000,39.880000,...,-0.080000,-0.080000,0.800000,0.96,0.500,0.500,0.60,0.094,0.000000,1.6
18,2.0,0.0,0.0,36.20,0.0,14.600000,7.0,50.240,6.000000,40.760000,...,0.300000,0.300000,0.900000,0.96,0.800,0.800,0.90,0.106,0.000000,2.0
19,2.0,0.0,0.0,38.40,0.0,14.200000,6.2,45.960,5.800000,40.760000,...,0.580000,0.580000,1.140000,1.00,0.540,0.540,0.66,0.128,0.200000,2.0
20,1.8,0.0,0.0,34.40,0.0,14.800000,5.4,39.280,6.200000,41.880000,...,-0.020000,-0.020000,0.880000,0.70,0.620,0.620,0.72,0.118,0.400000,1.8
21,2.0,0.0,0.0,36.20,0.0,14.400000,6.0,43.300,5.200000,37.240000,...,0.120000,0.120000,1.000000,0.80,0.640,0.640,1.00,0.130,0.600000,2.0
22,1.8,0.0,0.0,40.20,0.0,14.400000,5.8,42.040,5.600000,39.740000,...,-0.060000,-0.060000,1.060000,0.86,0.460,0.460,0.74,0.118,1.000000,1.8
23,2.4,0.2,0.0,40.60,0.2,17.600000,8.0,43.660,6.600000,38.120000,...,0.300000,0.140000,1.360000,1.00,0.900,0.860,0.84,0.128,1.000000,2.8
24,2.0,0.2,0.0,41.60,0.2,17.200000,8.6,49.600,6.200000,36.460000,...,-0.160000,-0.320000,1.040000,0.80,0.840,0.800,0.76,0.100,0.800000,2.4

In [37]:
df_vs_away_off= compute_rolling_averages(df_vs_away_off, offense)
df_vs_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.000000,0.0,0.0,47.00,0.0,20.000000,5.000000,25.000000,10.000000,50.000000,...,-0.100000,-0.100000,0.500000,0.500000,-2.000000e-01,-0.200,-0.500000,0.090000,1.000000,1.000000
1,0.500000,0.0,0.0,55.50,0.0,21.000000,6.000000,28.400000,11.000000,52.250000,...,-1.100000,-1.100000,0.300000,0.450000,-1.500000e-01,-0.150,-0.300000,0.060000,0.500000,0.500000
2,0.666667,0.0,0.0,53.00,0.0,20.333333,6.666667,32.966667,9.333333,45.366667,...,-0.833333,-0.833333,0.366667,0.466667,0.000000e+00,0.000,-0.033333,0.063333,0.333333,0.666667
3,0.500000,0.0,0.0,56.75,0.0,20.250000,6.500000,32.225000,10.250000,50.275000,...,-0.500000,-0.500000,0.500000,0.700000,-2.250000e-01,-0.225,-0.250000,0.065000,0.250000,0.500000
4,0.800000,0.0,0.0,59.40,0.0,20.200000,7.200000,35.780000,9.600000,47.220000,...,-0.480000,-0.320000,0.540000,0.740000,2.000000e-02,0.020,-0.140000,0.066000,0.400000,0.800000
5,0.600000,0.2,0.0,61.80,0.2,19.400000,8.000000,42.040000,8.600000,43.480000,...,-0.360000,-0.360000,0.500000,0.720000,0.000000e+00,-0.040,-0.100000,0.056000,0.200000,0.800000
6,0.800000,0.2,0.0,62.00,0.2,18.200000,8.800000,49.440000,7.000000,37.580000,...,0.340000,0.340000,0.940000,0.980000,-2.400000e-01,-0.280,-0.340000,0.072000,0.200000,1.000000
7,0.600000,0.2,0.0,62.20,0.2,16.200000,8.400000,54.360000,6.400000,37.920000,...,0.260000,0.260000,1.000000,0.960000,-5.000000e-01,-0.540,-0.600000,0.068000,0.200000,0.800000
8,0.800000,0.2,0.0,61.60,0.2,16.200000,8.400000,54.360000,6.000000,35.920000,...,-0.020000,-0.020000,0.960000,0.880000,-2.800000e-01,-0.320,-0.360000,0.068000,0.200000,1.000000
9,0.400000,0.2,0.0,56.80,0.2,16.200000,8.400000,54.360000,6.000000,35.920000,...,-0.340000,-0.500000,0.820000,0.760000,-5.000000e-01,-0.540,-0.420000,0.060000,0.000000,0.600000
10,1.000000,0.0,0.0,56.20,0.0,16.200000,7.000000,45.600000,7.400000,44.660000,...,-0.220000,-0.220000,1.020000,0.960000,-1.600000e-01,-0.160,-0.220000,0.072000,0.000000,1.000000
11,1.400000,0.0,0.0,56.40,0.0,16.800000,6.400000,40.260000,8.600000,50.180000,...,-0.340000,-0.340000,0.800000,0.780000,4.600000e-01,0.460,0.400000,0.062000,0.000000,1.400000
12,1.400000,0.0,0.0,57.60,0.0,18.800000,6.800000,35.340000,10.000000,54.040000,...,-0.420000,-0.260000,0.760000,0.820000,5.400000e-01,0.540,0.440000,0.068000,0.000000,1.400000
13,1.800000,0.0,0.0,57.80,0.0,20.200000,8.200000,38.960000,9.600000,49.700000,...,0.020000,0.180000,1.080000,0.900000,6.200000e-01,0.620,0.520000,0.082000,0.200000,1.800000
14,2.200000,0.0,0.0,62.80,0.0,19.200000,7.600000,38.300000,9.400000,50.700000,...,0.580000,0.740000,1.240000,1.000000,7.200000e-01,0.720,0.560000,0.096000,0.400000,2.200000
15,1.800000,0.0,0.0,61.60,0.0,19.200000,8.200000,42.060000,9.000000,48.200000,...,0.100000,0.260000,1.060000,0.940000,5.600000e-01,0.560,0.540000,0.086000,0.400000,1.800000
16,1.200000,0.0,0.0,61.20,0.0,20.400000,8.800000,42.440000,9.000000,45.680000,...,-0.100000,0.060000,0.920000,0.980000,6.000000e-02,0.060,0.080000,0.094000,0.400000,1.200000
17,1.200000,0.0,0.0,64.20,0.0,21.000000,9.200000,43.120000,9.000000,44.260000,...,0.080000,0.080000,0.960000,1.000000,4.440892e-17,0.000,0.040000,0.092000,0.600000,1.200000
18,0.600000,0.0,0.0,63.80,0.0,19.800000,9.000000,44.920000,8.800000,45.220000,...,-0.300000,-0.300000,0.660000,0.900000,-3.000000e-01,-0.300,-0.260000,0.078000,0.600000,0.600000
19,0.200000,0.0,0.0,61.60,0.0,19.600000,8.400000,41.300000,9.400000,50.080000,...,-0.580000,-0.580000,0.640000,0.940000,-6.800000e-01,-0.680,-0.440000,0.082000,0.400000,0.200000
20,0.200000,0.0,0.0,65.60,0.0,20.200000,8.200000,39.260000,10.000000,51.260000,...,0.020000,0.020000,0.880000,1.120000,-1.000000e+00,-1.000,-0.680000,0.090000,0.400000,0.200000
21,0.600000,0.0,0.0,63.80,0.0,19.000000,8.400000,43.100000,9.400000,50.620000,...,-0.120000,-0.120000,0.960000,1.080000,-6.400000e-01,-0.640,-0.360000,0.088000,0.400000,0.600000
22,1.600000,0.0,0.0,59.80,0.0,18.000000,8.600000,46.940000,8.000000,45.040000,...,0.060000,0.060000,0.960000,1.120000,2.000000e-01,0.200,0.440000,0.096000,0.400000,1.600000
23,1.600000,0.0,0.0,59.40,0.0,19.800000,9.000000,44.860000,9.400000,47.420000,...,-0.300000,-0.140000,0.940000,1.120000,2.000000e-01,0.200,0.460000,0.100000,0.400000,1.600000
24,2.000000,0.0,0.0,58.40,0.0,19.400000,9.200000,47.480000,8.800000,44.560000,...,0.160000,0.320000,1.120000,1.240000,4.800000e-01,0.480,0.680000,0.094000,0.400000,2.000000

In [38]:
df_home_def= compute_rolling_averages(df_home_def, defence)
df_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,24.00,1.0,4.200000,0.0,1.00,20.500000,0.0,NaN,0.0,0.0,...,11.000000,13.000000,4.000000,20.000000,39.0,0.000000,0.400,0.140000,0.400000,0.000000
1,19.00,1.0,5.650000,0.0,3.50,19.850000,0.0,NaN,0.0,0.0,...,7.500000,9.500000,4.000000,22.500000,27.5,0.500000,0.750,0.210000,0.250000,0.500000
2,20.00,1.0,5.266667,0.0,3.00,18.466667,0.0,NaN,0.0,0.0,...,7.333333,11.333333,7.333333,25.333333,29.0,0.666667,1.000,0.226667,0.666667,0.666667
3,18.25,1.0,5.875000,0.0,2.75,18.100000,0.0,NaN,0.0,0.0,...,5.750000,10.750000,6.750000,23.750000,28.0,0.750000,1.075,0.232500,0.575000,0.750000
4,17.20,0.8,4.700000,0.0,2.20,14.880000,0.0,NaN,0.0,0.0,...,5.000000,9.400000,7.400000,22.800000,25.4,1.200000,1.460,0.244000,0.460000,1.200000
5,15.60,0.8,5.120000,0.0,2.20,13.580000,0.0,NaN,0.0,0.0,...,4.000000,8.000000,8.600000,23.800000,22.2,1.400000,1.660,0.262000,0.460000,1.400000
6,13.20,0.8,13.700000,0.0,1.00,12.100000,0.0,NaN,0.0,0.0,...,3.400000,9.400000,9.400000,25.400000,20.6,1.200000,1.560,0.262000,0.560000,1.200000
7,10.40,0.6,12.800000,0.0,0.80,11.960000,0.0,NaN,0.0,0.0,...,2.400000,8.200000,9.200000,27.000000,15.6,1.200000,1.600,0.278000,0.400000,1.200000
8,11.00,0.8,13.760000,0.0,1.40,11.000000,0.0,NaN,0.0,0.0,...,3.000000,7.600000,9.400000,27.000000,13.2,1.400000,1.720,0.284000,0.320000,1.400000
9,12.60,1.2,15.660000,0.0,1.40,11.980000,0.0,NaN,0.0,0.0,...,3.400000,7.800000,8.600000,29.000000,15.4,0.800000,1.120,0.282500,0.320000,0.800000
10,13.00,1.6,17.740000,0.0,1.40,11.120000,0.0,NaN,0.0,0.0,...,2.800000,8.000000,9.400000,29.400000,15.4,0.800000,1.020,0.300000,0.220000,0.800000
11,14.20,1.4,7.740000,0.0,2.00,12.720000,0.0,NaN,0.0,0.2,...,3.600000,6.400000,9.200000,28.400000,18.0,0.800000,1.140,0.280000,-0.060000,1.200000
12,16.40,2.0,10.900000,0.0,2.20,12.800000,0.0,NaN,0.0,0.2,...,4.200000,6.200000,8.200000,24.600000,22.0,0.800000,0.980,0.272500,-0.220000,1.200000
13,15.80,2.2,13.020000,0.0,1.60,13.600000,0.0,NaN,0.0,0.2,...,4.600000,6.200000,8.000000,24.600000,22.8,0.600000,1.280,0.375000,-0.120000,1.400000
14,13.80,2.2,14.760000,0.0,2.60,16.360000,0.0,NaN,0.0,0.2,...,4.200000,6.400000,7.400000,21.800000,22.4,1.000000,1.740,0.368000,-0.460000,2.200000
15,11.40,2.0,18.080000,0.0,2.60,16.580000,0.0,NaN,0.0,0.2,...,4.200000,7.800000,5.800000,19.200000,20.8,0.800000,1.580,0.326000,-0.420000,2.000000
16,11.40,2.0,18.080000,0.0,2.00,16.020000,0.0,NaN,0.0,0.0,...,4.000000,8.400000,5.600000,17.800000,20.2,0.800000,1.380,0.310000,-0.220000,1.600000
17,10.20,1.8,18.000000,0.0,1.60,14.820000,0.0,NaN,0.0,0.0,...,3.200000,7.600000,5.600000,17.600000,19.8,0.600000,1.240,0.284000,-0.160000,1.400000
18,9.60,1.4,15.380000,0.0,1.20,13.480000,0.0,NaN,0.0,0.0,...,3.000000,7.400000,6.200000,19.200000,20.0,0.600000,0.560,0.182500,-0.240000,0.800000
19,11.60,1.4,13.640000,0.0,0.20,10.680000,0.0,NaN,0.0,0.0,...,3.200000,7.400000,7.400000,21.400000,22.2,0.200000,0.340,0.175000,0.140000,0.200000
20,12.00,1.0,6.980000,0.0,0.60,14.000000,0.0,NaN,0.0,0.0,...,3.000000,6.400000,8.600000,23.800000,22.4,0.200000,0.640,0.210000,0.440000,0.200000
21,14.20,1.0,6.980000,0.0,1.00,13.860000,0.0,NaN,0.0,0.0,...,2.800000,6.200000,8.000000,23.600000,25.4,0.800000,1.420,0.282500,0.420000,1.000000
22,13.80,0.6,3.900000,0.0,1.40,16.380000,0.0,NaN,0.0,0.0,...,3.200000,6.200000,8.600000,25.800000,24.6,0.800000,1.600,0.295000,0.400000,1.200000
23,16.00,0.6,2.860000,0.0,1.40,15.820000,0.0,NaN,0.0,0.0,...,3.600000,6.400000,7.800000,22.600000,26.6,0.600000,1.900,0.314000,0.300000,1.600000
24,13.80,0.6,4.960000,0.0,2.00,18.040000,0.0,NaN,0.0,0.2,...,3.400000,6.600000,7.400000,24.000000,23.8,0.800000,2.220,0.330000,0.020000,2.200000

In [39]:
df_vs_home_def= compute_rolling_averages(df_vs_home_def, defence)
df_vs_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,12.000000,2.000000,16.70,0.0,0.00,7.200000,0.0,NaN,0.0,0.0,...,2.000000,6.000000,3.000000,16.00,13.0,1.000000,0.600000,0.630000,-0.400000,1.000000
1,15.500000,2.000000,13.60,0.0,0.00,5.850000,0.0,NaN,0.0,0.0,...,3.500000,12.500000,4.500000,21.50,24.0,0.500000,1.600000,0.580000,0.600000,1.000000
2,13.666667,1.666667,12.40,0.0,0.00,7.166667,0.0,NaN,0.0,0.0,...,3.333333,12.666667,5.333333,24.00,20.0,0.333333,1.766667,0.623333,0.433333,1.333333
3,12.750000,1.500000,11.80,0.0,0.25,7.875000,0.0,NaN,0.0,0.0,...,3.500000,11.500000,6.500000,26.25,20.0,0.250000,1.750000,0.540000,0.250000,1.500000
4,12.400000,1.400000,11.26,0.0,0.20,8.500000,0.0,NaN,0.0,0.0,...,3.400000,9.800000,6.400000,26.00,20.2,0.400000,1.600000,0.474000,0.200000,1.400000
5,12.600000,1.000000,7.92,0.2,0.20,9.260000,0.0,0.0,0.0,0.0,...,3.600000,9.600000,7.200000,27.20,21.8,0.200000,1.700000,0.370000,0.300000,1.400000
6,12.400000,0.800000,6.94,0.4,0.40,10.920000,0.2,50.0,0.0,0.0,...,3.400000,7.000000,8.000000,27.60,20.8,0.200000,1.360000,0.272000,0.160000,1.200000
7,13.800000,0.800000,6.12,0.4,0.60,10.980000,0.2,50.0,0.0,0.0,...,4.400000,6.000000,8.400000,28.80,26.0,0.200000,1.120000,0.160000,0.320000,0.800000
8,13.600000,0.800000,6.34,0.4,0.80,11.980000,0.2,50.0,0.0,0.0,...,4.400000,6.600000,9.600000,27.80,27.0,0.200000,1.020000,0.218000,0.420000,0.600000
9,13.600000,1.000000,8.16,0.4,1.40,13.520000,0.2,50.0,0.0,0.0,...,4.400000,8.600000,9.600000,27.40,26.4,0.000000,1.080000,0.240000,0.480000,0.600000
10,15.600000,1.200000,9.02,0.2,1.40,12.600000,0.2,100.0,0.0,0.2,...,4.600000,8.400000,9.600000,30.20,27.6,0.200000,1.320000,0.296000,0.320000,1.000000
11,17.600000,1.000000,7.90,0.0,2.00,14.560000,0.0,NaN,0.0,0.2,...,5.000000,8.800000,9.600000,31.60,28.2,0.400000,1.220000,0.330000,0.220000,1.000000
12,17.800000,0.800000,6.72,0.0,2.80,17.500000,0.0,NaN,0.0,0.2,...,3.600000,8.400000,10.400000,33.20,25.4,0.400000,1.040000,0.375000,0.040000,1.200000
13,18.600000,0.800000,6.04,0.0,2.60,17.200000,0.0,NaN,0.0,0.2,...,3.600000,8.000000,9.200000,34.20,25.0,1.000000,1.300000,0.335000,-0.100000,1.600000
14,19.200000,0.600000,3.82,0.0,2.00,15.320000,0.0,NaN,0.0,0.2,...,3.400000,6.800000,8.800000,35.20,27.2,1.200000,1.300000,0.362500,-0.300000,1.800000
15,16.600000,0.400000,2.96,0.0,2.20,17.740000,0.0,NaN,0.0,0.2,...,4.000000,6.600000,10.000000,35.20,26.8,1.400000,1.700000,0.362500,-0.100000,2.000000
16,12.200000,0.600000,6.30,0.0,2.00,16.220000,0.0,NaN,0.0,0.2,...,3.000000,5.800000,8.800000,30.80,23.0,1.600000,1.980000,0.375000,-0.620000,2.800000
17,11.800000,1.000000,8.80,0.0,1.00,12.560000,0.0,NaN,0.0,0.2,...,4.400000,5.000000,7.200000,26.20,21.8,2.400000,2.640000,0.394000,-0.560000,3.200000
18,11.000000,0.800000,7.26,0.0,1.00,12.060000,0.0,NaN,0.0,0.2,...,4.400000,5.200000,6.800000,26.40,19.0,1.800000,2.480000,0.394000,-0.520000,3.000000
19,11.200000,1.600000,12.50,0.0,1.40,12.680000,0.0,NaN,0.0,0.2,...,5.400000,5.800000,7.800000,27.60,16.6,2.200000,2.660000,0.418000,-0.340000,3.000000
20,11.600000,1.800000,14.16,0.0,1.80,13.780000,0.0,NaN,0.0,0.0,...,5.200000,7.600000,7.200000,27.40,14.2,1.800000,2.160000,0.412000,-0.640000,2.800000
21,14.600000,1.800000,11.78,0.0,1.40,13.440000,0.0,NaN,0.0,0.2,...,6.200000,9.600000,9.000000,31.40,18.4,1.400000,1.920000,0.392000,-0.280000,2.200000
22,13.000000,1.800000,14.28,0.2,1.40,13.340000,0.0,0.0,0.0,0.2,...,5.400000,10.200000,9.000000,32.60,19.4,0.800000,1.800000,0.346000,-0.400000,2.200000
23,14.000000,1.800000,14.28,0.2,1.40,13.640000,0.0,0.0,0.0,0.2,...,4.800000,10.400000,8.800000,31.20,23.0,0.800000,1.800000,0.346000,-0.200000,2.000000
24,13.400000,0.800000,7.62,0.2,1.40,15.100000,0.0,0.0,0.0,0.2,...,3.600000,10.400000,8.200000,27.60,23.6,0.400000,1.440000,0.312000,-0.160000,1.600000

In [40]:
df_away_cmb= compute_rolling_averages(df_away_cmb, combined)
df_away_cmb['H/A']= df_away['H/A']
df_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,25.000000,15.000000,62.500000,1.000000,0.0,0.0,17.000000,8.0,49.000000,H
1,18.000000,9.500000,67.900000,2.000000,0.0,0.0,15.500000,11.0,49.500000,A
2,16.666667,11.666667,60.833333,2.333333,0.0,0.0,15.333333,13.0,47.666667,H
3,15.500000,14.000000,54.725000,2.750000,0.0,0.0,13.000000,13.5,46.750000,A
4,14.200000,14.800000,50.440000,3.400000,0.2,0.2,12.600000,12.8,43.200000,A
5,12.800000,13.200000,52.340000,3.600000,0.2,0.2,11.400000,14.2,40.200000,H
6,13.600000,15.000000,48.400000,3.800000,0.4,0.4,10.800000,13.6,37.200000,A
7,14.400000,14.600000,50.320000,3.600000,0.4,0.4,9.600000,12.4,36.200000,H
8,15.000000,15.200000,50.740000,3.400000,0.4,0.4,10.200000,12.4,36.600000,A
9,15.800000,14.600000,53.360000,2.400000,0.2,0.2,9.400000,12.0,39.000000,H
10,15.200000,17.600000,47.060000,2.200000,0.2,0.2,9.800000,10.2,41.000000,H
11,15.000000,17.200000,47.540000,1.800000,0.0,0.0,9.800000,10.0,39.800000,A
12,14.600000,17.800000,45.980000,1.600000,0.0,0.0,9.000000,10.6,39.000000,H
13,12.600000,14.400000,46.620000,1.800000,0.0,0.0,10.200000,9.0,38.600000,A
14,13.200000,14.200000,48.000000,2.000000,0.0,0.0,11.400000,9.4,38.600000,A
15,12.200000,11.400000,51.020000,1.800000,0.0,0.0,11.200000,9.4,38.800000,H
16,13.400000,12.600000,50.640000,2.200000,0.0,0.0,11.800000,9.4,41.400000,A
17,12.600000,11.800000,50.540000,2.600000,0.0,0.0,13.200000,9.2,43.400000,H
18,16.000000,15.600000,51.360000,2.000000,0.0,0.0,12.200000,10.4,45.000000,A
19,16.000000,15.200000,52.120000,2.000000,0.0,0.0,11.200000,10.4,45.400000,A
20,16.000000,17.200000,48.140000,2.400000,0.0,0.0,10.200000,11.2,44.200000,H
21,15.800000,18.200000,46.580000,1.600000,0.0,0.0,8.200000,12.8,44.000000,H
22,17.400000,17.400000,50.780000,1.600000,0.0,0.0,8.200000,12.0,43.000000,A
23,16.000000,13.800000,54.660000,1.600000,0.0,0.0,7.800000,11.8,42.000000,H
24,15.800000,14.600000,52.920000,1.200000,0.0,0.0,7.800000,12.2,41.200000,A

In [41]:
df_vs_away_cmb= compute_rolling_averages(df_vs_away_cmb, combined)
#df_away_cmb['H/A']= df_away['H/A']
df_vs_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,15.000000,25.000000,37.500000,3.000000,0.0,0.0,8.000000,17.000000,57.000000
1,9.500000,18.000000,32.100000,3.000000,0.0,0.0,11.000000,15.000000,48.000000
2,11.666667,16.666667,39.166667,3.333333,0.0,0.0,13.333333,14.333333,46.666667
3,14.000000,15.500000,45.275000,3.500000,0.0,0.0,13.750000,12.250000,46.750000
4,14.800000,14.200000,49.560000,3.400000,0.0,0.0,13.400000,11.600000,43.400000
5,13.200000,12.800000,47.660000,3.600000,0.0,0.0,14.800000,10.400000,37.800000
6,15.000000,13.600000,51.600000,4.200000,0.0,0.0,14.400000,9.800000,37.800000
7,14.600000,14.400000,49.700000,4.000000,0.0,0.0,13.200000,9.000000,38.000000
8,15.200000,15.000000,49.280000,4.200000,0.0,0.0,13.400000,9.600000,37.600000
9,14.600000,15.800000,46.660000,4.400000,0.2,0.2,12.800000,9.200000,38.200000
10,17.600000,15.200000,52.960000,3.800000,0.2,0.2,11.000000,9.600000,42.400000
11,17.200000,15.000000,52.480000,3.200000,0.2,0.2,10.600000,9.800000,40.800000
12,17.800000,14.600000,54.020000,3.200000,0.2,0.2,11.400000,9.000000,36.600000
13,14.400000,12.600000,53.380000,2.600000,0.2,0.2,9.600000,10.200000,36.200000
14,14.200000,13.200000,52.000000,1.800000,0.0,0.0,9.800000,11.400000,39.000000
15,11.400000,12.200000,48.980000,1.800000,0.0,0.0,9.800000,11.200000,36.200000
16,12.600000,13.400000,49.360000,1.800000,0.0,0.0,9.800000,11.800000,39.400000
17,11.800000,12.600000,49.460000,2.000000,0.2,0.2,9.200000,13.200000,44.600000
18,15.600000,16.000000,48.640000,2.400000,0.2,0.2,10.400000,12.200000,44.800000
19,15.200000,16.000000,47.880000,2.600000,0.2,0.2,10.400000,11.200000,43.800000
20,17.200000,16.000000,51.860000,2.600000,0.2,0.2,11.200000,10.200000,44.600000
21,18.200000,15.800000,53.420000,2.800000,0.2,0.2,12.800000,8.200000,43.200000
22,17.400000,17.400000,49.220000,2.400000,0.0,0.0,12.000000,8.200000,41.800000
23,13.800000,16.000000,45.340000,2.200000,0.0,0.0,12.000000,7.800000,41.800000
24,14.600000,15.800000,47.080000,2.000000,0.0,0.0,12.600000,7.800000,42.400000

In [42]:
df_home_cmb= compute_rolling_averages(df_home_cmb, combined)
df_home_cmb['H/A']= df_home['H/A']
df_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,7.000000,9.000000,43.800000,2.000000,1.000000,0.0,15.00,16.0,31.000000,H
1,8.500000,11.000000,43.650000,2.000000,0.500000,0.0,11.50,17.5,45.000000,A
2,8.666667,11.666667,42.733333,2.666667,0.333333,0.0,13.00,16.0,43.333333,H
3,9.750000,10.750000,47.525000,2.750000,0.250000,0.0,11.25,16.0,40.750000,A
4,10.800000,9.800000,52.300000,2.200000,0.200000,0.0,10.60,16.0,40.000000,A
5,12.000000,9.200000,57.220000,2.600000,0.000000,0.0,10.40,14.8,42.800000,H
6,12.200000,9.200000,57.680000,2.600000,0.000000,0.0,10.40,13.4,41.600000,A
7,12.400000,9.800000,57.200000,2.200000,0.000000,0.0,9.40,12.4,43.800000,H
8,12.600000,10.800000,55.200000,2.200000,0.000000,0.0,11.40,11.8,44.600000,A
9,13.200000,12.400000,52.180000,3.000000,0.000000,0.0,13.00,12.2,45.200000,H
10,15.000000,14.200000,50.400000,2.400000,0.000000,0.0,11.40,12.8,46.200000,A
11,14.200000,14.400000,47.900000,2.200000,0.000000,0.0,12.00,11.8,46.200000,H
12,15.400000,14.400000,50.200000,2.400000,0.000000,0.0,12.00,12.6,44.400000,A
13,14.400000,13.600000,49.820000,2.200000,0.000000,0.0,10.60,13.4,45.200000,H
14,12.600000,12.800000,48.040000,1.400000,0.000000,0.0,8.80,11.8,45.800000,A
15,10.400000,12.400000,45.300000,1.800000,0.000000,0.0,9.00,12.2,45.800000,H
16,10.400000,11.200000,47.980000,1.600000,0.000000,0.0,8.20,12.6,45.600000,A
17,10.000000,9.600000,50.700000,1.400000,0.000000,0.0,9.00,12.2,47.000000,H
18,10.000000,9.800000,50.180000,1.200000,0.000000,0.0,8.80,11.4,49.200000,A
19,12.200000,11.800000,50.700000,2.000000,0.000000,0.0,10.40,11.4,48.200000,A
20,13.600000,10.200000,57.200000,1.400000,0.000000,0.0,11.00,10.6,50.200000,H
21,15.400000,11.600000,58.180000,1.600000,0.000000,0.0,11.00,12.4,47.400000,H
22,13.400000,14.200000,48.660000,1.200000,0.000000,0.0,9.00,12.4,47.400000,A
23,14.200000,14.800000,49.180000,1.800000,0.000000,0.0,9.40,12.8,44.400000,H
24,11.200000,12.400000,46.880000,1.200000,0.000000,0.0,9.00,11.8,43.200000,A

In [43]:
df_vs_home_cmb= compute_rolling_averages(df_vs_home_cmb, combined)
#df_home_cmb['H/A']= df_home['H/A']
df_vs_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,9.000000,7.000000,56.30,4.000000,0.0,0.0,16.000000,15.00,35.000000
1,11.000000,8.500000,56.40,3.000000,0.0,0.0,18.000000,11.50,47.500000
2,11.666667,8.666667,57.30,3.333333,0.0,0.0,16.333333,13.00,46.666667
3,10.750000,9.750000,52.50,3.250000,0.0,0.0,16.500000,11.25,44.000000
4,9.800000,10.800000,47.72,3.800000,0.0,0.0,16.400000,10.60,42.800000
5,9.200000,12.000000,42.78,3.800000,0.0,0.0,15.200000,10.40,44.800000
6,9.200000,12.200000,42.32,3.600000,0.0,0.0,13.600000,10.40,43.600000
7,9.800000,12.400000,42.80,3.200000,0.0,0.0,12.800000,9.40,44.000000
8,10.800000,12.600000,44.80,3.800000,0.0,0.0,12.000000,11.20,45.800000
9,12.400000,13.200000,47.84,3.400000,0.0,0.0,12.400000,12.80,46.800000
10,14.200000,15.000000,49.62,2.800000,0.0,0.0,13.000000,11.20,46.600000
11,14.400000,14.200000,52.12,2.600000,0.0,0.0,12.200000,11.80,45.000000
12,14.400000,15.400000,49.82,2.800000,0.0,0.0,12.800000,11.80,45.200000
13,13.600000,14.400000,50.20,2.600000,0.0,0.0,13.600000,10.60,44.200000
14,12.800000,12.600000,51.96,2.400000,0.0,0.0,12.000000,8.60,46.200000
15,12.400000,10.400000,54.70,2.800000,0.0,0.0,12.600000,8.60,43.800000
16,11.200000,10.400000,52.02,3.200000,0.0,0.0,12.800000,7.60,44.600000
17,9.600000,10.000000,49.30,2.800000,0.2,0.0,12.400000,8.20,41.600000
18,9.800000,10.000000,49.82,2.000000,0.2,0.0,11.600000,7.80,44.800000
19,11.800000,12.200000,49.30,1.600000,0.2,0.0,11.800000,9.40,42.200000
20,10.200000,13.600000,42.80,1.400000,0.2,0.0,11.200000,10.20,46.800000
21,11.600000,15.400000,41.82,2.200000,0.2,0.0,13.000000,10.40,45.800000
22,14.200000,13.400000,51.34,2.200000,0.0,0.0,13.000000,8.60,47.400000
23,14.800000,14.200000,50.82,2.800000,0.0,0.0,13.400000,9.20,45.200000
24,12.400000,11.200000,53.12,2.600000,0.0,0.0,12.200000,9.00,44.800000

In [44]:
df_vs_away_cmb = df_vs_away_cmb.rename(columns=lambda x: 'vs_' + x)
df_vs_home_cmb = df_vs_home_cmb.rename(columns=lambda x: 'vs_' + x)

## Final DFs

In [45]:
df_home_gf= pd.concat([df_home_off, df_home_cmb, df_vs_home_cmb, df_vs_home_def, df_home[['GF']]], axis= 1)
df_home_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,1.000000,0.0,0.0,23.000000,0.0,7.0,1.00,14.300000,5.000000,71.400000,...,6.000000,3.000000,16.00,13.0,1.000000,0.600000,0.630000,-0.400000,1.000000,1
1,1.000000,0.0,0.0,42.000000,0.0,11.0,3.50,27.150000,6.000000,59.050000,...,12.500000,4.500000,21.50,24.0,0.500000,1.600000,0.580000,0.600000,1.000000,1
2,1.333333,0.0,0.0,39.666667,0.0,14.0,5.00,31.433333,7.333333,56.033333,...,12.666667,5.333333,24.00,20.0,0.333333,1.766667,0.623333,0.433333,1.333333,2
3,1.500000,0.0,0.0,42.500000,0.0,16.0,6.75,37.200000,7.500000,51.125000,...,11.500000,6.500000,26.25,20.0,0.250000,1.750000,0.540000,0.250000,1.500000,2
4,1.400000,0.0,0.0,46.200000,0.0,15.8,6.80,39.100000,7.000000,47.560000,...,9.800000,6.400000,26.00,20.2,0.400000,1.600000,0.474000,0.200000,1.400000,1
5,1.200000,0.2,0.0,49.200000,0.2,16.8,8.20,49.580000,6.400000,36.620000,...,9.600000,7.200000,27.20,21.8,0.200000,1.700000,0.370000,0.300000,1.400000,1
6,1.000000,0.2,0.2,50.400000,0.4,17.8,8.20,47.580000,6.800000,36.280000,...,7.000000,8.000000,27.60,20.8,0.200000,1.360000,0.272000,0.160000,1.200000,0
7,0.600000,0.2,0.2,55.400000,0.4,18.0,8.60,49.100000,6.400000,33.900000,...,6.000000,8.400000,28.80,26.0,0.200000,1.120000,0.160000,0.320000,0.800000,0
8,0.400000,0.2,0.2,55.200000,0.4,16.2,7.40,47.440000,5.600000,32.780000,...,6.600000,9.600000,27.80,27.0,0.200000,1.020000,0.218000,0.420000,0.600000,1
9,0.400000,0.2,0.2,50.400000,0.4,15.2,7.20,50.100000,5.200000,32.120000,...,8.600000,9.600000,27.40,26.4,0.000000,1.080000,0.240000,0.480000,0.600000,1
10,1.000000,0.0,0.2,54.000000,0.2,16.0,6.00,39.260000,7.200000,43.780000,...,8.400000,9.600000,30.20,27.6,0.200000,1.320000,0.296000,0.320000,1.000000,3
11,1.000000,0.0,0.0,51.200000,0.0,14.6,5.80,40.960000,7.000000,47.080000,...,8.800000,9.600000,31.60,28.2,0.400000,1.220000,0.330000,0.220000,1.000000,0
12,1.000000,0.0,0.0,49.400000,0.0,15.6,5.00,36.060000,8.600000,51.760000,...,8.400000,10.400000,33.20,25.4,0.400000,1.040000,0.375000,0.040000,1.200000,1
13,1.400000,0.0,0.0,47.800000,0.0,19.2,6.20,34.560000,9.600000,51.400000,...,8.000000,9.200000,34.20,25.0,1.000000,1.300000,0.335000,-0.100000,1.600000,3
14,1.600000,0.0,0.0,51.800000,0.0,22.4,7.80,33.320000,11.400000,54.640000,...,6.800000,8.800000,35.20,27.2,1.200000,1.300000,0.362500,-0.300000,1.800000,2
15,1.800000,0.0,0.0,52.400000,0.0,24.2,9.60,39.620000,11.200000,48.440000,...,6.600000,10.000000,35.20,26.8,1.400000,1.700000,0.362500,-0.100000,2.000000,4
16,2.600000,0.0,0.0,53.400000,0.0,24.8,10.80,45.680000,10.400000,41.140000,...,5.800000,8.800000,30.80,23.0,1.600000,1.980000,0.375000,-0.620000,2.800000,4
17,3.200000,0.0,0.0,55.600000,0.0,21.4,10.80,54.400000,7.600000,33.280000,...,5.000000,7.200000,26.20,21.8,2.400000,2.640000,0.394000,-0.560000,3.200000,3
18,3.000000,0.0,0.0,56.800000,0.0,19.2,9.60,52.660000,8.400000,40.480000,...,5.200000,6.800000,26.40,19.0,1.800000,2.480000,0.394000,-0.520000,3.000000,2
19,3.000000,0.0,0.0,54.200000,0.0,18.2,8.20,48.560000,8.000000,40.760000,...,5.800000,7.800000,27.60,16.6,2.200000,2.660000,0.418000,-0.340000,3.000000,2
20,2.800000,0.0,0.0,54.400000,0.0,18.6,9.20,51.620000,7.000000,36.400000,...,7.600000,7.200000,27.40,14.2,1.800000,2.160000,0.412000,-0.640000,2.800000,3
21,2.200000,0.0,0.0,54.000000,0.0,19.0,8.60,46.740000,7.800000,40.280000,...,9.600000,9.000000,31.40,18.4,1.400000,1.920000,0.392000,-0.280000,2.200000,1
22,2.000000,0.2,0.0,51.000000,0.2,20.4,8.80,42.160000,9.200000,47.100000,...,10.200000,9.000000,32.60,19.4,0.800000,1.800000,0.346000,-0.400000,2.200000,3
23,1.800000,0.2,0.0,51.200000,0.2,19.0,8.20,40.780000,8.000000,44.860000,...,10.400000,8.800000,31.20,23.0,0.800000,1.800000,0.346000,-0.200000,2.000000,1
24,1.400000,0.2,0.0,50.200000,0.2,15.8,7.00,38.120000,6.600000,47.340000,...,10.400000,8.200000,27.60,23.6,0.400000,1.440000,0.312000,-0.160000,1.600000,0

In [46]:
df_away_gf= pd.concat([df_away_off, df_away_cmb, df_vs_away_cmb, df_vs_away_def, df_away[['GF']]], axis= 1)
df_away_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,1.0,0.0,0.0,53.00,0.0,23.000000,9.0,39.100,10.000000,43.500000,...,10.0,14.000000,32.000000,29.00,1.00,1.700000,0.2300,7.000000e-01,1.0,1
1,1.0,0.0,0.0,44.50,0.0,21.500000,8.0,37.050,10.500000,49.250000,...,9.5,8.000000,26.000000,24.00,1.50,1.650000,0.2150,6.500000e-01,1.0,1
2,1.0,0.0,0.0,47.00,0.0,21.333333,8.0,37.400,9.666667,45.533333,...,9.0,8.666667,28.333333,25.00,1.00,1.666667,0.2600,6.666667e-01,1.0,1
3,1.0,0.0,0.0,43.25,0.0,19.500000,7.5,38.775,8.500000,43.075000,...,8.0,9.250000,27.000000,22.75,0.75,1.425000,0.2575,4.250000e-01,1.0,1
4,1.0,0.2,0.0,40.60,0.2,18.400000,7.6,42.440,7.400000,38.740000,...,9.0,8.800000,25.400000,19.80,0.60,1.480000,0.2600,2.800000e-01,1.2,2
5,0.8,0.2,0.0,38.20,0.2,15.000000,6.6,47.960,5.600000,33.380000,...,7.6,7.800000,22.200000,22.80,0.60,1.140000,0.2160,1.400000e-01,1.0,0
6,0.8,0.2,0.0,38.00,0.2,14.800000,7.0,50.440,4.800000,29.740000,...,7.4,9.000000,22.600000,22.60,0.40,1.140000,0.2120,1.400000e-01,1.0,1
7,0.8,0.2,0.0,37.80,0.2,16.000000,8.6,54.680,4.800000,28.040000,...,8.4,8.000000,21.600000,22.20,0.60,1.160000,0.2020,1.600000e-01,1.0,1
8,1.2,0.2,0.0,38.40,0.2,18.000000,10.4,58.600,4.800000,25.060000,...,9.2,7.000000,21.000000,24.20,0.80,1.360000,0.2200,-4.000000e-02,1.4,3
9,1.6,0.0,0.0,43.20,0.0,17.600000,10.0,57.180,5.000000,27.440000,...,7.8,7.800000,22.000000,29.00,1.00,1.600000,0.2620,-5.551115e-18,1.6,3
10,1.8,0.0,0.0,43.80,0.0,19.400000,10.4,51.840,6.000000,32.100000,...,8.6,8.800000,24.200000,24.80,1.00,1.780000,0.3200,-2.000000e-02,1.8,1
11,1.6,0.0,0.0,43.60,0.0,18.400000,9.4,48.080,5.800000,33.320000,...,8.0,8.000000,23.600000,23.80,0.80,1.460000,0.3550,-1.400000e-01,1.6,0
12,1.4,0.2,0.0,42.40,0.2,17.000000,7.6,43.220,6.000000,36.400000,...,5.8,7.800000,22.000000,23.00,0.80,1.400000,0.3075,-2.000000e-01,1.6,1
13,0.8,0.2,0.0,42.20,0.2,14.800000,5.6,38.420,6.000000,39.940000,...,5.4,7.600000,22.200000,20.80,1.00,1.160000,0.2675,1.600000e-01,1.0,0
14,0.8,0.2,0.0,37.20,0.2,15.600000,6.0,38.420,6.800000,43.280000,...,5.0,7.200000,21.800000,15.40,1.20,0.880000,0.2750,-1.200000e-01,1.0,3
15,1.0,0.2,0.0,38.40,0.2,15.600000,6.8,43.760,6.600000,41.940000,...,4.4,5.600000,19.800000,15.20,1.40,1.080000,0.2850,-1.200000e-01,1.2,2
16,1.4,0.2,0.0,38.80,0.2,16.600000,6.8,42.260,7.400000,43.880000,...,3.8,7.400000,22.000000,16.00,1.60,1.360000,0.2740,-2.400000e-01,1.6,2
17,1.6,0.0,0.0,35.80,0.0,15.800000,7.2,46.520,6.400000,39.880000,...,4.2,8.000000,21.600000,12.40,1.60,1.340000,0.3420,-2.600000e-01,1.6,1
18,2.0,0.0,0.0,36.20,0.0,14.600000,7.0,50.240,6.000000,40.760000,...,4.0,8.200000,21.800000,12.80,1.40,1.560000,0.3540,-4.400000e-01,2.0,2
19,2.0,0.0,0.0,38.40,0.0,14.200000,6.2,45.960,5.800000,40.760000,...,4.4,8.400000,22.000000,16.60,1.20,1.800000,0.4320,-2.000000e-01,2.0,3
20,1.8,0.0,0.0,34.40,0.0,14.800000,5.4,39.280,6.200000,41.880000,...,4.2,7.600000,21.000000,18.60,0.80,1.600000,0.4260,-2.000000e-01,1.8,1
21,2.0,0.0,0.0,36.20,0.0,14.400000,6.0,43.300,5.200000,37.240000,...,5.0,6.200000,18.400000,21.60,0.80,1.540000,0.4340,-4.600000e-01,2.0,3
22,1.8,0.0,0.0,40.20,0.0,14.400000,5.8,42.040,5.600000,39.740000,...,6.0,6.600000,21.000000,27.80,0.60,1.460000,0.3940,-3.400000e-01,1.8,0
23,2.4,0.2,0.0,40.60,0.2,17.600000,8.0,43.660,6.600000,38.120000,...,6.8,6.400000,21.800000,27.00,1.20,2.000000,0.4320,-6.000000e-01,2.8,7
24,2.0,0.2,0.0,41.60,0.2,17.200000,8.6,49.600,6.200000,36.460000,...,6.2,5.800000,20.200000,27.20,1.00,1.680000,0.3580,-5.200000e-01,2.4,1

In [47]:
nan_counts = df_home_gf.isna().sum()
for i in df_home_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 16
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [48]:
nan_counts = df_away_gf.isna().sum()
for i in df_away_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 13
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [49]:
df_home_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [50]:
df_away_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [51]:
df_home_gf = df_home_gf.fillna(0)

In [52]:
df_away_gf = df_away_gf.fillna(0)

# Model Home

In [53]:
target = "GF"  # Goals For

# Separate features and target
X = df_home_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
y = df_home_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [54]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [55]:
model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=25)

# Train the model
model_pipeline.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 1.133
RMSE: 1.498

In [57]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline.predict(X_test)
    y_cur= model_pipeline.predict(df_home_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 19, number of used features: 0
[LightGBM] [Info] Start training from score 1.736842
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [58]:
results_df

                        MAE      RMSE                   pred
Random Forest          0.88  1.164474                  [1.3]
XGBoost            1.353682  1.491011            [1.6749551]
LightGBM           0.747368  0.811619    [1.736842105263158]
Linear Regression  3.253853  5.003391  [0.15523611881344368]

# Model Away

In [59]:
target = "GF"  # Goals For

# Separate features and target
Xa = df_away_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
ya = df_away_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [60]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [61]:
model_pipeline2 = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [62]:
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.1, random_state=25)

# Train the model
model_pipeline2.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline2.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 0.167
RMSE: 0.212

In [63]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline2 = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline2.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline2.predict(X_test)
    y_cur= model_pipeline2.predict(df_away_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 19, number of used features: 0
[LightGBM] [Info] Start training from score 1.631579
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [64]:
results_df

                        MAE      RMSE                 pred
Random Forest          1.02  1.238548                [1.0]
XGBoost             0.98144  1.049709          [0.7176812]
LightGBM           0.926316  0.994166  [1.631578947368421]
Linear Regression  2.767812  3.157034  [2.027869952537424]