In [1]:
import pandas as pd
from datetime import datetime

In [2]:
#from collections import Counter

#my_list = ["apple", "banana", "apple", "orange", "banana", "banana"]

# Count occurrences
#count_dict = Counter(cols)
#count_dict# Output: {'banana': 3, 'apple': 2, 'orange': 1}

## Datasets

In [3]:
df_AGK= pd.read_csv("../Data/Passes (GK).csv")
df_AGK = df_AGK.rename(columns={"Launch%": "Pa Launch%", 
                                "AvgLen": "Pa AvgLen"})
df_AGK = df_AGK.drop(columns=["Att (GK).1"])
df_AGK

,Rk,Team,Date,Att (GK),Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,Thr,Pa Launch%,Pa AvgLen,Match Report
0,1,Dortmund,2025-01-10,69,NaN,Leverkusen,de Bundesliga,L 2-3,2,3,-1,70,1,1,1,0,3,8.7,24.5,Match Report
1,2,Strasbourg,2025-02-02,69,@,Rennes,fr Ligue 1,L 0-1,0,1,-1,54,0,0,0,0,4,7.2,25.1,Match Report
2,3,Barcelona,2024-11-10,65,@,Real Sociedad,es La Liga,L 0-1,0,1,-1,69,0,0,0,0,7,6.2,23.3,Match Report
3,4,St. Pauli,2025-02-15,65,NaN,Freiburg,de Bundesliga,L 0-1,0,1,-1,54,0,0,0,0,4,26.2,28.7,Match Report
4,5,Saint-Étienne,2024-12-13,62,@,Toulouse,fr Ligue 1,L 1-2,1,2,-1,61,1,0,0,0,7,19.4,28.5,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Napoli,2024-08-31,8,NaN,Parma,it Serie A,W 2-1,2,1,1,55,2,0,0,0,1,12.5,25.1,Match Report
2838,2839,Toulouse,2025-03-30,6,NaN,Brest,fr Ligue 1,L 2-4,2,4,-2,53,2,0,0,0,3,16.7,21.2,Match Report
2839,2840,Getafe,2024-10-05,6,NaN,Osasuna,es La Liga,D 1-1,1,1,0,41,1,0,0,0,0,100.0,61.8,Match Report
2840,2841,Mallorca,2024-08-18,5,NaN,Real Madrid,es La Liga,D 1-1,1,1,0,34,1,0,0,0,0,160.0,91.2,Match Report
2841,2842,Rayo Vallecano,2024-08-18,4,@,Real Sociedad,es La Liga,W 2-1,2,1,1,34,2,0,0,0,2,100.0,59.8,Match Report

In [4]:
df_ArW= pd.read_csv("../Data/Aeral Duels.csv")
df_ArW = df_ArW.drop(columns=["Won.1"])
df_ArW

,Rk,Team,Date,Won,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,Lost,Won%,Match Report
0,1,Lecce,2025-04-06,41,NaN,Venezia,it Serie A,D 1-1,1,1,0,50,1,0,0,0,17,70.7,Match Report
1,2,Valladolid,2024-11-22,39,@,Getafe,es La Liga,L 0-2,0,2,-2,43,0,0,0,0,32,54.9,Match Report
2,3,Union Berlin,2025-03-02,38,NaN,Holstein Kiel,de Bundesliga,L 0-1,0,1,-1,52,0,0,0,0,32,54.3,Match Report
3,4,Bochum,2024-12-22,38,NaN,Heidenheim,de Bundesliga,W 2-0,2,0,2,52,2,0,0,0,22,63.3,Match Report
4,5,Brentford,2024-11-09,37,NaN,Bournemouth,eng Premier League,W 3-2,3,2,1,51,3,0,0,0,18,67.3,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Paris S-G,2025-03-08,2,@,Rennes,fr Ligue 1,W 4-1,4,1,3,68,4,0,0,0,10,16.7,Match Report
2838,2839,Girona,2024-09-15,1,NaN,Barcelona,es La Liga,L 1-4,1,4,-3,45,1,0,0,0,5,16.7,Match Report
2839,2840,Girona,2024-08-15,1,@,Betis,es La Liga,D 1-1,1,1,0,61,1,0,0,0,8,11.1,Match Report
2840,2841,Rayo Vallecano,2025-03-09,1,@,Real Madrid,es La Liga,L 1-2,1,2,-1,54,1,0,0,0,7,12.5,Match Report
2841,2842,Girona,2024-12-07,0,NaN,Real Madrid,es La Liga,L 0-3,0,3,-3,42,0,0,0,0,2,0.0,Match Report

In [5]:
df_AtD= pd.read_csv("../Data/Take-Ons.csv")
df_AtD = df_AtD.rename(columns={"Att": "Att To"})
df_AtD = df_AtD.drop(columns=["Att.1"])
df_AtD

,Rk,Team,Date,Att To,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Poss,G-PK,PK,PKatt,PKm,Succ,Succ%,Tkld,Tkld%,Match Report
0,1,Real Madrid,2024-11-09,46,NaN,Osasuna,es La Liga,W 4-0,4,0,...,68,4,0,0,0,21,45.7,18,39.1,Match Report
1,2,West Ham,2024-12-03,45,@,Leicester City,eng Premier League,L 1-3,1,3,...,61,1,0,0,0,20,44.4,20,44.4,Match Report
2,3,Dortmund,2025-01-17,43,@,Eint Frankfurt,de Bundesliga,L 0-2,0,2,...,67,0,0,0,0,20,46.5,17,39.5,Match Report
3,4,Manchester City,2025-03-15,42,NaN,Brighton,eng Premier League,D 2-2,2,2,...,60,1,1,1,0,21,50.0,14,33.3,Match Report
4,5,Chelsea,2024-12-22,42,@,Everton,eng Premier League,D 0-0,0,0,...,75,0,0,0,0,17,40.5,18,42.9,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Genoa,2024-10-31,4,NaN,Fiorentina,it Serie A,L 0-1,0,1,...,33,0,0,0,0,3,75.0,1,25.0,Match Report
2838,2839,Empoli,2025-03-09,4,NaN,Roma,it Serie A,L 0-1,0,1,...,36,0,0,0,0,2,50.0,1,25.0,Match Report
2839,2840,Napoli,2025-02-15,3,@,Lazio,it Serie A,D 2-2,2,2,...,47,1,0,0,0,1,33.3,1,33.3,Match Report
2840,2841,Holstein Kiel,2025-01-24,2,@,Wolfsburg,de Bundesliga,D 2-2,2,2,...,31,2,0,0,0,1,50.0,1,50.0,Match Report
2841,2842,Alavés,2025-02-15,2,@,Leganés,es La Liga,D 3-3,3,3,...,57,2,1,1,0,0,0.0,2,100.0,Match Report

In [6]:
df_Car= pd.read_csv("../Data/Carries.csv")
df_Car = df_Car.rename(columns={"1/3": "Last3rd Car"})
df_Car = df_Car.drop(columns=["Carries.1", "Dis", "Rec", "CPA", "Rec", "PrgR", "Mis"])
df_Car

,Rk,Team,Date,Carries,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Poss,G-PK,PK,PKatt,PKm,TotDist,PrgDist,PrgC,Last3rd Car,Match Report
0,1,Paris S-G,2024-10-27,815,@,Marseille,fr Ligue 1,W 3-0,3,0,...,74,2,0,0,0,3820,1968,33,40,Match Report
1,2,Bayern Munich,2024-12-07,789,NaN,Heidenheim,de Bundesliga,W 4-2,4,2,...,82,4,0,0,0,3537,1765,27,22,Match Report
2,3,Marseille,2024-08-31,769,@,Toulouse,fr Ligue 1,W 3-1,3,1,...,76,2,0,0,0,3102,1379,16,17,Match Report
3,4,Leverkusen,2024-11-23,742,NaN,Heidenheim,de Bundesliga,W 5-2,5,2,...,78,5,0,0,0,4150,2349,35,38,Match Report
4,5,Paris S-G,2025-04-05,718,NaN,Angers,fr Ligue 1,W 1-0,1,0,...,81,1,0,0,0,3982,2051,37,41,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Reims,2025-03-29,107,NaN,Marseille,fr Ligue 1,W 3-1,3,1,...,20,3,0,0,0,629,387,7,2,Match Report
2838,2839,Mainz 05,2024-09-20,104,@,Augsburg,de Bundesliga,W 3-2,3,2,...,27,3,0,0,0,528,219,3,3,Match Report
2839,2840,Heidenheim,2025-02-23,103,@,RB Leipzig,de Bundesliga,D 2-2,2,2,...,26,1,1,1,0,565,289,7,4,Match Report
2840,2841,Getafe,2025-02-09,102,@,Alavés,es La Liga,W 1-0,1,0,...,35,0,1,1,0,493,184,4,5,Match Report
2841,2842,Getafe,2024-09-25,98,@,Barcelona,es La Liga,L 0-1,0,1,...,24,0,0,0,0,717,343,10,10,Match Report

In [7]:
df_CrA= pd.read_csv("../Data/Crosses (GK).csv")
df_CrA = df_CrA.rename(columns={"Opp": "OppCr", "Opp.1": "Opp"})
df_CrA= df_CrA.drop(columns=["Opp.2"])
df_CrA

,Rk,Team,Date,OppCr,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,Stp,Stp%,Match Report
0,1,Mainz 05,2024-12-21,48,@,Eint Frankfurt,de Bundesliga,W 3-1,3,1,2,30,2,0,0,0,4,8.3,Match Report
1,2,Valladolid,2024-12-13,45,NaN,Valencia,es La Liga,W 1-0,1,0,1,33,1,0,0,0,4,8.9,Match Report
2,3,Leicester City,2024-12-26,44,@,Liverpool,eng Premier League,L 1-3,1,3,-2,32,1,0,0,0,3,6.8,Match Report
3,4,Leganés,2025-01-26,42,@,Athletic Club,es La Liga,D 0-0,0,0,0,32,0,0,0,0,2,4.8,Match Report
4,5,Leganés,2024-11-30,42,@,Alavés,es La Liga,D 1-1,1,1,0,40,1,0,0,0,4,9.5,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Manchester City,2024-10-26,1,NaN,Southampton,eng Premier League,W 1-0,1,0,1,57,1,0,0,0,0,0.0,Match Report
2838,2839,Leverkusen,2025-02-15,1,NaN,Bayern Munich,de Bundesliga,D 0-0,0,0,0,57,0,0,0,0,0,0.0,Match Report
2839,2840,Milan,2024-08-24,1,@,Parma,it Serie A,L 1-2,1,2,-1,61,1,0,0,0,0,0.0,Match Report
2840,2841,Brest,2024-08-17,1,NaN,Marseille,fr Ligue 1,L 1-5,1,5,-4,50,1,0,1,1,0,0.0,Match Report
2841,2842,Bayern Munich,2024-10-06,0,@,Eint Frankfurt,de Bundesliga,D 3-3,3,3,0,74,3,0,0,0,0,NaN,Match Report

In [8]:
df_Crd= pd.read_csv("../Data/Cards and Fouls.csv")
#df_CrA = df_CrA.rename(columns={"Opp": "OppCr", "Opp.1": "Opp"})
df_Crd = df_Crd.drop(columns=["CrdY.1"])
df_Crd

,Rk,Team,Date,CrdY,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Poss,G-PK,PK,PKatt,PKm,CrdR,2CrdY,Fls,Fld,Match Report
0,1,Las Palmas,2024-10-21,9,@,Valencia,es La Liga,W 3-2,3,2,...,52,3,0,0,0,0,0,12,12,Match Report
1,2,Las Palmas,2025-03-09,8,@,Betis,es La Liga,L 0-1,0,1,...,33,0,0,0,0,1,1,14,12,Match Report
2,3,Osasuna,2025-01-24,8,@,Las Palmas,es La Liga,D 1-1,1,1,...,49,1,0,0,0,0,0,17,12,Match Report
3,4,Werder Bremen,2025-01-31,8,NaN,Mainz 05,de Bundesliga,W 1-0,1,0,...,38,1,0,1,1,2,2,14,12,Match Report
4,5,Cagliari,2024-11-04,8,@,Lazio,it Serie A,L 1-2,1,2,...,46,1,0,0,0,2,2,17,12,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2025-01-26,0,NaN,Inter,it Serie A,L 0-4,0,4,...,49,0,0,0,0,0,0,13,12,Match Report
2838,2839,Lecce,2025-01-05,0,NaN,Genoa,it Serie A,D 0-0,0,0,...,63,0,0,0,0,0,0,11,14,Match Report
2839,2840,Lecce,2024-11-08,0,NaN,Empoli,it Serie A,D 1-1,1,1,...,58,1,0,0,0,0,0,7,23,Match Report
2840,2841,Lecce,2024-10-20,0,NaN,Fiorentina,it Serie A,L 0-6,0,6,...,39,0,0,0,0,1,0,8,13,Match Report
2841,2842,Lecce,2024-08-19,0,NaN,Atalanta,it Serie A,L 0-4,0,4,...,48,0,0,0,0,0,0,10,24,Match Report

In [9]:
df_GcA= pd.read_csv("../Data/Goal Creating-Actions.csv")
df_GcA = df_GcA.rename(columns={"PassLive": "PassLive Gc",
                                "PassDead": "PassDead Gc",
                                "TO": "TO Gc",
                                "Fld": "Fld Gc",
                                "Def": "Def-Gc",
                                "Sh": "Sh-Gc"})
df_GcA = df_GcA.drop(columns=["GCA.1"])
df_GcA

,Rk,Team,Date,GCA,Unnamed: 4,Opp,Comp,Result,GF,GA,...,PK,PKatt,PKm,PassLive Gc,PassDead Gc,TO Gc,Sh-Gc,Fld Gc,Def-Gc,Match Report
0,1,Eint Frankfurt,2024-11-02,13,NaN,Bochum,de Bundesliga,W 7-2,7,2,...,0,0,0,7,0,3,0,1,2,Match Report
1,2,Monaco,2025-02-15,13,NaN,Nantes,fr Ligue 1,W 7-1,7,1,...,1,1,0,11,0,1,0,1,0,Match Report
2,3,Nice,2024-09-20,12,NaN,Saint-Étienne,fr Ligue 1,W 8-0,8,0,...,1,1,0,6,1,2,2,1,0,Match Report
3,4,Athletic Club,2025-02-23,12,NaN,Valladolid,es La Liga,W 7-1,7,1,...,0,0,0,8,0,2,2,0,0,Match Report
4,5,Paris S-G,2024-08-23,12,NaN,Montpellier,fr Ligue 1,W 6-0,6,0,...,0,0,0,11,0,1,0,0,0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-10-05,0,@,Udinese,it Serie A,L 0-1,0,1,...,0,0,0,0,0,0,0,0,0,Match Report
2838,2839,Lecce,2024-09-27,0,@,Milan,it Serie A,L 0-3,0,3,...,0,0,0,0,0,0,0,0,0,Match Report
2839,2840,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,...,0,0,0,0,0,0,0,0,0,Match Report
2840,2841,Lecce,2024-08-24,0,@,Inter,it Serie A,L 0-2,0,2,...,0,0,0,0,0,0,0,0,0,Match Report
2841,2842,Lecce,2024-08-19,0,NaN,Atalanta,it Serie A,L 0-4,0,4,...,0,0,0,0,0,0,0,0,0,Match Report

In [10]:
df_GKA= pd.read_csv("../Data/Goal Kicks (GK).csv")
df_GKA = df_GKA.rename(columns={"Att": "GK Att"})
df_GKA = df_GKA.drop(columns=["Att.1"])
df_GKA

,Rk,Team,Date,GK Att,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,Launch%,AvgLen,Match Report
0,1,Lecce,2024-11-02,24,@,Bologna,it Serie A,L 0-1,0,1,-1,28,0,0,0,0,87.5,55.6,Match Report
1,2,Augsburg,2025-03-08,20,@,Dortmund,de Bundesliga,W 1-0,1,0,1,29,1,0,0,0,85.0,61.7,Match Report
2,3,Leganés,2025-01-26,20,@,Athletic Club,es La Liga,D 0-0,0,0,0,32,0,0,0,0,100.0,69.9,Match Report
3,4,Cagliari,2025-01-11,20,@,Milan,it Serie A,D 1-1,1,1,0,32,1,0,0,0,80.0,52.7,Match Report
4,5,Las Palmas,2024-11-08,19,@,Rayo Vallecano,es La Liga,W 3-1,3,1,2,36,2,0,0,0,68.4,58.8,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Como,2024-10-04,0,@,Napoli,it Serie A,L 1-3,1,3,-2,59,1,0,0,0,NaN,NaN,Match Report
2838,2839,Fiorentina,2024-09-01,0,NaN,Monza,it Serie A,D 2-2,2,2,0,68,2,0,0,0,NaN,NaN,Match Report
2839,2840,Stuttgart,2025-01-15,0,NaN,RB Leipzig,de Bundesliga,W 2-1,2,1,1,58,2,0,0,0,NaN,NaN,Match Report
2840,2841,Genoa,2025-02-02,0,@,Fiorentina,it Serie A,L 1-2,1,2,-1,59,1,0,0,0,NaN,NaN,Match Report
2841,2842,Nott'ham Forest,2024-11-30,0,NaN,Ipswich Town,eng Premier League,W 1-0,1,0,1,45,0,1,1,0,NaN,NaN,Match Report

In [11]:
df_Gls= pd.read_csv("../Data/Shooting.csv")
df_Gls = df_Gls.drop(columns=["Gls.1", "Gls"])
df_Gls

,Rk,Team,Date,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,...,PKatt,PKm,Sh,G/Sh,G/SoT,SoT,SoT%,Dist,FK,Match Report
0,1,Nice,2024-09-20,NaN,Saint-Étienne,fr Ligue 1,W 8-0,8,0,8,...,1,0,17,0.35,0.55,11,64.7,15.3,0,Match Report
1,2,Barcelona,2024-08-31,NaN,Valladolid,es La Liga,W 7-0,7,0,7,...,0,0,23,0.30,0.64,11,47.8,13.7,1,Match Report
2,3,Athletic Club,2025-02-23,NaN,Valladolid,es La Liga,W 7-1,7,1,6,...,0,0,29,0.24,0.44,16,55.2,16.4,0,Match Report
3,4,Eint Frankfurt,2024-11-02,NaN,Bochum,de Bundesliga,W 7-2,7,2,5,...,0,0,18,0.39,0.78,9,50.0,17.0,2,Match Report
4,5,Monaco,2025-02-15,NaN,Nantes,fr Ligue 1,W 7-1,7,1,6,...,1,0,21,0.29,0.60,10,47.6,15.1,0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-10-05,@,Udinese,it Serie A,L 0-1,0,1,-1,...,0,0,9,0.00,0.00,3,33.3,22.0,0,Match Report
2838,2839,Lecce,2024-09-27,@,Milan,it Serie A,L 0-3,0,3,-3,...,0,0,16,0.00,0.00,7,43.8,19.2,0,Match Report
2839,2840,Lecce,2024-09-15,@,Torino,it Serie A,D 0-0,0,0,0,...,0,0,20,0.00,0.00,6,30.0,18.9,0,Match Report
2840,2841,Lecce,2024-08-24,@,Inter,it Serie A,L 0-2,0,2,-2,...,0,0,10,0.00,0.00,4,40.0,19.1,0,Match Report
2841,2842,Lecce,2024-08-19,NaN,Atalanta,it Serie A,L 0-4,0,4,-4,...,0,0,21,0.00,0.00,4,19.0,17.3,1,Match Report

In [12]:
df_Misc= pd.read_csv("../Data/Misc.csv")
df_Misc = df_Misc.drop(columns=["Off.1"])
df_Misc

,Rk,Team,Date,Off,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Poss,G-PK,PK,PKatt,PKm,PKwon,PKcon,OG,Recov,Match Report
0,1,Real Madrid,2024-10-26,12,NaN,Barcelona,es La Liga,L 0-4,0,4,...,43,0,0,0,0,0,0,0,42,Match Report
1,2,Mallorca,2024-12-03,11,NaN,Barcelona,es La Liga,L 1-5,1,5,...,41,1,0,0,0,0,1,0,47,Match Report
2,3,Alavés,2025-02-02,11,@,Barcelona,es La Liga,L 0-1,0,1,...,31,0,0,0,0,0,0,0,32,Match Report
3,4,Alavés,2024-10-06,11,NaN,Barcelona,es La Liga,L 0-3,0,3,...,29,0,0,0,0,0,0,0,39,Match Report
4,5,Osasuna,2024-09-28,10,NaN,Barcelona,es La Liga,W 4-2,4,2,...,27,3,1,1,0,1,0,0,48,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-11-02,0,@,Bologna,it Serie A,L 0-1,0,1,...,28,0,0,0,0,0,0,0,30,Match Report
2838,2839,Lecce,2024-10-26,0,@,Napoli,it Serie A,L 0-1,0,1,...,36,0,0,0,0,0,0,0,25,Match Report
2839,2840,Lecce,2024-10-20,0,NaN,Fiorentina,it Serie A,L 0-6,0,6,...,39,0,0,0,0,0,0,0,32,Match Report
2840,2841,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,...,47,0,0,0,0,0,0,0,39,Match Report
2841,2842,Lecce,2024-08-24,0,@,Inter,it Serie A,L 0-2,0,2,...,39,0,0,0,0,0,1,0,38,Match Report

In [13]:
df_OPA= pd.read_csv("../Data/Sweeper (GK).csv")
df_OPA = df_OPA.drop(columns=["#OPA.1"])
df_OPA

,Rk,Team,Date,#OPA,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,AvgDist,Match Report
0,1,Barcelona,2024-11-23,12,@,Celta Vigo,es La Liga,D 2-2,2,2,0,59,2,0,0,0,23.7,Match Report
1,2,Como,2025-03-29,12,NaN,Empoli,it Serie A,D 1-1,1,1,0,71,1,0,0,0,23.3,Match Report
2,3,Barcelona,2024-12-21,9,NaN,Atlético Madrid,es La Liga,L 1-2,1,2,-1,62,1,0,0,0,25.7,Match Report
3,4,Barcelona,2024-12-15,9,NaN,Leganés,es La Liga,L 0-1,0,1,-1,79,0,0,0,0,29.3,Match Report
4,5,Barcelona,2024-11-10,9,@,Real Sociedad,es La Liga,L 0-1,0,1,-1,69,0,0,0,0,30.8,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-10-26,0,@,Napoli,it Serie A,L 0-1,0,1,-1,36,0,0,0,0,7.0,Match Report
2838,2839,Lecce,2024-10-05,0,@,Udinese,it Serie A,L 0-1,0,1,-1,45,0,0,0,0,3.0,Match Report
2839,2840,Lecce,2024-09-21,0,NaN,Parma,it Serie A,D 2-2,2,2,0,39,2,0,0,0,4.5,Match Report
2840,2841,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,0,47,0,0,0,0,7.0,Match Report
2841,2842,Lecce,2024-08-24,0,@,Inter,it Serie A,L 0-2,0,2,-2,39,0,0,0,0,5.9,Match Report

In [14]:
df_Pas= pd.read_csv("../Data/Passing.csv")
df_Pas = df_Pas.rename(columns={"Cmp.2": "Cmp 5-15", "Att.1": "Att 5-15", "Cmp%.1": "Cmp% 5-15", 
                                "Cmp.3": "Cmp 15-30", "Att.2": "Att 15-30", "Cmp%.2": "Cmp% 15-30",
                                "Cmp.4": "Cmp 30+", "Att.3": "Att 30+", "Cmp%.3": "Cmp% 30+",
                                "1/3": "Last3rd PA", 
                                "PrgDist": "PrgDist Pas", 
                                "TotDist": "TotDist Pas", 
                                "Att": "Pas Att"})
df_Pas = df_Pas.drop(columns=["Cmp.1"])
df_Pas

,Rk,Team,Date,Cmp,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Cmp 5-15,Att 5-15,Cmp% 5-15,Cmp 15-30,Att 15-30,Cmp% 15-30,Cmp 30+,Att 30+,Cmp% 30+,Match Report
0,1,Paris S-G,2024-11-30,973,NaN,Nantes,fr Ligue 1,D 1-1,1,1,...,453,488,92.8,448,483,92.8,53,69,76.8,Match Report
1,2,Bayern Munich,2024-12-07,949,NaN,Heidenheim,de Bundesliga,W 4-2,4,2,...,510,531,96.0,342,364,94.0,66,86,76.7,Match Report
2,3,Paris S-G,2025-04-05,914,NaN,Angers,fr Ligue 1,W 1-0,1,0,...,483,507,95.3,364,389,93.6,48,58,82.8,Match Report
3,4,Leverkusen,2024-11-23,897,NaN,Heidenheim,de Bundesliga,W 5-2,5,2,...,508,533,95.3,333,362,92.0,30,53,56.6,Match Report
4,5,Bayern Munich,2025-02-07,883,NaN,Werder Bremen,de Bundesliga,W 3-0,3,0,...,503,520,96.7,312,330,94.5,54,73,74.0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Newcastle Utd,2024-08-17,128,NaN,Southampton,eng Premier League,W 1-0,1,0,...,72,93,77.4,36,53,67.9,15,50,30.0,Match Report
2838,2839,Getafe,2025-01-18,126,NaN,Barcelona,es La Liga,D 1-1,1,1,...,45,68,66.2,53,74,71.6,23,56,41.1,Match Report
2839,2840,Reims,2025-03-29,124,NaN,Marseille,fr Ligue 1,W 3-1,3,1,...,43,59,72.9,60,81,74.1,21,68,30.9,Match Report
2840,2841,Union Berlin,2025-03-15,108,NaN,Bayern Munich,de Bundesliga,D 1-1,1,1,...,42,63,66.7,29,57,50.9,23,55,41.8,Match Report
2841,2842,Getafe,2024-09-25,103,@,Barcelona,es La Liga,L 0-1,0,1,...,50,70,71.4,30,53,56.6,19,58,32.8,Match Report

In [15]:
df_PkA= pd.read_csv("../Data/PKs (GK).csv")
df_PkA = df_PkA.drop(columns=["PKatt.1", "PKm.1"])
df_PkA = df_PkA.rename(columns={"PKatt.2": "PKdef",
                                "Save%": "Missed PK%", 
                                "PKsv": "PKms"})
df_PkA

,Rk,Team,Date,PKatt,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKm,PKdef,PKA,PKms,Missed PK%,Match Report
0,1,Wolves,2024-11-30,3,NaN,Bournemouth,eng Premier League,L 2-4,2,4,-2,60,2,0,0,3,3,0,0.0,Match Report
1,2,Udinese,2025-01-26,2,NaN,Roma,it Serie A,L 1-2,1,2,-1,49,1,0,0,2,2,0,0.0,Match Report
2,3,Udinese,2024-10-30,2,@,Venezia,it Serie A,L 2-3,2,3,-1,43,2,0,0,2,2,0,0.0,Match Report
3,4,Augsburg,2024-11-22,2,@,Bayern Munich,de Bundesliga,L 0-3,0,3,-3,20,0,0,0,2,2,0,0.0,Match Report
4,5,Montpellier,2024-12-01,2,NaN,Lille,fr Ligue 1,D 2-2,2,2,0,42,2,0,0,2,2,0,0.0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-10-05,0,@,Udinese,it Serie A,L 0-1,0,1,-1,45,0,0,0,0,0,0,NaN,Match Report
2838,2839,Lecce,2024-09-27,0,@,Milan,it Serie A,L 0-3,0,3,-3,43,0,0,0,0,0,0,NaN,Match Report
2839,2840,Lecce,2024-09-21,0,NaN,Parma,it Serie A,D 2-2,2,2,0,39,2,0,0,0,0,0,NaN,Match Report
2840,2841,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,0,47,0,0,0,0,0,0,NaN,Match Report
2841,2842,Lecce,2024-08-31,0,NaN,Cagliari,it Serie A,W 1-0,1,0,1,35,1,0,0,0,0,0,NaN,Match Report

In [16]:
df_PkD= pd.read_csv("../Data/Goals Allowed (GK).csv")
df_PkD = df_PkD.drop(columns=["PKA.1", "PKA.2", "PKatt.1", "PKm.1"])
df_PkD = df_PkD.rename(columns={"PKA": "PKAg",
                                "Save%": "PK Save%", 
                                "FK": "FK Ag",
                                "CK": "CKG",
                                "OG": "OGK"})
df_PkD

,Rk,Team,Date,PKAg,Unnamed: 4,Opp,Comp,Result,GF,GA,...,G-PK,PK,PKatt,PKm,PKsv,PK Save%,FK Ag,CKG,OGK,Match Report
0,1,Wolves,2024-11-30,3,NaN,Bournemouth,eng Premier League,L 2-4,2,4,...,2,0,0,0,0,0.0,0,0,0,Match Report
1,2,Udinese,2025-01-26,2,NaN,Roma,it Serie A,L 1-2,1,2,...,1,0,0,0,0,0.0,0,0,0,Match Report
2,3,Udinese,2024-10-30,2,@,Venezia,it Serie A,L 2-3,2,3,...,2,0,0,0,0,0.0,1,0,0,Match Report
3,4,Augsburg,2024-11-22,2,@,Bayern Munich,de Bundesliga,L 0-3,0,3,...,0,0,0,0,0,0.0,0,0,0,Match Report
4,5,Montpellier,2024-12-01,2,NaN,Lille,fr Ligue 1,D 2-2,2,2,...,2,0,0,0,0,0.0,0,0,0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lecce,2024-10-05,0,@,Udinese,it Serie A,L 0-1,0,1,...,0,0,0,0,0,NaN,1,0,0,Match Report
2838,2839,Lecce,2024-09-27,0,@,Milan,it Serie A,L 0-3,0,3,...,0,0,0,0,0,NaN,0,0,0,Match Report
2839,2840,Lecce,2024-09-21,0,NaN,Parma,it Serie A,D 2-2,2,2,...,2,0,0,0,0,NaN,0,1,0,Match Report
2840,2841,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,...,0,0,0,0,0,NaN,0,0,0,Match Report
2841,2842,Lecce,2024-08-31,0,NaN,Cagliari,it Serie A,W 1-0,1,0,...,1,0,0,0,0,NaN,0,0,0,Match Report

In [17]:
df_PsT= pd.read_csv("../Data/Pass Types.csv")
df_PsT = df_PsT.rename(columns={"Live": "Live Pas",
                                "FK": "Pas FK",
                                "Off": "Ps Off",
                                "Blocks": "PTo"})
df_PsT = df_PsT.drop(columns=["Live.1"])
df_PsT

,Rk,Team,Date,Live Pas,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Sw,Crs,TI,CK,In,Out,Str,Ps Off,PTo,Match Report
0,1,Paris S-G,2024-11-30,1032,NaN,Nantes,fr Ligue 1,D 1-1,1,1,...,3,43,27,9,4,4,0,1,13,Match Report
1,2,Bayern Munich,2024-12-07,1000,NaN,Heidenheim,de Bundesliga,W 4-2,4,2,...,1,25,20,8,1,5,0,1,14,Match Report
2,3,Leverkusen,2024-11-23,952,NaN,Heidenheim,de Bundesliga,W 5-2,5,2,...,3,23,20,6,5,0,0,0,16,Match Report
3,4,Paris S-G,2025-04-05,948,NaN,Angers,fr Ligue 1,W 1-0,1,0,...,8,16,18,5,1,1,0,1,11,Match Report
4,5,Bayern Munich,2025-02-07,921,NaN,Werder Bremen,de Bundesliga,W 3-0,3,0,...,6,16,20,5,3,0,0,3,10,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Hellas Verona,2025-02-15,170,@,Milan,it Serie A,L 0-1,0,1,...,1,14,17,7,3,3,0,2,5,Match Report
2838,2839,Union Berlin,2025-03-15,170,NaN,Bayern Munich,de Bundesliga,D 1-1,1,1,...,1,15,9,2,1,1,0,1,4,Match Report
2839,2840,Reims,2025-03-29,170,NaN,Marseille,fr Ligue 1,W 3-1,3,1,...,2,2,9,0,0,0,0,1,2,Match Report
2840,2841,Newcastle Utd,2024-08-17,163,NaN,Southampton,eng Premier League,W 1-0,1,0,...,1,12,11,3,3,0,0,1,6,Match Report
2841,2842,Getafe,2024-09-25,158,@,Barcelona,es La Liga,L 0-1,0,1,...,2,18,17,5,2,1,0,7,8,Match Report

In [18]:
df_Rec= pd.read_csv("../Data/Receiving.csv")
df_Rec = df_Rec.rename(columns={"1/3": "Last3rd Rec"})
df_Rec = df_Rec.drop(columns=["Rec.1", "PrgR", "Carries", "TotDist", "PrgDist", "PrgC"])
df_Rec

,Rk,Team,Date,Rec,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Poss,G-PK,PK,PKatt,PKm,Last3rd Rec,CPA,Mis,Dis,Match Report
0,1,Paris S-G,2024-11-30,967,NaN,Nantes,fr Ligue 1,D 1-1,1,1,...,84,1,0,0,0,29,13,12,18,Match Report
1,2,Bayern Munich,2024-12-07,946,NaN,Heidenheim,de Bundesliga,W 4-2,4,2,...,82,4,0,0,0,22,6,14,6,Match Report
2,3,Paris S-G,2025-04-05,912,NaN,Angers,fr Ligue 1,W 1-0,1,0,...,81,1,0,0,0,41,14,8,12,Match Report
3,4,Leverkusen,2024-11-23,890,NaN,Heidenheim,de Bundesliga,W 5-2,5,2,...,78,5,0,0,0,38,9,7,13,Match Report
4,5,Bayern Munich,2025-02-07,878,NaN,Werder Bremen,de Bundesliga,W 3-0,3,0,...,75,1,2,2,0,28,6,12,9,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Newcastle Utd,2024-08-17,127,NaN,Southampton,eng Premier League,W 1-0,1,0,...,23,1,0,0,0,6,1,10,8,Match Report
2838,2839,Getafe,2025-01-18,126,NaN,Barcelona,es La Liga,D 1-1,1,1,...,23,1,0,0,0,6,1,20,4,Match Report
2839,2840,Reims,2025-03-29,121,NaN,Marseille,fr Ligue 1,W 3-1,3,1,...,20,3,0,0,0,2,3,17,7,Match Report
2840,2841,Union Berlin,2025-03-15,108,NaN,Bayern Munich,de Bundesliga,D 1-1,1,1,...,20,1,0,0,0,5,4,9,9,Match Report
2841,2842,Getafe,2024-09-25,102,@,Barcelona,es La Liga,L 0-1,0,1,...,24,0,0,0,0,10,5,14,5,Match Report

In [19]:
df_ScA= pd.read_csv("../Data/Shot-Creating Actions.csv")
df_ScA = df_ScA.rename(columns={"PassLive": "PassLive Sc",
                                         "PassDead": "PassDead Sc",
                                         "TO": "TO Sc",
                                         "Sh": "Sh-Sh", 
                                         "Fld": "Fld Sc",
                                         "Def": "Def-Sc"})
df_ScA = df_ScA.drop(columns=["SCA.1"])
df_ScA

,Rk,Team,Date,SCA,Unnamed: 4,Opp,Comp,Result,GF,GA,...,PK,PKatt,PKm,PassLive Sc,PassDead Sc,TO Sc,Sh-Sh,Fld Sc,Def-Sc,Match Report
0,1,Liverpool,2025-01-18,68,@,Brentford,eng Premier League,W 2-0,2,0,...,0,0,0,55,5,2,6,0,0,Match Report
1,2,Manchester City,2024-09-22,64,NaN,Arsenal,eng Premier League,D 2-2,2,2,...,0,0,0,55,1,3,3,1,1,Match Report
2,3,Bayern Munich,2024-11-22,61,NaN,Augsburg,de Bundesliga,W 3-0,3,0,...,2,2,0,47,0,7,3,3,1,Match Report
3,4,Arsenal,2024-09-28,58,NaN,Leicester City,eng Premier League,W 4-2,4,2,...,0,0,0,44,3,2,6,1,2,Match Report
4,5,Barcelona,2025-03-02,58,NaN,Real Sociedad,es La Liga,W 4-0,4,0,...,0,0,0,46,1,3,5,2,1,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lyon,2024-08-24,2,NaN,Monaco,fr Ligue 1,L 0-2,0,2,...,0,0,0,2,0,0,0,0,0,Match Report
2838,2839,Valencia,2024-10-27,1,@,Getafe,es La Liga,D 1-1,1,1,...,0,0,0,0,0,0,0,0,1,Match Report
2839,2840,Real Sociedad,2024-09-01,1,@,Getafe,es La Liga,D 0-0,0,0,...,0,0,0,0,1,0,0,0,0,Match Report
2840,2841,Werder Bremen,2024-09-21,0,NaN,Bayern Munich,de Bundesliga,L 0-5,0,5,...,0,0,0,0,0,0,0,0,0,Match Report
2841,2842,Real Sociedad,2025-03-02,0,@,Barcelona,es La Liga,L 0-4,0,4,...,0,0,0,0,0,0,0,0,0,Match Report

In [20]:
df_ShA= pd.read_csv("../Data/Basic (GK).csv")
df_ShA = df_ShA.drop(columns=["SoTA.1"])
df_ShA

,Rk,Team,Date,SoTA,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,Saves,Save%,Match Report
0,1,Valladolid,2025-02-23,16,@,Athletic Club,es La Liga,L 1-7,1,7,-6,43,1,0,0,0,9,56.3,Match Report
1,2,Leicester City,2024-09-28,16,@,Arsenal,eng Premier League,L 2-4,2,4,-2,26,2,0,0,0,13,75.0,Match Report
2,3,Augsburg,2024-11-22,14,@,Bayern Munich,de Bundesliga,L 0-3,0,3,-3,20,0,0,0,0,11,92.9,Match Report
3,4,Espanyol,2024-09-21,14,@,Real Madrid,es La Liga,L 1-4,1,4,-3,27,0,0,0,0,10,78.6,Match Report
4,5,Las Palmas,2025-01-19,13,@,Real Madrid,es La Liga,L 1-4,1,4,-3,39,1,0,0,0,9,76.9,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Lens,2025-01-26,0,NaN,Angers,fr Ligue 1,W 1-0,1,0,1,64,1,0,0,0,0,NaN,Match Report
2838,2839,Monaco,2024-12-14,0,@,Reims,fr Ligue 1,D 0-0,0,0,0,64,0,0,0,0,0,NaN,Match Report
2839,2840,Monaco,2024-08-24,0,@,Lyon,fr Ligue 1,W 2-0,2,0,2,60,2,0,0,0,0,NaN,Match Report
2840,2841,Lecce,2024-12-15,0,NaN,Monza,it Serie A,W 2-1,2,1,1,45,2,0,1,1,0,NaN,Match Report
2841,2842,Lecce,2024-09-15,0,@,Torino,it Serie A,D 0-0,0,0,0,47,0,0,0,0,0,NaN,Match Report

In [21]:
df_Tch= pd.read_csv("../Data/Touches.csv")
df_Tch = df_Tch.rename(columns={"Def 3rd": "Tch Def 3rd",
                                "Mid 3rd": "Tch Mid 3rd",
                                "Att 3rd": "Tch Att 3rd",
                                "Live": "Live Tch"})
df_Tch = df_Tch.drop(columns=["Touches.1"])
df_Tch

,Rk,Team,Date,Touches,Unnamed: 4,Opp,Comp,Result,GF,GA,...,PK,PKatt,PKm,Def Pen,Tch Def 3rd,Tch Mid 3rd,Tch Att 3rd,Att Pen,Live Tch,Match Report
0,1,Paris S-G,2024-11-30,1188,NaN,Nantes,fr Ligue 1,D 1-1,1,1,...,0,0,0,40,113,607,472,59,1188,Match Report
1,2,Bayern Munich,2024-12-07,1134,NaN,Heidenheim,de Bundesliga,W 4-2,4,2,...,0,0,0,13,85,700,358,37,1134,Match Report
2,3,Paris S-G,2025-04-05,1082,NaN,Angers,fr Ligue 1,W 1-0,1,0,...,0,0,0,30,110,606,375,44,1082,Match Report
3,4,Leverkusen,2024-11-23,1073,NaN,Heidenheim,de Bundesliga,W 5-2,5,2,...,0,0,0,34,104,625,352,41,1073,Match Report
4,5,Bayern Munich,2025-02-07,1046,NaN,Werder Bremen,de Bundesliga,W 3-0,3,0,...,2,2,0,25,159,538,354,35,1044,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Parma,2025-02-22,329,NaN,Bologna,it Serie A,W 2-0,2,0,...,1,1,0,75,193,101,43,9,328,Match Report
2838,2839,Torino,2024-10-05,328,@,Inter,it Serie A,L 2-3,2,3,...,1,1,0,91,173,114,41,6,327,Match Report
2839,2840,Getafe,2024-09-25,327,@,Barcelona,es La Liga,L 0-1,0,1,...,0,0,0,58,132,122,77,14,327,Match Report
2840,2841,Hellas Verona,2025-02-15,326,@,Milan,it Serie A,L 0-1,0,1,...,0,0,0,63,135,119,77,8,326,Match Report
2841,2842,Newcastle Utd,2024-08-17,317,NaN,Southampton,eng Premier League,W 1-0,1,0,...,0,0,0,84,150,101,72,12,317,Match Report

In [22]:
df_Tkl= pd.read_csv("../Data/Defensive Actions.csv")
df_Tkl = df_Tkl.drop(columns=["Tkl.1"])
df_Tkl = df_Tkl.rename(columns={"Def 3rd": "Tkl Def 3rd",
                                "Mid 3rd": "Tkl Mid 3rd",
                                "Att 3rd": "Tkl Att 3rd",
                                "Lost": "Lost Tkl",
                                "Blocks": "Ints",
                                "Sh": "BlcSh", 
                                "Att": "Tkl Att"})
df_Tkl

,Rk,Team,Date,Tkl,Unnamed: 4,Opp,Comp,Result,GF,GA,...,Tkl%,Lost Tkl,Ints,BlcSh,Pass,Int,Tkl+Int,Clr,Err,Match Report
0,1,Leicester City,2024-12-03,35,NaN,West Ham,eng Premier League,W 3-1,3,1,...,50.0,20,22,13,9,12,47,34,1,Match Report
1,2,Southampton,2025-02-01,34,@,Ipswich Town,eng Premier League,W 2-1,2,1,...,46.9,17,13,3,10,10,44,28,0,Match Report
2,3,Brest,2025-01-18,34,@,Rennes,fr Ligue 1,W 2-1,2,1,...,38.9,22,14,5,9,14,48,39,1,Match Report
3,4,Lecce,2024-11-02,34,@,Bologna,it Serie A,L 0-1,0,1,...,86.7,2,15,6,9,3,37,33,0,Match Report
4,5,Manchester Utd,2024-11-10,33,NaN,Leicester City,eng Premier League,W 3-0,3,0,...,44.1,19,6,0,6,7,40,20,0,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Las Palmas,2024-09-30,4,@,Villarreal,es La Liga,L 1-3,1,3,...,36.4,7,11,6,5,6,10,21,1,Match Report
2838,2839,Athletic Club,2024-09-19,4,@,Leganés,es La Liga,W 2-0,2,0,...,20.0,4,5,1,4,14,18,23,1,Match Report
2839,2840,Fiorentina,2025-02-06,4,NaN,Inter,it Serie A,W 3-0,3,0,...,40.0,3,15,4,11,6,10,28,0,Match Report
2840,2841,Fiorentina,2024-10-31,3,@,Genoa,it Serie A,W 1-0,1,0,...,25.0,3,11,4,7,6,9,31,2,Match Report
2841,2842,RB Leipzig,2024-11-30,3,NaN,Wolfsburg,de Bundesliga,L 1-5,1,5,...,20.0,8,14,3,11,9,12,12,2,Match Report

In [23]:
df_xG= pd.read_csv("../Data/Expected Stats.csv")
df_xG = df_xG.drop(columns=["xG.1", "Sh", "G/Sh", "G/SoT", "SoT", "SoT%", "Dist"])
df_xG = df_xG.rename(columns={"FK": "FKAtt"})
df_xG

,Rk,Team,Date,xG,Unnamed: 4,Opp,Comp,Result,GF,GA,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,Match Report
0,1,Marseille,2025-02-15,6.1,NaN,Saint-Étienne,fr Ligue 1,W 5-1,5,1,...,5.0,4.2,4.6,4.2,-1.1,-1.3,-1.6,0.22,0,Match Report
1,2,Real Madrid,2025-01-19,5.9,NaN,Las Palmas,es La Liga,W 4-1,4,1,...,4.8,4.0,4.9,3.7,-1.9,-2.1,-1.9,0.21,0,Match Report
2,3,Liverpool,2024-12-22,5.6,@,Tottenham,eng Premier League,W 6-3,6,3,...,4.3,4.3,3.9,2.6,0.4,0.4,0.1,0.26,0,Match Report
3,4,Roma,2024-12-22,5.4,NaN,Parma,it Serie A,W 5-0,5,0,...,5.0,3.4,3.8,2.3,-0.4,-0.8,-0.8,0.23,1,Match Report
4,5,Chelsea,2024-12-04,5.2,@,Southampton,eng Premier League,W 5-1,5,1,...,3.6,3.6,3.8,2.2,-0.2,-0.2,1.2,0.21,1,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Werder Bremen,2024-09-21,0.0,NaN,Bayern Munich,de Bundesliga,L 0-5,0,5,...,-3.0,-3.0,0.0,0.2,0.0,0.0,0.0,NaN,0,Match Report
2838,2839,Newcastle Utd,2024-11-30,0.0,@,Crystal Palace,eng Premier League,D 1-1,1,1,...,-1.7,-1.7,0.0,0.2,0.0,0.0,0.0,0.04,0,Match Report
2839,2840,Lyon,2024-08-24,0.0,NaN,Monaco,fr Ligue 1,L 0-2,0,2,...,-2.2,-2.2,0.0,0.3,0.0,0.0,0.0,0.03,0,Match Report
2840,2841,Real Sociedad,2025-03-02,0.0,@,Barcelona,es La Liga,L 0-4,0,4,...,-2.8,-2.8,0.0,0.1,0.0,0.0,0.0,NaN,0,Match Report
2841,2842,Real Sociedad,2024-09-01,0.0,@,Getafe,es La Liga,D 0-0,0,0,...,-0.5,-0.5,0.0,0.0,0.0,0.0,0.0,0.02,0,Match Report

In [24]:
df_xGK= pd.read_csv("../Data/Expected Stats (GK).csv")
df_xGK = df_xGK.drop(columns=["PSxG.1"])
df_xGK

,Rk,Team,Date,PSxG,Unnamed: 4,Opp,Comp,Result,GF,GA,GD,Poss,G-PK,PK,PKatt,PKm,PSxG/SoT,PSxG+/-,Match Report
0,1,Valladolid,2024-11-30,5.9,NaN,Atlético Madrid,es La Liga,L 0-5,0,5,-5,45,0,0,0,0,0.67,0.9,Match Report
1,2,Valladolid,2025-02-23,5.8,@,Athletic Club,es La Liga,L 1-7,1,7,-6,43,1,0,0,0,0.37,-1.2,Match Report
2,3,Hoffenheim,2025-01-15,5.6,@,Bayern Munich,de Bundesliga,L 0-5,0,5,-5,35,0,0,0,0,0.48,0.6,Match Report
3,4,Angers,2025-03-02,5.6,NaN,Toulouse,fr Ligue 1,L 0-4,0,4,-4,46,0,0,0,0,0.49,1.6,Match Report
4,5,Holstein Kiel,2025-02-01,5.5,@,Bayern Munich,de Bundesliga,L 3-4,3,4,-1,29,3,0,0,0,0.50,1.5,Match Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2838,Fulham,2024-12-22,0.0,NaN,Southampton,eng Premier League,D 0-0,0,0,0,57,0,0,0,0,0.04,0.0,Match Report
2838,2839,Fulham,2024-09-28,0.0,@,Nott'ham Forest,eng Premier League,W 1-0,1,0,1,59,0,1,1,0,0.01,0.0,Match Report
2839,2840,Lecce,2024-12-15,0.0,NaN,Monza,it Serie A,W 2-1,2,1,1,45,2,0,1,1,NaN,0.0,Match Report
2840,2841,Lecce,2024-10-29,0.0,NaN,Hellas Verona,it Serie A,W 1-0,1,0,1,58,1,0,0,0,0.03,0.0,Match Report
2841,2842,Lecce,2024-09-15,0.0,@,Torino,it Serie A,D 0-0,0,0,0,47,0,0,0,0,NaN,0.0,Match Report

In [25]:
dfs= [df_AGK, df_ArW, df_AtD, df_Car, df_CrA, df_Crd, df_GcA, df_GKA, df_Gls, df_Misc, df_OPA, df_Pas, df_PkA, df_PkD, 
      df_PsT, df_Rec, df_ScA, df_ShA, df_Tch, df_Tkl, df_xG, df_xGK]#df_Tkl
common_cols = set(dfs[0].columns)
df_AGK.sort_values(by=["Team", "Opp", "Date"], inplace= True)
df_AGK.reset_index(drop=True, inplace= True) 
for df in dfs[1:]:
    df.sort_values(by=["Team", "Opp", "Date"], inplace=True)
    df.reset_index(drop=True, inplace= True)
    common_cols &= set(df.columns)
common_cols = list(common_cols)  # Convert to list
common_cols

['Date',
 'PK',
 'PKm',
 'G-PK',
 'GF',
 'Poss',
 'Match Report',
 'GD',
 'GA',
 'Result',
 'Rk',
 'Unnamed: 4',
 'PKatt',
 'Comp',
 'Opp',
 'Team']

In [26]:
df_cols= df_ArW[common_cols]
for df in dfs:
    df.drop(columns=common_cols, inplace= True)
dfs.append(df_cols)

In [27]:
df_Teams_Games= pd.concat([df for df in dfs], axis=1)
df_Teams_Games

,Att (GK),Thr,Pa Launch%,Pa AvgLen,Won,Lost,Won%,Att To,Succ,Succ%,...,Match Report,GD,GA,Result,Rk,Unnamed: 4,PKatt,Comp,Opp,Team
0,42,4,52.4,36.8,17,16,51.5,15,6,40.0,...,Match Report,0,1,D 1-1,758,NaN,0,es La Liga,Athletic Club,Alavés
1,32,5,62.5,47.7,17,13,56.7,10,3,30.0,...,Match Report,-1,2,L 1-2,759,@,1,es La Liga,Atlético Madrid,Alavés
2,20,4,85.0,54.9,10,7,58.8,15,5,33.3,...,Match Report,-3,3,L 0-3,1999,NaN,0,es La Liga,Barcelona,Alavés
3,14,3,57.1,48.2,18,17,51.4,9,3,33.3,...,Match Report,-1,1,L 0-1,611,@,0,es La Liga,Barcelona,Alavés
4,18,1,66.7,44.7,9,14,39.1,17,6,35.3,...,Match Report,0,0,D 0-0,2196,NaN,0,es La Liga,Betis,Alavés
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,21,5,38.1,37.0,5,8,38.5,25,12,48.0,...,Match Report,2,0,W 2-0,2713,NaN,0,eng Premier League,Southampton,Wolves
2838,19,3,63.2,45.5,14,12,53.8,13,4,30.8,...,Match Report,1,1,W 2-1,1238,@,0,eng Premier League,Southampton,Wolves
2839,29,2,65.5,43.4,8,14,36.4,16,5,31.3,...,Match Report,0,2,D 2-2,2349,@,0,eng Premier League,Tottenham,Wolves
2840,34,2,70.6,45.0,24,20,54.5,12,8,66.7,...,Match Report,-1,2,L 1-2,155,@,0,eng Premier League,West Ham,Wolves
2841,21,4,52.4,44.3,9,11,45.0,21,8,38.1,...,Match Report,1,0,W 1-0,2193,NaN,0,eng Premier League,West Ham,Wolves

In [28]:
cols = common_cols + [col for col in df_Teams_Games.columns if col not in common_cols]
df1= df_Teams_Games[cols]
df1

,Date,PK,PKm,G-PK,GF,Poss,Match Report,GD,GA,Result,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,2024-12-15,0,0,1,1,52,Match Report,0,1,D 1-1,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,2024-11-23,1,0,0,1,30,Match Report,-1,2,L 1-2,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,2024-10-06,0,0,0,0,29,Match Report,-3,3,L 0-3,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,2025-02-02,0,0,0,0,31,Match Report,-1,1,L 0-1,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,2024-08-25,0,0,0,0,38,Match Report,0,0,D 0-0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,2024-11-09,0,0,2,2,29,Match Report,2,0,W 2-0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,2025-03-15,0,0,2,2,40,Match Report,1,1,W 2-1,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,2024-12-29,0,0,2,2,52,Match Report,0,2,D 2-2,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,2024-12-09,0,0,1,1,46,Match Report,-1,2,L 1-2,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,2025-04-01,0,0,1,1,42,Match Report,1,0,W 1-0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [29]:
id= ["Team", "Opp", "Date", "Result", "Unnamed: 4", "GF", "GA", "GD"]
cols2= id+ [col for col in df1.columns if not(col in id)]
df2= df1[cols2].copy()
df2

,Team,Opp,Date,Result,Unnamed: 4,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Alavés,Athletic Club,2024-12-15,D 1-1,NaN,1,1,0,0,0,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,Alavés,Atlético Madrid,2024-11-23,L 1-2,@,1,2,-1,1,0,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,Alavés,Barcelona,2024-10-06,L 0-3,NaN,0,3,-3,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,Alavés,Barcelona,2025-02-02,L 0-1,@,0,1,-1,0,0,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,Alavés,Betis,2024-08-25,D 0-0,NaN,0,0,0,0,0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,Wolves,Southampton,2024-11-09,W 2-0,NaN,2,0,2,0,0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,Wolves,Southampton,2025-03-15,W 2-1,@,2,1,1,0,0,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,Wolves,Tottenham,2024-12-29,D 2-2,@,2,2,0,0,0,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,Wolves,West Ham,2024-12-09,L 1-2,@,1,2,-1,0,0,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,Wolves,West Ham,2025-04-01,W 1-0,NaN,1,0,1,0,0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [30]:
cols_to_delete= ["Match Report", "Rk"]
df2["Date"] = pd.to_datetime(df2["Date"], format="%Y-%m-%d")
df3 = df2.drop(columns= cols_to_delete)
df3

,Team,Opp,Date,Result,Unnamed: 4,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Alavés,Athletic Club,2024-12-15,D 1-1,NaN,1,1,0,0,0,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,Alavés,Atlético Madrid,2024-11-23,L 1-2,@,1,2,-1,1,0,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,Alavés,Barcelona,2024-10-06,L 0-3,NaN,0,3,-3,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,Alavés,Barcelona,2025-02-02,L 0-1,@,0,1,-1,0,0,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,Alavés,Betis,2024-08-25,D 0-0,NaN,0,0,0,0,0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,Wolves,Southampton,2024-11-09,W 2-0,NaN,2,0,2,0,0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,Wolves,Southampton,2025-03-15,W 2-1,@,2,1,1,0,0,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,Wolves,Tottenham,2024-12-29,D 2-2,@,2,2,0,0,0,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,Wolves,West Ham,2024-12-09,L 1-2,@,1,2,-1,0,0,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,Wolves,West Ham,2025-04-01,W 1-0,NaN,1,0,1,0,0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [31]:
df4 = df3.rename(columns={"Unnamed: 4": "H/A"})
df4

,Team,Opp,Date,Result,H/A,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Alavés,Athletic Club,2024-12-15,D 1-1,NaN,1,1,0,0,0,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,Alavés,Atlético Madrid,2024-11-23,L 1-2,@,1,2,-1,1,0,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,Alavés,Barcelona,2024-10-06,L 0-3,NaN,0,3,-3,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,Alavés,Barcelona,2025-02-02,L 0-1,@,0,1,-1,0,0,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,Alavés,Betis,2024-08-25,D 0-0,NaN,0,0,0,0,0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,Wolves,Southampton,2024-11-09,W 2-0,NaN,2,0,2,0,0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,Wolves,Southampton,2025-03-15,W 2-1,@,2,1,1,0,0,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,Wolves,Tottenham,2024-12-29,D 2-2,@,2,2,0,0,0,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,Wolves,West Ham,2024-12-09,L 1-2,@,1,2,-1,0,0,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,Wolves,West Ham,2025-04-01,W 1-0,NaN,1,0,1,0,0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [32]:
df4["H/A"] = df4["H/A"].fillna("H").replace("@", "A")
df4

,Team,Opp,Date,Result,H/A,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Alavés,Athletic Club,2024-12-15,D 1-1,H,1,1,0,0,0,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,Alavés,Atlético Madrid,2024-11-23,L 1-2,A,1,2,-1,1,0,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,Alavés,Barcelona,2024-10-06,L 0-3,H,0,3,-3,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,Alavés,Barcelona,2025-02-02,L 0-1,A,0,1,-1,0,0,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,Alavés,Betis,2024-08-25,D 0-0,H,0,0,0,0,0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,Wolves,Southampton,2024-11-09,W 2-0,H,2,0,2,0,0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,Wolves,Southampton,2025-03-15,W 2-1,A,2,1,1,0,0,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,Wolves,Tottenham,2024-12-29,D 2-2,A,2,2,0,0,0,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,Wolves,West Ham,2024-12-09,L 1-2,A,1,2,-1,0,0,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,Wolves,West Ham,2025-04-01,W 1-0,H,1,0,1,0,0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [33]:
df4["Result"] = df4["Result"].str[0]
df4

,Team,Opp,Date,Result,H/A,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Alavés,Athletic Club,2024-12-15,D,H,1,1,0,0,0,...,0.2,0.4,0.1,0.1,-0.2,0.16,0,0.9,0.47,-0.1
1,Alavés,Atlético Madrid,2024-11-23,L,A,1,2,-1,1,0,...,0.0,0.2,0.1,-0.1,0.0,0.02,0,2.3,0.18,0.3
2,Alavés,Barcelona,2024-10-06,L,H,0,3,-3,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.07,0,3.9,0.46,0.9
3,Alavés,Barcelona,2025-02-02,L,A,0,1,-1,0,0,...,0.1,0.1,-0.1,-0.1,-0.1,0.03,0,1.2,0.43,0.2
4,Alavés,Betis,2024-08-25,D,H,0,0,0,0,0,...,0.1,0.3,-0.2,-0.2,-0.1,0.04,0,0.4,0.13,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2837,Wolves,Southampton,2024-11-09,W,H,2,0,2,0,0,...,1.2,0.6,0.7,0.7,0.8,0.16,0,0.0,NaN,0.0
2838,Wolves,Southampton,2025-03-15,W,A,2,1,1,0,0,...,0.4,0.3,1.6,1.6,1.6,0.07,0,1.8,0.62,0.8
2839,Wolves,Tottenham,2024-12-29,D,A,2,2,0,0,0,...,0.6,0.5,1.3,1.3,1.4,0.07,1,1.3,0.24,-0.7
2840,Wolves,West Ham,2024-12-09,L,A,1,2,-1,0,0,...,1.1,0.6,-0.4,-0.4,-0.1,0.08,0,0.4,0.11,-1.6
2841,Wolves,West Ham,2025-04-01,W,H,1,0,1,0,0,...,1.1,0.6,-0.2,-0.2,-1.1,0.13,1,0.2,0.22,0.2

In [34]:
df4.sort_values(by="Date", inplace=True)
df4

,Team,Opp,Date,Result,H/A,GF,GA,GD,PK,PKm,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
993,Girona,Betis,2024-08-15,D,A,1,1,0,0,0,...,1.6,1.4,-0.6,-0.6,-0.6,0.12,0,1.3,0.34,0.3
958,Getafe,Athletic Club,2024-08-15,D,A,1,1,0,0,0,...,0.7,0.3,0.2,0.2,0.3,0.09,0,0.8,0.23,-0.2
337,Betis,Girona,2024-08-15,D,H,1,1,0,0,0,...,1.1,0.9,-0.4,-0.4,-0.1,0.07,0,1.0,0.49,0.0
161,Athletic Club,Getafe,2024-08-15,D,H,1,1,0,0,0,...,0.3,0.5,0.7,0.7,0.7,0.05,1,1.0,0.49,0.0
2024,Paris S-G,Le Havre,2024-08-16,W,A,4,1,3,1,0,...,2.0,1.1,1.1,0.9,1.0,0.15,0,0.2,0.09,-0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,Leicester City,Newcastle Utd,2025-04-07,L,H,0,3,-3,0,0,...,0.4,0.6,-0.5,-0.5,-0.4,0.06,0,2.9,0.59,-0.1
404,Bologna,Napoli,2025-04-07,D,H,1,1,0,0,0,...,0.6,0.8,0.2,0.2,0.4,0.07,0,1.6,0.80,0.6
1390,Leganés,Osasuna,2025-04-07,D,H,1,1,0,1,0,...,0.5,0.7,-0.7,-1.0,-0.5,0.08,1,2.0,0.33,1.0
2005,Osasuna,Leganés,2025-04-07,D,A,1,1,0,0,0,...,1.9,1.9,-1.2,-1.2,-0.9,0.18,0,2.7,0.26,1.7
1914,Newcastle Utd,Leicester City,2025-04-07,W,A,3,0,3,0,0,...,1.0,0.8,-0.2,-0.2,0.0,0.21,1,0.4,0.18,0.4

In [35]:
df_league = {comp_value: df4[df4["Comp"] == comp_value] for comp_value in df4["Comp"].unique()}

In [36]:
df_league.keys()
for league in df_league.keys():
    print(str(league)[3:])

La Liga
Ligue 1
 Premier League
Serie A
Bundesliga

In [37]:
for league in df_league.keys():
    df_league[league].to_csv(f"../../../{str(league)[3:].strip(' ')}/Teams/Data/Games.csv", index=False)