In [1]:
import pandas as pd

In [2]:
df_sh= pd.read_csv("../Data/Shooting.csv")
#df_sh.drop(columns=['MP'], inplace= True)
df_sh

,Rk,Team,Date,H/A,Opp,Result,MP,Tm_FG,Tm_FGA,Tm_FG%,...,Opp_2P,Opp_2PA,Opp_2P%,Opp_3P,Opp_3PA,Opp_3P%,Opp_FT,Opp_FTA,Opp_FT%,Opp_PTS
0,1,DEN,2025-02-10,NaN,POR,"W, 146-117",240,60,91,0.659,...,25,51,0.490,15,37,0.405,22,26,0.846,117
1,2,IND,2025-03-27,@,WAS,"W, 162-109",240,59,92,0.641,...,27,55,0.491,11,30,0.367,22,26,0.846,109
2,3,MEM,2024-12-26,NaN,TOR,"W, 155-126",240,58,109,0.532,...,35,65,0.538,14,43,0.326,14,18,0.778,126
3,4,SAS,2025-01-23,@,IND,"W, 140-110",240,58,96,0.604,...,31,54,0.574,13,43,0.302,9,12,0.750,110
4,5,DEN,2025-03-07,NaN,PHO,"W, 149-141 (OT)",265,57,97,0.588,...,35,53,0.660,16,38,0.421,23,29,0.793,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,MIA,2025-02-24,@,ATL,"L, 86-98",240,27,84,0.321,...,31,53,0.585,9,35,0.257,9,12,0.750,98
2290,2291,TOR,2024-12-31,@,BOS,"L, 71-125",240,27,86,0.314,...,25,44,0.568,22,43,0.512,9,15,0.600,125
2291,2292,ORL,2025-01-23,NaN,POR,"L, 79-101",240,26,76,0.342,...,31,54,0.574,9,28,0.321,12,19,0.632,101
2292,2293,BRK,2025-01-15,@,LAC,"L, 67-126",240,25,83,0.301,...,31,47,0.660,12,32,0.375,28,30,0.933,126
2293,2294,PHO,2024-11-15,@,OKC,"L, 83-99",240,22,75,0.293,...,26,51,0.510,10,40,0.250,17,18,0.944,99

In [3]:
df_rbd= pd.read_csv("../Data/Rebounding.csv")
df_rbd.drop(columns= ['MP'], inplace= True)
df_rbd

,Rk,Team,Date,H/A,Opp,Result,Tm_ORB,Tm_DRB,Tm_TRB,Opp_ORB,Opp_DRB,Opp_TRB
0,1,TOR,2025-03-10,NaN,WAS,"W, 119-104",28,45,73,16,38,54
1,2,UTA,2025-02-07,@,PHO,"L, 127-135 (OT)",25,38,63,12,37,49
2,3,HOU,2025-03-04,@,IND,"L, 102-115",24,34,58,5,30,35
3,4,MEM,2025-02-05,@,TOR,"W, 138-107",24,37,61,14,20,34
4,5,MEM,2024-12-26,NaN,TOR,"W, 155-126",24,39,63,13,27,40
...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,LAC,2025-03-21,NaN,MEM,"W, 128-108",2,41,43,10,30,40
2290,2291,ORL,2024-11-20,@,LAC,"L, 93-104",2,22,24,15,34,49
2291,2292,PHI,2024-11-18,@,MIA,"L, 89-106",2,40,42,9,44,53
2292,2293,PHO,2024-12-03,NaN,SAS,"W, 104-93",2,42,44,18,35,53
2293,2294,PHO,2025-01-20,@,CLE,"L, 92-118",1,33,34,15,35,50

In [4]:
df_bsc= pd.read_csv("../Data/Basic.csv")
df_bsc.drop(columns= ['MP'], inplace= True)
df_bsc

,Rk,Team,Date,H/A,Opp,Result,Tm_AST,Tm_STL,Tm_BLK,Tm_TOV,Tm_PF,Opp_AST,Opp_STL,Opp_BLK,Opp_TOV,Opp_PF
0,1,IND,2025-03-27,@,WAS,"W, 162-109",48,8,2,15,19,19,9,2,15,15
1,2,DEN,2025-03-07,NaN,PHO,"W, 149-141 (OT)",45,8,3,9,22,36,6,2,13,18
2,3,NYK,2024-11-25,@,DEN,"W, 145-118",45,5,4,11,23,23,5,3,11,18
3,4,DEN,2025-02-10,NaN,POR,"W, 146-117",44,12,2,10,23,25,4,4,16,20
4,5,DEN,2025-01-01,NaN,ATL,"W, 139-120",44,8,5,13,16,34,10,5,14,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,PHI,2025-03-14,NaN,IND,"L, 100-112",13,7,9,16,19,31,6,4,11,17
2290,2291,PHI,2024-12-21,@,CLE,"L, 99-126",13,7,3,13,16,31,8,1,13,18
2291,2292,POR,2024-11-08,@,MIN,"L, 102-127",13,11,7,17,17,32,9,7,20,21
2292,2293,LAC,2024-11-15,@,HOU,"L, 104-125",12,6,6,15,15,31,11,3,12,25
2293,2294,HOU,2025-01-03,NaN,BOS,"L, 86-109",9,6,4,14,21,20,6,8,14,13

In [5]:
df_adv_sh= pd.read_csv("../Data/Advanced Shooting.csv")
#df_bsc.drop(columns= ['MP'], inplace= True)
df_adv_sh

,Rk,Team,Date,H/A,Opp,Result,Tm_ORtg,Tm_DRtg,Tm_FTr,Tm_3PAr,Tm_TS%,Tm_eFG%,Tm_FT/FGA,Opp_ORtg,Opp_DRtg,Opp_FTr,Opp_3PAr,Opp_TS%,Opp_eFG%,Opp_FT/FGA
0,1,IND,2025-03-27,@,WAS,"W, 162-109",163.4,109.9,0.207,0.511,0.807,0.788,0.185,109.9,163.4,0.306,0.353,0.565,0.512,0.259
1,2,DEN,2025-01-21,NaN,PHI,"W, 144-109",149.7,113.3,0.294,0.365,0.750,0.706,0.282,113.3,149.7,0.083,0.396,0.548,0.536,0.063
2,3,BOS,2024-12-27,NaN,IND,"W, 142-105",148.5,109.8,0.315,0.609,0.678,0.636,0.272,109.8,148.5,0.275,0.429,0.515,0.478,0.198
3,4,OKC,2025-03-21,NaN,CHO,"W, 141-106",147.7,111.0,0.181,0.415,0.695,0.686,0.128,111.0,147.7,0.163,0.513,0.618,0.581,0.163
4,5,MEM,2025-03-25,@,UTA,"W, 140-103",147.6,108.6,0.184,0.459,0.661,0.633,0.163,108.6,147.6,0.282,0.538,0.587,0.545,0.231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,CHO,2025-02-22,@,POR,"L, 88-141",82.1,131.6,0.214,0.327,0.410,0.372,0.153,131.6,82.1,0.310,0.494,0.713,0.701,0.218
2290,2291,POR,2024-11-10,NaN,MEM,"L, 89-134",80.6,121.4,0.210,0.420,0.407,0.360,0.170,121.4,80.6,0.329,0.506,0.688,0.647,0.282
2291,2292,LAC,2024-12-04,NaN,MIN,"L, 80-108",80.1,108.1,0.157,0.482,0.451,0.416,0.133,108.1,80.1,0.212,0.518,0.581,0.576,0.118
2292,2293,TOR,2024-12-31,@,BOS,"L, 71-125",75.2,132.3,0.128,0.465,0.391,0.372,0.081,132.3,75.2,0.172,0.494,0.668,0.667,0.103
2293,2294,BRK,2025-01-15,@,LAC,"L, 67-126",68.3,128.5,0.265,0.337,0.361,0.331,0.145,128.5,68.3,0.380,0.405,0.683,0.620,0.354

In [6]:
df_adv_rbd= pd.read_csv("../Data/Advanced Rebounding.csv")
#df_bsc.drop(columns= ['MP'], inplace= True)
df_adv_rbd

,Rk,Team,Date,H/A,Opp,Result,Tm_ORB%,Tm_DRB%,Tm_TRB%,Opp_ORB%,Opp_DRB%,Opp_TRB%
0,1,MEM,2025-02-05,@,TOR,"W, 138-107",54.5,72.5,35.8,27.5,45.5,35.8
1,2,TOR,2024-10-25,NaN,PHI,"W, 115-107",50.0,78.3,34.1,21.7,50.0,34.1
2,3,MEM,2025-03-03,NaN,ATL,"L, 130-132",48.6,65.0,42.7,35.0,51.4,42.7
3,4,POR,2024-10-27,NaN,NOP,"W, 125-103",47.8,65.9,43.3,34.1,52.2,43.3
4,5,MEM,2024-12-26,NaN,TOR,"W, 155-126",47.1,75.0,38.8,25.0,52.9,38.8
...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,PHO,2024-12-03,NaN,SAS,"W, 104-93",5.4,70.0,54.6,30.0,94.6,54.6
2290,2291,DAL,2024-12-30,@,SAC,"L, 100-110",4.8,65.4,61.7,34.6,95.2,61.7
2291,2292,PHI,2024-11-18,@,MIA,"L, 89-106",4.3,81.6,55.8,18.4,95.7,55.8
2292,2293,CHI,2024-12-08,NaN,PHI,"L, 100-108",4.2,76.7,61.5,23.3,95.8,61.5
2293,2294,PHO,2025-01-20,@,CLE,"L, 92-118",2.8,68.8,59.5,31.3,97.2,59.5

In [7]:
df_adv= pd.read_csv("../Data/Advanced.csv")
#df_bsc.drop(columns= ['MP'], inplace= True)
df_adv

,Rk,Team,Date,H/A,Opp,Result,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,1,BRK,2024-11-17,@,NYK,"L, 104-114",96.9,1.1,6.3,9.2,76.7,4.4,14.3,7.7
1,2,SAS,2024-12-15,NaN,MIN,"L, 92-106",91.9,6.0,12.3,16.7,65.0,11.0,8.7,10.1
2,3,WAS,2025-02-05,@,BRK,"W, 119-102",90.9,6.6,6.7,14.7,72.2,7.7,7.9,9.7
3,4,SAS,2025-02-23,@,NOP,"L, 96-114",90.6,10.7,11.5,8.5,64.3,2.9,6.5,13.9
4,5,LAC,2025-02-04,NaN,LAL,"L, 97-122",88.2,9.5,11.4,9.3,73.3,7.4,6.3,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,HOU,2024-12-03,@,SAC,"L, 111-120",34.1,6.2,1.6,13.5,70.2,7.3,14.8,9.1
2290,2291,MEM,2025-01-13,@,HOU,"L, 118-120",33.3,17.0,4.0,16.2,68.3,13.0,15.4,19.6
2291,2292,POR,2024-11-08,@,MIN,"L, 102-127",33.3,10.4,14.9,14.3,68.1,8.5,10.6,16.2
2292,2293,HOU,2024-11-11,NaN,WAS,"W, 107-92",32.5,11.9,17.5,17.6,58.3,13.9,7.8,16.9
2293,2294,HOU,2025-01-03,NaN,BOS,"L, 86-109",28.1,7.0,10.5,13.0,51.3,7.0,15.4,14.2

In [8]:
dfs= [df_sh, df_rbd, df_bsc, df_adv_sh, df_adv_rbd, df_adv]

In [9]:
common_cols = set(dfs[0].columns)
df_sh.sort_values(by=["Team", "Opp", "Date"], inplace= True)
df_sh.reset_index(drop=True, inplace= True) 
for df in dfs[1:]:
    df.sort_values(by=["Team", "Opp", "Date"], inplace=True)
    df.reset_index(drop=True, inplace= True)
    common_cols &= set(df.columns)
common_cols = list(common_cols)  # Convert to list
common_cols

['Opp', 'Rk', 'Result', 'Team', 'H/A', 'Date']

In [10]:
df_cols= df_rbd[common_cols]
for df in dfs:
    df.drop(columns= common_cols, inplace= True)
dfs.append(df_cols)

In [11]:
df_Teams_Games= pd.concat([df for df in dfs], axis=1)
df_Teams_Games

,MP,Tm_FG,Tm_FGA,Tm_FG%,Tm_2P,Tm_2PA,Tm_2P%,Tm_3P,Tm_3PA,Tm_3P%,...,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%,Opp,Rk,Result,Team,H/A,Date
0,240,37,89,0.416,31,58,0.534,6,31,0.194,...,56.3,14.3,12.1,11.0,BOS,1680,"L, 93-123",ATL,NaN,2024-11-04
1,240,50,99,0.505,40,67,0.597,10,32,0.313,...,73.7,7.1,7.5,18.7,BOS,61,"W, 117-116",ATL,@,2024-11-12
2,265,44,93,0.473,35,56,0.625,9,37,0.243,...,57.5,12.1,10.7,10.9,BOS,610,"W, 119-115 (OT)",ATL,@,2025-01-18
3,240,39,80,0.488,30,52,0.577,9,28,0.321,...,52.5,7.7,11.5,15.7,BRK,796,"W, 120-116",ATL,NaN,2024-10-23
4,240,42,90,0.467,31,53,0.585,11,37,0.297,...,76.7,7.0,9.4,14.5,BRK,1221,"L, 114-122",ATL,@,2025-03-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,240,44,100,0.440,31,62,0.500,13,38,0.342,...,60.0,11.3,9.7,12.2,TOR,24,"W, 118-117",WAS,@,2025-03-08
2290,240,38,105,0.362,22,50,0.440,16,55,0.291,...,60.5,3.0,4.0,6.9,TOR,303,"L, 104-119",WAS,@,2025-03-10
2291,240,35,87,0.402,24,50,0.480,11,37,0.297,...,68.3,10.4,12.0,9.6,TOR,1671,"L, 104-112",WAS,NaN,2025-03-24
2292,240,42,95,0.442,25,48,0.521,17,47,0.362,...,44.7,4.8,6.3,12.0,UTA,1454,"W, 125-122",WAS,NaN,2025-03-05
2293,240,43,93,0.462,31,48,0.646,12,45,0.267,...,60.0,7.0,2.1,14.9,UTA,783,"L, 112-128",WAS,@,2025-03-19

In [12]:
cols = common_cols + [col for col in df_Teams_Games.columns if col not in common_cols]
df1= df_Teams_Games[cols]
df1

,Opp,Rk,Result,Team,H/A,Date,MP,Tm_FG,Tm_FGA,Tm_FG%,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,BOS,1680,"L, 93-123",ATL,NaN,2024-11-04,240,37,89,0.416,...,83.0,53.8,62.2,8.6,6.8,17.2,56.3,14.3,12.1,11.0
1,BOS,61,"W, 117-116",ATL,@,2024-11-12,240,50,99,0.505,...,59.6,43.6,70.0,16.2,6.7,13.3,73.7,7.1,7.5,18.7
2,BOS,610,"W, 119-115 (OT)",ATL,@,2025-01-18,265,44,93,0.473,...,73.5,49.1,61.4,8.3,19.2,14.6,57.5,12.1,10.7,10.9
3,BRK,796,"W, 120-116",ATL,NaN,2024-10-23,240,39,80,0.488,...,72.1,48.9,64.1,11.6,18.8,13.8,52.5,7.7,11.5,15.7
4,BRK,1221,"L, 114-122",ATL,@,2025-03-16,240,42,90,0.467,...,73.7,51.3,64.3,11.9,20.0,12.2,76.7,7.0,9.4,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,TOR,24,"W, 118-117",WAS,@,2025-03-08,240,44,100,0.440,...,55.1,49.5,65.9,12.3,10.1,12.7,60.0,11.3,9.7,12.2
2290,TOR,303,"L, 104-119",WAS,@,2025-03-10,240,38,105,0.362,...,73.8,57.5,65.8,5.0,20.0,6.7,60.5,3.0,4.0,6.9
2291,TOR,1671,"L, 104-112",WAS,NaN,2025-03-24,240,35,87,0.402,...,82.7,55.6,68.6,7.5,13.8,14.3,68.3,10.4,12.0,9.6
2292,UTA,1454,"W, 125-122",WAS,NaN,2025-03-05,240,42,95,0.442,...,80.4,56.3,76.2,8.6,19.7,7.7,44.7,4.8,6.3,12.0
2293,UTA,783,"L, 112-128",WAS,@,2025-03-19,240,43,93,0.462,...,71.7,53.2,69.8,11.9,8.5,12.2,60.0,7.0,2.1,14.9

In [13]:
id= ["Team", "Opp", "Date", "Result", "H/A", "Tm_PTS", "Opp_PTS"]
cols2= id+ [col for col in df1.columns if not(col in id)]
df2= df1[cols2].copy()
df2

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,Rk,MP,Tm_FG,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,ATL,BOS,2024-11-04,"L, 93-123",NaN,93,123,1680,240,37,...,83.0,53.8,62.2,8.6,6.8,17.2,56.3,14.3,12.1,11.0
1,ATL,BOS,2024-11-12,"W, 117-116",@,117,116,61,240,50,...,59.6,43.6,70.0,16.2,6.7,13.3,73.7,7.1,7.5,18.7
2,ATL,BOS,2025-01-18,"W, 119-115 (OT)",@,119,115,610,265,44,...,73.5,49.1,61.4,8.3,19.2,14.6,57.5,12.1,10.7,10.9
3,ATL,BRK,2024-10-23,"W, 120-116",NaN,120,116,796,240,39,...,72.1,48.9,64.1,11.6,18.8,13.8,52.5,7.7,11.5,15.7
4,ATL,BRK,2025-03-16,"L, 114-122",@,114,122,1221,240,42,...,73.7,51.3,64.3,11.9,20.0,12.2,76.7,7.0,9.4,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,WAS,TOR,2025-03-08,"W, 118-117",@,118,117,24,240,44,...,55.1,49.5,65.9,12.3,10.1,12.7,60.0,11.3,9.7,12.2
2290,WAS,TOR,2025-03-10,"L, 104-119",@,104,119,303,240,38,...,73.8,57.5,65.8,5.0,20.0,6.7,60.5,3.0,4.0,6.9
2291,WAS,TOR,2025-03-24,"L, 104-112",NaN,104,112,1671,240,35,...,82.7,55.6,68.6,7.5,13.8,14.3,68.3,10.4,12.0,9.6
2292,WAS,UTA,2025-03-05,"W, 125-122",NaN,125,122,1454,240,42,...,80.4,56.3,76.2,8.6,19.7,7.7,44.7,4.8,6.3,12.0
2293,WAS,UTA,2025-03-19,"L, 112-128",@,112,128,783,240,43,...,71.7,53.2,69.8,11.9,8.5,12.2,60.0,7.0,2.1,14.9

In [14]:
cols_to_delete= ["Rk"]
df2["Date"] = pd.to_datetime(df2["Date"], format="%Y-%m-%d")
df3 = df2.drop(columns= cols_to_delete)
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,ATL,BOS,2024-11-04,"L, 93-123",NaN,93,123,240,37,89,...,83.0,53.8,62.2,8.6,6.8,17.2,56.3,14.3,12.1,11.0
1,ATL,BOS,2024-11-12,"W, 117-116",@,117,116,240,50,99,...,59.6,43.6,70.0,16.2,6.7,13.3,73.7,7.1,7.5,18.7
2,ATL,BOS,2025-01-18,"W, 119-115 (OT)",@,119,115,265,44,93,...,73.5,49.1,61.4,8.3,19.2,14.6,57.5,12.1,10.7,10.9
3,ATL,BRK,2024-10-23,"W, 120-116",NaN,120,116,240,39,80,...,72.1,48.9,64.1,11.6,18.8,13.8,52.5,7.7,11.5,15.7
4,ATL,BRK,2025-03-16,"L, 114-122",@,114,122,240,42,90,...,73.7,51.3,64.3,11.9,20.0,12.2,76.7,7.0,9.4,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,WAS,TOR,2025-03-08,"W, 118-117",@,118,117,240,44,100,...,55.1,49.5,65.9,12.3,10.1,12.7,60.0,11.3,9.7,12.2
2290,WAS,TOR,2025-03-10,"L, 104-119",@,104,119,240,38,105,...,73.8,57.5,65.8,5.0,20.0,6.7,60.5,3.0,4.0,6.9
2291,WAS,TOR,2025-03-24,"L, 104-112",NaN,104,112,240,35,87,...,82.7,55.6,68.6,7.5,13.8,14.3,68.3,10.4,12.0,9.6
2292,WAS,UTA,2025-03-05,"W, 125-122",NaN,125,122,240,42,95,...,80.4,56.3,76.2,8.6,19.7,7.7,44.7,4.8,6.3,12.0
2293,WAS,UTA,2025-03-19,"L, 112-128",@,112,128,240,43,93,...,71.7,53.2,69.8,11.9,8.5,12.2,60.0,7.0,2.1,14.9

In [15]:
df3["H/A"] = df3["H/A"].fillna("H").replace("@", "A")
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,ATL,BOS,2024-11-04,"L, 93-123",H,93,123,240,37,89,...,83.0,53.8,62.2,8.6,6.8,17.2,56.3,14.3,12.1,11.0
1,ATL,BOS,2024-11-12,"W, 117-116",A,117,116,240,50,99,...,59.6,43.6,70.0,16.2,6.7,13.3,73.7,7.1,7.5,18.7
2,ATL,BOS,2025-01-18,"W, 119-115 (OT)",A,119,115,265,44,93,...,73.5,49.1,61.4,8.3,19.2,14.6,57.5,12.1,10.7,10.9
3,ATL,BRK,2024-10-23,"W, 120-116",H,120,116,240,39,80,...,72.1,48.9,64.1,11.6,18.8,13.8,52.5,7.7,11.5,15.7
4,ATL,BRK,2025-03-16,"L, 114-122",A,114,122,240,42,90,...,73.7,51.3,64.3,11.9,20.0,12.2,76.7,7.0,9.4,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,WAS,TOR,2025-03-08,"W, 118-117",A,118,117,240,44,100,...,55.1,49.5,65.9,12.3,10.1,12.7,60.0,11.3,9.7,12.2
2290,WAS,TOR,2025-03-10,"L, 104-119",A,104,119,240,38,105,...,73.8,57.5,65.8,5.0,20.0,6.7,60.5,3.0,4.0,6.9
2291,WAS,TOR,2025-03-24,"L, 104-112",H,104,112,240,35,87,...,82.7,55.6,68.6,7.5,13.8,14.3,68.3,10.4,12.0,9.6
2292,WAS,UTA,2025-03-05,"W, 125-122",H,125,122,240,42,95,...,80.4,56.3,76.2,8.6,19.7,7.7,44.7,4.8,6.3,12.0
2293,WAS,UTA,2025-03-19,"L, 112-128",A,112,128,240,43,93,...,71.7,53.2,69.8,11.9,8.5,12.2,60.0,7.0,2.1,14.9

In [16]:
df3["Result"] = df3["Result"].str[0]
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,ATL,BOS,2024-11-04,L,H,93,123,240,37,89,...,83.0,53.8,62.2,8.6,6.8,17.2,56.3,14.3,12.1,11.0
1,ATL,BOS,2024-11-12,W,A,117,116,240,50,99,...,59.6,43.6,70.0,16.2,6.7,13.3,73.7,7.1,7.5,18.7
2,ATL,BOS,2025-01-18,W,A,119,115,265,44,93,...,73.5,49.1,61.4,8.3,19.2,14.6,57.5,12.1,10.7,10.9
3,ATL,BRK,2024-10-23,W,H,120,116,240,39,80,...,72.1,48.9,64.1,11.6,18.8,13.8,52.5,7.7,11.5,15.7
4,ATL,BRK,2025-03-16,L,A,114,122,240,42,90,...,73.7,51.3,64.3,11.9,20.0,12.2,76.7,7.0,9.4,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,WAS,TOR,2025-03-08,W,A,118,117,240,44,100,...,55.1,49.5,65.9,12.3,10.1,12.7,60.0,11.3,9.7,12.2
2290,WAS,TOR,2025-03-10,L,A,104,119,240,38,105,...,73.8,57.5,65.8,5.0,20.0,6.7,60.5,3.0,4.0,6.9
2291,WAS,TOR,2025-03-24,L,H,104,112,240,35,87,...,82.7,55.6,68.6,7.5,13.8,14.3,68.3,10.4,12.0,9.6
2292,WAS,UTA,2025-03-05,W,H,125,122,240,42,95,...,80.4,56.3,76.2,8.6,19.7,7.7,44.7,4.8,6.3,12.0
2293,WAS,UTA,2025-03-19,L,A,112,128,240,43,93,...,71.7,53.2,69.8,11.9,8.5,12.2,60.0,7.0,2.1,14.9

In [17]:
df3.sort_values(by="Date", inplace=True)
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Opp_DRB%,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
1455,NYK,BOS,2024-10-22,L,A,109,132,240,43,78,...,85.3,54.1,46.5,2.2,8.8,12.4,68.8,6.7,6.3,3.9
1032,LAL,MIN,2024-10-22,W,H,110,103,240,42,95,...,70.0,50.5,52.4,7.3,18.2,6.2,48.6,4.2,1.5,14.2
125,BOS,NYK,2024-10-22,W,H,132,109,240,48,95,...,72.5,45.9,68.8,6.7,6.3,3.9,46.5,2.2,8.8,12.4
1331,MIN,LAL,2024-10-22,L,A,103,110,240,35,85,...,72.1,49.5,48.6,4.2,1.5,14.2,52.4,7.3,18.2,6.2
1198,MIA,ORL,2024-10-23,L,H,97,116,240,32,82,...,81.3,58.2,75.0,5.2,17.0,10.4,68.3,8.3,16.7,11.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2130,TOR,POR,2025-04-03,L,H,103,112,240,44,96,...,74.0,60.7,65.9,14.0,1.9,15.5,47.6,10.0,9.7,20.9
2277,WAS,ORL,2025-04-03,L,H,97,109,240,38,85,...,81.0,55.3,42.1,4.4,5.8,12.6,71.1,7.7,14.5,11.4
1015,LAL,GSW,2025-04-03,L,H,116,123,240,39,86,...,69.6,54.1,59.0,5.5,7.5,9.4,76.9,5.5,5.1,12.0
1104,MEM,MIA,2025-04-03,W,A,110,108,240,40,85,...,72.7,49.0,60.0,8.3,6.5,16.3,61.5,11.4,17.0,9.6
1281,MIL,PHI,2025-04-03,W,A,126,113,240,46,82,...,78.4,50.0,69.6,7.2,14.0,10.5,69.8,8.2,7.8,13.3

In [18]:
df3["Tm_Rest"] = df3.groupby("Team")["Date"].diff().dt.days.fillna(5)

In [19]:
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Opp_TRB%,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%,Tm_Rest
1455,NYK,BOS,2024-10-22,L,A,109,132,240,43,78,...,54.1,46.5,2.2,8.8,12.4,68.8,6.7,6.3,3.9,5.0
1032,LAL,MIN,2024-10-22,W,H,110,103,240,42,95,...,50.5,52.4,7.3,18.2,6.2,48.6,4.2,1.5,14.2,5.0
125,BOS,NYK,2024-10-22,W,H,132,109,240,48,95,...,45.9,68.8,6.7,6.3,3.9,46.5,2.2,8.8,12.4,5.0
1331,MIN,LAL,2024-10-22,L,A,103,110,240,35,85,...,49.5,48.6,4.2,1.5,14.2,52.4,7.3,18.2,6.2,5.0
1198,MIA,ORL,2024-10-23,L,H,97,116,240,32,82,...,58.2,75.0,5.2,17.0,10.4,68.3,8.3,16.7,11.7,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2130,TOR,POR,2025-04-03,L,H,103,112,240,44,96,...,60.7,65.9,14.0,1.9,15.5,47.6,10.0,9.7,20.9,2.0
2277,WAS,ORL,2025-04-03,L,H,97,109,240,38,85,...,55.3,42.1,4.4,5.8,12.6,71.1,7.7,14.5,11.4,1.0
1015,LAL,GSW,2025-04-03,L,H,116,123,240,39,86,...,54.1,59.0,5.5,7.5,9.4,76.9,5.5,5.1,12.0,3.0
1104,MEM,MIA,2025-04-03,W,A,110,108,240,40,85,...,49.0,60.0,8.3,6.5,16.3,61.5,11.4,17.0,9.6,2.0
1281,MIL,PHI,2025-04-03,W,A,126,113,240,46,82,...,50.0,69.6,7.2,14.0,10.5,69.8,8.2,7.8,13.3,2.0

In [20]:
df3["Opp_Rest"] = df3.groupby("Opp")["Date"].diff().dt.days.fillna(5)
df3

,Team,Opp,Date,Result,H/A,Tm_PTS,Opp_PTS,MP,Tm_FG,Tm_FGA,...,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%,Tm_Rest,Opp_Rest
1455,NYK,BOS,2024-10-22,L,A,109,132,240,43,78,...,46.5,2.2,8.8,12.4,68.8,6.7,6.3,3.9,5.0,5.0
1032,LAL,MIN,2024-10-22,W,H,110,103,240,42,95,...,52.4,7.3,18.2,6.2,48.6,4.2,1.5,14.2,5.0,5.0
125,BOS,NYK,2024-10-22,W,H,132,109,240,48,95,...,68.8,6.7,6.3,3.9,46.5,2.2,8.8,12.4,5.0,5.0
1331,MIN,LAL,2024-10-22,L,A,103,110,240,35,85,...,48.6,4.2,1.5,14.2,52.4,7.3,18.2,6.2,5.0,5.0
1198,MIA,ORL,2024-10-23,L,H,97,116,240,32,82,...,75.0,5.2,17.0,10.4,68.3,8.3,16.7,11.7,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2130,TOR,POR,2025-04-03,L,H,103,112,240,44,96,...,65.9,14.0,1.9,15.5,47.6,10.0,9.7,20.9,2.0,2.0
2277,WAS,ORL,2025-04-03,L,H,97,109,240,38,85,...,42.1,4.4,5.8,12.6,71.1,7.7,14.5,11.4,1.0,2.0
1015,LAL,GSW,2025-04-03,L,H,116,123,240,39,86,...,59.0,5.5,7.5,9.4,76.9,5.5,5.1,12.0,3.0,2.0
1104,MEM,MIA,2025-04-03,W,A,110,108,240,40,85,...,60.0,8.3,6.5,16.3,61.5,11.4,17.0,9.6,2.0,1.0
1281,MIL,PHI,2025-04-03,W,A,126,113,240,46,82,...,69.6,7.2,14.0,10.5,69.8,8.2,7.8,13.3,2.0,2.0

In [21]:
df3['Tm_Pos']= 0.5* ((df3['Tm_FGA']+ 0.4* df3['Tm_FTA']- 1.07*(df3['Tm_ORB%']/100)* (df3['Tm_FGA']- df3['Tm_FG'])+ df3['Tm_TOV'])+ (df3['Opp_FGA']+ 0.4* df3['Opp_FTA']- 1.07*(df3['Opp_ORB%']/100)* (df3['Opp_FGA']- df3['Opp_FG'])+ df3['Opp_TOV']))
df3['Tm_Pos']

1455     89.632550
1032     95.930250
125      89.632550
1331     95.930250
1198     96.078000
           ...
2130    100.003360
2277     91.313370
1015     90.397125
1104     96.499045
1281     97.239680
Name: Tm_Pos, Length: 2294, dtype: float64

In [22]:
df3['Tm_Pace']= 240/df3['MP']*df3['Tm_Pos']
df3['Tm_Pace']

1455     89.632550
1032     95.930250
125      89.632550
1331     95.930250
1198     96.078000
           ...
2130    100.003360
2277     91.313370
1015     90.397125
1104     96.499045
1281     97.239680
Name: Tm_Pace, Length: 2294, dtype: float64

Pace Calculation Formula=[240/(Team Minutes)]*(Possessionteam+Possessionopponent)/2

In [23]:
df3['Opp_Pace']= 240/df3['MP']*df3['Tm_Pos']
df3['Opp_Pace']

1455     89.632550
1032     95.930250
125      89.632550
1331     95.930250
1198     96.078000
           ...
2130    100.003360
2277     91.313370
1015     90.397125
1104     96.499045
1281     97.239680
Name: Opp_Pace, Length: 2294, dtype: float64

In [24]:
df_team = {comp_value: df3[df3["Team"] == comp_value] for comp_value in df3["Team"].unique()}
df_opp = {comp_value: df3[df3["Opp"] == comp_value] for comp_value in df3["Opp"].unique()}

In [25]:
for team in df_team.keys():
    df_team[team].to_csv(f"../Data/{team}.csv", index=False)
    df_opp[team].to_csv(f"../Data/vs {team}.csv", index=False)

## Season

In [26]:
df_pr_gm= pd.read_csv("../Data/Per Game.csv")
df_pr_gm.head()

,Team,G,W,L,W/L%,MP,Tm_FG,Tm_FGA,Tm_2P,Tm_2PA,...,Opp_FTA,Opp_ORB,Opp_DRB,Opp_TRB,Opp_AST,Opp_STL,Opp_BLK,Opp_TOV,Opp_PF,Opp_PTS
0,WAS,59,11,48,0.186,240.8,39.6,89.8,26.6,51.0,...,24.0,12.2,35.4,47.6,28.7,9.3,5.4,13.5,18.7,120.8
1,UTA,59,15,44,0.254,241.7,40.3,87.8,26.3,48.5,...,22.6,11.3,31.6,42.9,29.0,9.6,6.3,11.8,19.7,119.3
2,TOR,60,18,42,0.300,242.1,41.6,89.5,30.1,56.6,...,25.5,11.4,32.9,44.3,26.2,9.3,5.7,14.6,18.4,116.4
3,SAS,58,25,33,0.431,240.9,41.2,89.8,27.6,50.3,...,18.3,12.4,34.3,46.8,26.7,8.2,4.6,13.7,17.9,114.7
4,SAC,59,31,28,0.525,243.0,43.4,90.9,30.9,55.2,...,22.5,10.2,32.7,42.9,26.8,8.1,4.5,14.3,18.8,115.3

In [27]:
df_sea_adv= pd.read_csv("../Data/Season Advanced.csv")
df_sea_adv.head()

,Team,G,W,L,W/L%,MOV,SOS,SRS,Pace,ORtg,...,Tm_TOV%,Tm_ORB%,Tm_DRB%,Tm_FTr,Opp_eFG%,Opp_TS%,Opp_TOV%,Opp_ORB%,Opp_DRB%,Opp_FTr
0,WAS,59,11,48,0.186,-12.46,0.87,-11.59,101.4,106.5,...,14.1,23.0,73.1,0.233,0.551,0.587,11.6,26.9,77.0,0.259
1,UTA,59,15,44,0.254,-7.02,0.82,-6.20,99.2,112.4,...,15.0,27.9,74.8,0.258,0.555,0.586,10.4,25.2,72.1,0.246
2,TOR,60,18,42,0.300,-5.97,1.51,-4.46,99.2,110.3,...,13.7,26.3,73.8,0.235,0.547,0.584,12.8,26.2,73.7,0.288
3,SAS,58,25,33,0.431,-1.98,0.04,-1.94,99.4,113.0,...,12.4,24.3,73.0,0.237,0.538,0.566,11.9,27.0,75.7,0.196
4,SAC,59,31,28,0.525,1.47,-0.48,1.00,99.2,116.3,...,11.9,25.3,76.9,0.239,0.548,0.584,12.7,23.1,74.7,0.252

In [28]:
dfs= [df_pr_gm, df_sea_adv]

In [29]:
common_cols = set(dfs[0].columns)
#df_sh.sort_values(by=["Team", "Opp", "Date"], inplace= True)
#df_sh.reset_index(drop=True, inplace= True) 
for df in dfs[1:]:
    #df.sort_values(by=["Team", "Opp", "Date"], inplace=True)
    #df.reset_index(drop=True, inplace= True)
    common_cols &= set(df.columns)
common_cols = list(common_cols)  # Convert to list
common_cols

['W', 'L', 'G', 'Team', 'W/L%']

In [30]:
df_cols= df_sea_adv[common_cols]
for df in dfs:
    df.drop(columns= common_cols, inplace= True)
dfs.append(df_cols)

In [31]:
df_Teams_Season= pd.concat([df for df in dfs], axis=1)
df_Teams_Season.head()

,MP,Tm_FG,Tm_FGA,Tm_2P,Tm_2PA,Tm_3P,Tm_3PA,Tm_FT,Tm_FTA,Tm_ORB,...,Opp_TS%,Opp_TOV%,Opp_ORB%,Opp_DRB%,Opp_FTr,W,L,G,Team,W/L%
0,240.8,39.6,89.8,26.6,51.0,13.0,38.8,16.3,20.9,10.6,...,0.587,11.6,26.9,77.0,0.259,11,48,59,WAS,0.186
1,241.7,40.3,87.8,26.3,48.5,14.0,39.3,17.6,22.7,12.2,...,0.586,10.4,25.2,72.1,0.246,15,44,59,UTA,0.254
2,242.1,41.6,89.5,30.1,56.6,11.5,33.0,15.7,21.0,11.7,...,0.584,12.8,26.2,73.7,0.288,18,42,60,TOR,0.300
3,240.9,41.2,89.8,27.6,50.3,13.7,39.5,16.6,21.3,11.0,...,0.566,11.9,27.0,75.7,0.196,25,33,58,SAS,0.431
4,243.0,43.4,90.9,30.9,55.2,12.5,35.7,17.6,21.8,11.1,...,0.584,12.7,23.1,74.7,0.252,31,28,59,SAC,0.525

In [32]:
cols = common_cols + [col for col in df_Teams_Season.columns if col not in common_cols]
dfa= df_Teams_Season[cols]
dfa

,W,L,G,Team,W/L%,MP,Tm_FG,Tm_FGA,Tm_2P,Tm_2PA,...,Tm_TOV%,Tm_ORB%,Tm_DRB%,Tm_FTr,Opp_eFG%,Opp_TS%,Opp_TOV%,Opp_ORB%,Opp_DRB%,Opp_FTr
0,11,48,59,WAS,0.186,240.8,39.6,89.8,26.6,51.0,...,14.1,23.0,73.1,0.233,0.551,0.587,11.6,26.9,77.0,0.259
1,15,44,59,UTA,0.254,241.7,40.3,87.8,26.3,48.5,...,15.0,27.9,74.8,0.258,0.555,0.586,10.4,25.2,72.1,0.246
2,18,42,60,TOR,0.300,242.1,41.6,89.5,30.1,56.6,...,13.7,26.3,73.8,0.235,0.547,0.584,12.8,26.2,73.7,0.288
3,25,33,58,SAS,0.431,240.9,41.2,89.8,27.6,50.3,...,12.4,24.3,73.0,0.237,0.538,0.566,11.9,27.0,75.7,0.196
4,31,28,59,SAC,0.525,243.0,43.4,90.9,30.9,55.2,...,11.9,25.3,76.9,0.239,0.548,0.584,12.7,23.1,74.7,0.252
5,27,33,60,POR,0.450,240.4,40.3,88.9,27.8,52.8,...,14.0,27.9,72.2,0.250,0.544,0.581,13.5,27.8,72.1,0.263
6,28,32,60,PHO,0.467,242.1,41.1,86.1,26.8,48.4,...,12.8,21.6,73.1,0.254,0.541,0.575,10.9,26.9,78.4,0.243
7,21,38,59,PHI,0.356,241.7,39.2,86.3,26.6,49.9,...,12.3,22.8,73.0,0.266,0.567,0.602,14.9,27.0,77.2,0.254
8,29,32,61,ORL,0.475,240.8,37.8,86.0,27.0,50.5,...,13.2,25.7,78.0,0.269,0.542,0.580,15.2,22.0,74.3,0.294
9,48,11,59,OKC,0.814,240.4,44.2,92.8,30.1,53.8,...,10.5,24.8,73.6,0.214,0.508,0.549,15.6,26.4,75.2,0.289
10,39,20,59,NYK,0.661,241.7,43.9,89.2,31.3,55.3,...,11.7,25.7,74.6,0.238,0.550,0.581,12.7,25.4,74.3,0.217
11,16,44,60,NOP,0.267,241.3,40.7,90.6,28.4,55.4,...,12.4,26.1,72.3,0.247,0.561,0.592,12.7,27.7,73.9,0.228
12,32,29,61,MIN,0.525,241.2,40.0,87.2,25.2,47.7,...,13.2,25.7,74.7,0.249,0.530,0.562,13.2,25.3,74.3,0.233
13,34,25,59,MIL,0.576,240.4,41.7,87.0,27.4,49.7,...,12.3,19.6,76.1,0.257,0.526,0.561,11.4,23.9,80.4,0.230
14,28,30,58,MIA,0.483,243.4,39.7,86.8,25.7,48.2,...,12.5,22.3,75.5,0.246,0.541,0.569,12.3,24.5,77.7,0.201
15,38,22,60,MEM,0.633,240.4,45.2,93.5,31.4,55.9,...,13.6,29.7,74.1,0.261,0.529,0.564,13.1,25.9,70.3,0.266
16,37,21,58,LAL,0.638,240.4,41.1,85.4,28.8,50.6,...,12.6,22.8,74.9,0.274,0.535,0.567,12.5,25.1,77.2,0.218
17,32,27,59,LAC,0.542,241.3,40.7,86.7,28.5,52.6,...,14.2,24.9,76.8,0.248,0.537,0.570,14.1,23.2,75.1,0.249
18,33,25,58,IND,0.569,241.3,43.4,88.5,30.5,53.8,...,12.1,21.2,74.2,0.241,0.548,0.582,13.2,25.8,78.8,0.254
19,37,23,60,HOU,0.617,241.3,41.6,93.2,29.4,57.7,...,11.9,31.2,75.6,0.249,0.522,0.555,13.0,24.4,68.8,0.253
20,32,28,60,GSW,0.533,240.4,41.1,91.9,25.8,49.3,...,12.0,27.4,75.8,0.228,0.539,0.573,13.6,24.2,72.6,0.249
21,34,27,61,DET,0.557,241.6,42.4,89.6,29.4,53.8,...,13.6,26.4,77.0,0.236,0.541,0.577,13.3,23.0,73.6,0.267
22,39,21,60,DEN,0.650,241.7,45.8,90.2,33.8,58.7,...,12.6,27.1,74.9,0.253,0.537,0.568,11.5,25.1,72.9,0.221
23,32,29,61,DAL,0.525,240.8,42.0,88.5,28.9,53.0,...,12.5,24.8,72.8,0.260,0.528,0.561,11.8,27.2,75.2,0.236
24,49,10,59,CLE,0.831,240.0,45.1,90.5,28.9,49.4,...,11.6,25.5,75.3,0.233,0.527,0.559,12.8,24.7,74.5,0.232
25,14,45,59,CHO,0.237,241.3,38.2,89.9,24.8,50.6,...,13.6,27.3,74.7,0.221,0.543,0.577,12.7,25.3,72.7,0.245
26,24,36,60,CHI,0.400,241.3,42.6,92.1,26.6,48.8,...,13.0,21.6,76.0,0.208,0.542,0.575,10.8,24.0,78.4,0.226
27,21,39,60,BRK,0.350,241.3,37.4,85.6,24.3,47.3,...,14.1,25.2,75.2,0.248,0.558,0.593,14.2,24.8,74.8,0.279
28,42,18,60,BOS,0.700,242.1,41.6,90.3,23.8,42.1,...,10.8,24.3,76.4,0.220,0.522,0.553,11.8,23.6,75.7,0.204
29,27,33,60,ATL,0.450,241.7,42.5,91.7,29.4,54.4,...,13.5,25.7,76.2,0.263,0.561,0.595,14.1,23.8,74.3,0.244

In [33]:
id= ["Team", "G", "W", "L", "W/L%"]#, "Tm_PTS", "Opp_PTS"]
cols2= id+ [col for col in dfa.columns if not(col in id)]
dfb= dfa[cols2].copy()
dfb

,Team,G,W,L,W/L%,MP,Tm_FG,Tm_FGA,Tm_2P,Tm_2PA,...,Tm_TOV%,Tm_ORB%,Tm_DRB%,Tm_FTr,Opp_eFG%,Opp_TS%,Opp_TOV%,Opp_ORB%,Opp_DRB%,Opp_FTr
0,WAS,59,11,48,0.186,240.8,39.6,89.8,26.6,51.0,...,14.1,23.0,73.1,0.233,0.551,0.587,11.6,26.9,77.0,0.259
1,UTA,59,15,44,0.254,241.7,40.3,87.8,26.3,48.5,...,15.0,27.9,74.8,0.258,0.555,0.586,10.4,25.2,72.1,0.246
2,TOR,60,18,42,0.300,242.1,41.6,89.5,30.1,56.6,...,13.7,26.3,73.8,0.235,0.547,0.584,12.8,26.2,73.7,0.288
3,SAS,58,25,33,0.431,240.9,41.2,89.8,27.6,50.3,...,12.4,24.3,73.0,0.237,0.538,0.566,11.9,27.0,75.7,0.196
4,SAC,59,31,28,0.525,243.0,43.4,90.9,30.9,55.2,...,11.9,25.3,76.9,0.239,0.548,0.584,12.7,23.1,74.7,0.252
5,POR,60,27,33,0.450,240.4,40.3,88.9,27.8,52.8,...,14.0,27.9,72.2,0.250,0.544,0.581,13.5,27.8,72.1,0.263
6,PHO,60,28,32,0.467,242.1,41.1,86.1,26.8,48.4,...,12.8,21.6,73.1,0.254,0.541,0.575,10.9,26.9,78.4,0.243
7,PHI,59,21,38,0.356,241.7,39.2,86.3,26.6,49.9,...,12.3,22.8,73.0,0.266,0.567,0.602,14.9,27.0,77.2,0.254
8,ORL,61,29,32,0.475,240.8,37.8,86.0,27.0,50.5,...,13.2,25.7,78.0,0.269,0.542,0.580,15.2,22.0,74.3,0.294
9,OKC,59,48,11,0.814,240.4,44.2,92.8,30.1,53.8,...,10.5,24.8,73.6,0.214,0.508,0.549,15.6,26.4,75.2,0.289
10,NYK,59,39,20,0.661,241.7,43.9,89.2,31.3,55.3,...,11.7,25.7,74.6,0.238,0.550,0.581,12.7,25.4,74.3,0.217
11,NOP,60,16,44,0.267,241.3,40.7,90.6,28.4,55.4,...,12.4,26.1,72.3,0.247,0.561,0.592,12.7,27.7,73.9,0.228
12,MIN,61,32,29,0.525,241.2,40.0,87.2,25.2,47.7,...,13.2,25.7,74.7,0.249,0.530,0.562,13.2,25.3,74.3,0.233
13,MIL,59,34,25,0.576,240.4,41.7,87.0,27.4,49.7,...,12.3,19.6,76.1,0.257,0.526,0.561,11.4,23.9,80.4,0.230
14,MIA,58,28,30,0.483,243.4,39.7,86.8,25.7,48.2,...,12.5,22.3,75.5,0.246,0.541,0.569,12.3,24.5,77.7,0.201
15,MEM,60,38,22,0.633,240.4,45.2,93.5,31.4,55.9,...,13.6,29.7,74.1,0.261,0.529,0.564,13.1,25.9,70.3,0.266
16,LAL,58,37,21,0.638,240.4,41.1,85.4,28.8,50.6,...,12.6,22.8,74.9,0.274,0.535,0.567,12.5,25.1,77.2,0.218
17,LAC,59,32,27,0.542,241.3,40.7,86.7,28.5,52.6,...,14.2,24.9,76.8,0.248,0.537,0.570,14.1,23.2,75.1,0.249
18,IND,58,33,25,0.569,241.3,43.4,88.5,30.5,53.8,...,12.1,21.2,74.2,0.241,0.548,0.582,13.2,25.8,78.8,0.254
19,HOU,60,37,23,0.617,241.3,41.6,93.2,29.4,57.7,...,11.9,31.2,75.6,0.249,0.522,0.555,13.0,24.4,68.8,0.253
20,GSW,60,32,28,0.533,240.4,41.1,91.9,25.8,49.3,...,12.0,27.4,75.8,0.228,0.539,0.573,13.6,24.2,72.6,0.249
21,DET,61,34,27,0.557,241.6,42.4,89.6,29.4,53.8,...,13.6,26.4,77.0,0.236,0.541,0.577,13.3,23.0,73.6,0.267
22,DEN,60,39,21,0.650,241.7,45.8,90.2,33.8,58.7,...,12.6,27.1,74.9,0.253,0.537,0.568,11.5,25.1,72.9,0.221
23,DAL,61,32,29,0.525,240.8,42.0,88.5,28.9,53.0,...,12.5,24.8,72.8,0.260,0.528,0.561,11.8,27.2,75.2,0.236
24,CLE,59,49,10,0.831,240.0,45.1,90.5,28.9,49.4,...,11.6,25.5,75.3,0.233,0.527,0.559,12.8,24.7,74.5,0.232
25,CHO,59,14,45,0.237,241.3,38.2,89.9,24.8,50.6,...,13.6,27.3,74.7,0.221,0.543,0.577,12.7,25.3,72.7,0.245
26,CHI,60,24,36,0.400,241.3,42.6,92.1,26.6,48.8,...,13.0,21.6,76.0,0.208,0.542,0.575,10.8,24.0,78.4,0.226
27,BRK,60,21,39,0.350,241.3,37.4,85.6,24.3,47.3,...,14.1,25.2,75.2,0.248,0.558,0.593,14.2,24.8,74.8,0.279
28,BOS,60,42,18,0.700,242.1,41.6,90.3,23.8,42.1,...,10.8,24.3,76.4,0.220,0.522,0.553,11.8,23.6,75.7,0.204
29,ATL,60,27,33,0.450,241.7,42.5,91.7,29.4,54.4,...,13.5,25.7,76.2,0.263,0.561,0.595,14.1,23.8,74.3,0.244

In [34]:
cols_to_delete= ["MP"]
dfc = dfb.drop(columns= cols_to_delete)
dfc

,Team,G,W,L,W/L%,Tm_FG,Tm_FGA,Tm_2P,Tm_2PA,Tm_3P,...,Tm_TOV%,Tm_ORB%,Tm_DRB%,Tm_FTr,Opp_eFG%,Opp_TS%,Opp_TOV%,Opp_ORB%,Opp_DRB%,Opp_FTr
0,WAS,59,11,48,0.186,39.6,89.8,26.6,51.0,13.0,...,14.1,23.0,73.1,0.233,0.551,0.587,11.6,26.9,77.0,0.259
1,UTA,59,15,44,0.254,40.3,87.8,26.3,48.5,14.0,...,15.0,27.9,74.8,0.258,0.555,0.586,10.4,25.2,72.1,0.246
2,TOR,60,18,42,0.300,41.6,89.5,30.1,56.6,11.5,...,13.7,26.3,73.8,0.235,0.547,0.584,12.8,26.2,73.7,0.288
3,SAS,58,25,33,0.431,41.2,89.8,27.6,50.3,13.7,...,12.4,24.3,73.0,0.237,0.538,0.566,11.9,27.0,75.7,0.196
4,SAC,59,31,28,0.525,43.4,90.9,30.9,55.2,12.5,...,11.9,25.3,76.9,0.239,0.548,0.584,12.7,23.1,74.7,0.252
5,POR,60,27,33,0.450,40.3,88.9,27.8,52.8,12.5,...,14.0,27.9,72.2,0.250,0.544,0.581,13.5,27.8,72.1,0.263
6,PHO,60,28,32,0.467,41.1,86.1,26.8,48.4,14.3,...,12.8,21.6,73.1,0.254,0.541,0.575,10.9,26.9,78.4,0.243
7,PHI,59,21,38,0.356,39.2,86.3,26.6,49.9,12.6,...,12.3,22.8,73.0,0.266,0.567,0.602,14.9,27.0,77.2,0.254
8,ORL,61,29,32,0.475,37.8,86.0,27.0,50.5,10.8,...,13.2,25.7,78.0,0.269,0.542,0.580,15.2,22.0,74.3,0.294
9,OKC,59,48,11,0.814,44.2,92.8,30.1,53.8,14.2,...,10.5,24.8,73.6,0.214,0.508,0.549,15.6,26.4,75.2,0.289
10,NYK,59,39,20,0.661,43.9,89.2,31.3,55.3,12.7,...,11.7,25.7,74.6,0.238,0.550,0.581,12.7,25.4,74.3,0.217
11,NOP,60,16,44,0.267,40.7,90.6,28.4,55.4,12.2,...,12.4,26.1,72.3,0.247,0.561,0.592,12.7,27.7,73.9,0.228
12,MIN,61,32,29,0.525,40.0,87.2,25.2,47.7,14.8,...,13.2,25.7,74.7,0.249,0.530,0.562,13.2,25.3,74.3,0.233
13,MIL,59,34,25,0.576,41.7,87.0,27.4,49.7,14.3,...,12.3,19.6,76.1,0.257,0.526,0.561,11.4,23.9,80.4,0.230
14,MIA,58,28,30,0.483,39.7,86.8,25.7,48.2,14.0,...,12.5,22.3,75.5,0.246,0.541,0.569,12.3,24.5,77.7,0.201
15,MEM,60,38,22,0.633,45.2,93.5,31.4,55.9,13.8,...,13.6,29.7,74.1,0.261,0.529,0.564,13.1,25.9,70.3,0.266
16,LAL,58,37,21,0.638,41.1,85.4,28.8,50.6,12.3,...,12.6,22.8,74.9,0.274,0.535,0.567,12.5,25.1,77.2,0.218
17,LAC,59,32,27,0.542,40.7,86.7,28.5,52.6,12.2,...,14.2,24.9,76.8,0.248,0.537,0.570,14.1,23.2,75.1,0.249
18,IND,58,33,25,0.569,43.4,88.5,30.5,53.8,12.9,...,12.1,21.2,74.2,0.241,0.548,0.582,13.2,25.8,78.8,0.254
19,HOU,60,37,23,0.617,41.6,93.2,29.4,57.7,12.2,...,11.9,31.2,75.6,0.249,0.522,0.555,13.0,24.4,68.8,0.253
20,GSW,60,32,28,0.533,41.1,91.9,25.8,49.3,15.3,...,12.0,27.4,75.8,0.228,0.539,0.573,13.6,24.2,72.6,0.249
21,DET,61,34,27,0.557,42.4,89.6,29.4,53.8,13.0,...,13.6,26.4,77.0,0.236,0.541,0.577,13.3,23.0,73.6,0.267
22,DEN,60,39,21,0.650,45.8,90.2,33.8,58.7,12.0,...,12.6,27.1,74.9,0.253,0.537,0.568,11.5,25.1,72.9,0.221
23,DAL,61,32,29,0.525,42.0,88.5,28.9,53.0,13.1,...,12.5,24.8,72.8,0.260,0.528,0.561,11.8,27.2,75.2,0.236
24,CLE,59,49,10,0.831,45.1,90.5,28.9,49.4,16.2,...,11.6,25.5,75.3,0.233,0.527,0.559,12.8,24.7,74.5,0.232
25,CHO,59,14,45,0.237,38.2,89.9,24.8,50.6,13.3,...,13.6,27.3,74.7,0.221,0.543,0.577,12.7,25.3,72.7,0.245
26,CHI,60,24,36,0.400,42.6,92.1,26.6,48.8,16.0,...,13.0,21.6,76.0,0.208,0.542,0.575,10.8,24.0,78.4,0.226
27,BRK,60,21,39,0.350,37.4,85.6,24.3,47.3,13.1,...,14.1,25.2,75.2,0.248,0.558,0.593,14.2,24.8,74.8,0.279
28,BOS,60,42,18,0.700,41.6,90.3,23.8,42.1,17.8,...,10.8,24.3,76.4,0.220,0.522,0.553,11.8,23.6,75.7,0.204
29,ATL,60,27,33,0.450,42.5,91.7,29.4,54.4,13.1,...,13.5,25.7,76.2,0.263,0.561,0.595,14.1,23.8,74.3,0.244

In [35]:
dfc.to_csv(f"../Data/Season.csv", index=False)