In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from bs4 import BeautifulSoup

# Setup WebDriver (Automatically finds the correct driver)
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

In [2]:
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")  # Opens browser in full-screen
options.add_argument("--disable-blink-features=AutomationControlled")  # Avoid detection
options.add_experimental_option("detach", True)  # Keeps browser open
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome() 

# Open the Google login page
driver.get("https://accounts.google.com/signin")

# Wait for the page to load
time.sleep(5)

# Find and fill in the email field
email_input = driver.find_element(By.ID, "identifierId")
email_input.send_keys("joel.tchapnda@aims.ac.rw")  # Replace with your email
email_input.send_keys(Keys.RETURN)
time.sleep(5)

In [3]:
shooting_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&comp_id=NBA&year_min=2025&comp_type=reg&order_by=fg&year_max=2025&team_game_min=1&match=team_game&timeframe=seasons&team_game_max=84&offset="
url= shooting_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_sh_data = [cell.text.strip() for cell in cells]
        print(col_sh_data)

['', '', '', 'Team', 'Opponent', 'Rk', 'Team', 'Date', 'FG', '', 'Opp', 'Result', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'PTS', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'PTS']

In [4]:
col_sh= col_sh_data[5:]

In [5]:
col_sh[8:21]

['FG',
 'FGA',
 'FG%',
 '2P',
 '2PA',
 '2P%',
 '3P',
 '3PA',
 '3P%',
 'FT',
 'FTA',
 'FT%',
 'PTS']

In [6]:
for i in range(8, 21):
    col_sh[i]= "Tm_"+ col_sh[i]
for i in range(21, 34):
    col_sh[i]= "Opp_"+ col_sh[i]

In [8]:
row_sh_data= []
for page in range(0, 2400, 200):
    url= shooting_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_sh_data.append(data)

In [9]:
df_sh= pd.DataFrame(row_sh_data, columns= col_sh)
df_sh

,Rk,Team,Date,FG,,Opp,Result,MP,Tm_FG,Tm_FGA,...,Opp_2P,Opp_2PA,Opp_2P%,Opp_3P,Opp_3PA,Opp_3P%,Opp_FT,Opp_FTA,Opp_FT%,Opp_PTS
0,1,DEN,2025-02-10,60,,POR,"W, 146-117",240,60,91,...,25,51,.490,15,37,.405,22,26,.846,117
1,2,IND,2025-03-27,59,@,WAS,"W, 162-109",240,59,92,...,27,55,.491,11,30,.367,22,26,.846,109
2,3,MEM,2024-12-26,58,,TOR,"W, 155-126",240,58,109,...,35,65,.538,14,43,.326,14,18,.778,126
3,4,SAS,2025-01-23,58,@,IND,"W, 140-110",240,58,96,...,31,54,.574,13,43,.302,9,12,.750,110
4,5,DEN,2025-03-07,57,,PHO,"W, 149-141 (OT)",265,57,97,...,35,53,.660,16,38,.421,23,29,.793,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,MIA,2025-02-24,27,@,ATL,"L, 86-98",240,27,84,...,31,53,.585,9,35,.257,9,12,.750,98
2290,2291,TOR,2024-12-31,27,@,BOS,"L, 71-125",240,27,86,...,25,44,.568,22,43,.512,9,15,.600,125
2291,2292,ORL,2025-01-23,26,,POR,"L, 79-101",240,26,76,...,31,54,.574,9,28,.321,12,19,.632,101
2292,2293,BRK,2025-01-15,25,@,LAC,"L, 67-126",240,25,83,...,31,47,.660,12,32,.375,28,30,.933,126
2293,2294,PHO,2024-11-15,22,@,OKC,"L, 83-99",240,22,75,...,26,51,.510,10,40,.250,17,18,.944,99

In [10]:
rebound_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&team_game_max=84&comp_type=reg&timeframe=seasons&order_by=orb&year_max=2025&comp_id=NBA&team_game_min=1&year_min=2025&match=team_game&offset="
url= rebound_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_rbd_data = [cell.text.strip() for cell in cells]
        print(col_rbd_data)

['', '', '', 'Team', 'Opponent', 'Rk', 'Team', 'Date', 'ORB', '', 'Opp', 'Result', 'MP', 'ORB', 'DRB', 'TRB', 'ORB', 'DRB', 'TRB']

In [11]:
col_rbd= col_rbd_data[5:]

In [12]:
for i in range(8, 11):
    col_rbd[i]= "Tm_"+ col_rbd[i]
for i in range(11, 14):
    col_rbd[i]= "Opp_"+ col_rbd[i]

In [13]:
row_rbd_data= []
for page in range(0, 2400, 200):
    url= rebound_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_rbd_data.append(data)

In [14]:
df_rbd= pd.DataFrame(row_rbd_data, columns= col_rbd)
df_rbd

,Rk,Team,Date,ORB,,Opp,Result,MP,Tm_ORB,Tm_DRB,Tm_TRB,Opp_ORB,Opp_DRB,Opp_TRB
0,1,TOR,2025-03-10,28,,WAS,"W, 119-104",240,28,45,73,16,38,54
1,2,UTA,2025-02-07,25,@,PHO,"L, 127-135 (OT)",265,25,38,63,12,37,49
2,3,HOU,2025-03-04,24,@,IND,"L, 102-115",240,24,34,58,5,30,35
3,4,MEM,2025-02-05,24,@,TOR,"W, 138-107",240,24,37,61,14,20,34
4,5,MEM,2024-12-26,24,,TOR,"W, 155-126",240,24,39,63,13,27,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,LAC,2025-03-21,2,,MEM,"W, 128-108",240,2,41,43,10,30,40
2290,2291,ORL,2024-11-20,2,@,LAC,"L, 93-104",240,2,22,24,15,34,49
2291,2292,PHI,2024-11-18,2,@,MIA,"L, 89-106",240,2,40,42,9,44,53
2292,2293,PHO,2024-12-03,2,,SAS,"W, 104-93",240,2,42,44,18,35,53
2293,2294,PHO,2025-01-20,1,@,CLE,"L, 92-118",240,1,33,34,15,35,50

In [15]:
basic_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&timeframe=seasons&year_min=2025&comp_type=reg&team_game_min=1&comp_id=NBA&year_max=2025&match=team_game&team_game_max=84&order_by=ast&offset="
url= basic_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_bsc_data = [cell.text.strip() for cell in cells]
        print(col_bsc_data)

['', '', '', 'Team', 'Opponent', 'Rk', 'Team', 'Date', 'AST', '', 'Opp', 'Result', 'MP', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'AST', 'STL', 'BLK', 'TOV', 'PF']

In [16]:
col_bsc= col_bsc_data[5:]

In [17]:
for i in range(8, 13):
    col_bsc[i]= "Tm_"+ col_bsc[i]
for i in range(13, 18):
    col_bsc[i]= "Opp_"+ col_bsc[i]

In [18]:
row_bsc_data= []
for page in range(0, 2400, 200):
    url= basic_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_bsc_data.append(data)

In [19]:
df_bsc= pd.DataFrame(row_bsc_data, columns= col_bsc)
df_bsc

,Rk,Team,Date,AST,,Opp,Result,MP,Tm_AST,Tm_STL,Tm_BLK,Tm_TOV,Tm_PF,Opp_AST,Opp_STL,Opp_BLK,Opp_TOV,Opp_PF
0,1,IND,2025-03-27,48,@,WAS,"W, 162-109",240,48,8,2,15,19,19,9,2,15,15
1,2,DEN,2025-03-07,45,,PHO,"W, 149-141 (OT)",265,45,8,3,9,22,36,6,2,13,18
2,3,NYK,2024-11-25,45,@,DEN,"W, 145-118",240,45,5,4,11,23,23,5,3,11,18
3,4,DEN,2025-02-10,44,,POR,"W, 146-117",240,44,12,2,10,23,25,4,4,16,20
4,5,DEN,2025-01-01,44,,ATL,"W, 139-120",240,44,8,5,13,16,34,10,5,14,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,PHI,2025-03-14,13,,IND,"L, 100-112",240,13,7,9,16,19,31,6,4,11,17
2290,2291,PHI,2024-12-21,13,@,CLE,"L, 99-126",240,13,7,3,13,16,31,8,1,13,18
2291,2292,POR,2024-11-08,13,@,MIN,"L, 102-127",240,13,11,7,17,17,32,9,7,20,21
2292,2293,LAC,2024-11-15,12,@,HOU,"L, 104-125",240,12,6,6,15,15,31,11,3,12,25
2293,2294,HOU,2025-01-03,9,,BOS,"L, 86-109",240,9,6,4,14,21,20,6,8,14,13

In [20]:
advanced_shooting_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&team_game_max=84&comp_type=reg&order_by=team_off_rtg&match=team_game&comp_id=NBA&timeframe=seasons&year_min=2025&team_game_min=1&year_max=2025&offset="
url= advanced_shooting_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_adv_sh_data = [cell.text.strip() for cell in cells]
        print(col_adv_sh_data)

['', '', '', 'Team', 'Opponent', 'Rk', 'Team', 'Date', 'ORtg', '', 'Opp', 'Result', 'ORtg', 'DRtg', 'FTr', '3PAr', 'TS%', 'eFG%', 'FT/FGA', 'ORtg', 'DRtg', 'FTr', '3PAr', 'TS%', 'eFG%', 'FT/FGA']

In [21]:
col_adv_sh= col_adv_sh_data[5:]

In [22]:
for i in range(7, 14):
    col_adv_sh[i]= "Tm_"+ col_adv_sh[i]
for i in range(14, 21):
    col_adv_sh[i]= "Opp_"+ col_adv_sh[i]

In [23]:
row_adv_sh_data= []
for page in range(0, 2400, 200):
    url= advanced_shooting_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_adv_sh_data.append(data)

In [24]:
df_adv_sh= pd.DataFrame(row_adv_sh_data, columns= col_adv_sh)
df_adv_sh

,Rk,Team,Date,ORtg,,Opp,Result,Tm_ORtg,Tm_DRtg,Tm_FTr,...,Tm_TS%,Tm_eFG%,Tm_FT/FGA,Opp_ORtg,Opp_DRtg,Opp_FTr,Opp_3PAr,Opp_TS%,Opp_eFG%,Opp_FT/FGA
0,1,IND,2025-03-27,163.4,@,WAS,"W, 162-109",163.4,109.9,.207,...,.807,.788,.185,109.9,163.4,.306,.353,.565,.512,.259
1,2,DEN,2025-01-21,149.7,,PHI,"W, 144-109",149.7,113.3,.294,...,.750,.706,.282,113.3,149.7,.083,.396,.548,.536,.063
2,3,BOS,2024-12-27,148.5,,IND,"W, 142-105",148.5,109.8,.315,...,.678,.636,.272,109.8,148.5,.275,.429,.515,.478,.198
3,4,OKC,2025-03-21,147.7,,CHO,"W, 141-106",147.7,111.0,.181,...,.695,.686,.128,111.0,147.7,.163,.513,.618,.581,.163
4,5,MEM,2025-03-25,147.6,@,UTA,"W, 140-103",147.6,108.6,.184,...,.661,.633,.163,108.6,147.6,.282,.538,.587,.545,.231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,CHO,2025-02-22,82.1,@,POR,"L, 88-141",82.1,131.6,.214,...,.410,.372,.153,131.6,82.1,.310,.494,.713,.701,.218
2290,2291,POR,2024-11-10,80.6,,MEM,"L, 89-134",80.6,121.4,.210,...,.407,.360,.170,121.4,80.6,.329,.506,.688,.647,.282
2291,2292,LAC,2024-12-04,80.1,,MIN,"L, 80-108",80.1,108.1,.157,...,.451,.416,.133,108.1,80.1,.212,.518,.581,.576,.118
2292,2293,TOR,2024-12-31,75.2,@,BOS,"L, 71-125",75.2,132.3,.128,...,.391,.372,.081,132.3,75.2,.172,.494,.668,.667,.103
2293,2294,BRK,2025-01-15,68.3,@,LAC,"L, 67-126",68.3,128.5,.265,...,.361,.331,.145,128.5,68.3,.380,.405,.683,.620,.354

In [25]:
advanced_rebounding_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&year_max=2025&match=team_game&order_by=team_orb_pct&timeframe=seasons&comp_type=reg&team_game_max=84&comp_id=NBA&year_min=2025&team_game_min=1&offset="
url= advanced_rebounding_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_adv_rb_data = [cell.text.strip() for cell in cells]
        print(col_adv_rb_data)

['', '', '', 'Team', 'Opponent', 'Rk', 'Team', 'Date', 'ORB%', '', 'Opp', 'Result', 'ORB%', 'DRB%', 'TRB%', 'ORB%', 'DRB%', 'TRB%']

In [26]:
col_adv_rb= col_adv_rb_data[5:]

In [27]:
for i in range(7, 10):
    col_adv_rb[i]= "Tm_"+ col_adv_rb[i]
for i in range(10, 13):
    col_adv_rb[i]= "Opp_"+ col_adv_rb[i]

In [28]:
row_adv_rb_data= []
for page in range(0, 2400, 200):
    url= advanced_rebounding_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_adv_rb_data.append(data)

In [29]:
df_adv_rb= pd.DataFrame(row_adv_rb_data, columns= col_adv_rb)
df_adv_rb

,Rk,Team,Date,ORB%,,Opp,Result,Tm_ORB%,Tm_DRB%,Tm_TRB%,Opp_ORB%,Opp_DRB%,Opp_TRB%
0,1,MEM,2025-02-05,54.5,@,TOR,"W, 138-107",54.5,72.5,35.8,27.5,45.5,35.8
1,2,TOR,2024-10-25,50.0,,PHI,"W, 115-107",50.0,78.3,34.1,21.7,50.0,34.1
2,3,MEM,2025-03-03,48.6,,ATL,"L, 130-132",48.6,65.0,42.7,35.0,51.4,42.7
3,4,POR,2024-10-27,47.8,,NOP,"W, 125-103",47.8,65.9,43.3,34.1,52.2,43.3
4,5,MEM,2024-12-26,47.1,,TOR,"W, 155-126",47.1,75.0,38.8,25.0,52.9,38.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,PHO,2024-12-03,5.4,,SAS,"W, 104-93",5.4,70.0,54.6,30.0,94.6,54.6
2290,2291,DAL,2024-12-30,4.8,@,SAC,"L, 100-110",4.8,65.4,61.7,34.6,95.2,61.7
2291,2292,PHI,2024-11-18,4.3,@,MIA,"L, 89-106",4.3,81.6,55.8,18.4,95.7,55.8
2292,2293,CHI,2024-12-08,4.2,,PHI,"L, 100-108",4.2,76.7,61.5,23.3,95.8,61.5
2293,2294,PHO,2025-01-20,2.8,@,CLE,"L, 92-118",2.8,68.8,59.5,31.3,97.2,59.5

In [30]:
advanced_url = "https://stathead.com/basketball/team-game-finder.cgi?request=1&team_game_min=1&team_game_max=84&comp_id=NBA&year_min=2025&timeframe=seasons&comp_type=reg&year_max=2025&order_by=team_ast_pct&match=team_game&offset="
url= advanced_url+ "0"
driver.get(url)

time.sleep(5)  # Wait for the page to load



# Get page source after login
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
table = soup.find("table")

table
if table:
    head = table.find_all("thead")
    for row in head:
        cells = row.find_all("th")
        col_adv_data = [cell.text.strip() for cell in cells]
        print(col_adv_data)

['', '', '', 'Advanced', 'Opponent', 'Rk', 'Team', 'Date', 'AST%', '', 'Opp', 'Result', 'AST%', 'STL%', 'BLK%', 'TOV%', 'AST%', 'STL%', 'BLK%', 'TOV%']

In [31]:
col_adv= col_adv_data[5:]

In [32]:
col_adv[11:14]

['AST%', 'STL%', 'BLK%']

In [33]:
for i in range(7, 11):
    col_adv[i]= "Tm_"+ col_adv[i]
for i in range(11, 15):
    col_adv[i]= "Opp_"+ col_adv[i]

In [34]:
row_adv_data= []
for page in range(0,2400, 200):
    url= advanced_url + str(page)
    driver.get(url)

    time.sleep(5)  # Wait for the page to load

# Get page source after login
    html = driver.page_source
    time.sleep(3)
    soup = BeautifulSoup(html, "html.parser")
    table = soup.find("table")
    body= table.find_all("tbody")
    rows= body[0].find_all("tr")
    for row in rows:
        cells= row.find_all(["th", "td"])
        data= [cell.text.strip() for cell in cells]
        if data[0] not in ['', 'Rk']:
            row_adv_data.append(data)

In [35]:
df_adv= pd.DataFrame(row_adv_data, columns= col_adv)
df_adv

,Rk,Team,Date,AST%,,Opp,Result,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,1,BRK,2024-11-17,96.9,@,NYK,"L, 104-114",96.9,1.1,6.3,9.2,76.7,4.4,14.3,7.7
1,2,SAS,2024-12-15,91.9,,MIN,"L, 92-106",91.9,6.0,12.3,16.7,65.0,11.0,8.7,10.1
2,3,WAS,2025-02-05,90.9,@,BRK,"W, 119-102",90.9,6.6,6.7,14.7,72.2,7.7,7.9,9.7
3,4,SAS,2025-02-23,90.6,@,NOP,"L, 96-114",90.6,10.7,11.5,8.5,64.3,2.9,6.5,13.9
4,5,LAC,2025-02-04,88.2,,LAL,"L, 97-122",88.2,9.5,11.4,9.3,73.3,7.4,6.3,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,HOU,2024-12-03,34.1,@,SAC,"L, 111-120",34.1,6.2,1.6,13.5,70.2,7.3,14.8,9.1
2290,2291,MEM,2025-01-13,33.3,@,HOU,"L, 118-120",33.3,17.0,4.0,16.2,68.3,13.0,15.4,19.6
2291,2292,POR,2024-11-08,33.3,@,MIN,"L, 102-127",33.3,10.4,14.9,14.3,68.1,8.5,10.6,16.2
2292,2293,HOU,2024-11-11,32.5,,WAS,"W, 107-92",32.5,11.9,17.5,17.6,58.3,13.9,7.8,16.9
2293,2294,HOU,2025-01-03,28.1,,BOS,"L, 86-109",28.1,7.0,10.5,13.0,51.3,7.0,15.4,14.2

In [36]:
dfs= [df_sh, df_rbd, df_bsc, df_adv_sh, df_adv_rb, df_adv]
for df in dfs:
    df.drop(df.columns[3], axis=1, inplace=True)

In [37]:
for df in dfs:
    df.rename(columns={"": "H/A"}, inplace=True)

In [38]:
df_adv

,Rk,Team,Date,H/A,Opp,Result,Tm_AST%,Tm_STL%,Tm_BLK%,Tm_TOV%,Opp_AST%,Opp_STL%,Opp_BLK%,Opp_TOV%
0,1,BRK,2024-11-17,@,NYK,"L, 104-114",96.9,1.1,6.3,9.2,76.7,4.4,14.3,7.7
1,2,SAS,2024-12-15,,MIN,"L, 92-106",91.9,6.0,12.3,16.7,65.0,11.0,8.7,10.1
2,3,WAS,2025-02-05,@,BRK,"W, 119-102",90.9,6.6,6.7,14.7,72.2,7.7,7.9,9.7
3,4,SAS,2025-02-23,@,NOP,"L, 96-114",90.6,10.7,11.5,8.5,64.3,2.9,6.5,13.9
4,5,LAC,2025-02-04,,LAL,"L, 97-122",88.2,9.5,11.4,9.3,73.3,7.4,6.3,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2290,HOU,2024-12-03,@,SAC,"L, 111-120",34.1,6.2,1.6,13.5,70.2,7.3,14.8,9.1
2290,2291,MEM,2025-01-13,@,HOU,"L, 118-120",33.3,17.0,4.0,16.2,68.3,13.0,15.4,19.6
2291,2292,POR,2024-11-08,@,MIN,"L, 102-127",33.3,10.4,14.9,14.3,68.1,8.5,10.6,16.2
2292,2293,HOU,2024-11-11,,WAS,"W, 107-92",32.5,11.9,17.5,17.6,58.3,13.9,7.8,16.9
2293,2294,HOU,2025-01-03,,BOS,"L, 86-109",28.1,7.0,10.5,13.0,51.3,7.0,15.4,14.2

In [39]:
df_sh.to_csv("../Data/Shooting.csv", index=False)
df_rbd.to_csv("../Data/Rebounding.csv", index=False)
df_bsc.to_csv("../Data/Basic.csv", index=False)
df_adv_sh.to_csv("../Data/Advanced Shooting.csv", index=False)
df_adv_rb.to_csv("../Data/Advanced Rebounding.csv", index=False)
df_adv.to_csv("../Data/Advanced.csv", index=False)