In [57]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error
sns.set_theme(style="darkgrid")

# Teams

In [58]:
home= "Sevilla"
away= "Mallorca"

In [59]:
df_home= pd.read_csv(f"../Data/{home}.csv")
df_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Sevilla,Las Palmas,2024-08-16,D,A,2,2,0,1,0,...,1.5,1.5,-0.8,-0.8,-0.5,0.10,0,1.1,0.23,0.1
1,Sevilla,Villarreal,2024-08-23,L,H,1,2,-1,1,0,...,0.5,0.6,0.0,0.0,0.5,0.07,1,0.9,0.15,-1.1
2,Sevilla,Mallorca,2024-08-27,D,A,0,0,0,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.05,0,0.9,0.22,0.9
3,Sevilla,Girona,2024-09-01,L,H,0,2,-2,0,0,...,0.6,0.5,-0.9,-0.9,-0.6,0.06,2,1.7,0.24,-0.3
4,Sevilla,Getafe,2024-09-14,W,H,1,0,1,1,0,...,0.9,0.3,-0.4,-0.4,0.1,0.14,0,0.4,0.10,0.4
5,Sevilla,Alavés,2024-09-20,L,A,1,2,-1,1,0,...,0.5,0.5,0.5,0.5,0.5,0.07,0,0.8,0.19,-1.2
6,Sevilla,Valladolid,2024-09-24,W,H,2,1,1,1,0,...,1.5,1.0,-1.1,-1.1,-1.5,0.10,0,0.9,0.46,-0.1
7,Sevilla,Athletic Club,2024-09-29,D,A,1,1,0,0,0,...,0.4,0.3,-1.1,-1.1,-0.4,0.09,2,1.4,0.27,0.4
8,Sevilla,Betis,2024-10-06,W,H,1,0,1,0,1,...,0.5,0.4,-0.4,-0.7,-0.5,0.05,1,0.6,0.19,0.6
9,Sevilla,Barcelona,2024-10-20,L,A,1,5,-4,1,0,...,0.9,0.2,0.0,0.0,0.1,0.14,0,4.5,0.41,-0.5
10,Sevilla,Espanyol,2024-10-25,W,A,2,0,2,2,0,...,0.6,0.9,1.2,1.2,1.4,0.13,0,0.1,0.07,0.1
11,Sevilla,Real Sociedad,2024-11-03,L,H,0,2,-2,0,0,...,0.3,0.3,-1.1,-1.1,-0.3,0.14,0,1.1,0.08,-0.9
12,Sevilla,Leganés,2024-11-09,L,A,0,1,-1,0,0,...,0.5,0.6,-0.6,-0.6,-0.5,0.04,0,1.3,0.07,0.3
13,Sevilla,Rayo Vallecano,2024-11-24,W,H,1,0,1,1,0,...,1.0,0.5,-0.1,-0.1,0.0,0.10,0,0.1,0.06,0.1
14,Sevilla,Osasuna,2024-12-02,D,H,1,1,0,1,0,...,1.3,1.1,-0.3,-0.3,-0.3,0.11,0,0.5,0.17,-0.5
15,Sevilla,Atlético Madrid,2024-12-08,L,A,3,4,-1,3,0,...,0.4,0.7,2.6,2.6,2.6,0.11,0,2.6,0.28,-1.4
16,Sevilla,Celta Vigo,2024-12-14,W,H,1,0,1,1,0,...,0.5,0.3,0.3,0.3,0.5,0.08,0,1.1,0.54,1.1
17,Sevilla,Real Madrid,2024-12-22,L,A,2,4,-2,2,0,...,1.2,0.8,0.7,0.7,0.8,0.13,0,1.8,0.26,-2.2
18,Sevilla,Valencia,2025-01-11,D,H,1,1,0,1,0,...,0.5,0.5,0.5,0.5,0.5,0.04,0,0.3,0.27,-0.7
19,Sevilla,Girona,2025-01-18,W,A,2,1,1,2,0,...,1.4,0.7,-0.6,0.2,-0.4,0.15,0,1.5,0.37,0.5
20,Sevilla,Espanyol,2025-01-25,D,H,1,1,0,1,0,...,0.9,0.8,-0.2,-0.2,0.1,0.05,1,0.8,0.79,-0.2
21,Sevilla,Getafe,2025-02-01,D,A,0,0,0,0,0,...,0.6,0.3,-0.9,-0.9,-0.6,0.07,1,0.4,0.43,0.4
22,Sevilla,Barcelona,2025-02-09,L,H,1,4,-3,1,0,...,0.6,1.1,0.3,0.3,0.4,0.09,0,2.8,0.48,-1.2
23,Sevilla,Valladolid,2025-02-16,W,A,4,0,4,4,0,...,0.8,0.3,2.9,2.9,3.2,0.10,0,0.1,0.11,0.1

In [60]:
df_vs_home= pd.read_csv(f"../Data/vs {home}.csv")
df_vs_home

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Las Palmas,Sevilla,2024-08-16,D,H,2,2,0,1,0,...,1.4,1.1,-0.4,-0.4,-0.4,0.09,0,1.5,0.31,0.5
1,Villarreal,Sevilla,2024-08-23,W,A,2,1,1,2,0,...,0.7,0.6,1.1,1.1,0.3,0.11,0,0.8,0.11,-0.2
2,Mallorca,Sevilla,2024-08-27,D,H,0,0,0,0,0,...,0.4,0.8,-0.9,-0.9,-0.4,0.08,0,1.0,0.14,1.0
3,Girona,Sevilla,2024-09-01,W,A,2,0,2,1,1,...,0.9,1.1,0.1,-0.2,0.1,0.12,0,0.4,0.07,0.4
4,Getafe,Sevilla,2024-09-14,L,A,0,1,-1,0,0,...,0.8,0.5,-1.0,-1.0,-0.8,0.07,1,1.1,0.28,0.1
5,Alavés,Sevilla,2024-09-20,W,H,2,1,1,2,0,...,0.7,0.6,0.9,0.9,0.3,0.12,1,1.5,0.74,0.5
6,Valladolid,Sevilla,2024-09-24,L,A,1,2,-1,1,0,...,0.5,0.7,0.3,0.3,0.5,0.09,1,1.5,0.30,0.5
7,Athletic Club,Sevilla,2024-09-29,D,H,1,1,0,1,0,...,1.5,1.0,-1.0,-1.0,-0.5,0.15,0,0.3,0.09,0.3
8,Betis,Sevilla,2024-10-06,L,A,0,1,-1,0,0,...,0.4,0.7,-0.6,-0.6,-0.4,0.06,0,0.8,0.04,-0.2
9,Barcelona,Sevilla,2024-10-20,W,H,5,1,4,4,1,...,2.7,1.8,1.2,0.9,-0.7,0.16,1,0.8,0.82,-0.2
10,Espanyol,Sevilla,2024-10-25,L,H,0,2,-2,0,0,...,0.7,0.8,-1.2,-1.2,-0.7,0.08,1,2.1,0.71,0.1
11,Real Sociedad,Sevilla,2024-11-03,W,A,2,0,2,1,1,...,0.6,0.6,0.6,0.4,0.4,0.07,0,0.0,NaN,0.0
12,Leganés,Sevilla,2024-11-09,W,H,1,0,1,0,1,...,0.2,0.2,-0.1,-0.3,-0.2,0.04,2,0.1,0.04,0.1
13,Rayo Vallecano,Sevilla,2024-11-24,L,A,0,1,-1,0,0,...,0.6,0.4,-0.8,-0.8,-0.6,0.10,1,1.1,0.35,0.1
14,Osasuna,Sevilla,2024-12-02,D,A,1,1,0,1,0,...,0.6,0.4,0.3,0.3,0.4,0.11,0,1.7,0.34,0.7
15,Atlético Madrid,Sevilla,2024-12-08,W,H,4,3,1,4,0,...,1.9,1.6,2.0,2.0,1.1,0.15,0,1.4,0.47,-1.6
16,Celta Vigo,Sevilla,2024-12-14,L,A,0,1,-1,0,0,...,1.1,0.7,-1.2,-1.2,-1.1,0.12,0,0.8,0.25,-0.2
17,Real Madrid,Sevilla,2024-12-22,W,H,4,2,2,4,0,...,1.9,1.8,2.0,2.0,2.1,0.13,0,1.3,0.32,-0.7
18,Valencia,Sevilla,2025-01-11,D,A,1,1,0,1,0,...,0.5,0.4,0.3,0.3,0.5,0.13,0,0.3,0.06,-0.7
19,Girona,Sevilla,2025-01-18,L,H,1,2,-1,1,0,...,0.8,1.0,0.0,0.0,0.2,0.14,0,2.5,0.35,0.5
20,Espanyol,Sevilla,2025-01-25,D,A,1,1,0,1,0,...,0.2,0.5,0.3,0.3,-0.2,0.12,1,0.5,0.12,-0.5
21,Getafe,Sevilla,2025-02-01,D,H,0,0,0,0,0,...,0.5,0.2,-1.0,-1.0,-0.5,0.14,0,0.0,NaN,0.0
22,Barcelona,Sevilla,2025-02-09,W,A,4,1,3,4,0,...,1.4,1.7,2.1,2.1,1.6,0.19,0,1.1,0.28,0.1
23,Valladolid,Sevilla,2025-02-16,L,H,0,4,-4,0,0,...,0.4,0.7,-0.5,-0.5,-0.4,0.07,0,2.8,0.47,-1.2

In [61]:
df_away= pd.read_csv(f"../Data/{away}.csv")
df_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Mallorca,Real Madrid,2024-08-18,D,H,1,1,0,1,0,...,0.4,0.5,0.0,0.0,0.6,0.09,0,1.2,0.25,0.2
1,Mallorca,Osasuna,2024-08-24,L,A,0,1,-1,0,0,...,0.6,1.1,-0.6,-0.6,-0.6,0.06,0,0.6,0.12,-0.4
2,Mallorca,Sevilla,2024-08-27,D,H,0,0,0,0,0,...,0.4,0.8,-0.9,-0.9,-0.4,0.08,0,1.0,0.14,1.0
3,Mallorca,Leganés,2024-08-31,W,A,1,0,1,1,0,...,0.7,1.4,0.0,0.0,0.3,0.08,0,0.0,0.01,0.0
4,Mallorca,Villarreal,2024-09-14,L,H,1,2,-1,0,0,...,0.2,0.5,-0.3,-0.3,-0.2,0.04,0,2.0,0.51,0.0
5,Mallorca,Real Sociedad,2024-09-17,W,H,1,0,1,0,1,...,0.4,0.5,-0.2,-0.4,-0.4,0.04,0,0.2,0.05,0.2
6,Mallorca,Betis,2024-09-23,W,A,2,1,1,2,0,...,0.9,0.5,1.0,1.0,1.1,0.15,0,1.0,0.17,0.0
7,Mallorca,Valladolid,2024-09-27,W,A,2,1,1,2,0,...,1.8,0.8,-0.2,-0.2,-0.8,0.13,0,0.9,0.88,-0.1
8,Mallorca,Espanyol,2024-10-05,L,A,1,2,-1,1,0,...,1.4,0.8,-0.6,-0.6,-0.4,0.16,1,1.1,0.38,-0.9
9,Mallorca,Rayo Vallecano,2024-10-20,W,H,1,0,1,1,0,...,1.6,1.3,-1.0,-1.0,-0.6,0.11,0,0.1,0.06,0.1
10,Mallorca,Athletic Club,2024-10-28,D,H,0,0,0,0,0,...,0.4,0.3,-0.5,-0.5,-0.4,0.15,0,0.1,0.07,0.1
11,Mallorca,Alavés,2024-11-01,L,A,0,1,-1,0,0,...,0.3,0.6,-0.5,-0.5,-0.3,0.07,0,1.2,0.40,0.2
12,Mallorca,Atlético Madrid,2024-11-10,L,H,0,1,-1,0,0,...,0.5,0.8,-0.6,-0.6,-0.5,0.05,2,1.2,0.58,0.2
13,Mallorca,Las Palmas,2024-11-23,W,A,3,2,1,3,0,...,1.1,0.9,1.3,1.3,0.9,0.19,0,1.0,0.10,-1.0
14,Mallorca,Valencia,2024-11-29,W,H,2,1,1,2,0,...,0.6,0.6,1.2,1.2,1.4,0.08,0,0.6,0.00,-0.4
15,Mallorca,Barcelona,2024-12-03,L,H,1,5,-4,1,0,...,0.8,0.8,0.1,0.1,0.2,0.16,0,5.2,0.51,0.2
16,Mallorca,Celta Vigo,2024-12-06,L,A,0,2,-2,0,0,...,0.8,0.9,-0.8,-0.8,-0.8,0.09,0,0.4,0.08,-1.6
17,Mallorca,Girona,2024-12-14,W,H,2,1,1,2,0,...,0.6,0.6,0.8,0.8,0.4,0.15,0,0.9,0.87,-0.1
18,Mallorca,Getafe,2024-12-21,W,A,1,0,1,0,1,...,1.4,0.5,-1.3,-1.5,-1.4,0.19,0,0.7,0.13,0.7
19,Mallorca,Villarreal,2025-01-20,L,A,0,4,-4,0,0,...,0.4,0.5,-0.5,-0.5,-0.4,0.06,1,3.1,0.44,-0.9
20,Mallorca,Betis,2025-01-25,L,H,0,1,-1,0,0,...,0.7,0.7,-1.0,-1.0,-0.7,0.06,1,0.7,0.24,-0.3
21,Mallorca,Atlético Madrid,2025-02-01,L,A,0,2,-2,0,0,...,0.5,0.7,-0.5,-0.5,-0.5,0.05,0,1.6,0.33,-0.4
22,Mallorca,Osasuna,2025-02-10,D,H,1,1,0,0,1,...,0.2,0.7,-0.3,-0.5,-0.2,0.05,1,1.0,0.32,0.0
23,Mallorca,Las Palmas,2025-02-16,W,H,3,1,2,3,0,...,1.3,1.5,1.3,1.3,0.7,0.12,0,0.9,0.23,-0.1

In [62]:
df_vs_away= pd.read_csv(f"../Data/vs {away}.csv")
df_vs_away

,Team,Opp,Date,Result,H/A,GF,GA,GD,G-PK,PK,...,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,PSxG,PSxG/SoT,PSxG+/-
0,Real Madrid,Mallorca,2024-08-18,D,A,1,1,0,1,0,...,0.4,1.0,0.4,0.4,0.6,0.05,0,0.6,0.12,-0.4
1,Osasuna,Mallorca,2024-08-24,W,H,1,0,1,1,0,...,0.2,0.3,0.4,0.4,-0.2,0.04,1,0.1,0.06,0.1
2,Sevilla,Mallorca,2024-08-27,D,A,0,0,0,0,0,...,0.6,0.5,-0.7,-0.7,-0.6,0.05,0,0.9,0.22,0.9
3,Leganés,Mallorca,2024-08-31,L,H,0,1,-1,0,0,...,0.3,0.7,-0.3,-0.3,-0.3,0.04,0,1.2,0.39,0.2
4,Villarreal,Mallorca,2024-09-14,W,A,2,1,1,2,0,...,1.6,2.4,0.2,0.2,0.4,0.08,0,0.3,0.08,0.3
5,Real Sociedad,Mallorca,2024-09-17,L,A,0,1,-1,0,0,...,0.5,0.6,-0.6,-0.6,-0.5,0.05,0,0.9,0.08,-0.1
6,Betis,Mallorca,2024-09-23,L,H,1,2,-1,1,0,...,0.9,1.0,0.0,0.0,0.1,0.06,0,1.3,0.21,-0.7
7,Valladolid,Mallorca,2024-09-27,L,H,1,2,-1,1,0,...,0.6,0.6,-0.2,-0.2,0.4,0.10,0,2.8,0.47,0.8
8,Espanyol,Mallorca,2024-10-05,W,H,2,1,1,2,0,...,0.9,0.8,1.1,1.1,1.1,0.12,0,2.6,0.52,1.6
9,Rayo Vallecano,Mallorca,2024-10-20,L,A,0,1,-1,0,0,...,0.6,0.4,-0.6,-0.6,-0.6,0.06,0,1.6,0.31,0.6
10,Athletic Club,Mallorca,2024-10-28,D,A,0,0,0,0,0,...,0.4,1.0,-0.6,-0.6,-0.4,0.03,0,0.3,0.28,0.3
11,Alavés,Mallorca,2024-11-01,W,H,1,0,1,1,0,...,0.7,0.6,-0.1,-0.1,-0.7,0.09,0,0.3,0.15,0.3
12,Atlético Madrid,Mallorca,2024-11-10,W,A,1,0,1,1,0,...,0.6,0.6,0.4,0.4,0.4,0.07,0,0.2,0.04,0.2
13,Las Palmas,Mallorca,2024-11-23,L,H,2,3,-1,1,1,...,0.2,0.6,0.8,0.6,-0.2,0.03,1,1.9,0.63,-1.1
14,Valencia,Mallorca,2024-11-29,L,A,1,2,-1,0,1,...,0.5,0.4,-0.3,-0.5,-0.5,0.09,0,1.5,0.50,-0.5
15,Barcelona,Mallorca,2024-12-03,W,A,5,1,4,4,1,...,3.1,1.7,0.0,-0.2,-1.1,0.23,1,1.0,0.99,0.0
16,Celta Vigo,Mallorca,2024-12-06,W,H,2,0,2,2,0,...,0.8,0.9,1.1,1.1,1.2,0.07,2,1.9,0.46,1.9
17,Girona,Mallorca,2024-12-14,L,A,1,2,-1,1,0,...,0.6,1.0,0.2,0.2,-0.6,0.06,0,1.7,0.87,-0.3
18,Getafe,Mallorca,2024-12-21,L,H,0,1,-1,0,0,...,0.6,0.6,-0.8,-0.8,-0.6,0.05,0,1.2,0.21,0.2
19,Villarreal,Mallorca,2025-01-20,W,H,4,0,4,4,0,...,2.4,2.2,1.6,1.6,1.6,0.17,0,0.3,0.17,0.3
20,Betis,Mallorca,2025-01-25,W,A,1,0,1,1,0,...,0.3,0.8,0.6,0.6,0.7,0.05,0,0.8,0.26,0.8
21,Atlético Madrid,Mallorca,2025-02-01,W,H,2,0,2,2,0,...,1.1,1.5,0.7,0.7,0.9,0.08,1,0.0,0.02,0.0
22,Osasuna,Mallorca,2025-02-10,D,A,1,1,0,1,0,...,0.8,1.0,-0.4,-0.4,-0.8,0.09,0,0.8,0.02,-0.2
23,Las Palmas,Mallorca,2025-02-16,L,A,1,3,-2,1,0,...,0.8,0.7,0.2,0.2,0.2,0.09,0,2.2,0.45,-0.8

In [63]:
print(list(df_away.columns))

['Team', 'Opp', 'Date', 'Result', 'H/A', 'GF', 'GA', 'GD', 'G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att (GK)', 'Thr', 'Pa Launch%', 'Pa AvgLen', 'Won', 'Lost', 'Won%', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 'PrgC', 'Last3rd Car', 'OppCr', 'Stp', 'Stp%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'GK Att', 'Launch%', 'AvgLen', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'PKcon', 'OG', 'Recov', '#OPA', 'AvgDist', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'PKdef', 'PKA', 'PKms', 'Missed PK%', 'PKAg', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 'Fld Sc', 'Def-Sc', 'SoTA', 'Saves', 'Save%', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'xG', 'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'PSxG', 'PSxG/SoT', 'PSxG+/-']

# Features

## Offense

In [64]:
offense= ['G-PK', 'PK', 'PKm', 'Poss', 'PKatt', 'Att To', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist', 'PrgDist', 
          'PrgC', 'Last3rd Car', 'GCA', 'PassLive Gc', 'PassDead Gc', 'TO Gc', 'Sh-Gc', 'Fld Gc', 'Def-Gc', 'Sh', 'G/Sh', 
          'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Off', 'PKwon', 'Cmp', 'Pas Att', 'Cmp%', 'KP', 'Last3rd PA', 'PPA', 'CrsPA', 
          'PrgP', 'TotDist Pas', 'PrgDist Pas', 'Cmp 5-15', 'Att 5-15', 'Cmp% 5-15', 'Cmp 15-30', 'Att 15-30', 'Cmp% 15-30', 
          'Cmp 30+', 'Att 30+', 'Cmp% 30+', 'Live Pas', 'Dead', 'Pas FK', 'TB', 'Sw', 'Crs', 'TI', 'CK', 'In', 'Out', 'Str', 
          'Ps Off', 'PTo', 'Rec', 'Last3rd Rec', 'CPA', 'Mis', 'Dis', 'SCA', 'PassLive Sc', 'PassDead Sc', 'TO Sc', 'Sh-Sh', 
          'Fld Sc', 'Def-Sc', 'Touches', 'Def Pen', 'Tch Def 3rd', 'Tch Mid 3rd', 'Tch Att 3rd', 'Att Pen', 'Live Tch', 'xG', 
          'npxG', 'xGD', 'npxGD', 'xAG', 'xA', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'FKAtt', 'GF']

In [65]:
df_home_off= df_home[offense]
df_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,52,0,20,7,35.0,9,45.0,...,0.4,0.4,1.5,1.5,-0.8,-0.8,-0.5,0.10,0,2
1,1,0,0,59,0,26,14,53.8,9,34.6,...,0.2,0.2,0.5,0.6,0.0,0.0,0.5,0.07,1,1
2,0,0,0,55,0,10,5,50.0,5,50.0,...,-0.1,-0.1,0.6,0.5,-0.7,-0.7,-0.6,0.05,0,0
3,0,0,0,50,0,27,10,37.0,12,44.4,...,-1.0,-0.2,0.6,0.5,-0.9,-0.9,-0.6,0.06,2,0
4,1,0,0,60,0,28,16,57.1,9,32.1,...,0.4,0.4,0.9,0.3,-0.4,-0.4,0.1,0.14,0,1
5,1,0,0,65,0,21,12,57.1,9,42.9,...,-0.6,-0.6,0.5,0.5,0.5,0.5,0.5,0.07,0,1
6,1,0,0,54,0,20,7,35.0,12,60.0,...,1.5,1.5,1.5,1.0,-1.1,-1.1,-1.5,0.10,0,2
7,0,0,0,61,0,28,15,53.6,9,32.1,...,-0.9,-0.9,0.4,0.3,-1.1,-1.1,-0.4,0.09,2,1
8,0,1,0,51,1,20,14,70.0,5,25.0,...,0.8,0.0,0.5,0.4,-0.4,-0.7,-0.5,0.05,1,1
9,1,0,0,33,0,21,10,47.6,9,42.9,...,-2.9,-2.1,0.9,0.2,0.0,0.0,0.1,0.14,0,1
10,2,0,0,57,0,18,9,50.0,7,38.9,...,-0.4,-0.4,0.6,0.9,1.2,1.2,1.4,0.13,0,2
11,0,0,0,55,0,17,6,35.3,11,64.7,...,-0.3,0.5,0.3,0.3,-1.1,-1.1,-0.3,0.14,0,0
12,0,0,0,57,0,19,7,36.8,11,57.9,...,-0.5,0.3,0.5,0.6,-0.6,-0.6,-0.5,0.04,0,0
13,1,0,0,53,0,18,9,50.0,8,44.4,...,0.2,0.2,1.0,0.5,-0.1,-0.1,0.0,0.10,0,1
14,1,0,0,64,0,16,5,31.3,11,68.8,...,0.6,0.6,1.3,1.1,-0.3,-0.3,-0.3,0.11,0,1
15,3,0,0,43,0,17,9,52.9,8,47.1,...,-1.6,-1.6,0.4,0.7,2.6,2.6,2.6,0.11,0,3
16,1,0,0,45,0,15,5,33.3,9,60.0,...,-0.5,-0.5,0.5,0.3,0.3,0.3,0.5,0.08,0,1
17,2,0,0,41,0,23,12,52.2,9,39.1,...,-0.7,-0.7,1.2,0.8,0.7,0.7,0.8,0.13,0,2
18,1,0,0,54,0,16,6,37.5,9,56.3,...,-0.1,-0.1,0.5,0.5,0.5,0.5,0.5,0.04,0,1
19,2,0,1,40,1,18,6,33.3,9,50.0,...,1.6,0.8,1.4,0.7,-0.6,0.2,-0.4,0.15,0,2
20,1,0,0,74,0,36,12,33.3,20,55.6,...,0.5,0.5,0.9,0.8,-0.2,-0.2,0.1,0.05,1,1
21,0,0,0,55,0,22,14,63.6,7,31.8,...,-0.1,-0.1,0.6,0.3,-0.9,-0.9,-0.6,0.07,1,0
22,1,0,0,40,0,22,11,50.0,8,36.4,...,-1.2,-1.2,0.6,1.1,0.3,0.3,0.4,0.09,0,1
23,4,0,0,48,0,14,5,35.7,7,50.0,...,0.6,0.6,0.8,0.3,2.9,2.9,3.2,0.10,0,4

In [66]:
df_vs_home_off= df_vs_home[offense]
df_vs_home_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,48,0,13,3,23.1,7,53.8,...,-0.4,-0.4,1.4,1.1,-0.4,-0.4,-0.4,0.09,0,2
1,2,0,0,41,0,15,3,20.0,8,53.3,...,-0.2,-0.2,0.7,0.6,1.1,1.1,0.3,0.11,0,2
2,0,0,0,45,0,10,6,60.0,3,30.0,...,0.1,0.1,0.4,0.8,-0.9,-0.9,-0.4,0.08,0,0
3,1,1,0,50,1,23,10,43.5,12,52.2,...,1.0,0.2,0.9,1.1,0.1,-0.2,0.1,0.12,0,2
4,0,0,0,40,0,12,4,33.3,4,33.3,...,-0.4,-0.4,0.8,0.5,-1.0,-1.0,-0.8,0.07,1,0
5,2,0,0,35,0,10,2,20.0,8,80.0,...,0.6,0.6,0.7,0.6,0.9,0.9,0.3,0.12,1,2
6,1,0,0,46,0,15,6,40.0,6,40.0,...,-1.5,-1.5,0.5,0.7,0.3,0.3,0.5,0.09,1,1
7,1,0,0,39,0,20,5,25.0,13,65.0,...,0.9,0.9,1.5,1.0,-1.0,-1.0,-0.5,0.15,0,1
8,0,0,0,49,0,15,6,40.0,7,46.7,...,-0.8,0.0,0.4,0.7,-0.6,-0.6,-0.4,0.06,0,0
9,4,1,0,67,1,28,14,50.0,10,35.7,...,2.9,2.1,2.7,1.8,1.2,0.9,-0.7,0.16,1,5
10,0,0,0,43,0,17,4,23.5,11,64.7,...,0.4,0.4,0.7,0.8,-1.2,-1.2,-0.7,0.08,1,0
11,1,1,0,45,1,11,5,45.5,6,54.5,...,0.3,-0.5,0.6,0.6,0.6,0.4,0.4,0.07,0,2
12,0,1,0,43,1,12,7,58.3,5,41.7,...,0.5,-0.3,0.2,0.2,-0.1,-0.3,-0.2,0.04,2,1
13,0,0,0,47,0,13,5,38.5,5,38.5,...,-0.2,-0.2,0.6,0.4,-0.8,-0.8,-0.6,0.10,1,0
14,1,0,0,36,0,12,5,41.7,7,58.3,...,-0.6,-0.6,0.6,0.4,0.3,0.3,0.4,0.11,0,1
15,4,0,0,57,0,25,12,48.0,12,48.0,...,1.6,1.6,1.9,1.6,2.0,2.0,1.1,0.15,0,4
16,0,0,0,55,0,20,8,40.0,9,45.0,...,0.5,0.5,1.1,0.7,-1.2,-1.2,-1.1,0.12,0,0
17,4,0,0,59,0,17,7,41.2,6,35.3,...,0.7,0.7,1.9,1.8,2.0,2.0,2.1,0.13,0,4
18,1,0,0,46,0,13,6,46.2,7,53.8,...,0.1,0.1,0.5,0.4,0.3,0.3,0.5,0.13,0,1
19,1,0,0,60,0,19,6,31.6,10,52.6,...,-1.6,-0.8,0.8,1.0,0.0,0.0,0.2,0.14,0,1
20,1,0,0,26,0,14,6,42.9,5,35.7,...,-0.5,-0.5,0.2,0.5,0.3,0.3,-0.2,0.12,1,1
21,0,0,0,45,0,10,5,50.0,4,40.0,...,0.1,0.1,0.5,0.2,-1.0,-1.0,-0.5,0.14,0,0
22,4,0,0,60,0,22,10,45.5,11,50.0,...,1.2,1.2,1.4,1.7,2.1,2.1,1.6,0.19,0,4
23,0,0,0,52,0,14,8,57.1,4,28.6,...,-0.6,-0.6,0.4,0.7,-0.5,-0.5,-0.4,0.07,0,0

In [67]:
df_away_off= df_away[offense]
df_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,34,0,15,6,40.0,9,60.0,...,0.4,0.4,0.4,0.5,0.0,0.0,0.6,0.09,0,1
1,0,0,0,54,0,24,9,37.5,14,58.3,...,0.0,0.0,0.6,1.1,-0.6,-0.6,-0.6,0.06,0,0
2,0,0,0,45,0,10,6,60.0,3,30.0,...,0.1,0.1,0.4,0.8,-0.9,-0.9,-0.4,0.08,0,0
3,1,0,0,46,0,10,3,30.0,6,60.0,...,0.7,0.7,0.7,1.4,0.0,0.0,0.3,0.08,0,1
4,0,0,0,53,0,12,4,33.3,6,50.0,...,-1.4,-1.4,0.2,0.5,-0.3,-0.3,-0.2,0.04,0,1
5,0,1,0,40,1,13,10,76.9,2,15.4,...,0.6,-0.2,0.4,0.5,-0.2,-0.4,-0.4,0.04,0,1
6,2,0,0,39,0,15,6,40.0,8,53.3,...,0.0,0.0,0.9,0.5,1.0,1.0,1.1,0.15,0,2
7,2,0,0,49,0,17,10,58.8,6,35.3,...,1.1,1.1,1.8,0.8,-0.2,-0.2,-0.8,0.13,0,2
8,1,0,0,60,0,19,12,63.2,7,36.8,...,0.7,0.7,1.4,0.8,-0.6,-0.6,-0.4,0.16,1,1
9,1,0,0,51,0,14,5,35.7,4,28.6,...,1.4,1.4,1.6,1.3,-1.0,-1.0,-0.6,0.11,0,1
10,0,0,0,33,0,16,5,31.3,11,68.8,...,-0.1,-0.1,0.4,0.3,-0.5,-0.5,-0.4,0.15,0,0
11,0,0,0,49,0,18,7,38.9,7,38.9,...,-0.6,-0.6,0.3,0.6,-0.5,-0.5,-0.3,0.07,0,0
12,0,0,0,53,0,18,7,38.9,8,44.4,...,0.0,0.0,0.5,0.8,-0.6,-0.6,-0.5,0.05,2,0
13,3,0,0,39,0,11,5,45.5,5,45.5,...,0.5,1.3,1.1,0.9,1.3,1.3,0.9,0.19,0,3
14,2,0,0,48,0,12,6,50.0,3,25.0,...,-0.5,0.2,0.6,0.6,1.2,1.2,1.4,0.08,0,2
15,1,0,0,41,0,12,3,25.0,5,41.7,...,-4.1,-3.3,0.8,0.8,0.1,0.1,0.2,0.16,0,1
16,0,0,0,50,0,11,6,54.5,4,36.4,...,0.0,0.0,0.8,0.9,-0.8,-0.8,-0.8,0.09,0,0
17,2,0,0,32,0,13,6,46.2,7,53.8,...,0.4,0.4,0.6,0.6,0.8,0.8,0.4,0.15,0,2
18,0,1,0,46,1,13,3,23.1,4,30.8,...,1.5,0.7,1.4,0.5,-1.3,-1.5,-1.4,0.19,0,1
19,0,0,0,57,0,17,5,29.4,10,58.8,...,-1.9,-1.9,0.4,0.5,-0.5,-0.5,-0.4,0.06,1,0
20,0,0,0,48,0,35,15,42.9,17,48.6,...,0.6,0.6,0.7,0.7,-1.0,-1.0,-0.7,0.06,1,0
21,0,0,0,47,0,15,7,46.7,6,40.0,...,-0.8,-0.8,0.5,0.7,-0.5,-0.5,-0.5,0.05,0,0
22,0,1,0,46,1,8,2,25.0,5,62.5,...,-0.2,-0.9,0.2,0.7,-0.3,-0.5,-0.2,0.05,1,1
23,3,0,0,49,0,27,14,51.9,11,40.7,...,0.9,0.9,1.3,1.5,1.3,1.3,0.7,0.12,0,3

In [68]:
df_vs_away_off= df_vs_away[offense]
df_vs_away_off

,G-PK,PK,PKm,Poss,PKatt,Att To,Succ,Succ%,Tkld,Tkld%,...,xGD,npxGD,xAG,xA,G-xG,np:G-xG,A-xAG,npxG/Sh,FKAtt,GF
0,1,0,0,66,0,20,11,55.0,8,40.0,...,-0.4,-0.4,0.4,1.0,0.4,0.4,0.6,0.05,0,1
1,1,0,0,46,0,12,4,33.3,8,66.7,...,0.0,0.0,0.2,0.3,0.4,0.4,-0.2,0.04,1,1
2,0,0,0,55,0,10,5,50.0,5,50.0,...,-0.1,-0.1,0.6,0.5,-0.7,-0.7,-0.6,0.05,0,0
3,0,0,0,54,0,19,10,52.6,8,42.1,...,-0.7,-0.7,0.3,0.7,-0.3,-0.3,-0.3,0.04,0,0
4,2,0,0,47,0,8,2,25.0,6,75.0,...,1.4,1.4,1.6,2.4,0.2,0.2,0.4,0.08,0,2
5,0,0,0,60,0,14,6,42.9,8,57.1,...,-0.6,0.2,0.5,0.6,-0.6,-0.6,-0.5,0.05,0,0
6,1,0,0,61,0,11,6,54.5,4,36.4,...,0.0,0.0,0.9,1.0,0.0,0.0,0.1,0.06,0,1
7,1,0,0,51,0,13,5,38.5,8,61.5,...,-1.1,-1.1,0.6,0.6,-0.2,-0.2,0.4,0.10,0,1
8,2,0,0,40,0,12,7,58.3,5,41.7,...,-0.7,-0.7,0.9,0.8,1.1,1.1,1.1,0.12,0,2
9,0,0,0,49,0,9,4,44.4,3,33.3,...,-1.4,-1.4,0.6,0.4,-0.6,-0.6,-0.6,0.06,0,0
10,0,0,0,67,0,18,5,27.8,11,61.1,...,0.1,0.1,0.4,1.0,-0.6,-0.6,-0.4,0.03,0,0
11,1,0,0,51,0,11,3,27.3,8,72.7,...,0.6,0.6,0.7,0.6,-0.1,-0.1,-0.7,0.09,0,1
12,1,0,0,47,0,13,3,23.1,9,69.2,...,0.0,0.0,0.6,0.6,0.4,0.4,0.4,0.07,0,1
13,1,1,0,61,1,8,3,37.5,2,25.0,...,-0.5,-1.3,0.2,0.6,0.8,0.6,-0.2,0.03,1,2
14,0,1,0,52,1,11,1,9.1,10,90.9,...,0.5,-0.2,0.5,0.4,-0.3,-0.5,-0.5,0.09,0,1
15,4,1,0,59,1,15,8,53.3,7,46.7,...,4.1,3.3,3.1,1.7,0.0,-0.2,-1.1,0.23,1,5
16,2,0,0,50,0,12,6,50.0,6,50.0,...,0.0,0.0,0.8,0.9,1.1,1.1,1.2,0.07,2,2
17,1,0,0,68,0,7,2,28.6,5,71.4,...,-0.4,-0.4,0.6,1.0,0.2,0.2,-0.6,0.06,0,1
18,0,0,0,54,0,16,10,62.5,6,37.5,...,-1.5,-0.7,0.6,0.6,-0.8,-0.8,-0.6,0.05,0,0
19,4,0,0,43,0,7,1,14.3,5,71.4,...,1.9,1.9,2.4,2.2,1.6,1.6,1.6,0.17,0,4
20,1,0,0,52,0,21,12,57.1,8,38.1,...,-0.6,-0.6,0.3,0.8,0.6,0.6,0.7,0.05,0,1
21,2,0,0,53,0,17,8,47.1,7,41.2,...,0.8,0.8,1.1,1.5,0.7,0.7,0.9,0.08,1,2
22,1,0,0,54,0,18,5,27.8,9,50.0,...,0.2,0.9,0.8,1.0,-0.4,-0.4,-0.8,0.09,0,1
23,1,0,0,51,0,18,12,66.7,3,16.7,...,-0.9,-0.9,0.8,0.7,0.2,0.2,0.2,0.09,0,1

## Defence

In [69]:
defence= ['OppCr', 'Stp', 'Stp%', 'PKcon', '#OPA', 'AvgDist', 'PKsv', 'PK Save%', 'FK Ag', 'CKG', 'OGK', 'SoTA', 'Saves', 
          'Save%', 'Tkl', 'TklW', 'Tkl Def 3rd', 'Tkl Mid 3rd', 'Tkl Att 3rd', 'Tkl.2', 'Tkl Att', 'Tkl%', 'Lost Tkl', 
          'Ints', 'BlcSh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',  'PSxG', 'PSxG/SoT', 'PSxG+/-', 'GA']

In [70]:
df_home_def= df_home[defence]
df_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,22,0,0.0,0,2,23.0,0,NaN,0,0,...,4,7,10,23,26,0,1.1,0.23,0.1,2
1,6,0,0.0,0,0,NaN,0,NaN,0,0,...,0,10,8,28,11,0,0.9,0.15,-1.1,2
2,20,1,5.0,0,1,11.6,0,NaN,0,0,...,2,8,8,21,28,0,0.9,0.22,0.9,0
3,17,0,0.0,1,0,NaN,0,0.0,0,0,...,2,9,4,21,17,0,1.7,0.24,-0.3,2
4,21,1,4.8,0,0,4.7,0,NaN,0,0,...,5,6,6,25,22,1,0.4,0.10,0.4,0
5,9,0,0.0,0,2,20.7,0,NaN,0,0,...,3,8,11,23,15,0,0.8,0.19,-1.2,2
6,13,2,15.4,0,0,11.0,0,NaN,0,0,...,3,5,6,22,16,0,0.9,0.46,-0.1,1
7,13,0,0.0,0,0,12.1,0,NaN,0,0,...,2,2,14,36,21,1,1.4,0.27,0.4,1
8,8,2,25.0,0,3,15.0,0,NaN,0,0,...,1,5,8,29,21,1,0.6,0.19,0.6,0
9,13,1,7.7,1,2,11.3,0,0.0,1,1,...,4,11,12,34,21,0,4.5,0.41,-0.5,5
10,32,2,6.3,0,2,12.8,0,NaN,0,0,...,3,9,8,30,44,1,0.1,0.07,0.1,0
11,12,0,0.0,1,0,NaN,0,0.0,0,0,...,2,5,11,24,15,0,1.1,0.08,-0.9,2
12,6,1,16.7,1,0,13.7,0,0.0,0,0,...,1,7,15,25,12,1,1.3,0.07,0.3,1
13,7,0,0.0,0,4,23.8,0,NaN,0,0,...,4,0,5,17,26,1,0.1,0.06,0.1,0
14,12,0,0.0,0,0,5.0,0,NaN,0,0,...,2,10,6,16,24,0,0.5,0.17,-0.5,1
15,23,0,0.0,0,2,21.8,0,NaN,0,0,...,1,8,12,28,35,0,2.6,0.28,-1.4,4
16,16,3,18.8,0,5,16.1,0,NaN,0,0,...,1,8,16,35,26,0,1.1,0.54,1.1,0
17,8,1,12.5,0,1,15.3,0,NaN,0,1,...,5,4,13,32,13,2,1.8,0.26,-2.2,4
18,7,1,14.3,0,3,14.6,0,NaN,0,0,...,1,5,12,27,4,1,0.3,0.27,-0.7,1
19,14,0,0.0,0,2,22.5,0,NaN,0,1,...,0,14,13,32,33,0,1.5,0.37,0.5,1
20,4,1,25.0,0,1,12.1,0,NaN,0,0,...,3,6,7,16,2,1,0.8,0.79,-0.2,1
21,12,1,8.3,0,0,9.3,0,NaN,0,0,...,1,8,7,25,31,1,0.4,0.43,0.4,0
22,13,0,0.0,0,1,16.0,0,NaN,0,1,...,0,7,4,22,29,0,2.8,0.48,-1.2,4
23,15,2,13.3,0,3,15.1,0,NaN,0,0,...,3,4,4,14,17,0,0.1,0.11,0.1,0

In [71]:
df_vs_home_def= df_vs_home[defence]
df_vs_home_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,13,0,0.0,0,1,29.5,0,NaN,0,0,...,3,9,9,25,15,0,1.5,0.31,0.5,2
1,19,1,5.3,0,0,4.7,0,NaN,0,0,...,2,9,7,23,25,0,0.8,0.11,-0.2,1
2,16,0,0.0,0,0,NaN,0,NaN,0,0,...,3,5,8,21,27,0,1.0,0.14,1.0,0
3,8,1,12.5,0,1,16.0,0,NaN,0,0,...,4,10,8,32,15,0,0.4,0.07,0.4,0
4,7,0,0.0,0,2,23.5,0,NaN,0,0,...,2,6,3,33,15,1,1.1,0.28,0.1,1
5,11,0,0.0,0,0,5.0,0,NaN,0,0,...,2,9,6,28,17,0,1.5,0.74,0.5,1
6,16,2,12.5,0,0,9.0,0,NaN,0,0,...,10,4,8,33,27,3,1.5,0.30,0.5,2
7,11,2,18.2,0,0,4.5,0,NaN,0,0,...,3,4,17,38,19,0,0.3,0.09,0.3,1
8,13,1,7.7,1,4,22.1,0,0.0,0,0,...,2,7,8,21,27,2,0.8,0.04,-0.2,1
9,4,0,0.0,0,7,28.0,0,NaN,0,0,...,4,7,7,24,6,0,0.8,0.82,-0.2,1
10,7,0,0.0,0,1,20.3,0,NaN,0,0,...,2,8,7,28,17,0,2.1,0.71,0.1,2
11,12,0,0.0,0,2,15.6,0,NaN,0,0,...,3,17,7,28,29,1,0.0,NaN,0.0,0
12,14,0,0.0,0,2,14.7,0,NaN,0,0,...,4,5,9,32,28,0,0.1,0.04,0.1,0
13,15,1,6.7,0,2,14.4,0,NaN,0,0,...,2,10,6,25,24,1,1.1,0.35,0.1,1
14,17,0,0.0,0,0,18.0,0,NaN,0,0,...,2,7,13,29,31,0,1.7,0.34,0.7,1
15,3,0,0.0,0,2,29.0,0,NaN,0,1,...,0,11,6,24,12,0,1.4,0.47,-1.6,3
16,9,0,0.0,0,2,19.3,0,NaN,0,1,...,0,5,10,22,21,0,0.8,0.25,-0.2,1
17,12,1,8.3,0,0,9.1,0,NaN,0,0,...,1,4,6,31,15,1,1.3,0.32,-0.7,2
18,17,3,17.6,0,0,5.4,0,NaN,0,0,...,4,7,7,26,28,2,0.3,0.06,-0.7,1
19,10,1,10.0,1,3,16.8,1,100.0,0,1,...,4,2,6,19,18,1,2.5,0.35,0.5,2
20,24,3,12.5,0,0,5.0,0,NaN,0,0,...,7,4,8,35,37,1,0.5,0.12,-0.5,1
21,10,0,0.0,0,2,16.5,0,NaN,0,0,...,3,12,4,22,24,1,0.0,NaN,0.0,0
22,15,0,0.0,0,5,25.3,0,NaN,0,0,...,4,10,5,21,13,0,1.1,0.28,0.1,1
23,11,1,9.1,0,2,14.4,0,NaN,0,0,...,0,6,5,14,17,0,2.8,0.47,-1.2,4

In [72]:
df_away_def= df_away[defence]
df_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,9,0,0.0,0,0,3.5,0,NaN,0,0,...,3,8,14,32,29,0,1.2,0.25,0.2,1
1,17,0,0.0,0,0,8.3,0,NaN,0,0,...,3,7,6,29,45,1,0.6,0.12,-0.4,1
2,16,0,0.0,0,0,NaN,0,NaN,0,0,...,3,5,8,21,27,0,1.0,0.14,1.0,0
3,12,0,0.0,0,1,17.5,0,NaN,0,0,...,1,4,15,28,32,0,0.0,0.01,0.0,0
4,15,1,6.7,0,0,4.0,0,NaN,0,1,...,7,8,4,19,12,0,2.0,0.51,0.0,2
5,13,0,0.0,0,0,7.0,0,NaN,0,0,...,2,6,11,28,31,0,0.2,0.05,0.2,0
6,18,1,5.6,0,0,2.0,0,NaN,0,0,...,5,6,4,19,33,1,1.0,0.17,0.0,1
7,21,0,0.0,0,0,17.0,0,NaN,0,0,...,4,6,7,26,26,0,0.9,0.88,-0.1,1
8,10,0,0.0,0,0,8.3,0,NaN,0,0,...,0,8,10,22,20,1,1.1,0.38,-0.9,2
9,15,0,0.0,0,1,18.5,0,NaN,0,0,...,1,9,12,23,14,0,0.1,0.06,0.1,0
10,25,1,4.0,0,2,12.8,0,NaN,0,0,...,8,6,12,32,34,0,0.1,0.07,0.1,0
11,17,3,17.6,0,2,12.8,0,NaN,0,0,...,6,4,13,29,25,1,1.2,0.40,0.2,1
12,5,0,0.0,0,1,18.5,0,NaN,0,0,...,3,5,8,27,17,1,1.2,0.58,0.2,1
13,23,1,4.3,1,0,9.0,0,0.0,0,0,...,5,4,11,22,24,0,1.0,0.10,-1.0,2
14,17,0,0.0,1,0,5.0,0,0.0,0,0,...,0,9,12,36,22,0,0.6,0.00,-0.4,1
15,8,1,12.5,1,0,8.5,0,0.0,0,0,...,4,8,9,23,17,3,5.2,0.51,0.2,5
16,7,0,0.0,0,0,10.8,0,NaN,0,0,...,1,11,17,28,12,0,0.4,0.08,-1.6,2
17,29,1,3.4,0,0,7.0,0,NaN,0,0,...,6,3,8,18,34,0,0.9,0.87,-0.1,1
18,20,1,5.0,0,0,7.3,0,NaN,0,0,...,3,6,8,22,36,0,0.7,0.13,0.7,0
19,10,1,10.0,0,2,15.8,0,NaN,0,1,...,3,3,9,22,22,0,3.1,0.44,-0.9,4
20,10,1,10.0,0,0,10.3,0,NaN,0,0,...,3,6,10,30,27,1,0.7,0.24,-0.3,1
21,20,1,5.0,0,1,10.5,0,NaN,0,0,...,4,8,5,15,28,2,1.6,0.33,-0.4,2
22,29,1,3.4,0,1,10.3,0,NaN,0,0,...,11,6,13,30,40,0,1.0,0.32,0.0,1
23,19,1,5.3,0,0,9.5,0,NaN,0,0,...,2,4,3,11,31,0,0.9,0.23,-0.1,1

In [73]:
df_vs_away_def= df_vs_away[defence]
df_vs_away_def

,OppCr,Stp,Stp%,PKcon,#OPA,AvgDist,PKsv,PK Save%,FK Ag,CKG,...,BlcSh,Pass,Int,Tkl+Int,Clr,Err,PSxG,PSxG/SoT,PSxG+/-,GA
0,21,1,4.8,0,0,4.5,0,NaN,0,1,...,1,6,4,19,23,0,0.6,0.12,-0.4,1
1,20,2,10.0,0,0,7.0,0,NaN,0,0,...,5,10,10,33,19,0,0.1,0.06,0.1,0
2,20,1,5.0,0,1,11.6,0,NaN,0,0,...,2,8,8,21,28,0,0.9,0.22,0.9,0
3,15,1,6.7,0,0,10.2,0,NaN,0,0,...,4,7,14,29,27,0,1.2,0.39,0.2,1
4,27,2,7.4,0,0,6.0,0,NaN,0,0,...,2,7,6,16,28,0,0.3,0.08,0.3,1
5,11,1,9.1,1,3,17.8,0,0.0,0,0,...,0,3,7,22,12,0,0.9,0.08,-0.1,1
6,10,0,0.0,0,1,15.3,0,NaN,0,1,...,0,6,7,29,16,0,1.3,0.21,-0.7,2
7,18,2,11.1,0,0,5.3,0,NaN,0,0,...,3,6,7,20,18,2,2.8,0.47,0.8,2
8,26,1,3.8,0,0,7.3,0,NaN,0,1,...,4,10,10,39,44,1,2.6,0.52,1.6,1
9,21,2,9.5,0,1,12.5,0,NaN,0,1,...,4,6,8,20,26,0,1.6,0.31,0.6,1
10,6,2,33.3,0,0,14.2,0,NaN,0,0,...,1,6,6,24,13,0,0.3,0.28,0.3,0
11,12,1,8.3,0,0,6.0,0,NaN,0,0,...,2,2,7,29,22,0,0.3,0.15,0.3,0
12,20,0,0.0,0,1,23.0,0,NaN,0,0,...,3,2,10,30,23,1,0.2,0.04,0.2,0
13,15,1,6.7,0,0,10.0,0,NaN,0,0,...,0,6,1,12,21,0,1.9,0.63,-1.1,3
14,9,0,0.0,0,2,17.5,0,NaN,0,0,...,1,7,3,21,16,0,1.5,0.50,-0.5,2
15,12,1,8.3,0,8,21.3,0,NaN,0,0,...,3,6,6,18,21,0,1.0,0.99,0.0,1
16,17,0,0.0,0,2,17.0,0,NaN,0,0,...,2,6,8,28,23,0,1.9,0.46,1.9,0
17,8,0,0.0,0,1,9.8,0,NaN,0,0,...,1,3,2,16,14,1,1.7,0.87,-0.3,2
18,6,0,0.0,1,0,NaN,0,0.0,0,0,...,2,7,8,22,15,0,1.2,0.21,0.2,1
19,19,1,5.3,0,1,12.0,0,NaN,0,0,...,2,10,9,31,15,1,0.3,0.17,0.3,0
20,17,1,5.9,0,1,13.3,0,NaN,0,0,...,6,8,11,38,29,0,0.8,0.26,0.8,0
21,14,0,0.0,0,0,3.0,0,NaN,0,0,...,7,7,5,15,23,0,0.0,0.02,0.0,0
22,15,4,26.7,1,3,19.0,0,0.0,0,0,...,3,8,9,30,26,0,0.8,0.02,-0.2,1
23,21,0,0.0,0,1,15.3,0,NaN,0,0,...,3,8,2,20,40,3,2.2,0.45,-0.8,3

## Combined

In [74]:
combined= ['Won', 'Lost', 'Won%', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Recov']

In [75]:
df_home_cmb= df_home[combined]
df_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    20    11  64.5     2     0      0   15   13     44
1    13    17  43.3     3     0      0   16    7     48
2    12    14  46.2     1     1      0   10   14     38
3     3     4  42.9     3     0      0    6   13     41
4    18    21  46.2     3     1      1   19   15     39
5    20    14  58.8     4     0      0   16   11     35
6    10    16  38.5     5     1      1   14   12     36
7    11    10  52.4     3     0      0    7    6     46
8    17    13  56.7     6     1      1   15   12     35
9     6     6  50.0     2     0      0   14    5     41
10   16    15  51.6     0     0      0    9   13     36
11   12    14  46.2     2     0      0    6   17     37
12   27    16  62.8     1     1      0   10    7     41
13   19     9  67.9     2     0      0   14   13     29
14   16    15  51.6     1     0      0   11   14     42
15   13    13  50.0     3     0      0    8   11     50
16   10     6  62.5     7     0      0   12    9     53
17    6     4  60.0     2     0      0   14    5     45
18   19     8  70.4     1     0      0   16    8     42
19    7     9  43.8     4     0      0   15    6     47
20   19    16  54.3     1     0      0   13   13     53
21   22    17  56.4     6     0      0   12   10     34
22    7     5  58.3     5     0      0   14    6     42
23    5    12  29.4     2     0      0   10   10     37

In [76]:
df_vs_home_cmb= df_vs_home[combined]
df_vs_home_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    11    20  35.5     2     0      0   14   13     36
1    17    13  56.7     5     0      0    8   15     35
2    14    12  53.8     0     0      0   15    9     40
3     4     3  57.1     2     0      0   14    5     36
4    21    18  53.8     4     0      0   15   17     33
5    14    20  41.2     1     0      0   11   16     34
6    16    10  61.5     4     0      0   12   13     31
7    10    11  47.6     0     1      0    6    7     39
8    13    17  43.3     3     0      0   15   15     32
9     6     6  50.0     1     0      0    6   14     40
10   15    16  48.4     2     0      0   14    9     38
11   14    12  53.8     1     0      0   17    5     48
12   16    27  37.2     2     0      0    7   10     45
13    9    19  32.1     5     1      0   14   12     25
14   15    16  48.4     1     0      0   15   11     36
15   13    13  50.0     4     0      0   11    7     54
16    6    10  37.5     3     0      0    9   12     43
17    4     7  36.4     1     0      0    5   14     43
18    8    19  29.6     2     0      0    8   15     30
19    9     7  56.3     0     0      0    6   15     46
20   16    19  45.7     4     0      0   14   12     30
21   17    22  43.6     4     0      0   15   12     30
22    5     7  41.7     2     1      0    6   13     35
23   12     5  70.6     4     0      0   11   10     31

In [77]:
df_away_cmb= df_away[combined]
df_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    10    10  50.0     1     0      0   11    6     42
1    25    18  58.1     1     0      0    8   10     40
2    14    12  53.8     0     0      0   15    9     40
3    26    17  60.5     3     0      0   17   10     33
4    12    21  36.4     3     1      0   11    9     41
5    22    18  55.0     1     0      0    5    9     50
6    12    14  46.2     3     0      0   14   12     33
7    20    18  52.6     2     0      0   11   15     41
8    18    24  42.9     5     0      0   19   10     39
9    20    11  64.5     1     0      0    9   12     46
10   23    12  65.7     5     1      1    9   12     42
11   19    27  41.3     2     0      0   12   19     36
12   19     6  76.0     1     0      0   10   16     42
13   17    13  56.7     2     1      0   18    9     33
14   17    11  60.7     1     0      0    9   13     48
15    7    11  38.9     4     0      0   13   13     47
16   23    17  57.5     0     1      0   12    8     45
17   10     6  62.5     5     1      0   10   14     36
18   30    32  48.4     3     0      0   13   19     25
19   10    13  43.5     3     0      0   12    9     38
20   18    13  58.1     2     1      0   12   18     46
21   17    11  60.7     3     0      0   14    8     31
22   17    20  45.9     1     0      0    7   11     48
23   23    16  59.0     1     0      0    7   13     47

In [78]:
df_vs_away_cmb= df_vs_away[combined]
df_vs_away_cmb

    Won  Lost  Won%  CrdY  CrdR  2CrdY  Fls  Fld  Recov
0    10    10  50.0     0     1      0    6   11     38
1    18    25  41.9     2     0      0   10    8     40
2    12    14  46.2     1     1      0   10   14     38
3    17    26  39.5     1     0      0   11   17     37
4    21    12  63.6     3     0      0   10   10     52
5    18    22  45.0     1     0      0   10    5     50
6    14    12  53.8     3     0      0   12   11     39
7    18    20  47.4     3     0      0   16   11     36
8    24    18  57.1     1     0      0   14   17     37
9    11    20  35.5     1     0      0   13    8     38
10   12    23  34.3     1     0      0   12    8     50
11   27    19  58.7     3     0      0   19   11     29
12    6    19  24.0     3     0      0   16    9     34
13   13    17  43.3     4     0      0   10   15     29
14   11    17  39.3     1     0      0   14    8     46
15   11     7  61.1     3     0      0   13   13     46
16   17    23  42.5     1     0      0    9   11     42
17    6    10  37.5     2     0      0   14    9     47
18   32    30  51.6     4     0      0   19   13     40
19   13    10  56.5     1     0      0    9   12     44
20   13    18  41.9     2     0      0   18   12     51
21   11    17  39.3     2     0      0    9   14     45
22   20    17  54.1     4     0      0   11    6     38
23   16    23  41.0     4     0      0   13    7     31

## By Team

In [79]:
def compute_rolling_averages(df, features, window=5):
    """
    Compute rolling averages for a list of features in a team-level dataset.

    Parameters:
    df (pd.DataFrame): Dataframe containing team-level data sorted by date.
    features (list): List of features to compute rolling averages for.
    window (int): Rolling window size (default=5).

    Returns:
    pd.DataFrame: Dataframe with new rolling average features.
    """
    df = df.copy()
    
    for feature in features:
        df[f"{feature}_rolling_avg"] = df[feature].rolling(window, min_periods=1).mean()
    
    return df[[i for i in df.columns if i[-12:]=='_rolling_avg']]

In [80]:
df_home_off= compute_rolling_averages(df_home_off, offense)
df_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.000000,0.0,0.0,52.000000,0.0,20.000000,7.000000,35.000000,9.000000,45.00,...,0.400000,4.000000e-01,1.500000,1.500000,-0.80,-0.80,-5.000000e-01,0.100000,0.000000,2.00
1,1.000000,0.0,0.0,55.500000,0.0,23.000000,10.500000,44.400000,9.000000,39.80,...,0.300000,3.000000e-01,1.000000,1.050000,-0.40,-0.40,0.000000e+00,0.085000,0.500000,1.50
2,0.666667,0.0,0.0,55.333333,0.0,18.666667,8.666667,46.266667,7.666667,43.20,...,0.166667,1.666667e-01,0.866667,0.866667,-0.50,-0.50,-2.000000e-01,0.073333,0.333333,1.00
3,0.500000,0.0,0.0,54.000000,0.0,20.750000,9.000000,43.950000,8.750000,43.50,...,-0.125000,7.500000e-02,0.800000,0.775000,-0.60,-0.60,-3.000000e-01,0.070000,0.750000,0.75
4,0.600000,0.0,0.0,55.200000,0.0,22.200000,10.400000,46.580000,8.800000,41.22,...,-0.020000,1.400000e-01,0.820000,0.680000,-0.56,-0.56,-2.200000e-01,0.084000,0.600000,0.80
5,0.600000,0.0,0.0,57.800000,0.0,22.400000,11.400000,51.000000,8.800000,40.80,...,-0.220000,-6.000000e-02,0.620000,0.480000,-0.30,-0.30,-2.000000e-02,0.078000,0.600000,0.60
6,0.600000,0.0,0.0,56.800000,0.0,21.200000,10.000000,47.240000,9.400000,45.88,...,0.040000,2.000000e-01,0.820000,0.560000,-0.52,-0.52,-4.200000e-01,0.084000,0.400000,0.80
7,0.600000,0.0,0.0,58.000000,0.0,24.800000,12.000000,47.960000,10.200000,42.30,...,-0.120000,4.000000e-02,0.780000,0.520000,-0.60,-0.60,-3.800000e-01,0.092000,0.800000,1.00
8,0.600000,0.2,0.0,58.200000,0.2,23.400000,12.800000,54.560000,8.800000,38.42,...,0.240000,8.000000e-02,0.760000,0.500000,-0.50,-0.56,-3.600000e-01,0.090000,0.600000,1.20
9,0.600000,0.2,0.0,52.800000,0.2,22.000000,11.600000,52.660000,8.800000,40.58,...,-0.420000,-4.200000e-01,0.760000,0.480000,-0.42,-0.48,-3.600000e-01,0.090000,0.600000,1.20
10,0.800000,0.2,0.0,51.200000,0.2,21.400000,11.000000,51.240000,8.400000,39.78,...,-0.380000,-3.800000e-01,0.780000,0.560000,-0.28,-0.34,-1.800000e-01,0.102000,0.600000,1.40
11,0.600000,0.2,0.0,51.400000,0.2,20.800000,10.800000,51.300000,8.200000,40.72,...,-0.740000,-5.800000e-01,0.540000,0.420000,-0.28,-0.34,6.000000e-02,0.110000,0.600000,1.00
12,0.600000,0.2,0.0,50.600000,0.2,19.000000,9.200000,47.940000,8.600000,45.88,...,-0.660000,-3.400000e-01,0.560000,0.480000,-0.18,-0.24,4.000000e-02,0.100000,0.200000,0.80
13,0.800000,0.0,0.0,51.000000,0.0,18.600000,8.200000,43.940000,9.200000,49.76,...,-0.780000,-3.000000e-01,0.660000,0.500000,-0.12,-0.12,1.400000e-01,0.110000,0.000000,0.80
14,0.800000,0.0,0.0,57.200000,0.0,17.600000,7.200000,40.680000,9.600000,54.94,...,-0.080000,2.400000e-01,0.740000,0.680000,-0.18,-0.18,6.000000e-02,0.104000,0.000000,0.80
15,1.000000,0.0,0.0,54.400000,0.0,17.400000,7.200000,41.260000,9.800000,56.58,...,-0.320000,0.000000e+00,0.700000,0.640000,0.10,0.10,3.000000e-01,0.100000,0.000000,1.00
16,1.200000,0.0,0.0,52.400000,0.0,17.000000,7.000000,40.860000,9.400000,55.64,...,-0.360000,-2.000000e-01,0.740000,0.640000,0.38,0.38,4.600000e-01,0.088000,0.000000,1.20
17,1.600000,0.0,0.0,49.200000,0.0,17.800000,8.000000,43.940000,9.000000,51.88,...,-0.400000,-4.000000e-01,0.880000,0.680000,0.64,0.64,7.200000e-01,0.106000,0.000000,1.60
18,1.600000,0.0,0.0,49.400000,0.0,17.400000,7.400000,41.440000,9.200000,54.26,...,-0.460000,-4.600000e-01,0.780000,0.680000,0.76,0.76,8.200000e-01,0.094000,0.000000,1.60
19,1.800000,0.0,0.2,44.600000,0.2,17.800000,7.600000,41.840000,8.800000,50.50,...,-0.260000,-4.200000e-01,0.800000,0.600000,0.70,0.86,8.000000e-01,0.102000,0.000000,1.80
20,1.400000,0.0,0.2,50.800000,0.2,21.600000,8.200000,37.920000,11.200000,52.20,...,0.160000,4.440892e-17,0.900000,0.620000,0.14,0.30,3.000000e-01,0.090000,0.200000,1.40
21,1.200000,0.0,0.2,52.800000,0.2,23.000000,10.000000,43.980000,10.800000,46.56,...,0.240000,8.000000e-02,0.920000,0.620000,-0.10,0.06,8.000000e-02,0.088000,0.400000,1.20
22,1.000000,0.0,0.2,52.600000,0.2,22.800000,9.800000,43.540000,10.600000,46.02,...,0.140000,-2.000000e-02,0.800000,0.680000,-0.18,-0.02,-8.881784e-17,0.080000,0.400000,1.00
23,1.600000,0.0,0.2,51.400000,0.2,22.400000,9.600000,43.180000,10.200000,44.76,...,0.280000,1.200000e-01,0.860000,0.640000,0.30,0.46,5.400000e-01,0.092000,0.400000,1.60

In [81]:
df_vs_home_off= compute_rolling_averages(df_vs_home_off, offense)
df_vs_home_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.0,0.00,0.0,48.000000,0.00,13.000000,3.0,23.100000,7.0,53.800,...,-0.400000,-4.000000e-01,1.400000,1.100000,-0.400000,-4.000000e-01,-0.400000,0.090000,0.0,2.000000
1,1.5,0.00,0.0,44.500000,0.00,14.000000,3.0,21.550000,7.5,53.550,...,-0.300000,-3.000000e-01,1.050000,0.850000,0.350000,3.500000e-01,-0.050000,0.100000,0.0,2.000000
2,1.0,0.00,0.0,44.666667,0.00,12.666667,4.0,34.366667,6.0,45.700,...,-0.166667,-1.666667e-01,0.833333,0.833333,-0.066667,-6.666667e-02,-0.166667,0.093333,0.0,1.333333
3,1.0,0.25,0.0,46.000000,0.25,15.250000,5.5,36.650000,7.5,47.325,...,0.125000,-7.500000e-02,0.850000,0.900000,-0.025000,-1.000000e-01,-0.100000,0.100000,0.0,1.500000
4,0.8,0.20,0.0,44.800000,0.20,14.600000,5.2,35.980000,6.8,44.520,...,0.020000,-1.400000e-01,0.840000,0.820000,-0.220000,-2.800000e-01,-0.240000,0.094000,0.2,1.200000
5,1.0,0.20,0.0,42.200000,0.20,14.000000,5.0,35.360000,7.0,49.760,...,0.220000,6.000000e-02,0.700000,0.720000,0.040000,-2.000000e-02,-0.100000,0.100000,0.4,1.200000
6,0.8,0.20,0.0,43.200000,0.20,14.000000,5.6,39.360000,6.6,47.100,...,-0.040000,-2.000000e-01,0.660000,0.740000,-0.120000,-1.800000e-01,-0.060000,0.096000,0.6,1.000000
7,1.0,0.20,0.0,42.000000,0.20,16.000000,5.4,32.360000,8.6,54.100,...,0.120000,-4.000000e-02,0.880000,0.780000,-0.140000,-2.000000e-01,-0.080000,0.110000,0.6,1.200000
8,0.8,0.00,0.0,41.800000,0.00,14.400000,4.6,31.660000,7.6,53.000,...,-0.240000,-8.000000e-02,0.780000,0.700000,-0.280000,-2.800000e-01,-0.180000,0.098000,0.6,0.800000
9,1.6,0.20,0.0,47.200000,0.20,17.600000,6.6,35.000000,8.8,53.480,...,0.420000,4.200000e-01,1.160000,0.960000,0.160000,1.000000e-01,-0.160000,0.116000,0.6,1.800000
10,1.2,0.20,0.0,48.800000,0.20,19.000000,7.0,35.700000,9.4,50.420,...,0.380000,3.800000e-01,1.160000,1.000000,-0.260000,-3.200000e-01,-0.360000,0.108000,0.6,1.400000
11,1.2,0.40,0.0,48.600000,0.40,18.200000,6.8,36.800000,9.4,53.320,...,0.740000,5.800000e-01,1.180000,0.980000,-0.200000,-3.000000e-01,-0.380000,0.104000,0.4,1.600000
12,1.0,0.60,0.0,49.400000,0.60,16.600000,7.2,43.460000,7.8,48.660,...,0.660000,3.400000e-01,0.920000,0.820000,-0.020000,-1.600000e-01,-0.320000,0.082000,0.8,1.600000
13,1.0,0.60,0.0,49.000000,0.60,16.200000,7.0,43.160000,7.4,47.020,...,0.780000,3.000000e-01,0.960000,0.760000,-0.060000,-2.000000e-01,-0.360000,0.090000,1.0,1.600000
14,0.4,0.40,0.0,42.800000,0.40,13.000000,5.2,41.500000,6.8,51.540,...,0.080000,-2.400000e-01,0.540000,0.480000,-0.240000,-3.200000e-01,-0.140000,0.080000,0.8,0.800000
15,1.2,0.40,0.0,45.600000,0.40,14.600000,6.8,46.400000,7.0,48.200,...,0.320000,0.000000e+00,0.780000,0.640000,0.400000,3.200000e-01,0.220000,0.094000,0.6,1.600000
16,1.0,0.20,0.0,47.600000,0.20,16.400000,7.4,45.300000,7.6,46.300,...,0.360000,2.000000e-01,0.880000,0.660000,0.040000,4.440892e-17,-0.080000,0.104000,0.6,1.200000
17,1.8,0.00,0.0,50.800000,0.00,17.400000,7.4,41.880000,7.8,45.020,...,0.400000,4.000000e-01,1.220000,0.980000,0.460000,4.600000e-01,0.380000,0.122000,0.2,1.800000
18,2.0,0.00,0.0,50.600000,0.00,17.400000,7.6,43.420000,8.2,48.080,...,0.460000,4.600000e-01,1.200000,0.980000,0.680000,6.800000e-01,0.600000,0.128000,0.0,2.000000
19,2.0,0.00,0.0,55.400000,0.00,18.800000,7.8,41.400000,8.8,46.940,...,0.260000,4.200000e-01,1.240000,1.100000,0.620000,6.200000e-01,0.560000,0.134000,0.0,2.000000
20,1.4,0.00,0.0,49.200000,0.00,16.600000,6.6,40.380000,7.4,44.480,...,-0.160000,-4.440892e-17,0.900000,0.880000,0.280000,2.800000e-01,0.300000,0.128000,0.2,1.400000
21,1.4,0.00,0.0,47.200000,0.00,14.600000,6.0,42.380000,6.4,43.480,...,-0.240000,-8.000000e-02,0.780000,0.780000,0.320000,3.200000e-01,0.420000,0.132000,0.2,1.400000
22,1.4,0.00,0.0,47.400000,0.00,15.600000,6.6,43.240000,7.4,46.420,...,-0.140000,2.000000e-02,0.680000,0.760000,0.340000,3.400000e-01,0.320000,0.144000,0.2,1.400000
23,1.2,0.00,0.0,48.600000,0.00,15.800000,7.0,45.420000,6.8,41.380,...,-0.280000,-1.200000e-01,0.660000,0.820000,0.180000,1.800000e-01,0.140000,0.132000,0.2,1.200000

In [82]:
df_away_def= compute_rolling_averages(df_away_def, defence)
df_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,9.0,0.0,0.00,0.0,0.00,3.500000,0.0,NaN,0.0,0.0,...,3.0,8.000000,14.000000,32.000000,29.000000,0.000000,1.200000,0.250,0.200000,1.000000
1,13.0,0.0,0.00,0.0,0.00,5.900000,0.0,NaN,0.0,0.0,...,3.0,7.500000,10.000000,30.500000,37.000000,0.500000,0.900000,0.185,-0.100000,1.000000
2,14.0,0.0,0.00,0.0,0.00,5.900000,0.0,NaN,0.0,0.0,...,3.0,6.666667,9.333333,27.333333,33.666667,0.333333,0.933333,0.170,0.266667,0.666667
3,13.5,0.0,0.00,0.0,0.25,9.766667,0.0,NaN,0.0,0.0,...,2.5,6.000000,10.750000,27.500000,33.250000,0.250000,0.700000,0.130,0.200000,0.500000
4,13.8,0.2,1.34,0.0,0.20,8.325000,0.0,NaN,0.0,0.2,...,3.4,6.400000,9.400000,25.800000,29.000000,0.200000,0.960000,0.206,0.160000,0.800000
5,14.6,0.2,1.34,0.0,0.20,9.200000,0.0,NaN,0.0,0.2,...,3.2,6.000000,8.800000,25.000000,29.400000,0.200000,0.760000,0.166,0.160000,0.600000
6,14.8,0.4,2.46,0.0,0.20,7.625000,0.0,NaN,0.0,0.2,...,3.6,5.800000,8.400000,23.000000,27.000000,0.200000,0.840000,0.176,0.240000,0.600000
7,15.8,0.4,2.46,0.0,0.20,9.500000,0.0,NaN,0.0,0.2,...,3.8,6.000000,8.200000,24.000000,26.800000,0.200000,0.820000,0.324,0.020000,0.800000
8,15.4,0.4,2.46,0.0,0.00,7.660000,0.0,NaN,0.0,0.2,...,3.6,6.800000,7.200000,22.800000,24.400000,0.400000,1.040000,0.398,-0.160000,1.200000
9,15.4,0.2,1.12,0.0,0.20,10.560000,0.0,NaN,0.0,0.0,...,2.4,7.000000,8.800000,23.600000,24.800000,0.400000,0.660000,0.308,-0.140000,0.800000
10,17.8,0.4,1.92,0.0,0.60,11.720000,0.0,NaN,0.0,0.0,...,3.6,7.000000,9.000000,24.400000,25.400000,0.400000,0.640000,0.312,-0.160000,0.800000
11,17.6,0.8,4.32,0.0,1.00,13.880000,0.0,NaN,0.0,0.0,...,3.8,6.600000,10.800000,26.400000,23.800000,0.400000,0.680000,0.358,-0.120000,0.800000
12,14.4,0.8,4.32,0.0,1.20,14.180000,0.0,NaN,0.0,0.0,...,3.6,6.400000,11.000000,26.600000,22.000000,0.600000,0.740000,0.298,-0.060000,0.800000
13,17.0,1.0,5.18,0.2,1.20,14.320000,0.0,0.0,0.0,0.0,...,4.6,5.600000,11.200000,26.600000,22.800000,0.400000,0.720000,0.242,-0.080000,0.800000
14,17.4,1.0,5.18,0.4,1.00,11.620000,0.0,0.0,0.0,0.0,...,4.4,5.600000,11.200000,29.200000,24.400000,0.400000,0.820000,0.230,-0.180000,1.000000
15,14.0,1.0,6.88,0.6,0.60,10.760000,0.0,0.0,0.0,0.0,...,3.6,6.000000,10.600000,27.400000,21.000000,1.000000,1.840000,0.318,-0.160000,2.000000
16,12.0,0.4,3.36,0.6,0.20,10.360000,0.0,0.0,0.0,0.0,...,2.6,7.400000,11.400000,27.200000,18.400000,0.800000,1.680000,0.254,-0.520000,2.200000
17,16.8,0.6,4.04,0.6,0.00,8.060000,0.0,0.0,0.0,0.0,...,3.2,7.000000,11.400000,25.400000,21.800000,0.600000,1.620000,0.312,-0.580000,2.200000
18,16.2,0.6,4.18,0.4,0.00,7.720000,0.0,0.0,0.0,0.0,...,2.8,7.400000,10.800000,25.400000,24.200000,0.600000,1.560000,0.318,-0.240000,1.800000
19,14.8,0.8,6.18,0.2,0.40,9.880000,0.0,0.0,0.0,0.2,...,3.4,6.200000,10.200000,22.600000,24.200000,0.600000,2.060000,0.406,-0.340000,2.400000
20,15.2,0.8,5.68,0.0,0.40,10.240000,0.0,NaN,0.0,0.2,...,3.2,5.800000,10.400000,24.000000,26.200000,0.200000,1.160000,0.352,-0.440000,1.600000
21,17.8,1.0,6.68,0.0,0.60,10.180000,0.0,NaN,0.0,0.2,...,3.8,5.200000,8.000000,21.400000,29.400000,0.600000,1.400000,0.402,-0.200000,1.600000
22,17.8,1.0,6.68,0.0,0.80,10.840000,0.0,NaN,0.0,0.2,...,4.8,5.800000,9.000000,23.800000,30.600000,0.600000,1.420000,0.292,-0.180000,1.600000
23,17.6,1.0,6.74,0.0,0.80,11.280000,0.0,NaN,0.0,0.2,...,4.6,5.400000,8.000000,21.600000,29.600000,0.600000,1.460000,0.312,-0.340000,1.800000

In [83]:
df_vs_away_def= compute_rolling_averages(df_vs_away_def, defence)
df_vs_away_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,21.000000,1.000000,4.800,0.0,0.000000,4.500,0.0,NaN,0.0,1.000000,...,1.000000,6.00,4.000000,19.000000,23.000000,0.0,0.600000,0.120000,-4.000000e-01,1.000000
1,20.500000,1.500000,7.400,0.0,0.000000,5.750,0.0,NaN,0.0,0.500000,...,3.000000,8.00,7.000000,26.000000,21.000000,0.0,0.350000,0.090000,-1.500000e-01,0.500000
2,20.333333,1.333333,6.600,0.0,0.333333,7.700,0.0,NaN,0.0,0.333333,...,2.666667,8.00,7.333333,24.333333,23.333333,0.0,0.533333,0.133333,2.000000e-01,0.333333
3,19.000000,1.250000,6.625,0.0,0.250000,8.325,0.0,NaN,0.0,0.250000,...,3.000000,7.75,9.000000,25.500000,24.250000,0.0,0.700000,0.197500,2.000000e-01,0.500000
4,20.600000,1.400000,6.780,0.0,0.200000,7.860,0.0,NaN,0.0,0.200000,...,2.800000,7.60,8.400000,23.600000,25.000000,0.0,0.620000,0.174000,2.200000e-01,0.600000
5,18.600000,1.400000,7.640,0.2,0.800000,10.520,0.0,0.0,0.0,0.000000,...,2.600000,7.00,9.000000,24.200000,22.800000,0.0,0.680000,0.166000,2.800000e-01,0.600000
6,16.600000,1.000000,5.640,0.2,1.000000,12.180,0.0,0.0,0.0,0.200000,...,1.600000,6.20,8.400000,23.400000,22.200000,0.0,0.920000,0.196000,1.200000e-01,1.000000
7,16.200000,1.200000,6.860,0.2,0.800000,10.920,0.0,0.0,0.0,0.200000,...,1.800000,5.80,8.200000,23.200000,20.200000,0.4,1.300000,0.246000,1.000000e-01,1.400000
8,18.400000,1.200000,6.280,0.2,0.800000,10.340,0.0,0.0,0.0,0.400000,...,1.800000,6.40,7.400000,25.200000,23.600000,0.6,1.580000,0.272000,3.800000e-01,1.400000
9,17.200000,1.200000,6.700,0.2,1.000000,11.640,0.0,0.0,0.0,0.600000,...,2.200000,6.20,7.800000,26.000000,23.200000,0.6,1.840000,0.318000,4.400000e-01,1.400000
10,16.200000,1.400000,11.540,0.0,0.400000,10.920,0.0,NaN,0.0,0.600000,...,2.400000,6.80,7.600000,26.400000,23.400000,0.6,1.720000,0.358000,5.200000e-01,1.200000
11,16.600000,1.600000,13.200,0.0,0.200000,9.060,0.0,NaN,0.0,0.400000,...,2.800000,6.00,7.600000,26.400000,24.600000,0.6,1.520000,0.346000,7.200000e-01,0.800000
12,17.000000,1.200000,10.980,0.0,0.400000,12.600,0.0,NaN,0.0,0.400000,...,2.800000,5.20,8.200000,28.400000,25.600000,0.4,1.000000,0.260000,6.000000e-01,0.400000
13,14.800000,1.200000,11.560,0.0,0.400000,13.140,0.0,NaN,0.0,0.200000,...,2.000000,4.40,6.400000,23.000000,21.000000,0.2,0.860000,0.282000,6.000000e-02,0.800000
14,12.400000,0.800000,9.660,0.0,0.600000,14.140,0.0,NaN,0.0,0.000000,...,1.400000,4.60,5.400000,23.200000,19.000000,0.2,0.840000,0.320000,-1.600000e-01,1.000000
15,13.600000,0.600000,4.660,0.0,2.200000,15.560,0.0,NaN,0.0,0.000000,...,1.800000,4.60,5.400000,22.000000,20.600000,0.2,0.980000,0.462000,-2.200000e-01,1.200000
16,14.600000,0.400000,3.000,0.0,2.600000,17.760,0.0,NaN,0.0,0.000000,...,1.800000,5.40,5.600000,21.800000,20.800000,0.2,1.300000,0.524000,1.000000e-01,1.200000
17,12.200000,0.400000,3.000,0.0,2.600000,15.120,0.0,NaN,0.0,0.000000,...,1.400000,5.60,4.000000,19.000000,19.000000,0.2,1.600000,0.690000,-4.440892e-17,1.600000
18,10.400000,0.200000,1.660,0.2,2.600000,16.400,0.0,0.0,0.0,0.000000,...,1.800000,5.80,5.400000,21.000000,17.800000,0.2,1.460000,0.606000,2.600000e-01,1.200000
19,12.400000,0.400000,2.720,0.2,2.400000,15.025,0.0,0.0,0.0,0.000000,...,2.000000,6.40,6.600000,23.000000,17.600000,0.4,1.220000,0.540000,4.200000e-01,0.800000
20,13.400000,0.400000,2.240,0.2,1.000000,13.025,0.0,0.0,0.0,0.000000,...,2.600000,6.80,7.600000,27.000000,19.200000,0.4,1.180000,0.394000,5.800000e-01,0.600000
21,12.800000,0.400000,2.240,0.2,0.600000,9.525,0.0,0.0,0.0,0.000000,...,3.600000,7.00,7.000000,24.400000,19.200000,0.4,0.800000,0.306000,2.000000e-01,0.600000
22,14.200000,1.200000,7.580,0.4,1.000000,11.825,0.0,0.0,0.0,0.000000,...,4.000000,8.00,8.400000,27.200000,21.600000,0.2,0.620000,0.136000,2.200000e-01,0.400000
23,17.200000,1.200000,7.580,0.2,1.200000,12.520,0.0,0.0,0.0,0.000000,...,4.200000,8.20,7.200000,26.800000,26.600000,0.8,0.820000,0.184000,2.000000e-02,0.800000

In [84]:
df_away_off= compute_rolling_averages(df_away_off, offense)
df_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.000000,0.0,0.0,34.000000,0.0,15.000000,6.0,40.000000,9.000000,60.000000,...,0.400000,0.400000,0.400000,0.50,0.000,0.000,0.600000,0.090000,0.0,1.000000
1,0.500000,0.0,0.0,44.000000,0.0,19.500000,7.5,38.750000,11.500000,59.150000,...,0.200000,0.200000,0.500000,0.80,-0.300,-0.300,0.000000,0.075000,0.0,0.500000
2,0.333333,0.0,0.0,44.333333,0.0,16.333333,7.0,45.833333,8.666667,49.433333,...,0.166667,0.166667,0.466667,0.80,-0.500,-0.500,-0.133333,0.076667,0.0,0.333333
3,0.500000,0.0,0.0,44.750000,0.0,14.750000,6.0,41.875000,8.000000,52.075000,...,0.300000,0.300000,0.525000,0.95,-0.375,-0.375,-0.025000,0.077500,0.0,0.500000
4,0.400000,0.0,0.0,46.400000,0.0,14.200000,5.6,40.160000,7.600000,51.660000,...,-0.040000,-0.040000,0.460000,0.86,-0.360,-0.360,-0.060000,0.070000,0.0,0.600000
5,0.200000,0.2,0.0,47.600000,0.2,13.800000,6.4,47.540000,6.200000,42.740000,...,0.000000,-0.160000,0.460000,0.86,-0.400,-0.440,-0.260000,0.060000,0.0,0.600000
6,0.600000,0.2,0.0,44.600000,0.2,12.000000,5.8,48.040000,5.000000,41.740000,...,0.000000,-0.160000,0.520000,0.74,-0.080,-0.120,0.080000,0.078000,0.0,1.000000
7,1.000000,0.2,0.0,45.400000,0.2,13.400000,6.6,47.800000,5.600000,42.800000,...,0.200000,0.040000,0.800000,0.74,0.060,0.020,0.000000,0.088000,0.0,1.400000
8,1.000000,0.2,0.0,48.200000,0.2,15.200000,8.4,54.440000,5.800000,38.160000,...,0.200000,0.040000,0.940000,0.62,-0.060,-0.100,-0.140000,0.104000,0.2,1.400000
9,1.200000,0.2,0.0,47.800000,0.2,15.600000,8.6,54.920000,5.400000,33.880000,...,0.760000,0.600000,1.220000,0.78,-0.200,-0.240,-0.220000,0.118000,0.2,1.400000
10,1.200000,0.0,0.0,46.400000,0.0,16.200000,7.6,45.800000,7.200000,44.560000,...,0.620000,0.620000,1.220000,0.74,-0.260,-0.260,-0.220000,0.140000,0.2,1.200000
11,0.800000,0.0,0.0,48.400000,0.0,16.800000,7.8,45.580000,7.000000,41.680000,...,0.500000,0.500000,1.100000,0.76,-0.560,-0.560,-0.500000,0.124000,0.2,0.800000
12,0.400000,0.0,0.0,49.200000,0.0,17.000000,7.2,41.600000,7.400000,43.500000,...,0.280000,0.280000,0.840000,0.76,-0.640,-0.640,-0.440000,0.108000,0.6,0.400000
13,0.800000,0.0,0.0,45.000000,0.0,15.400000,5.8,38.060000,7.000000,45.240000,...,0.240000,0.400000,0.780000,0.78,-0.260,-0.260,-0.180000,0.114000,0.4,0.800000
14,1.000000,0.0,0.0,44.400000,0.0,15.000000,6.0,40.920000,6.800000,44.520000,...,-0.140000,0.160000,0.580000,0.64,0.180,0.180,0.220000,0.108000,0.4,1.000000
15,1.200000,0.0,0.0,46.000000,0.0,14.200000,5.6,39.660000,5.600000,39.100000,...,-0.940000,-0.480000,0.660000,0.74,0.300,0.300,0.340000,0.110000,0.4,1.200000
16,1.200000,0.0,0.0,46.200000,0.0,12.800000,5.4,42.780000,5.000000,38.600000,...,-0.820000,-0.360000,0.760000,0.80,0.240,0.240,0.240000,0.114000,0.4,1.200000
17,1.600000,0.0,0.0,42.000000,0.0,11.800000,5.2,44.240000,4.800000,40.480000,...,-0.740000,-0.280000,0.780000,0.76,0.520,0.520,0.420000,0.134000,0.0,1.600000
18,1.000000,0.2,0.0,43.400000,0.2,12.200000,4.8,39.760000,4.600000,37.540000,...,-0.540000,-0.400000,0.840000,0.68,0.000,-0.040,-0.040000,0.134000,0.0,1.200000
19,0.600000,0.2,0.0,45.200000,0.2,13.200000,4.6,35.640000,6.000000,44.300000,...,-0.820000,-0.820000,0.800000,0.66,-0.340,-0.380,-0.400000,0.130000,0.2,0.800000
20,0.400000,0.2,0.0,46.600000,0.2,17.800000,7.0,39.220000,8.400000,45.680000,...,0.120000,-0.040000,0.780000,0.64,-0.560,-0.600,-0.580000,0.110000,0.4,0.600000
21,0.400000,0.2,0.0,46.000000,0.2,18.600000,7.2,37.660000,8.800000,46.400000,...,-0.040000,-0.200000,0.720000,0.60,-0.500,-0.540,-0.520000,0.102000,0.4,0.600000
22,0.000000,0.4,0.0,48.800000,0.4,17.600000,6.4,33.420000,8.400000,48.140000,...,-0.160000,-0.460000,0.640000,0.62,-0.720,-0.800,-0.640000,0.082000,0.6,0.400000
23,0.600000,0.2,0.0,49.400000,0.2,20.400000,8.6,39.180000,9.800000,50.120000,...,-0.280000,-0.420000,0.620000,0.82,-0.200,-0.240,-0.220000,0.068000,0.6,0.800000

In [85]:
df_vs_away_off= compute_rolling_averages(df_vs_away_off, offense)
df_vs_away_off

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,xGD_rolling_avg,npxGD_rolling_avg,xAG_rolling_avg,xA_rolling_avg,G-xG_rolling_avg,np:G-xG_rolling_avg,A-xAG_rolling_avg,npxG/Sh_rolling_avg,FKAtt_rolling_avg,GF_rolling_avg
0,1.000000,0.0,0.0,66.000000,0.0,20.00,11.000000,55.000,8.00,40.000000,...,-0.400000,-0.400000,0.400,1.000,4.000000e-01,4.000000e-01,0.600000,0.050000,0.000000,1.000000
1,1.000000,0.0,0.0,56.000000,0.0,16.00,7.500000,44.150,8.00,53.350000,...,-0.200000,-0.200000,0.300,0.650,4.000000e-01,4.000000e-01,0.200000,0.045000,0.500000,1.000000
2,0.666667,0.0,0.0,55.666667,0.0,14.00,6.666667,46.100,7.00,52.233333,...,-0.166667,-0.166667,0.400,0.600,3.333333e-02,3.333333e-02,-0.066667,0.046667,0.333333,0.666667
3,0.500000,0.0,0.0,55.250000,0.0,15.25,7.500000,47.725,7.25,49.700000,...,-0.300000,-0.300000,0.375,0.625,-5.000000e-02,-5.000000e-02,-0.125000,0.045000,0.250000,0.500000
4,0.800000,0.0,0.0,53.600000,0.0,13.80,6.400000,43.180,7.00,54.760000,...,0.040000,0.040000,0.620,0.980,2.220446e-17,2.220446e-17,-0.020000,0.052000,0.200000,0.800000
5,0.600000,0.0,0.0,52.400000,0.0,12.60,5.400000,40.760,7.00,58.180000,...,0.000000,0.160000,0.640,0.900,-2.000000e-01,-2.000000e-01,-0.240000,0.052000,0.200000,0.600000
6,0.600000,0.0,0.0,55.400000,0.0,12.40,5.800000,45.000,6.20,52.120000,...,0.000000,0.160000,0.780,1.040,-2.800000e-01,-2.800000e-01,-0.180000,0.056000,0.000000,0.600000
7,0.800000,0.0,0.0,54.600000,0.0,13.00,5.800000,42.700,6.80,54.420000,...,-0.200000,-0.040000,0.780,1.060,-1.800000e-01,-1.800000e-01,0.020000,0.066000,0.000000,0.800000
8,1.200000,0.0,0.0,51.800000,0.0,11.60,5.200000,43.840,6.20,54.340000,...,-0.200000,-0.040000,0.900,1.080,1.000000e-01,1.000000e-01,0.300000,0.082000,0.000000,1.200000
9,0.800000,0.0,0.0,52.200000,0.0,11.80,5.600000,47.720,5.60,46.000000,...,-0.760000,-0.600000,0.700,0.680,-6.000000e-02,-6.000000e-02,0.100000,0.078000,0.000000,0.800000
10,0.800000,0.0,0.0,53.600000,0.0,12.60,5.400000,44.700,6.20,46.800000,...,-0.620000,-0.620000,0.680,0.760,-6.000000e-02,-6.000000e-02,0.120000,0.074000,0.000000,0.800000
11,0.800000,0.0,0.0,51.600000,0.0,12.60,4.800000,39.260,7.00,54.060000,...,-0.500000,-0.500000,0.640,0.680,-8.000000e-02,-8.000000e-02,-0.040000,0.080000,0.000000,0.800000
12,0.800000,0.0,0.0,50.800000,0.0,12.60,4.400000,36.180,7.20,55.600000,...,-0.280000,-0.280000,0.640,0.680,4.000000e-02,4.000000e-02,-0.040000,0.074000,0.000000,0.800000
13,0.600000,0.2,0.0,55.000000,0.2,11.80,3.600000,32.020,6.60,52.260000,...,-0.240000,-0.400000,0.500,0.640,-2.000000e-02,-6.000000e-02,-0.300000,0.056000,0.200000,0.800000
14,0.600000,0.4,0.0,55.600000,0.4,12.20,3.000000,24.960,8.00,63.780000,...,0.140000,-0.160000,0.480,0.640,4.000000e-02,-4.000000e-02,-0.280000,0.062000,0.200000,1.000000
15,1.400000,0.6,0.0,54.000000,0.6,11.60,3.600000,30.060,7.20,60.900000,...,0.940000,0.480000,1.020,0.780,1.600000e-01,4.000000e-02,-0.420000,0.102000,0.400000,2.000000
16,1.600000,0.6,0.0,53.800000,0.6,11.80,4.200000,34.600,6.80,56.360000,...,0.820000,0.360000,1.040,0.840,4.000000e-01,2.800000e-01,-0.040000,0.098000,0.800000,2.200000
17,1.600000,0.6,0.0,58.000000,0.6,10.60,4.000000,35.700,6.00,56.800000,...,0.740000,0.280000,1.040,0.920,3.600000e-01,2.400000e-01,-0.240000,0.096000,0.800000,2.200000
18,1.400000,0.4,0.0,56.600000,0.4,12.20,5.400000,40.700,6.80,59.300000,...,0.540000,0.400000,1.120,0.920,4.000000e-02,-4.000000e-02,-0.320000,0.100000,0.600000,1.800000
19,2.200000,0.2,0.0,54.800000,0.2,11.40,5.400000,41.740,5.80,55.400000,...,0.820000,0.820000,1.500,1.280,4.200000e-01,3.800000e-01,0.100000,0.116000,0.600000,2.400000
20,1.600000,0.0,0.0,53.400000,0.0,12.60,6.200000,42.500,6.00,53.680000,...,-0.120000,0.040000,0.940,1.100,5.400000e-01,5.400000e-01,0.460000,0.080000,0.400000,1.600000
21,1.600000,0.0,0.0,54.000000,0.0,13.60,6.600000,41.920,6.20,51.920000,...,0.040000,0.200000,1.000,1.220,4.600000e-01,4.600000e-01,0.400000,0.082000,0.200000,1.600000
22,1.600000,0.0,0.0,51.200000,0.0,15.80,7.200000,41.760,7.00,47.640000,...,0.160000,0.460000,1.040,1.220,3.400000e-01,3.400000e-01,0.360000,0.088000,0.200000,1.600000
23,1.800000,0.0,0.0,50.600000,0.0,16.20,7.600000,42.600,6.40,43.480000,...,0.280000,0.420000,1.080,1.240,5.400000e-01,5.400000e-01,0.520000,0.096000,0.200000,1.800000

In [86]:
df_home_def= compute_rolling_averages(df_home_def, defence)
df_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,22.00,0.000000,0.000000,0.00,2.00,23.000000,0.0,NaN,0.0,0.0,...,4.0,7.000000,10.000000,23.00,26.000000,0.0,1.100000,0.230,1.000000e-01,2.000000
1,14.00,0.000000,0.000000,0.00,1.00,23.000000,0.0,NaN,0.0,0.0,...,2.0,8.500000,9.000000,25.50,18.500000,0.0,1.000000,0.190,-5.000000e-01,2.000000
2,16.00,0.333333,1.666667,0.00,1.00,17.300000,0.0,NaN,0.0,0.0,...,2.0,8.333333,8.666667,24.00,21.666667,0.0,0.966667,0.200,-3.333333e-02,1.333333
3,16.25,0.250000,1.250000,0.25,0.75,17.300000,0.0,0.0,0.0,0.0,...,2.0,8.500000,7.500000,23.25,20.500000,0.0,1.150000,0.210,-1.000000e-01,1.500000
4,17.20,0.400000,1.960000,0.20,0.60,13.100000,0.0,0.0,0.0,0.0,...,2.6,8.000000,7.200000,23.60,20.800000,0.2,1.000000,0.188,1.110223e-17,1.200000
5,14.60,0.400000,1.960000,0.20,0.60,12.333333,0.0,0.0,0.0,0.0,...,2.4,8.200000,7.400000,23.60,18.600000,0.2,0.940000,0.180,-2.600000e-01,1.200000
6,16.00,0.800000,5.040000,0.20,0.60,12.000000,0.0,0.0,0.0,0.0,...,3.0,7.200000,7.000000,22.40,19.600000,0.2,0.940000,0.242,-6.000000e-02,1.000000
7,14.60,0.600000,4.040000,0.20,0.40,12.125000,0.0,0.0,0.0,0.0,...,3.0,6.000000,8.200000,25.40,18.200000,0.4,1.040000,0.252,-1.600000e-01,1.200000
8,12.80,1.000000,9.040000,0.00,1.00,12.700000,0.0,NaN,0.0,0.0,...,2.8,5.200000,9.000000,27.00,19.000000,0.6,0.820000,0.242,2.000000e-02,0.800000
9,11.20,1.000000,9.620000,0.20,1.40,14.020000,0.0,0.0,0.2,0.2,...,2.6,6.200000,10.200000,28.80,18.800000,0.4,1.640000,0.304,-1.600000e-01,1.800000
10,15.80,1.400000,10.880000,0.20,1.40,12.440000,0.0,0.0,0.2,0.2,...,2.6,6.400000,9.600000,30.20,24.600000,0.6,1.500000,0.280,1.000000e-01,1.400000
11,15.60,1.000000,7.800000,0.40,1.40,12.800000,0.0,0.0,0.2,0.2,...,2.4,6.400000,10.600000,30.60,24.400000,0.6,1.540000,0.204,-6.000000e-02,1.600000
12,14.20,1.200000,11.140000,0.60,1.40,13.200000,0.0,0.0,0.2,0.2,...,2.2,7.400000,10.800000,28.40,22.600000,0.6,1.520000,0.164,-8.000000e-02,1.600000
13,14.00,0.800000,6.140000,0.60,1.60,15.400000,0.0,0.0,0.2,0.2,...,2.8,6.400000,10.200000,26.00,23.600000,0.6,1.420000,0.138,-1.800000e-01,1.600000
14,13.80,0.600000,4.600000,0.40,1.20,13.825000,0.0,0.0,0.0,0.0,...,2.4,6.200000,9.000000,22.40,24.200000,0.6,0.620000,0.090,-1.800000e-01,0.800000
15,12.00,0.200000,3.340000,0.40,1.20,16.075000,0.0,0.0,0.0,0.0,...,2.0,6.000000,9.800000,22.00,22.400000,0.4,1.120000,0.132,-4.800000e-01,1.600000
16,12.80,0.800000,7.100000,0.20,2.20,16.080000,0.0,0.0,0.0,0.0,...,1.8,6.600000,10.800000,24.20,24.600000,0.4,1.120000,0.224,-8.000000e-02,1.200000
17,13.20,0.800000,6.260000,0.00,2.40,16.400000,0.0,NaN,0.0,0.2,...,2.6,6.000000,10.400000,25.60,24.800000,0.6,1.220000,0.262,-5.800000e-01,1.800000
18,13.20,1.000000,9.120000,0.00,2.20,14.560000,0.0,NaN,0.0,0.2,...,2.0,7.000000,11.800000,27.60,20.400000,0.6,1.260000,0.304,-7.400000e-01,2.000000
19,13.60,1.000000,9.120000,0.00,2.60,18.060000,0.0,NaN,0.0,0.4,...,1.6,7.800000,13.200000,30.80,22.200000,0.6,1.460000,0.344,-5.400000e-01,2.000000
20,9.80,1.200000,14.120000,0.00,2.40,16.120000,0.0,NaN,0.0,0.4,...,2.0,7.400000,12.200000,28.40,15.600000,0.8,1.100000,0.446,-3.000000e-01,1.400000
21,9.00,0.800000,12.020000,0.00,1.40,14.760000,0.0,NaN,0.0,0.4,...,2.0,7.400000,10.400000,26.40,16.600000,1.0,0.960000,0.424,-4.400000e-01,1.400000
22,10.00,0.600000,9.520000,0.00,1.40,14.900000,0.0,NaN,0.0,0.4,...,1.0,8.000000,8.600000,24.40,19.800000,0.6,1.160000,0.468,-2.400000e-01,1.400000
23,11.60,0.800000,9.320000,0.00,1.40,15.000000,0.0,NaN,0.0,0.4,...,1.4,7.800000,7.000000,21.80,22.400000,0.4,1.120000,0.436,-8.000000e-02,1.200000

In [87]:
df_vs_home_def= compute_rolling_averages(df_vs_home_def, defence)
df_vs_home_def

,OppCr_rolling_avg,Stp_rolling_avg,Stp%_rolling_avg,PKcon_rolling_avg,#OPA_rolling_avg,AvgDist_rolling_avg,PKsv_rolling_avg,PK Save%_rolling_avg,FK Ag_rolling_avg,CKG_rolling_avg,...,BlcSh_rolling_avg,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg
0,13.0,0.000000,0.000000,0.0,1.000000,29.500000,0.0,NaN,0.0,0.0,...,3.000000,9.000000,9.0,25.00,15.000000,0.0,1.500,0.310000,5.000000e-01,2.00
1,16.0,0.500000,2.650000,0.0,0.500000,17.100000,0.0,NaN,0.0,0.0,...,2.500000,9.000000,8.0,24.00,20.000000,0.0,1.150,0.210000,1.500000e-01,1.50
2,16.0,0.333333,1.766667,0.0,0.333333,17.100000,0.0,NaN,0.0,0.0,...,2.666667,7.666667,8.0,23.00,22.333333,0.0,1.100,0.186667,4.333333e-01,1.00
3,14.0,0.500000,4.450000,0.0,0.500000,16.733333,0.0,NaN,0.0,0.0,...,3.000000,8.250000,8.0,25.25,20.500000,0.0,0.925,0.157500,4.250000e-01,0.75
4,12.6,0.400000,3.560000,0.0,0.800000,18.425000,0.0,NaN,0.0,0.0,...,2.800000,7.800000,7.0,26.80,19.400000,0.2,0.960,0.182000,3.600000e-01,0.80
5,12.2,0.400000,3.560000,0.0,0.600000,12.300000,0.0,NaN,0.0,0.0,...,2.600000,7.800000,6.4,27.40,19.800000,0.2,0.960,0.268000,3.600000e-01,0.60
6,11.6,0.600000,5.000000,0.0,0.600000,13.375000,0.0,NaN,0.0,0.0,...,4.200000,6.800000,6.6,29.40,20.200000,0.8,1.100,0.306000,5.000000e-01,0.80
7,10.6,1.000000,8.640000,0.0,0.600000,11.600000,0.0,NaN,0.0,0.0,...,4.200000,6.600000,8.4,32.80,18.600000,0.8,0.960,0.296000,3.600000e-01,1.00
8,11.6,1.000000,7.680000,0.2,1.200000,12.820000,0.0,0.0,0.0,0.0,...,3.800000,6.000000,8.4,30.60,21.000000,1.2,1.040,0.290000,2.400000e-01,1.20
9,11.0,1.000000,7.680000,0.2,2.200000,13.720000,0.0,0.0,0.0,0.0,...,4.200000,6.200000,9.2,28.80,19.200000,1.0,0.980,0.398000,1.800000e-01,1.20
10,10.2,1.000000,7.680000,0.2,2.400000,16.780000,0.0,0.0,0.0,0.0,...,4.200000,6.000000,9.4,28.80,19.200000,1.0,1.100,0.392000,1.000000e-01,1.40
11,9.4,0.600000,5.180000,0.2,2.800000,18.100000,0.0,0.0,0.0,0.0,...,2.800000,8.600000,9.2,27.80,19.600000,0.6,0.800,0.415000,-5.551115e-18,1.00
12,10.0,0.200000,1.540000,0.2,3.200000,20.140000,0.0,0.0,0.0,0.0,...,3.000000,8.800000,7.6,26.60,21.400000,0.6,0.760,0.402500,-4.000000e-02,0.80
13,10.4,0.200000,1.340000,0.0,2.800000,18.600000,0.0,NaN,0.0,0.0,...,3.000000,9.400000,7.2,27.40,20.800000,0.4,0.820,0.480000,2.000000e-02,0.80
14,13.0,0.200000,1.340000,0.0,1.400000,16.600000,0.0,NaN,0.0,0.0,...,2.600000,9.400000,8.4,28.40,25.800000,0.4,1.000,0.360000,2.000000e-01,0.80
15,12.2,0.200000,1.340000,0.0,1.600000,18.340000,0.0,NaN,0.0,0.2,...,2.200000,10.000000,8.2,27.60,24.800000,0.4,0.860,0.300000,-1.400000e-01,1.00
16,11.6,0.200000,1.340000,0.0,1.600000,19.080000,0.0,NaN,0.0,0.4,...,1.600000,7.600000,8.8,26.40,23.200000,0.2,1.020,0.290000,-1.800000e-01,1.20
17,11.2,0.400000,3.000000,0.0,1.200000,17.960000,0.0,NaN,0.0,0.4,...,1.000000,7.400000,8.2,26.20,20.600000,0.4,1.260,0.346000,-3.400000e-01,1.60
18,11.6,0.800000,5.180000,0.0,0.800000,16.160000,0.0,NaN,0.0,0.4,...,1.400000,6.800000,8.4,26.40,21.400000,0.6,1.100,0.288000,-5.000000e-01,1.60
19,10.2,1.000000,7.180000,0.2,1.400000,15.920000,0.2,100.0,0.0,0.6,...,1.800000,5.800000,7.0,24.40,18.800000,0.8,1.260,0.290000,-5.400000e-01,1.80
20,14.4,1.600000,9.680000,0.2,1.000000,11.120000,0.2,100.0,0.0,0.4,...,3.200000,4.400000,7.4,26.60,23.800000,1.0,1.080,0.220000,-3.200000e-01,1.40
21,14.6,1.600000,9.680000,0.2,1.000000,10.560000,0.2,100.0,0.0,0.2,...,3.800000,5.800000,6.2,26.60,24.400000,1.2,0.920,0.212500,-2.800000e-01,1.20
22,15.2,1.400000,8.020000,0.2,2.000000,13.800000,0.2,100.0,0.0,0.2,...,4.400000,7.000000,6.0,24.60,24.000000,1.0,0.880,0.202500,-1.200000e-01,1.00
23,14.0,1.000000,6.320000,0.2,2.400000,15.600000,0.2,100.0,0.0,0.2,...,3.600000,6.800000,5.6,22.20,21.800000,0.6,1.380,0.305000,-2.200000e-01,1.60

In [88]:
df_away_cmb= compute_rolling_averages(df_away_cmb, combined)
df_away_cmb['H/A']= df_away['H/A']
df_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,10.000000,10.000000,50.000000,1.000000,0.0,0.0,11.000000,6.000000,42.000000,H
1,17.500000,14.000000,54.050000,1.000000,0.0,0.0,9.500000,8.000000,41.000000,A
2,16.333333,13.333333,53.966667,0.666667,0.0,0.0,11.333333,8.333333,40.666667,H
3,18.750000,14.250000,55.600000,1.250000,0.0,0.0,12.750000,8.750000,38.750000,A
4,17.400000,15.600000,51.760000,1.600000,0.2,0.0,12.400000,8.800000,39.200000,H
5,19.800000,17.200000,52.760000,1.600000,0.2,0.0,11.200000,9.400000,40.800000,H
6,17.200000,16.400000,50.380000,2.000000,0.2,0.0,12.400000,9.800000,39.400000,A
7,18.400000,17.600000,50.140000,2.400000,0.2,0.0,11.600000,11.000000,39.600000,A
8,16.800000,19.000000,46.620000,2.800000,0.2,0.0,12.000000,11.000000,40.800000,A
9,18.400000,17.000000,52.240000,2.400000,0.0,0.0,11.600000,11.600000,41.800000,H
10,18.600000,15.800000,54.380000,3.200000,0.2,0.2,12.400000,12.200000,40.200000,H
11,20.000000,18.400000,53.400000,3.000000,0.2,0.2,12.000000,13.600000,40.800000,A
12,19.800000,16.000000,58.080000,2.800000,0.2,0.2,11.800000,13.800000,41.000000,H
13,19.600000,13.800000,60.840000,2.200000,0.4,0.2,11.600000,13.600000,39.800000,A
14,19.000000,13.800000,60.080000,2.200000,0.4,0.2,11.600000,13.800000,40.200000,H
15,15.800000,13.600000,54.720000,2.000000,0.2,0.0,12.400000,14.000000,41.200000,H
16,16.600000,11.600000,57.960000,1.600000,0.4,0.0,12.400000,11.800000,43.000000,A
17,14.800000,11.600000,55.260000,2.400000,0.6,0.0,12.400000,11.400000,41.800000,H
18,17.400000,15.400000,53.600000,2.600000,0.4,0.0,11.400000,13.400000,40.200000,A
19,16.000000,15.800000,50.160000,3.000000,0.4,0.0,12.000000,12.600000,38.200000,A
20,18.200000,16.200000,54.000000,2.600000,0.6,0.0,11.800000,13.600000,38.000000,H
21,17.000000,15.000000,54.640000,3.200000,0.4,0.0,12.200000,13.600000,35.200000,A
22,18.400000,17.800000,51.320000,2.400000,0.2,0.0,11.600000,13.000000,37.600000,H
23,17.000000,14.600000,53.440000,2.000000,0.2,0.0,10.400000,11.800000,42.000000,H

In [89]:
df_vs_away_cmb= compute_rolling_averages(df_vs_away_cmb, combined)
#df_away_cmb['H/A']= df_away['H/A']
df_vs_away_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,10.000000,10.000000,50.000000,0.0,1.000000,0.0,6.000000,11.0,38.000000
1,14.000000,17.500000,45.950000,1.0,0.500000,0.0,8.000000,9.5,39.000000
2,13.333333,16.333333,46.033333,1.0,0.666667,0.0,8.666667,11.0,38.666667
3,14.250000,18.750000,44.400000,1.0,0.500000,0.0,9.250000,12.5,38.250000
4,15.600000,17.400000,48.240000,1.4,0.400000,0.0,9.400000,12.0,41.000000
5,17.200000,19.800000,47.240000,1.6,0.200000,0.0,10.200000,10.8,43.400000
6,16.400000,17.200000,49.620000,1.8,0.200000,0.0,10.600000,11.4,43.200000
7,17.600000,18.400000,49.860000,2.2,0.000000,0.0,11.800000,10.8,42.800000
8,19.000000,16.800000,53.380000,2.2,0.000000,0.0,12.400000,10.8,42.800000
9,17.000000,18.400000,47.760000,1.8,0.000000,0.0,13.000000,10.4,40.000000
10,15.800000,18.600000,45.620000,1.8,0.000000,0.0,13.400000,11.0,40.000000
11,18.400000,20.000000,46.600000,1.8,0.000000,0.0,14.800000,11.0,38.000000
12,16.000000,19.800000,41.920000,1.8,0.000000,0.0,14.800000,10.6,37.600000
13,13.800000,19.600000,39.160000,2.4,0.000000,0.0,14.000000,10.2,36.000000
14,13.800000,19.000000,39.920000,2.4,0.000000,0.0,14.200000,10.2,37.600000
15,13.600000,15.800000,45.280000,2.8,0.000000,0.0,14.400000,11.2,36.800000
16,11.600000,16.600000,42.040000,2.4,0.000000,0.0,12.400000,11.2,39.400000
17,11.600000,14.800000,44.740000,2.2,0.000000,0.0,12.000000,11.2,42.000000
18,15.400000,17.400000,46.400000,2.2,0.000000,0.0,13.800000,10.8,44.200000
19,15.800000,16.000000,49.840000,2.2,0.000000,0.0,12.800000,11.6,43.800000
20,16.200000,18.200000,46.000000,2.0,0.000000,0.0,13.800000,11.4,44.800000
21,15.000000,17.000000,45.360000,2.2,0.000000,0.0,13.800000,12.0,45.400000
22,17.800000,18.400000,48.680000,2.6,0.000000,0.0,13.200000,11.4,43.600000
23,14.600000,17.000000,46.560000,2.6,0.000000,0.0,12.000000,10.2,41.800000

In [90]:
df_home_cmb= compute_rolling_averages(df_home_cmb, combined)
df_home_cmb['H/A']= df_home['H/A']
df_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg,H/A
0,20.0,11.0,64.500000,2.00,0.000000,0.0,15.000000,13.000000,44.000000,A
1,16.5,14.0,53.900000,2.50,0.000000,0.0,15.500000,10.000000,46.000000,H
2,15.0,14.0,51.333333,2.00,0.333333,0.0,13.666667,11.333333,43.333333,A
3,12.0,11.5,49.225000,2.25,0.250000,0.0,11.750000,11.750000,42.750000,H
4,13.2,13.4,48.620000,2.40,0.400000,0.2,13.200000,12.400000,42.000000,H
5,13.2,14.0,47.480000,2.80,0.400000,0.2,13.400000,12.000000,40.200000,A
6,12.6,13.8,46.520000,3.20,0.600000,0.4,13.000000,13.000000,37.800000,H
7,12.4,13.0,47.760000,3.60,0.400000,0.4,12.400000,11.400000,39.400000,A
8,15.2,14.8,50.520000,4.20,0.600000,0.6,14.200000,11.200000,38.200000,H
9,12.8,11.8,51.280000,4.00,0.400000,0.4,13.200000,9.200000,38.600000,A
10,12.0,12.0,49.840000,3.20,0.400000,0.4,11.800000,9.600000,38.800000,A
11,12.4,11.6,51.380000,2.60,0.200000,0.2,10.200000,10.600000,39.000000,H
12,15.6,12.8,53.460000,2.20,0.400000,0.2,10.800000,10.800000,38.000000,A
13,16.0,12.0,55.700000,1.40,0.200000,0.0,10.600000,11.000000,36.800000,H
14,18.0,13.8,56.020000,1.20,0.200000,0.0,10.000000,12.800000,37.000000,H
15,17.4,13.4,55.700000,1.80,0.200000,0.0,9.800000,12.400000,39.800000,A
16,17.0,11.8,58.960000,2.80,0.200000,0.0,11.000000,10.800000,43.000000,H
17,12.8,9.4,58.400000,3.00,0.000000,0.0,11.800000,10.400000,43.800000,A
18,12.8,9.2,58.900000,2.80,0.000000,0.0,12.200000,9.400000,46.400000,H
19,11.0,8.0,57.340000,3.40,0.000000,0.0,13.000000,7.800000,47.400000,A
20,12.2,8.6,58.200000,3.00,0.000000,0.0,14.000000,8.200000,48.000000,H
21,14.6,10.8,56.980000,2.80,0.000000,0.0,14.000000,8.400000,44.200000,A
22,14.8,11.0,56.640000,3.40,0.000000,0.0,14.000000,8.600000,43.600000,H
23,12.0,11.8,48.440000,3.60,0.000000,0.0,12.800000,9.000000,42.600000,A

In [91]:
df_vs_home_cmb= compute_rolling_averages(df_vs_home_cmb, combined)
#df_home_cmb['H/A']= df_home['H/A']
df_vs_home_cmb

,Won_rolling_avg,Lost_rolling_avg,Won%_rolling_avg,CrdY_rolling_avg,CrdR_rolling_avg,2CrdY_rolling_avg,Fls_rolling_avg,Fld_rolling_avg,Recov_rolling_avg
0,11.0,20.0,35.500000,2.000000,0.0,0.0,14.000000,13.000000,36.00
1,14.0,16.5,46.100000,3.500000,0.0,0.0,11.000000,14.000000,35.50
2,14.0,15.0,48.666667,2.333333,0.0,0.0,12.333333,12.333333,37.00
3,11.5,12.0,50.775000,2.250000,0.0,0.0,12.750000,10.500000,36.75
4,13.4,13.2,51.380000,2.600000,0.0,0.0,13.200000,11.800000,36.00
5,14.0,13.2,52.520000,2.400000,0.0,0.0,12.600000,12.400000,35.60
6,13.8,12.6,53.480000,2.200000,0.0,0.0,13.400000,12.000000,34.80
7,13.0,12.4,52.240000,2.200000,0.2,0.0,11.600000,11.600000,34.60
8,14.8,15.2,49.480000,2.400000,0.2,0.0,11.800000,13.600000,33.80
9,11.8,12.8,48.720000,1.800000,0.2,0.0,10.000000,13.000000,35.20
10,12.0,12.0,50.160000,2.000000,0.2,0.0,10.600000,11.600000,36.00
11,11.6,12.4,48.620000,1.400000,0.2,0.0,11.600000,10.000000,39.40
12,12.8,15.6,46.540000,1.800000,0.0,0.0,11.800000,10.600000,40.60
13,12.0,16.0,44.300000,2.200000,0.2,0.0,11.600000,10.000000,39.20
14,13.8,18.0,43.980000,2.200000,0.2,0.0,13.400000,9.400000,38.40
15,13.4,17.4,44.300000,2.600000,0.2,0.0,12.800000,9.000000,41.60
16,11.8,17.0,41.040000,3.000000,0.2,0.0,11.200000,10.400000,40.60
17,9.4,13.0,40.880000,2.800000,0.2,0.0,10.800000,11.200000,40.20
18,9.2,13.0,40.380000,2.200000,0.0,0.0,9.600000,11.800000,41.20
19,8.0,11.2,41.960000,2.000000,0.0,0.0,7.800000,12.600000,43.20
20,8.6,12.4,41.100000,2.000000,0.0,0.0,8.400000,13.600000,38.40
21,10.8,14.8,42.320000,2.200000,0.0,0.0,9.600000,13.600000,35.80
22,11.0,14.8,43.380000,2.400000,0.2,0.0,9.800000,13.400000,34.20
23,11.8,12.0,51.580000,2.800000,0.2,0.0,10.400000,12.400000,34.40

In [92]:
df_vs_away_cmb = df_vs_away_cmb.rename(columns=lambda x: 'vs_' + x)
df_vs_home_cmb = df_vs_home_cmb.rename(columns=lambda x: 'vs_' + x)

## Final DFs

In [93]:
df_home_gf= pd.concat([df_home_off, df_home_cmb, df_vs_home_cmb, df_vs_home_def, df_home[['GF']]], axis= 1)
df_home_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,1.000000,0.0,0.0,52.000000,0.0,20.000000,7.000000,35.000000,9.000000,45.00,...,9.000000,9.0,25.00,15.000000,0.0,1.500,0.310000,5.000000e-01,2.00,2
1,1.000000,0.0,0.0,55.500000,0.0,23.000000,10.500000,44.400000,9.000000,39.80,...,9.000000,8.0,24.00,20.000000,0.0,1.150,0.210000,1.500000e-01,1.50,1
2,0.666667,0.0,0.0,55.333333,0.0,18.666667,8.666667,46.266667,7.666667,43.20,...,7.666667,8.0,23.00,22.333333,0.0,1.100,0.186667,4.333333e-01,1.00,0
3,0.500000,0.0,0.0,54.000000,0.0,20.750000,9.000000,43.950000,8.750000,43.50,...,8.250000,8.0,25.25,20.500000,0.0,0.925,0.157500,4.250000e-01,0.75,0
4,0.600000,0.0,0.0,55.200000,0.0,22.200000,10.400000,46.580000,8.800000,41.22,...,7.800000,7.0,26.80,19.400000,0.2,0.960,0.182000,3.600000e-01,0.80,1
5,0.600000,0.0,0.0,57.800000,0.0,22.400000,11.400000,51.000000,8.800000,40.80,...,7.800000,6.4,27.40,19.800000,0.2,0.960,0.268000,3.600000e-01,0.60,1
6,0.600000,0.0,0.0,56.800000,0.0,21.200000,10.000000,47.240000,9.400000,45.88,...,6.800000,6.6,29.40,20.200000,0.8,1.100,0.306000,5.000000e-01,0.80,2
7,0.600000,0.0,0.0,58.000000,0.0,24.800000,12.000000,47.960000,10.200000,42.30,...,6.600000,8.4,32.80,18.600000,0.8,0.960,0.296000,3.600000e-01,1.00,1
8,0.600000,0.2,0.0,58.200000,0.2,23.400000,12.800000,54.560000,8.800000,38.42,...,6.000000,8.4,30.60,21.000000,1.2,1.040,0.290000,2.400000e-01,1.20,1
9,0.600000,0.2,0.0,52.800000,0.2,22.000000,11.600000,52.660000,8.800000,40.58,...,6.200000,9.2,28.80,19.200000,1.0,0.980,0.398000,1.800000e-01,1.20,1
10,0.800000,0.2,0.0,51.200000,0.2,21.400000,11.000000,51.240000,8.400000,39.78,...,6.000000,9.4,28.80,19.200000,1.0,1.100,0.392000,1.000000e-01,1.40,2
11,0.600000,0.2,0.0,51.400000,0.2,20.800000,10.800000,51.300000,8.200000,40.72,...,8.600000,9.2,27.80,19.600000,0.6,0.800,0.415000,-5.551115e-18,1.00,0
12,0.600000,0.2,0.0,50.600000,0.2,19.000000,9.200000,47.940000,8.600000,45.88,...,8.800000,7.6,26.60,21.400000,0.6,0.760,0.402500,-4.000000e-02,0.80,0
13,0.800000,0.0,0.0,51.000000,0.0,18.600000,8.200000,43.940000,9.200000,49.76,...,9.400000,7.2,27.40,20.800000,0.4,0.820,0.480000,2.000000e-02,0.80,1
14,0.800000,0.0,0.0,57.200000,0.0,17.600000,7.200000,40.680000,9.600000,54.94,...,9.400000,8.4,28.40,25.800000,0.4,1.000,0.360000,2.000000e-01,0.80,1
15,1.000000,0.0,0.0,54.400000,0.0,17.400000,7.200000,41.260000,9.800000,56.58,...,10.000000,8.2,27.60,24.800000,0.4,0.860,0.300000,-1.400000e-01,1.00,3
16,1.200000,0.0,0.0,52.400000,0.0,17.000000,7.000000,40.860000,9.400000,55.64,...,7.600000,8.8,26.40,23.200000,0.2,1.020,0.290000,-1.800000e-01,1.20,1
17,1.600000,0.0,0.0,49.200000,0.0,17.800000,8.000000,43.940000,9.000000,51.88,...,7.400000,8.2,26.20,20.600000,0.4,1.260,0.346000,-3.400000e-01,1.60,2
18,1.600000,0.0,0.0,49.400000,0.0,17.400000,7.400000,41.440000,9.200000,54.26,...,6.800000,8.4,26.40,21.400000,0.6,1.100,0.288000,-5.000000e-01,1.60,1
19,1.800000,0.0,0.2,44.600000,0.2,17.800000,7.600000,41.840000,8.800000,50.50,...,5.800000,7.0,24.40,18.800000,0.8,1.260,0.290000,-5.400000e-01,1.80,2
20,1.400000,0.0,0.2,50.800000,0.2,21.600000,8.200000,37.920000,11.200000,52.20,...,4.400000,7.4,26.60,23.800000,1.0,1.080,0.220000,-3.200000e-01,1.40,1
21,1.200000,0.0,0.2,52.800000,0.2,23.000000,10.000000,43.980000,10.800000,46.56,...,5.800000,6.2,26.60,24.400000,1.2,0.920,0.212500,-2.800000e-01,1.20,0
22,1.000000,0.0,0.2,52.600000,0.2,22.800000,9.800000,43.540000,10.600000,46.02,...,7.000000,6.0,24.60,24.000000,1.0,0.880,0.202500,-1.200000e-01,1.00,1
23,1.600000,0.0,0.2,51.400000,0.2,22.400000,9.600000,43.180000,10.200000,44.76,...,6.800000,5.6,22.20,21.800000,0.6,1.380,0.305000,-2.200000e-01,1.60,4

In [94]:
df_away_gf= pd.concat([df_away_off, df_away_cmb, df_vs_away_cmb, df_vs_away_def, df_away[['GF']]], axis= 1)
df_away_gf

,G-PK_rolling_avg,PK_rolling_avg,PKm_rolling_avg,Poss_rolling_avg,PKatt_rolling_avg,Att To_rolling_avg,Succ_rolling_avg,Succ%_rolling_avg,Tkld_rolling_avg,Tkld%_rolling_avg,...,Pass_rolling_avg,Int_rolling_avg,Tkl+Int_rolling_avg,Clr_rolling_avg,Err_rolling_avg,PSxG_rolling_avg,PSxG/SoT_rolling_avg,PSxG+/-_rolling_avg,GA_rolling_avg,GF
0,1.000000,0.0,0.0,34.000000,0.0,15.000000,6.0,40.000000,9.000000,60.000000,...,6.00,4.000000,19.000000,23.000000,0.0,0.600000,0.120000,-4.000000e-01,1.000000,1
1,0.500000,0.0,0.0,44.000000,0.0,19.500000,7.5,38.750000,11.500000,59.150000,...,8.00,7.000000,26.000000,21.000000,0.0,0.350000,0.090000,-1.500000e-01,0.500000,0
2,0.333333,0.0,0.0,44.333333,0.0,16.333333,7.0,45.833333,8.666667,49.433333,...,8.00,7.333333,24.333333,23.333333,0.0,0.533333,0.133333,2.000000e-01,0.333333,0
3,0.500000,0.0,0.0,44.750000,0.0,14.750000,6.0,41.875000,8.000000,52.075000,...,7.75,9.000000,25.500000,24.250000,0.0,0.700000,0.197500,2.000000e-01,0.500000,1
4,0.400000,0.0,0.0,46.400000,0.0,14.200000,5.6,40.160000,7.600000,51.660000,...,7.60,8.400000,23.600000,25.000000,0.0,0.620000,0.174000,2.200000e-01,0.600000,1
5,0.200000,0.2,0.0,47.600000,0.2,13.800000,6.4,47.540000,6.200000,42.740000,...,7.00,9.000000,24.200000,22.800000,0.0,0.680000,0.166000,2.800000e-01,0.600000,1
6,0.600000,0.2,0.0,44.600000,0.2,12.000000,5.8,48.040000,5.000000,41.740000,...,6.20,8.400000,23.400000,22.200000,0.0,0.920000,0.196000,1.200000e-01,1.000000,2
7,1.000000,0.2,0.0,45.400000,0.2,13.400000,6.6,47.800000,5.600000,42.800000,...,5.80,8.200000,23.200000,20.200000,0.4,1.300000,0.246000,1.000000e-01,1.400000,2
8,1.000000,0.2,0.0,48.200000,0.2,15.200000,8.4,54.440000,5.800000,38.160000,...,6.40,7.400000,25.200000,23.600000,0.6,1.580000,0.272000,3.800000e-01,1.400000,1
9,1.200000,0.2,0.0,47.800000,0.2,15.600000,8.6,54.920000,5.400000,33.880000,...,6.20,7.800000,26.000000,23.200000,0.6,1.840000,0.318000,4.400000e-01,1.400000,1
10,1.200000,0.0,0.0,46.400000,0.0,16.200000,7.6,45.800000,7.200000,44.560000,...,6.80,7.600000,26.400000,23.400000,0.6,1.720000,0.358000,5.200000e-01,1.200000,0
11,0.800000,0.0,0.0,48.400000,0.0,16.800000,7.8,45.580000,7.000000,41.680000,...,6.00,7.600000,26.400000,24.600000,0.6,1.520000,0.346000,7.200000e-01,0.800000,0
12,0.400000,0.0,0.0,49.200000,0.0,17.000000,7.2,41.600000,7.400000,43.500000,...,5.20,8.200000,28.400000,25.600000,0.4,1.000000,0.260000,6.000000e-01,0.400000,0
13,0.800000,0.0,0.0,45.000000,0.0,15.400000,5.8,38.060000,7.000000,45.240000,...,4.40,6.400000,23.000000,21.000000,0.2,0.860000,0.282000,6.000000e-02,0.800000,3
14,1.000000,0.0,0.0,44.400000,0.0,15.000000,6.0,40.920000,6.800000,44.520000,...,4.60,5.400000,23.200000,19.000000,0.2,0.840000,0.320000,-1.600000e-01,1.000000,2
15,1.200000,0.0,0.0,46.000000,0.0,14.200000,5.6,39.660000,5.600000,39.100000,...,4.60,5.400000,22.000000,20.600000,0.2,0.980000,0.462000,-2.200000e-01,1.200000,1
16,1.200000,0.0,0.0,46.200000,0.0,12.800000,5.4,42.780000,5.000000,38.600000,...,5.40,5.600000,21.800000,20.800000,0.2,1.300000,0.524000,1.000000e-01,1.200000,0
17,1.600000,0.0,0.0,42.000000,0.0,11.800000,5.2,44.240000,4.800000,40.480000,...,5.60,4.000000,19.000000,19.000000,0.2,1.600000,0.690000,-4.440892e-17,1.600000,2
18,1.000000,0.2,0.0,43.400000,0.2,12.200000,4.8,39.760000,4.600000,37.540000,...,5.80,5.400000,21.000000,17.800000,0.2,1.460000,0.606000,2.600000e-01,1.200000,1
19,0.600000,0.2,0.0,45.200000,0.2,13.200000,4.6,35.640000,6.000000,44.300000,...,6.40,6.600000,23.000000,17.600000,0.4,1.220000,0.540000,4.200000e-01,0.800000,0
20,0.400000,0.2,0.0,46.600000,0.2,17.800000,7.0,39.220000,8.400000,45.680000,...,6.80,7.600000,27.000000,19.200000,0.4,1.180000,0.394000,5.800000e-01,0.600000,0
21,0.400000,0.2,0.0,46.000000,0.2,18.600000,7.2,37.660000,8.800000,46.400000,...,7.00,7.000000,24.400000,19.200000,0.4,0.800000,0.306000,2.000000e-01,0.600000,0
22,0.000000,0.4,0.0,48.800000,0.4,17.600000,6.4,33.420000,8.400000,48.140000,...,8.00,8.400000,27.200000,21.600000,0.2,0.620000,0.136000,2.200000e-01,0.400000,1
23,0.600000,0.2,0.0,49.400000,0.2,20.400000,8.6,39.180000,9.800000,50.120000,...,8.20,7.200000,26.800000,26.600000,0.8,0.820000,0.184000,2.000000e-02,0.800000,3

In [95]:
nan_counts = df_home_gf.isna().sum()
for i in df_home_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 14
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [96]:
nan_counts = df_away_gf.isna().sum()
for i in df_away_gf.columns:
    print(f"{i}: {nan_counts[i]}")

G-PK_rolling_avg: 0
PK_rolling_avg: 0
PKm_rolling_avg: 0
Poss_rolling_avg: 0
PKatt_rolling_avg: 0
Att To_rolling_avg: 0
Succ_rolling_avg: 0
Succ%_rolling_avg: 0
Tkld_rolling_avg: 0
Tkld%_rolling_avg: 0
Carries_rolling_avg: 0
TotDist_rolling_avg: 0
PrgDist_rolling_avg: 0
PrgC_rolling_avg: 0
Last3rd Car_rolling_avg: 0
GCA_rolling_avg: 0
PassLive Gc_rolling_avg: 0
PassDead Gc_rolling_avg: 0
TO Gc_rolling_avg: 0
Sh-Gc_rolling_avg: 0
Fld Gc_rolling_avg: 0
Def-Gc_rolling_avg: 0
Sh_rolling_avg: 0
G/Sh_rolling_avg: 0
G/SoT_rolling_avg: 0
SoT_rolling_avg: 0
SoT%_rolling_avg: 0
Dist_rolling_avg: 0
FK_rolling_avg: 0
Off_rolling_avg: 0
PKwon_rolling_avg: 0
Cmp_rolling_avg: 0
Pas Att_rolling_avg: 0
Cmp%_rolling_avg: 0
KP_rolling_avg: 0
Last3rd PA_rolling_avg: 0
PPA_rolling_avg: 0
CrsPA_rolling_avg: 0
PrgP_rolling_avg: 0
TotDist Pas_rolling_avg: 0
PrgDist Pas_rolling_avg: 0
Cmp 5-15_rolling_avg: 0
Att 5-15_rolling_avg: 0
Cmp% 5-15_rolling_avg: 0
Cmp 15-30_rolling_avg: 0
Att 15-30_rolling_avg: 0
Cmp% 15-30_rolling_avg: 0
Cmp 30+_rolling_avg: 0
Att 30+_rolling_avg: 0
Cmp% 30+_rolling_avg: 0
Live Pas_rolling_avg: 0
Dead_rolling_avg: 0
Pas FK_rolling_avg: 0
TB_rolling_avg: 0
Sw_rolling_avg: 0
Crs_rolling_avg: 0
TI_rolling_avg: 0
CK_rolling_avg: 0
In_rolling_avg: 0
Out_rolling_avg: 0
Str_rolling_avg: 0
Ps Off_rolling_avg: 0
PTo_rolling_avg: 0
Rec_rolling_avg: 0
Last3rd Rec_rolling_avg: 0
CPA_rolling_avg: 0
Mis_rolling_avg: 0
Dis_rolling_avg: 0
SCA_rolling_avg: 0
PassLive Sc_rolling_avg: 0
PassDead Sc_rolling_avg: 0
TO Sc_rolling_avg: 0
Sh-Sh_rolling_avg: 0
Fld Sc_rolling_avg: 0
Def-Sc_rolling_avg: 0
Touches_rolling_avg: 0
Def Pen_rolling_avg: 0
Tch Def 3rd_rolling_avg: 0
Tch Mid 3rd_rolling_avg: 0
Tch Att 3rd_rolling_avg: 0
Att Pen_rolling_avg: 0
Live Tch_rolling_avg: 0
xG_rolling_avg: 0
npxG_rolling_avg: 0
xGD_rolling_avg: 0
npxGD_rolling_avg: 0
xAG_rolling_avg: 0
xA_rolling_avg: 0
G-xG_rolling_avg: 0
np:G-xG_rolling_avg: 0
A-xAG_rolling_avg: 0
npxG/Sh_rolling_avg: 0
FKAtt_rolling_avg: 0
GF_rolling_avg: 0
Won_rolling_avg: 0
Lost_rolling_avg: 0
Won%_rolling_avg: 0
CrdY_rolling_avg: 0
CrdR_rolling_avg: 0
2CrdY_rolling_avg: 0
Fls_rolling_avg: 0
Fld_rolling_avg: 0
Recov_rolling_avg: 0
H/A: 0
vs_Won_rolling_avg: 0
vs_Lost_rolling_avg: 0
vs_Won%_rolling_avg: 0
vs_CrdY_rolling_avg: 0
vs_CrdR_rolling_avg: 0
vs_2CrdY_rolling_avg: 0
vs_Fls_rolling_avg: 0
vs_Fld_rolling_avg: 0
vs_Recov_rolling_avg: 0
OppCr_rolling_avg: 0
Stp_rolling_avg: 0
Stp%_rolling_avg: 0
PKcon_rolling_avg: 0
#OPA_rolling_avg: 0
AvgDist_rolling_avg: 0
PKsv_rolling_avg: 0
PK Save%_rolling_avg: 13
FK Ag_rolling_avg: 0
CKG_rolling_avg: 0
OGK_rolling_avg: 0
SoTA_rolling_avg: 0
Saves_rolling_avg: 0
Save%_rolling_avg: 0
Tkl_rolling_avg: 0
TklW_rolling_avg: 0
Tkl Def 3rd_rolling_avg: 0
Tkl Mid 3rd_rolling_avg: 0
Tkl Att 3rd_rolling_avg: 0
Tkl.2_rolling_avg: 0
Tkl Att_rolling_avg: 0
Tkl%_rolling_avg: 0
Lost Tkl_rolling_avg: 0
Ints_rolling_avg: 0
BlcSh_rolling_avg: 0
Pass_rolling_avg: 0
Int_rolling_avg: 0
Tkl+Int_rolling_avg: 0
Clr_rolling_avg: 0
Err_rolling_avg: 0
PSxG_rolling_avg: 0
PSxG/SoT_rolling_avg: 0
PSxG+/-_rolling_avg: 0
GA_rolling_avg: 0
GF: 0

In [97]:
df_home_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [98]:
df_away_gf.drop(columns=["PK Save%_rolling_avg"], inplace= True)

In [99]:
df_home_gf = df_home_gf.fillna(0)

In [100]:
df_away_gf = df_away_gf.fillna(0)

# Model Home

In [101]:
target = "GF"  # Goals For

# Separate features and target
X = df_home_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
y = df_home_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [102]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [103]:
model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=25)

# Train the model
model_pipeline.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 1.433
RMSE: 1.483

In [105]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline.predict(X_test)
    y_cur= model_pipeline.predict(df_home_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 18, number of used features: 0
[LightGBM] [Info] Start training from score 1.166667
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [106]:
results_df

                        MAE      RMSE                  pred
Random Forest           0.5  0.570964                 [1.6]
XGBoost            0.909491  1.097987           [1.7239914]
LightGBM                0.3  0.401386  [1.1666666666666667]
Linear Regression  1.904105   2.53412  [1.8367397917472335]

# Model Away

In [107]:
target = "GF"  # Goals For

# Separate features and target
Xa = df_away_gf.drop(columns=[target]).iloc[:-1].reset_index(drop=True)
ya = df_away_gf[target].iloc[1:].reset_index(drop=True)
categorical_features = ["H/A"]  # Home/Away column
numerical_features = X.select_dtypes(include=[np.number]).columns.tolist()

In [108]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(drop="first"), categorical_features)
])

In [109]:
model_pipeline2 = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=20, random_state=25))
])

In [110]:
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.1, random_state=25)

# Train the model
model_pipeline2.fit(X_train, y_train)

# Predictions
y_pred = model_pipeline2.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE: 0.900
RMSE: 1.016

In [111]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=10, random_state=25),
    "XGBoost": XGBRegressor(n_estimators=10, random_state=25),
    "LightGBM": LGBMRegressor(n_estimators=10, random_state=25),
    "Linear Regression": LinearRegression()
}

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(Xa, ya, test_size=0.2, random_state=42)

# Train and evaluate each model
results = {}
for name, model in models.items():
    # Define the pipeline
    model_pipeline2 = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])
    
    # Train the model
    model_pipeline2.fit(X_train, y_train)
    
    # Predictions
    y_pred = model_pipeline2.predict(X_test)
    y_cur= model_pipeline2.predict(df_away_gf.drop(columns=[target]).iloc[-1:])
    
    # Evaluate performance
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    results[name] = {"MAE": mae, "RMSE": rmse, "pred": y_cur}

# Convert results to a DataFrame and display
results_df = pd.DataFrame(results).T

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 18, number of used features: 0
[LightGBM] [Info] Start training from score 1.111111
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

In [112]:
results_df

                        MAE      RMSE                  pred
Random Forest          0.58  0.725259                 [1.7]
XGBoost            0.818582  0.972938           [2.2552068]
LightGBM           0.711111  0.863527  [1.1111111111111112]
Linear Regression  1.322378  1.591942    [2.58244737385657]